### ISSUE TITLE
Barcode not printed

### ISSUE THREAD

**Issue by senaacls** [DantSu/ESCPOS-ThermalPrinter-Android#1]
I using mini portable printer, then I used your sample program but barcode cannot display but qr code worked
https://shopee.co.id/MINI-PORTABLE-MOBILE-RECIEPT-POS-PRINTER-PANDA-PRJ-58B-58MM-KERTAS-KASIR-PPOB-THERMAL(USB-BLUETOOTH)-i.106333154.1672697414

thank you

**Comment by DantSu** [comment]
Hi,
It is barcodes compatible ? I can't find any caracteristics of this printer on Internet.

**Comment by senaacls** [comment]
Thank you , solved..
I changed new printer
