### ISSUE TITLE
Need a few easy steps to connect to printer

### ISSUE THREAD

**Issue by htooaunghlaing** [DantSu/ESCPOS-ThermalPrinter-Android#10]
I tried to print sample image, I turn off bluetooth, but it does not request any bluetooth enable request.Connecting to printer process is not smooth and sometimes app crash, because of **Attempt to read from null array**
<img width="1249" alt="Screenshot 2020-05-22 at 11 41 55 PM" src="https://user-images.githubusercontent.com/6047310/82693058-cef5fe00-9c86-11ea-9b7b-094672acd82a.png">
But, [https://github.com/iYaroslav/esc-pos-android](https://github.com/iYaroslav/esc-pos-android) this one is implemented for the easy and simply way to connect to printer, we can forget about connecting process, but it does not support image and QR code printing yet

**Comment by DantSu** [comment]
Is not to the library to do this... is to you. You have to implement all the UI side. 

I will look to the null array bug.

**Comment by DantSu** [comment]
done

**Comment by htooaunghlaing** [comment]
Thanks
