### ISSUE TITLE
Issue with first letter of r symbol and last letter of r symbol 

### ISSUE THREAD

**Issue by vijayakumarksv** [DantSu/ESCPOS-ThermalPrinter-Android#103]
Hi, 
When I print the data at the time left and right side of the data r symbol is coming, how to remove that symbol? 

![WhatsApp Image 2021-02-03 at 5](https://user-images.githubusercontent.com/50190122/106788477-01118980-6677-11eb-80ce-6d7cc27d1a1d.png)

**Comment by DantSu** [comment]
try v2.0.9
