### ISSUE TITLE
No printer connect timeout

### ISSUE THREAD

**Issue by kot721** [DantSu/ESCPOS-ThermalPrinter-Android#104]
Thanks for best escpos-thermal printer library for android.

But can you add method to set socket connect timeout? Sometime time connect is very long to receive responce when printer was disconnected.

**Comment by DantSu** [comment]
v3.0.1 released : https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/releases/tag/3.0.1
TCP timeout parameter added.
Bluetooth connection doesn't have timeout parameter.
