### ISSUE TITLE
How to print Hindi on Bluetooth & USB Thermal Printer

### ISSUE THREAD

**Issue by prakashandroid** [DantSu/ESCPOS-ThermalPrinter-Android#107]
I was trying to print Hindi font on thermal printer bus was not able to print is. I have tried everything.

1. I have tried to convert the text to image and then print but it is not printing in full width. (Is there any way to print image in full width or we can define the width of the image as per our requirement either 2inch or 3inch)

2. Apart from it I have tried many sdk to print in Hindi but nothing worked. (Kindly specify the way to print in Hindi.)

3. I have tried character set for Hindi that also not worked. let me know which character set or character code I need to use to print in Hindi.

**Comment by DantSu** [comment]
Read this issue to split image to keep full size : 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70
