### ISSUE TITLE
Text Aligment

### ISSUE THREAD

**Issue by DevMmfk** [DantSu/ESCPOS-ThermalPrinter-Android#109]
All text printed alignment is left

**Comment by DantSu** [comment]
may be yes, may be not, I don't know..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
