### ISSUE TITLE
Not able to print Latin letter 

### ISSUE THREAD

**Issue by AdilTechDart** [DantSu/ESCPOS-ThermalPrinter-Android#11]
I am trying to print Latin letter For Ex. 
Ç, ü, é, â, ä, à, å, ç, ê, ë, è, ï, î, ì, Ä, Å, É, æ, Æ, ô, ö, ò, û, ù, ÿ, Ö, Ü, ¢, £, ¥, ?, ƒ, á, í, ó, ú, ñ, Ñ,
but it's change to something else
![image](https://user-images.githubusercontent.com/37257868/82715138-3aea5d80-9cab-11ea-963a-a8e339002134.png)

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/6
