### ISSUE TITLE
80mm printers

### ISSUE THREAD

**Issue by i-Tor** [DantSu/ESCPOS-ThermalPrinter-Android#110]
I am just discovering this great project for enabling us small developers to use bluetooth thermal printers.

I have some models in the current project, but I can test with one of these 80mm printers https://www.alibaba.com/product-detail/Android-80mm-Portable-Wireless-POS-Bluetooth_62059903844.html?spm=a2700.7724857.normal_offer.d_image.20633d17q0UmsJ 

So far, by debugging I have found that the major device class returned when connecting is 7936, and thus originally it wouldn't print anything. By bypassing this section of the code I can get it to print!! happy with the progress. I can see the image and the barcodes

But I have found that the width of the overall text is still configured for 58mm printing. Even if I change the declaration to
    EscPosPrinter(printerConnection, 203, 72f, 48, new EscPosCharsetEncoding("windows-1252", 16))

It won't use the whole 80mm. Curiously, the 2d barcode is centered, but not the rest.

Is there anything I can do to make the text centered in 80mm?

Thank you for sharing your progress, and let me know if there is anything I can do to help.

**Comment by DantSu** [comment]
print this : "[L]012345678901234567890123456789012345678901234567890123456789"

How many chars are there in a line ?

**Comment by DantSu** [comment]
Are you sure that is a 203 dpi printer ?

**Comment by i-Tor** [comment]
Ok, problem resolved (it was me). 

I was modifying the WRONG line, in the printIt method. Please excuse me.

The printer is a 203dpi printer I belive, yes. I'm assuming this from the product page and also seeing it works.

    012345678901234567890123456789012345678901234567

According to your request, this was printed so I am asuming it is a 48 char line, yes.

Also, if it is of interest to anyone, the effective print mm size for a 80mm paper printer is 72mm. This way the images are correctly centered.

Thank you very much for your quick answer @DantSu. I am partially ashamed of reporting this as an issue when it was my fault, but if it serves anyone I'll be happy.

**Comment by DantSu** [comment]
ok perfect.
Have fun with this library ;)
