### ISSUE TITLE
TAGS not working

### ISSUE THREAD

**Issue by Sarim-Ahmed93** [DantSu/ESCPOS-ThermalPrinter-Android#111]
Hi, 
This is library is best. I have Android-PDA4G Handheld POS Devices. When i print with bluetooth using same device printer the alignment tags do not work.

**Comment by DantSu** [comment]
Be more explicite. Piece of code + pictures

**Comment by Sarim-Ahmed93** [comment]
> Be more explicite. Piece of code + pictures

Using your sample code: 

![IMG_20210305_100101](https://user-images.githubusercontent.com/15017565/110092528-fc391600-7d99-11eb-9cae-96e8e6bfa4be.jpg)

I have device similar to this : https://de.aliexpress.com/item/32971775060.html

Printer size: 58mm

**Comment by DantSu** [comment]
Your printer seems to not be compatible with ESC/POS commands. So the library is not compatible with your printer.

**Comment by Sarim-Ahmed93** [comment]
> Your printer seems to not be compatible with ESC/POS commands. So the library is not compatible with your printer.

Oh Ok. Thank you. When i print with a network printer the result seems fine. May be it is not compatible with my bluetooth printer.

**Comment by DantSu** [comment]
Yes this bluetooth printer seems to not be compatible with ESC commands (Epson Standard Code for Printers).
https://en.wikipedia.org/wiki/ESC/P
