### ISSUE TITLE
Print Bitmap with a specific size

### ISSUE THREAD

**Issue by celsomh** [DantSu/ESCPOS-ThermalPrinter-Android#114]
How to print a bitmap with a specific size?, when i add width to the bitmap it works, but when i add height it goes back to his normal size(small). I’m using this:
printer.printFormattedText("[L]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap) + "</img>"

**Comment by DantSu** [comment]
Read this issue to split image to keep full size :
#70
