### ISSUE TITLE
Print scrollview bitmap

### ISSUE THREAD

**Issue by ara97** [DantSu/ESCPOS-ThermalPrinter-Android#12]
Hello, I'm trying to print a bitmap of a scrollview. The scrollview has a tablelayout inside it, when there are less than 5 rows in the tablelayout it prints the bitmap without any problems but when there are more than 5 rows it does not print anything. could you help me with this ?

thank you.

**Comment by DantSu** [comment]
Split the bitmap. The size of the bitmap may to be too big for the printer cache. Try to split the bitmap every 200 px.

**Comment by ara97** [comment]
thank you, yeah you are right it seems like the printer can't draw large bitmaps. I solved it by splitting the bitmap as you said and now it prints the bitmap without any problems not matter how many rows the tablelayout has.

**Comment by Fiks33** [comment]
@ara97 can you give sample how to splitting the bitmap & put it on this library?
