### ISSUE TITLE
Problem when print arabic text 

### ISSUE THREAD

**Issue by azmiradi** [DantSu/ESCPOS-ThermalPrinter-Android#122]
![IMG_20210408_142757](https://user-images.githubusercontent.com/46796758/114026749-e4602080-9876-11eb-9f72-e38d61014812.jpg)
![IMG_20210408_143041](https://user-images.githubusercontent.com/46796758/114026853-06f23980-9877-11eb-8274-3bfd41610fb1.jpg)
![IMG_20210408_143032](https://user-images.githubusercontent.com/46796758/114026949-2ab57f80-9877-11eb-82ea-65607b5b5a8d.jpg)

**Comment by DantSu** [comment]
find the correct charset id and charset name used by your printer.
