### ISSUE TITLE
Print in for sentence list, 

### ISSUE THREAD

**Issue by jesulo** [DantSu/ESCPOS-ThermalPrinter-Android#123]
Hi, print in for sentence list, how can I  print after some time (10 seconds)  for cute the paper and then still for sentence. Regards

**Comment by DantSu** [comment]
I don't understand your question

**Comment by jesulo** [comment]
I need to print a list with 5 articles each, for which I use a For statement, but it prints everything at once, how can I use the sleep or Wait method to allow me 5 seconds to start the sheet?

**Comment by DantSu** [comment]
Create a `StringBuilder` and call `printFormattedTextAndCut` just one time. I don't understand your need. Give me example code.

**Comment by jesulo** [comment]
I have a Chinese thermal printer, those mobiles, that you have to tear off the sheet manually. My application generates a list of articles but so that the sheet is not so long I use a for statement to put 7 articles on each sheet, now my problem is that everything is printed at once, I would like the printing to stop 5 seconds at the end of each sheet and thus be able to sort each sheet of 7 items manually

**Comment by jesulo** [comment]
Is there a command to the printer to wait a few seconds before printing something?

**Comment by DantSu** [comment]
No, you can use `Timer.sleep` in an async task.
