### ISSUE TITLE
uncut paper apparently due to disconnect before finishing printing

### ISSUE THREAD

**Issue by zvalejandro** [DantSu/ESCPOS-ThermalPrinter-Android#124]
Thanks for best escpos-thermal printer library for android.

But when I use for example

```
printer.printFormattedTextAndCut(content)
printer.disconnectPrinter()
```

The paper stuck, because of the tests that I have carried out, it has to do with the logo, the instruction to print is sent, apparently it does not finish printing when it is disconnected, so it does not finish printing and no longer cuts.

Could you help me to know if I need some callback or something like that in order to know when the printer finished printing all and after that disconnectPrinter().

Because for example if I add a delay, works as expected but the delay is not the best approach.

```
printer.printFormattedTextAndCut(content)
delay(1000)
printer.disconnectPrinter()
```

Thanks

**Comment by DantSu** [comment]
Try v2.0.11
