### ISSUE TITLE
getDrawableForDensity deprecated

### ISSUE THREAD

**Issue by developerGM** [DantSu/ESCPOS-ThermalPrinter-Android#128]
`PrinterTextParserImg.bitmapToHexadecimalString(printer, this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo, DisplayMetrics.DENSITY_MEDIUM))`

`getDrawableForDensity` is now deprecated. What can we use instead?

**Comment by DantSu** [comment]
Search on stackoverflow and post the answer here !

**Comment by developerGM** [comment]
Do you know how search on stackoverflow?
if I had found the answer I would have already written it here! :D

**Comment by developerGM** [comment]
Ahahah, why you create a public library and than if a dev open ad issue you reply "find by yourself"???
Your library has a bug with image...so if you want solve and have an updated and worked library, fine!

In any case Excellent behavior for community if you answer like that!
