### ISSUE TITLE
Is there any ways to know the printer status?

### ISSUE THREAD

**Issue by yehtetnyimin** [DantSu/ESCPOS-ThermalPrinter-Android#13]
How can we know printer is connected to device? Is there any callback methods to know the printer state : CONNECTED, DISCONNECTED, CONNECTING. Very thank you for your great library and I 'm from Myanmar.I 'm trying to print Myanmar Characters. I bought one chinese 80MM thermal printer [Rongta RPP-300](https://www.rongtatech.com/rpp300-72mm-mobile-printer_p29.html).As your encoding method, `EscPosCharsetEncoding(String charsetName, int escPosCharsetId)`, I don't know how to find my charsetName and escPosCharsetId for that. I knew to use "UTF-8" encoding to print myanmar chars. Thanks for your time.

**Comment by DantSu** [comment]
For printer state, I just publish the v2.0.0 version with a better management of device connection.
For `escPosCharsetId`, read https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/6 . I can't help you more.
