### ISSUE TITLE
When i start a second print, it prints the last print and the new, and successively accumulate the prints

### ISSUE THREAD

**Issue by Christian7glz** [DantSu/ESCPOS-ThermalPrinter-Android#130]
I have 2 activities( “A” and “B”) and both have a button to print some text (Activity “A” has to print “Hola” and Activity “B” has to print “Mundo”)

When i am on the Activity “A”, i click on the button and prints perfectly:
Hola

The problem comes when i move to the Activity “B” and press the button print;
The activity “B” prints:

Hola
Mundo

And if i return to Activity “A” and try to print again, it prints:
Hola
Mundo
Hola

And successively...

im using the same method on both activities(Just changing the text to print) and the USB connection:

public AsyncEscPosPrinter getAsyncEscPosPrinter(DeviceConnection printerConnection) 
{
        AsyncEscPosPrinter printer = new AsyncEscPosPrinter(printerConnection, 203, 48f, 32);
        return printer.setTextToPrint("Hola");
}
How can i erase the past prints and just print the new text?

**Comment by DantSu** [comment]
Wow it's a very weird behavior. Unfortunatly, this month, I haven't enought time to test this bug. I keep this issue opened until I have enought time to test it.

**Comment by Christian7glz** [comment]
Thanks for the support! we keep in touch

**Comment by shaheer20** [comment]
Having same issue

**Comment by DantSu** [comment]
Have try to `.disconnect()` printer before switching activity ?

**Comment by shaheer20** [comment]
Yes i do.

**Comment by DantSu** [comment]
Can you create an example that reproduce this problem on Github that I can clone. Next week I will work on it.

**Comment by Christian7glz** [comment]
Hi DantSu, i made a modified version of this project (i just add a new button to show another view, and that new view has the method printUsb()) to show the issue.

https://github.com/Christian7glz/ThermalPrinter_BugTest.git

**Comment by DantSu** [comment]
thx, I will look it today

**Comment by shaheer20** [comment]
Any update?

**Comment by DantSu** [comment]
You forgot to unregister the receiver before changing activity.

```java
    private void nextView() {
        unregisterReceiver(this.usbReceiver);
        Intent changeView = new Intent(this, Nueva.class);
        startActivity(changeView);
    }
```

Problem solved ;)

**Comment by Christian7glz** [comment]
It works perfectly, thank you @DantSu ! greetings from México.
