### ISSUE TITLE
Image not printing properly

### ISSUE THREAD

**Issue by uplamartya** [DantSu/ESCPOS-ThermalPrinter-Android#132]
On printing image, its as greyish block
 ![1620827521467](https://user-images.githubusercontent.com/47631015/117986700-7b793600-b357-11eb-9f89-5be60489437d.JPEG)

**Comment by DantSu** [comment]
Show me the original picture

**Comment by uplamartya** [comment]
![download](https://user-images.githubusercontent.com/47631015/118154470-b7ce9400-b434-11eb-983b-6c138d8a2b61.png)


this image i am trying to print

**Comment by DantSu** [comment]
Weird, that should work 😕
Jpg, png, gif ? Indexed color, 8bits, 16bits?

**Comment by uplamartya** [comment]
I am using png & not exactly aware of bits.

**Comment by DantSu** [comment]
It's not a transparent background ?

**Comment by uplsourav** [comment]
I'm also facing the same problem, while I'm trying to print it's printing white block instead of the image.

**Comment by uplamartya** [comment]
> It's not a transparent background ?
Yes its a transparent background. with white text on it

**Comment by uplamartya** [comment]
> > It's not a transparent background ?
Yes its a transparent background. with white text on it

**Comment by DantSu** [comment]
Ok that's the problem. Create a black and white picture.

**Comment by uplamartya** [comment]
Thanks @DantSu , Its working now.
