### ISSUE TITLE
Using USB Printer I got too much space in printer receipt.

### ISSUE THREAD

**Issue by jays1799** [DantSu/ESCPOS-ThermalPrinter-Android#133]
![1621050597371](https://user-images.githubusercontent.com/57652965/118450581-fa80bc80-b711-11eb-8eab-636913b3740e.JPEG)

I'm printing data dynamically, using for loop. I think system takes time so meanwhile I got too much space in receipt, I shared receipt for getting better idea. I used Bluetooth code also and it's working good but only I got error in USB Printer function.

Can you please help me to fix this issue, Hope I'll be got respond from your side with positive reply.

Thanks & Regards,
Jay.

**Comment by DantSu** [comment]
Show me your code.

**Comment by jays1799** [comment]
try {
                    printer.printFormattedText(
                        """
                     [C]${getString(R.string.tax_invoice)}
                     [C]<b>${outletsTable?.outlet_name}</b>
                     [C]${outletsTable?.address}
                     [C]MO-${outletsTable?.phone}
                     [L]------------------------------------------------
                     <b>${getString(R.string.date)}          ${getString(R.string.customer)}        ${getString(R.string.bill_no)}</b>
                     [L]------------------------------------------------
                     """.trimIndent()
                    )
                    when {
                        orderForDirectInvoice.customer_name.isNullOrEmpty() -> {
                            printer.printFormattedText(
                                """
                                 [L]${outletsTable?.starting_date}       ${getString(R.string.admin)}       ${orderForDirectInvoice.id}
                                 """.trimIndent()
                            )
                        }
                        !orderForDirectInvoice.customer_name.isNullOrEmpty() && orderForDirectInvoice.customer_name?.length!! >= 15 -> {
                            orderForDirectInvoice.customer_name =
                                orderForDirectInvoice.customer_name?.substring(0, 15)
                            printer.printFormattedText(
                                """
                                 [L]${outletsTable?.starting_date}      ${orderForDirectInvoice.customer_name}    ${orderForDirectInvoice.id}
                                 """.trimIndent()
                            )
                        }
                        else -> {
                            val customer_name =
                                fixedLengthString(
                                    orderForDirectInvoice.customer_name,
                                    14
                                ).toString()
                            printer.printFormattedText(
                                """
                                 [L]${outletsTable?.starting_date}     $customer_name    ${orderForDirectInvoice.id}
                                 """.trimIndent()
                            )
                        }
                    }
                    printer.printFormattedText(
                        """
                    [L]------------------------------------------------
                    [L]<b>${getString(R.string.items)}   |  ${getString(R.string.qty)}   |  ${
                            getString(
                                R.string.dis
                            )
                        }   |  ${
                            getString(
                                R.string.rate
                            )
                        }   |  ${getString(R.string.AMT)}</b>
                    [L]------------------------------------------------
                    """.trimIndent()
                    )

                    orderForDirectInvoice.item?.forEachIndexed { i, _ ->

                        var productShortName = orderForDirectInvoice.item!![i].menuName
                        var discount = orderForDirectInvoice.item!![i].discount_amount
                        var qty = orderForDirectInvoice.item!![i].qty
                        var price = orderForDirectInvoice.item!![i].Price
                        var totalAmount: String? =
                            (if (qty.isNullOrEmpty()) 0.0 else qty.toDouble() * if (price.isNullOrEmpty()) 0.0 else price.toDouble() - if (discount.isNullOrEmpty()) 0.0 else discount.toDouble()).toString()

                        val productName = productShortName!!.replace(" ", "").trim()
                        if (productName.length >= 15) {
                            productShortName = productName.substring(0, 12) + "..."
                            discount = fixedLength(discount, 6)
                            qty = fixedLength(qty, 3)
                            price = fixedLength(price, 6)
                            totalAmount = fixedLength(totalAmount, 7)
                        } else {
                            productShortName = fixedLengthString(productShortName, 15).toString()
                            discount = fixedLength(discount, 6)
                            qty = fixedLength(qty, 3)
                            price = fixedLength(price, 6)
                            totalAmount = fixedLength(totalAmount, 7)
                        }

                        printer.printFormattedText(
                            """ 
                        [L]<font size='small'>$productShortName $qty $discount $price $totalAmount</font>
                    """.trimIndent()
                        )
                    }

                    val subtotal = fixedLength(orderForDirectInvoice.subtotal, 8)
                    val totalDiscount = fixedLength(orderForDirectInvoice.totalDiscount, 8)
                    val delivery = fixedLength(orderForDirectInvoice.delivery, 8)
                    val totalPayble = fixedLength(orderForDirectInvoice.totalPayble, 8)

                    printer.printFormattedTextAndCut(
                        """
                      [L]------------------------------------------------
                      [L]                      ${getString(R.string.sub_total)}  $subtotal
                      [L]            ${getString(R.string.total_discount)}  $totalDiscount
                      [L]                ${getString(R.string.ser_deli_charge)}  $delivery
                      [L]<b>            ${getString(R.string.total_payable)}  $totalPayble</b>
                      [L]
                      [L]************** ${getString(R.string.thanks_for_visit)} *************** "
                      [L]
                      """.trimIndent()
                    )
                    printer.disconnectPrinter()
                } catch (e: EscPosConnectionException) {
                    e.printStackTrace()
                    AlertDialog.Builder(this)
                        .setTitle(getString(R.string.broken_connection))
                        .setMessage(e.message)
                        .show()
                } catch (e: EscPosParserException) {
                    e.printStackTrace()
                    AlertDialog.Builder(this)
                        .setTitle(getString(R.string.invalid_formatted_text))
                        .setMessage(e.message)
                        .show()
                } catch (e: EscPosEncodingException) {
                    e.printStackTrace()
                    AlertDialog.Builder(this)
                        .setTitle(getString(R.string.bad_selected_encoding))
                        .setMessage(e.message)
                        .show()
                } catch (e: EscPosBarcodeException) {
                    e.printStackTrace()
                    AlertDialog.Builder(this)
                        .setTitle(getString(R.string.invalid_barcode))
                        .setMessage(e.message)
                        .show()
                }



>

**Comment by DantSu** [comment]
You have to use StringBuilder class. Create a string that contain the full content of your receipt and call printFormattedText just one time.
