### ISSUE TITLE
 Could not find method implementation() - Can you help me?

### ISSUE THREAD

**Issue by nguyenhuy289** [DantSu/ESCPOS-ThermalPrinter-Android#134]
![image](https://user-images.githubusercontent.com/76772626/118677025-1b3a3680-b826-11eb-8cc6-6669ed5469f0.png)

**Comment by nguyenhuy289** [comment]
Im so sorry, i fixed

**Comment by DantSu** [comment]
How do you fix it ?

**Comment by nguyenhuy289** [comment]
i implemented wrong at /build.gradle, not at /app/build/build.gradle, so sorry

**Comment by DantSu** [comment]
Thx for the answer 🙂
