### ISSUE TITLE
use only formatting of your library without printing part

### ISSUE THREAD

**Issue by dato09** [DantSu/ESCPOS-ThermalPrinter-Android#135]
I want to use your library for formatting text (in android).
I will send your library text in your format  and want to get string generated from it.
It will be good for devices, where to print you need special method to print, which you can not insert in your library.

ex:
String EscText= "[L]\n" +
        "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
        "[L]\n" +
        "[C]================================\n";

String txt = ESCPOS.formatText(EscText);

EscText will contain only text, it won't contain image or barcode.

**Comment by DantSu** [comment]
You can't do that yet. sorry
