### ISSUE TITLE
How can remember printer for after print command ?

### ISSUE THREAD

**Issue by nguyenhuy289** [DantSu/ESCPOS-ThermalPrinter-Android#136]
How can i assign printer into "SharedPreferences" to use for print after ?

I want to choose printer in first time, and then can print from this normally without choose it again after i closed app.

Now, i test in your app, if i choose the printer first time, i can print from this normally. But when i close app, i must choose printer again to print, although i choose it before. If not, once time print OK, but the next command to print, app show error dialog.

![](https://f42-zpg.zdn.vn/6981701022953616996/cc2cac2fe3f216ac4fe3.jpg)

**Comment by DantSu** [comment]
You have to create a sqlite database that save the bluetooth device id to retrieve it after an application restart.

**Comment by nguyenhuy289** [comment]
I have just added new command to check printer. if null, user must check and choose printer and then print again.
