### ISSUE TITLE
How to add image bottom margin or padding 

### ISSUE THREAD

**Issue by natsirasrafi** [DantSu/ESCPOS-ThermalPrinter-Android#137]
How to add image bottom margin or padding , i print image with 1 new line is too close but when i print with 2 new line is to far the space, how to set margin / padding for image ?

**Comment by DantSu** [comment]
Add blank space inside image.

**Comment by natsirasrafi** [comment]
How to add that space automaticaly, i want space by code because many user have many image

**Comment by DantSu** [comment]
At top and bottom, use blank line. Use another library if is not your needs
