### ISSUE TITLE
Print line height is too much

### ISSUE THREAD

**Issue by patrickbussmann** [DantSu/ESCPOS-ThermalPrinter-Android#138]
I'm testing with this demo code.

```
EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32);
printer
    .printFormattedText(
        "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
        "[L]\n" +
        "[C]================================\n" +
        "[L]\n" +
        "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
        "[L]  + Size : S\n" +
        "[L]\n" +
        "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
        "[L]  + Size : 57/58\n" +
        "[L]\n" +
        "[C]--------------------------------\n"
    );
```

And I'm using a printer from the tested printers list -> JP-Q2 POS Terminal PDA (Embedded printer is configured as Bluetooth device).

**This is the output:**

![20210528_scan_163518](https://user-images.githubusercontent.com/15617021/120016253-a6fd5100-bfe4-11eb-8ff2-654ae9822b5f.jpg)

Some ideas?

```
"[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
"[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
```

results in:

![20210528_scan_164127](https://user-images.githubusercontent.com/15617021/120016260-a9f84180-bfe4-11eb-8d81-abd6e1c5f244.jpg)

In the settings I have `Print density` on `5` and `Print coding format` I tried with `CP1251`, `UTF-8` and `GBK`.

Thanks for help 😊

**Comment by DantSu** [comment]
It's not a line height problem. Your printer doesn't reconized ESC/POS commands. Do you have a esc pos mode to enabled somewhere ?

**Comment by patrickbussmann** [comment]
But font size is working, too. Only the line height is a bit crazy.
Maybe there is one command which is not recognized?

When I debug the command which is generated by your library there are many "32" bytes in it at each column end.
I think this is the problem.

So simple "H\ne\nl\nl\no" has 5 columns with configuration ESC commands and many 32 at the end.

I only wondering because this printer is in the tested printers list.

**Comment by DantSu** [comment]
Underline and bold not works. 9.99e have to be on the same line of  beautiful shirt. It's not line height, the printer back to new line too many times.

**Comment by patrickbussmann** [comment]
But this small example:

```
EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32);
printer.printFormattedText("H\ne\nl\nl\no");
```

Results in many line breaks, too.
And there is no formatting.

Do you know how to solve that problem?



And one question "by the way" I wanted to make a pull request for reading from POS printer. -> For getting the status.
Do you have an idea how to do this? Separate thread for reading?

**Comment by DantSu** [comment]
Which version do you use ?

I searched and I did not find any way to get data from printer. I haven't find solution to get status.

**Comment by patrickbussmann** [comment]
I'm using newest one.

For the status I think about this:
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=124#gs_lr

I think its as easy as your "stream.write". -> "stream.read".
Separate thread and then we can read the whole time and if there is data which we can proceed then we can do.
Or?

**Comment by DantSu** [comment]
Unfortunately, I can't help you. Your problem seems to come from your printer. I think some esc pos commands is not reconized. This printer has added by a contributor in the list. I haven't this model and I can't test it.

For the printer status, this command is for paper end, ink level... my printer doesn't have this sensors. I can't test it. I searched command for printing status (currently printing, printing ended...) but withoit success.
