### ISSUE TITLE
What is configuration for 3 inch ? paper size, words and all ?

### ISSUE THREAD

**Issue by flobizDipen** [DantSu/ESCPOS-ThermalPrinter-Android#14]

**Comment by htooaunghlaing** [comment]
Currently I'm using that config for my 3 " printer.
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 72f, 48);
203 is your printerDPI,
72f is printing width in MM
48 is characters per line,
I hope this will help for you.
