### ISSUE TITLE
Is there a way to detect the width of the printer?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [DantSu/ESCPOS-ThermalPrinter-Android#140]
I'm currently using `EscPosPrinter(DeviceConnection printerConnection, int printerDpi, float printerWidthMM, int printerNbrCharactersPerLine)` to create a printer, but I wonder if is there is a way to detect the width of the printer? Is this supported? I'm currently passing a hardcoded value but I need to support two different printer with different widths

**Comment by DantSu** [comment]
Hi, no.
