### ISSUE TITLE
Sound before print 

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [DantSu/ESCPOS-ThermalPrinter-Android#142]
How should i play default  sound of printer if have before print any receipt

**Comment by DantSu** [comment]
I don't know any command that can do that.

**Comment by DantSu** [comment]
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=212#esc_lparen_ca_fn48
May be this. But I can't help you more.

**Comment by iAmAndroidDeveloper** [comment]
Ok but I have not any specific printer like Epson also have several printers so must used command that support in all printers

**Comment by DantSu** [comment]
Your printer is compatible with ESC Command. Epson Standard Commands.

**Comment by iAmAndroidDeveloper** [comment]
@DantSu i declare following sound command in EscPosPrinterCommands class how i used and check sound before print any receipt please guide me

public static final byte[] PRINTER_SOUND = new byte[]{27, 66, 2, 1};

**Comment by DantSu** [comment]
what's 27, 66, 2, 1 where did you find it ?

something like this should works :

```
                    DeviceConnection deviceConnection = printerData.getPrinterConnection();

                    if(deviceConnection == null) {
                        return AsyncEscPosPrint.FINISH_NO_PRINTER;
                    }

                   deviceConnection.write(new byte[]{27, 66, 2, 1});
                   deviceConnection.send();

                    EscPosPrinter printer = new EscPosPrinter(
                            deviceConnection,
                            printerData.getPrinterDpi(),
                            printerData.getPrinterWidthMM(),
                            printerData.getPrinterNbrCharactersPerLine(),
                            new EscPosCharsetEncoding("windows-1252", 16)
                    );

                    this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);

                    printer.printFormattedTextAndCut(printerData.getTextToPrint());

                   deviceConnection.write(new byte[]{27, 66, 2, 1});
                   deviceConnection.send();
```

**Comment by iAmAndroidDeveloper** [comment]
@DantSu this command already work in one of my friends application for print receipt, Let me try this and let you know if working for me then i think you can also check and integrate this feature as well

Mostly as i know this command useful for Kitchen print when many extra noise present so chef not focus on printer only and sound alert them for new order

**Comment by iAmAndroidDeveloper** [comment]
@DantSu this command not working please share if you have anything regarding same

**Comment by DantSu** [comment]
Maybe this works according to the documentation : https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=211

But `n, c: different depending on the printers`. This command this to not be standard...

```java
                   deviceConnection.write(new byte[]{0x1B, 0x28, 0x41, 0x04, 0x00, 0x30, 0x00, 0x01, 0x10});
                   deviceConnection.send();
```

**Comment by iAmAndroidDeveloper** [comment]
@DantSu  when i used this code after convert Hexadecimal  {27, 66, 2, 1} and check it's work

**Comment by DantSu** [comment]
What's the final code ?

**Comment by iAmAndroidDeveloper** [comment]
i Just create on function on EscPosPrinterCommands class

 /**
     * printers sound.
     */
    public EscPosPrinterCommands addSound() {
        if (!this.printerConnection.isConnected()) {
            return this;
        }

        this.printerConnection.write(new byte[]{0x1b,0x42,0x02,0x01});
        try {
            this.printerConnection.send(100);
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
        return this;
    }

This call from 

 public EscPosPrinter printFormattedTextAndOpenCashBox(String text, int dotsFeedPaper) throws EscPosConnectionException, EscPosParserException, EscPosEncodingException, EscPosBarcodeException {
        if (this.printer == null || this.printerNbrCharactersPerLine == 0) {
            return this;
        }

       //Just call it from here and its work 
        this.printer.addSound();

}

**Comment by DantSu** [comment]
Thx for your reply

**Comment by iAmAndroidDeveloper** [comment]
I think you comment something else what you say please tell me for my knowledge may be I was wrong with above code

**Comment by DantSu** [comment]
This is a good example and if anyone else open an issue for a simimar thing I will redirect him here.

**Comment by iAmAndroidDeveloper** [comment]
@DantSu i am facing receipt printing issue only Bluetooth printer :-  bottom part of the receipt goes to next receipt upper part

Printer:- Xprinter XP-N160II 80mm Thermal Receipt Printer

val printer = AsyncEscPosPrinter(printerConnection, 203, 75f, 48)

**Comment by DantSu** [comment]
Plz open a new issue
