### ISSUE TITLE
Label printing

### ISSUE THREAD

**Issue by donUA** [DantSu/ESCPOS-ThermalPrinter-Android#143]
Is it possible to print barcode labels with this library?

**Comment by DantSu** [comment]
I don't know. Maybe ^^
Which printer do you use to do that ?

**Comment by donUA** [comment]
I have a Bluetooth thermal printer (58mm). I use the library to print bills and it works fine. However, I can't use it to print barcode labels since it doesn't recognize the gaps in-between the labels.

**Comment by DantSu** [comment]
You can use dotFeedPaper param.

**Comment by donUA** [comment]
Please expound on that.

**Comment by DantSu** [comment]
search in documentation dotsFeedPaper
