### ISSUE TITLE
Tall and big font size print problem

### ISSUE THREAD

**Issue by vviwork** [DantSu/ESCPOS-ThermalPrinter-Android#146]
Thanks for awesome library. The idea to define report markup is great!

I'm using Milestone MHT-P80F printer (ESCPOS, 80mm) with ESCPOS-ThermalPrinter-Android v2.0.11.

I have a print problem using font tag with Tall and Big size: print line height is cropped.
When I print font size test from RawBT app, it prints without problems. 

I saw a similar issue [Print big or tall font why cropped](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/88)

```
EscPosCharsetEncoding charsetEncoding = new EscPosCharsetEncoding("windows-1252", 16);
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 72f, 48, charsetEncoding);
printer.printFormattedText(
       "[L]Font sizes:\n" +
       "\n" +
       "[L]<font size='normal'>normal Font Size</font>\n" +
       "[L]<font size='wide'>wide Font Size</font>\n" +
       "[L]<font size='tall'>tall Font Size</font>\n" +
       "[L]<font size='big'>Font Size Big</font>\n" +
       "[L]<b>Bold Text</b>\n" +
       "[L]<u>Underlined Text</u>\n"); 
```

Print outputs:
![20210614_140645](https://user-images.githubusercontent.com/63791603/121885469-de763800-cd1c-11eb-92fb-7cef30090993.jpg)

**Comment by DantSu** [comment]
I can"t help you, this works well on my printer. I don't where this problem come from.

**Comment by vviwork** [comment]
I'm ok to donate to buy Milestone MHT-P80F printer for test purposes.
Let me know if it is good suggestion.

**Comment by DantSu** [comment]
Can you try this ?
```java
printer.printFormattedText(
       "[L]<font size='tall'>\n" +
       "[L]Tall Font Size\n" +
       "[L]</font>\n"); 
```

**Comment by vviwork** [comment]
```
            EscPosCharsetEncoding charsetEncoding = new EscPosCharsetEncoding("windows-1252", 16);
            EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 72f, 48, charsetEncoding);
            printer.printFormattedText(
                    "[L]<font size='tall'>\n" +
                    "[L]Tall Font Size\n" +
                    "[L]</font>\n");
```

![20210615_140336](https://user-images.githubusercontent.com/63791603/122042634-1182ff00-cde3-11eb-9201-764ff00720c1.jpg)

**Comment by DantSu** [comment]
I don't understand what's going on.

**Comment by vviwork** [comment]
Many thanks for your attention.

I planning to: 
- get another Milestone MHT-P80F printer instance
- contact printer manufacturer support
- test printer SDK

**Comment by DantSu** [comment]
Any news ?

**Comment by vviwork** [comment]
Not really much to share. Waiting for printer support feedback.
I decided to use wide font size as a temp workaround for big fonts.

I have detected that my printer instance firmware has no code pages support(only GBK).
Another printer instance firmware has support but does not print code pages Ids 
in self test page. I want to get sorted with these basic issues before going further.

![Image_20210618_124536](https://user-images.githubusercontent.com/63791603/124933166-5712a080-e00c-11eb-9a52-31f33ff31dde.jpeg)

**Comment by DantSu** [comment]
In v3.0.0, I have add this : 

```java
    /**
     * Print all characters of all charset encoding
     *
     * @return Fluent interface
     */
    public EscPosPrinter printAllCharsetsEncodingCharacters() {
        this.printer.printAllCharsetsEncodingCharacters();
        return this;
    }

    /**
     * Print all characters of selected charsets encoding
     *
     * @param charsetsId Array of charset id to print.
     * @return Fluent interface
     */
    public EscPosPrinter printCharsetsEncodingCharacters(int[] charsetsId) {
        this.printer.printCharsetsEncodingCharacters(charsetsId);
        return this;
    }

    /**
     * Print all characters of a charset encoding
     *
     * @param charsetId Charset id to print.
     * @return Fluent interface
     */
    public EscPosPrinter printCharsetEncodingCharacters(int charsetId) {
        this.printer.printCharsetEncodingCharacters(charsetId);
        return this;
    }
```

That will print all characters of a charset id.

**Comment by vviwork** [comment]
Cool and handy feature.

**Comment by yovi-ep** [comment]
halo, me too

payload:
[C]<font size='tall'>Nueta Toserba PT</font>
[C]<font size='normal'>jl pattimura 22 blok bc101</font>
[C]<font size='normal'>Kab. Tangerang Banten 22553</font>
[C]<font size='normal'>Indonesia</font>
[C]<font size='normal'>SI.2021.07.00061</font>
[C]<font size='normal'>14 Juli 2021</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>Pelanggan Umum</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>Nama Produk</font>[R]<font size='normal'>Total Harga</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>adidas tanpa disc def</font>
[L]<font size='normal'>1 PCS x 500.000</font>[R]<font size='normal'>500.000</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>Sub Total</font>[R]<font size='normal'>500.000</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>Total</font>[R]<font size='normal'>500.000</font>
[L]<font size='normal'></font>
[C]<font size='normal'>|BELUM LUNAS|</font>
[L]<font size='normal'>Jatuh tempo</font>[R]<font size='normal'>14/07/2021</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>Kurang bayar</font>[R]<font size='normal'>500.000</font>
[L]<font size='normal'>--------------------------------</font>
[L]<font size='normal'>rna nisssa</font>[R]<font size='normal'>14/07/2021 15:04</font>
[L]<font size='normal'></font>
[C]<font size='normal'>--TERIMAKASIH--</font>

and result:
![photo_2021-07-14_16-05-50](https://user-images.githubusercontent.com/17000456/125595427-ef8af96a-ca9d-4e9b-9741-55dafcd6ba83.jpg)

can you help me?

**Comment by yovi-ep** [comment]
> halo, me too
> 
> payload:
> [C]Nueta Toserba PT
> [C]jl pattimura 22 blok bc101
> [C]Kab. Tangerang Banten 22553
> [C]Indonesia
> [C]SI.2021.07.00061
> [C]14 Juli 2021
> [L]--------------------------------
> [L]Pelanggan Umum
> [L]--------------------------------
> [L]Nama Produk[R]Total Harga
> [L]--------------------------------
> [L]adidas tanpa disc def
> [L]1 PCS x 500.000[R]500.000
> [L]--------------------------------
> [L]Sub Total[R]500.000
> [L]--------------------------------
> [L]Total[R]500.000
> [L]
> [C]|BELUM LUNAS|
> [L]Jatuh tempo[R]14/07/2021
> [L]--------------------------------
> [L]Kurang bayar[R]500.000
> [L]--------------------------------
> [L]rna nisssa[R]14/07/2021 15:04
> [L]
> [C]--TERIMAKASIH--
> 
> and result: there is character <y
> ![photo_2021-07-14_16-05-50](https://user-images.githubusercontent.com/17000456/125595427-ef8af96a-ca9d-4e9b-9741-55dafcd6ba83.jpg)
> 
> can you help me?

and i have tried encoder:
"windows-1252", 16, and
"windows-1252", 6

**Comment by yovi-ep** [comment]
> halo, me too
> 
> payload:
> `[C]<font size='tall'>Nueta Toserba PT</font>`
> `[C]<font size='normal'>jl pattimura 22 blok bc101</font>`
> `[C]<font size='normal'>Kab. Tangerang Banten 22553</font>`
> `[C]<font size='normal'>Indonesia</font>`
> `[C]<font size='normal'>SI.2021.07.00061</font>`
> `[C]<font size='normal'>14 Juli 2021</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>Pelanggan Umum</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>Nama Produk</font>[R]<font size='normal'>Total Harga</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>adidas tanpa disc def</font>`
> `[L]<font size='normal'>1 PCS x 500.000</font>[R]<font size='normal'>500.000</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>Sub Total</font>[R]<font size='normal'>500.000</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>Total</font>[R]<font size='normal'>500.000</font>`
> `[L]<font size='normal'></font>`
> `[C]<font size='normal'>|BELUM LUNAS|</font>`
> `[L]<font size='normal'>Jatuh tempo</font>[R]<font size='normal'>14/07/2021</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>Kurang bayar</font>[R]<font size='normal'>500.000</font>`
> `[L]<font size='normal'>--------------------------------</font>`
> `[L]<font size='normal'>rna nisssa</font>[R]<font size='normal'>14/07/2021 15:04</font>`
> `[L]<font size='normal'></font>`
> `[C]<font size='normal'>--TERIMAKASIH--</font>`
> 
> and result: there is character <y
> ![photo_2021-07-14_16-05-50](https://user-images.githubusercontent.com/17000456/125595427-ef8af96a-ca9d-4e9b-9741-55dafcd6ba83.jpg)
> 
> can you help me?

and i have tried encoder:
"windows-1252", 16, and
"windows-1252", 6

**Comment by DantSu** [comment]
It's not the same problem open a new issue

**Comment by yovi-ep** [comment]
waw, my issue has deleted.
bay the way, my issue resolved with:
`printer.printFormattedText(`
`       "[L]<font size='tall'>Halo</font>" +`
`       "\n"`
` ); `

**Comment by DantSu** [comment]
@yovi-ep open your own issue

**Comment by vviwork** [comment]
![charsets 0-20](https://user-images.githubusercontent.com/63791603/127629508-84178b16-c7b6-4189-9178-c64336027b4b.jpeg)
Few new facts to share:

1. I have tested font size printing on other two Milestone MHT-P80F printers
   The same tall and big font size print problem.
   
2. It looks that printer ignores ESC t command and uses code page configured 
   on printer manually with buttons. Printout for v3.0.0 printCharsetEncodingCharacters
   for charset range 0 - 20:

**Comment by vviwork** [comment]
No feedback from printer support. I'm closing this issue for a while.

**Comment by DantSu** [comment]
Yes it seems to be the same charset !
