### ISSUE TITLE
EscPosPrinterCommands: default escPosCharsetId typo

### ISSUE THREAD

**Issue by vviwork** [DantSu/ESCPOS-ThermalPrinter-Android#147]
EscPosPrinterCommands.java

```
    public EscPosPrinterCommands(DeviceConnection printerConnection, EscPosCharsetEncoding charsetEncoding) {
        this.printerConnection = printerConnection;
        this.charsetEncoding = charsetEncoding != null ? charsetEncoding : new EscPosCharsetEncoding("windows-1252", 6);
    }
```
Is it correct to say that 6 is a typo and 16 is a right value?

**Comment by DantSu** [comment]
No is not correct, each printer have their own charset ID. For my printer, 6 is the correct value for windows-1252. For your printer maybe is 16 or 28 or 52 or another number between 0 and 255, I don't know.
