### ISSUE TITLE
ean8 barcode

### ISSUE THREAD

**Issue by jesulo** [DantSu/ESCPOS-ThermalPrinter-Android#149]
Hi, 

I m printing number 1000001 but codebar print 10000007, 

"[R]<barcode type='ean8'>"+1000001+"</barcode>\n";

printing number 1234567 but codebar print 12345670, 

"[R]<barcode type='ean8'>"+1234567 +"</barcode>\n";

what can be the error?

**Comment by DantSu** [comment]
It's not an error. The last number is calculated with seven first number. Same for ean13.
