### ISSUE TITLE
Not Working On Handheld pos Terminal 

### ISSUE THREAD

**Issue by AdilTechDart** [DantSu/ESCPOS-ThermalPrinter-Android#15]
GZWEIOU Pda Printer Supplies Handheld pos Terminal With All in one Thermal Printer Android Mobile POS Smart Roll Pos Paper NFC
here is the link:
https://tinyurl.com/ycak9cv2

**Comment by DantSu** [comment]
It seems to not be a ESC printer so the library isn't compatible.

**Comment by AdilTechDart** [comment]
This is where i am getting the error.The error is
"Attempt to read from null array" 
![image](https://user-images.githubusercontent.com/37257868/83738155-5c652500-a66d-11ea-9160-9a871996ad75.png)
Is there any way to put the UUID manually in BluetoothConnection class?

**Comment by AdilTechDart** [comment]
Add a method in BluetoothConnection class to set UUID

**Comment by htooaunghlaing** [comment]
I think "Attempt to read from null array" has been fixed in V2.0.0. Please make sure you are using V2.0.0.

**Comment by AdilTechDart** [comment]
Yes it fixed but i need a method to set the UUID in BluetoothConnection class manually

**Comment by DantSu** [comment]
Can you test the v2.0.3 on your embedded printer ?

**Comment by AdilTechDart** [comment]
Is there any way to open the cash register after print?

**Comment by saputraiqbal** [comment]
I've came with the same problem when run on Android Lollipop (v5.0.2) Changing to v2.0.3 or higher solved the UUID error, but it pops out another error. I got "java.io.IOException: read failed, socket might closed or timeout, read ret: -1" after getting output stream in BluetoothConnection.java when run on debug

**Comment by saputraiqbal** [comment]
It looks like this. I run it on Samsung Grand Prime
![image](https://user-images.githubusercontent.com/17638445/91930723-cf814480-ed0b-11ea-9643-6b8c7a162510.png)
