### ISSUE TITLE
Half of the portion is Printing

### ISSUE THREAD

**Issue by flobizDipen** [DantSu/ESCPOS-ThermalPrinter-Android#151]
- I am generating the Bill with this library, already 48+ Lacs users are using our [application](https://play.google.com/store/apps/details?id=com.valorem.flobooks&hl=en_IN&gl=US)

- In our application, we are iterating the item list which may have any number of items (Mostly can have 60-70 items)
- Printing properly but stuck after some time, Let's say after 25 items it's not able to print

**Comment by DantSu** [comment]
How do you print items ?
Share me some code to see if a work around is possible.

**Comment by flobizDipen** [comment]
Please check the code

```
private fun getItemListForThreeInch(list: List<Item>): String {
        var itemList = ""
        val srNo = "SN"
        val mrpHeader = "Mrp"
        val qtyHeader = " Qty" // 5
        val unit = "Unt"
        val rate = "Rate"
        val amount = "Amount"

        var srNoLength = 4
        var qtyLength = 11
        var unitLength = 3
        var mrpLength = 0
        var rateLength = 14
        var amountLength = 15

        if (list.isNotEmpty()) {
            itemList = "<font size ='$smallFontSize'><b>" +
                    "${PrintingHelper.trimWithLength(srNo, srNoLength, "end")}$space" +
                    "Item Description" + getNewLine() +
                    "${PrintingHelper.trimWithLength(qtyHeader, qtyLength, "end")}$space" +
                    "${PrintingHelper.trimWithLength(unit, unitLength, "start")}$space" +
                    "${PrintingHelper.trimWithLength(mrpHeader, mrpLength, "start")}$space" +
                    "${PrintingHelper.trimWithLength(rate, rateLength, "start")}$space" +
                    "${PrintingHelper.trimWithLength(amount, amountLength, "start")}</b></font>\n" +
                    getNewLineWithDashes()

            for (i in list.indices) {

                val item = list[i]

                itemList +=
                    PrintingHelper.trimWithLength((i + 1).toString(), srNoLength, "end") + space
                itemList += "${item.name}\n"
                itemList += " ${
                PrintingHelper.trimWithLength(
                        item.quantity.toString().convertToDouble().truncateAfterThreeDecimal(),
                        qtyLength,
                        "end"
                )
                }$space"
                itemList += "${
                PrintingHelper.trimWithLength(item.selectedUnit ?: "", unitLength, "start")
                }$space"
                itemList += getMrp(item.mrp ?: "0.0", mrpLength, isMRP)
                itemList += "${
                PrintingHelper.trimWithLength(
                        getPriceWithTax(item.totalAmount, item.quantity),
                        rateLength,
                        "start"
                )
                }$space"
                itemList += "${
                PrintingHelper.trimWithLength(
                        item.totalAmount.roundUpToTwoDecimal().toBigDecimal().toPlainString(),
                        amountLength,
                        "start"
                )
                }\n"
            }
        }

        return itemList
    }
```


trimWithLength - It will check the length of the length and concatenate the space based on "Start" and "End"

**Comment by flobizDipen** [comment]
I am using this printer
https://www.atpos.in/product/atpos-at-502-80mm-3-inch-thermal-receipt-printer-usblan-auto-cutter/

**Comment by DantSu** [comment]
So you genrate the full text of your bill and call juste one time printFormattedTextAndCut, that's it ?

**Comment by flobizDipen** [comment]
Yes I am preparing the formatted data first and then running `printer.printFormattedTextAndCut(content)` command.

Also, it is a very random issue, sometimes works sometimes not,
Happen to one of our customers. He connected the printer from multiple mobile devices.

**Comment by flobizDipen** [comment]
These are list of steps

```
BluetoothConnections().list.find { it.device.address == selectedThermalPrinter.printerAddress }
            ?.let { _connection ->
                    _connection.connect()
                    val printer = EscPosPrinter(
                        _connection,
                        PageSizeEnum.TWO_INCH.printerDpi,
                        PageSizeEnum.TWO_INCH.printerWidthMM,
                        pageSize
                    )
                    val content = PrintingHelper.getPrintingFormattedData(
                        invoiceDetail = voucher,
                        currentCompany = currentCompany,
                        invoiceParty = party,
                        itemList = invoiceItemList,
                        itemSubtotal = itemSubtotal,
                        cessAmount = keralaCessAmount,
                        discountValue = discountValue,
                        totalValue = totalValue,
                        showBranding = showBranding()
                    )

                    val status = if (content.isNotEmpty()) {
                        printer.printFormattedTextAndCut(content)
                    }
}
```

**Comment by DantSu** [comment]
Bluetooth connection cause many problems. I think something is missing in the `[BluetoothConnection](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/connection/bluetooth/BluetoothConnection.java)` class but after many research I don't find anything. It's very difficult to resolv because it's totaly random. I will continue to investigate on it.

**Comment by flobizDipen** [comment]
So you are saying the connection is lost while printing? But if that is the case then how print works a second time or print correctly for shorter invoices?

**Comment by DantSu** [comment]
if it's connect multiple device on a same printer, I think that others printers can broke the connection. Bluetooth device never works properly with many connection.

Or maybe the library seems to randomly send to many data than the printer can accept. and broke the printing. 

I don't know what's the real source of this issue.

**Comment by flobizDipen** [comment]
Okay, it might be an issue, well I will also work on this issue, update you if I found anything.
Thanks, @DantSu for your time.

**Comment by DantSu** [comment]
I have look other project to see how they manage bluetooth connection... I don't do anything wrong in my code... but bluetooth isn't stable... I really don't know how fix this...

**Comment by DantSu** [comment]
I have do some update on bluetooth connection. I don't think that fix your bug but you can try.
