### ISSUE TITLE
Bluetooth printer print issue

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [DantSu/ESCPOS-ThermalPrinter-Android#153]
@DantSu i am facing receipt printing issue only Bluetooth printer :- bottom part of the receipt goes to next receipt upper part

Printer:- Xprinter XP-N160II 80mm Thermal Receipt Printer

val printer = AsyncEscPosPrinter(printerConnection, 203, 75f, 48)

When i am increase printer DPI that time image not proper center alignment can you please help me

**Comment by DantSu** [comment]
Share me a photo please

**Comment by iAmAndroidDeveloper** [comment]
![image](https://user-images.githubusercontent.com/26490351/123759294-62175380-d8dd-11eb-9f13-6a0dcdc491fe.png)

**Comment by iAmAndroidDeveloper** [comment]
@DantSu i just attached receipt image can you please check

**Comment by DantSu** [comment]
You have to decrease the picture size. Yet, It's too big.

**Comment by iAmAndroidDeveloper** [comment]
@DantSu which one ? didn't get your point, please explain

**Comment by DantSu** [comment]
it's a pre-cut paper ? And you want to reduce the picture height no ?

**Comment by iAmAndroidDeveloper** [comment]
@DantSu  i think some confusions in that 

My question is :- it's a pre-cut paper as you can see in shared image not picture size

**Comment by DantSu** [comment]
So you want to have a receipt that fill inside the pre cut paper.

**Comment by iAmAndroidDeveloper** [comment]
yes i want that print full receipt and then after cut paper and this issue faced only Bluetooth printer only

**Comment by iAmAndroidDeveloper** [comment]
![image](https://user-images.githubusercontent.com/26490351/123763203-2c746980-d8e1-11eb-86a6-853b71fb73ed.png)

Check above receipt its cut before print full given text and when i try to print anther one then half of previous one are display in next receipt

In-short i want that after print full text for print and then and then only cut the paper @DantSu let me know should i do anything wrong in given code?

**Comment by DantSu** [comment]
Ok so it's not a precut paper. It's cut by the printer ? The printer doesn't wait to finish to print the text for cutting the paper ?

**Comment by iAmAndroidDeveloper** [comment]
Yes now you got that actual point, should I do anything wrong?

**Comment by iAmAndroidDeveloper** [comment]
Yes, I used same

But when I change any param like Dpi Or printer size(mm) then results not got that i want

Should I pass anything wrong?

**Comment by DantSu** [comment]
no, that the bluetooth problem.
Share me the code part when you call printFormattedTextAndCut.

**Comment by iAmAndroidDeveloper** [comment]
val printer = AsyncEscPosPrinter(printerConnection, 203, 72f, 48)

AsyncBluetoothEscPosPrint(context).execute( printer.setTextToPrint("text ant image that go for print") )

**Comment by DantSu** [comment]
No this issue come from bluetooth. Your printer don't execute command in order that it receive it. That 's it.
```java
            EscPosPrinter printer = new EscPosPrinter(
                    deviceConnection,
                    printerData.getPrinterDpi(),
                    printerData.getPrinterWidthMM(),
                    printerData.getPrinterNbrCharactersPerLine(),
                    new EscPosCharsetEncoding("GB18030", 16)
            );

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);

            printer.printFormattedText(printerData.getTextToPrint());

            try {
                Thread.sleep(500);
             } catch (InterruptedException e) {
                e.printStackTrace();
             }

            printer.printFormattedTextAndCut("");

```

**Comment by DantSu** [comment]
Your printer doesn't finish to print when it execute cut command. So you can wait 0.5 seconds to send cut command. It's an ugly workarround.

**Comment by iAmAndroidDeveloper** [comment]
ok le me try this

**Comment by iAmAndroidDeveloper** [comment]
@DantSu your solution worked for me, Thanks i am closing this issue
