### ISSUE TITLE
Thermal Print Coming Blank while printing

### ISSUE THREAD

**Issue by flobizDipen** [DantSu/ESCPOS-ThermalPrinter-Android#155]
Info : 
[Printer Info of User](https://www.xprintertech.com/portable-usb-receipt-printer-xp-p323b)

When a user is trying to print the invoice/ bill from [myBillBook](https://play.google.com/store/apps/details?id=com.valorem.flobooks&hl=en_IN&gl=US) only blank print is coming out from the printer.

I tried user to check with another app too where the user is able to test the print.

Any known issue related to this?

**Comment by flobizDipen** [comment]
**Reference Video**

https://user-images.githubusercontent.com/52924493/123972222-49d82f00-d9d8-11eb-9315-ff94c2f0bfab.mp4

**Comment by DantSu** [comment]
I see "TSPL、EPL、ZPL、DPL、CPCL、ESC/POS", ask us if there are on ESC/POS mode.

**Comment by DantSu** [comment]
In second time, that can be the id Charset Encoding, that refer to an unknow charset table inside the printer.

**Comment by DantSu** [comment]
The problem with charsets, It's that every printer have there own charsets. You can't made an application that works with all printers. Or you have to print only image.

**Comment by flobizDipen** [comment]
Okay regarding **print only Images**

- I need to generate HTML format from android and feed the data dynamically and after convert it to the image and print
That's what you are suggesting right?
- Image Height can be an issue in that case? (Eg. Longer Bills)

**Comment by DantSu** [comment]
see this : 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70#issuecomment-714390014

**Comment by gaikwadChetan93** [comment]
I also faced the same problem. I solved it by changing the charset to cp437.
But yeah, the best way is to print only images as suggested by @DantSu
