### ISSUE TITLE
Datecs Dpp-250 don't get listed

### ISSUE THREAD

**Issue by maicomstoppa** [DantSu/ESCPOS-ThermalPrinter-Android#156]
Hi! 

The function BluetoothPrintersConnections.getList() doesn't list the printer "DPP-250" from "DATECS LTD" (https://www.datecs.bg/en/products/61). 

The issue is that this device's MajorDeviceClass and DeviceClass are set as 7936 (0x00001f00) - UNCATEGORIZED.

I believe it is a good idea to accommodate this situation in the function, since it is probably  a bigger problem to hide  miscategorizated devices that are printers than show miscategorizated devices that aren't.

```
if ((majDeviceCl == BluetoothClass.Device.Major.IMAGING || majDeviceCl == 7936) && (deviceCl == 1664 || deviceCl == 7936 || deviceCl == BluetoothClass.Device.Major.IMAGING)) {
    printersTmp[i++] = new BluetoothConnection(device);
}
```

Thank you. Your work in this library is very much appreciated.

**Comment by DantSu** [comment]
Extend the class and override the method. I will not add "UNCATEGORIZED" in the default method.
