### ISSUE TITLE
Alignment not looking as per expectation on variable paper/roll width 

### ISSUE THREAD

**Issue by uplamartya** [DantSu/ESCPOS-ThermalPrinter-Android#157]
printerWidthMM parameter not working .

**Comment by DantSu** [comment]
it's works.
Explain your problem....

**Comment by uplamartya** [comment]
@DantSu Sorry for delayed reply, Actually I am using a roll of 88mm & passing the value to  printerWidthMM parameter but the alignment doesn't look as expected.

**Comment by DantSu** [comment]
Take a picture of a receipt. Share me your code where you create a new instance of `EscPosPrinter`. And give specification of your printer : Number of characters printed on the same line in medium size, dpi of the printer

**Comment by uplamartya** [comment]
receipt picture - 
![1625820018871](https://user-images.githubusercontent.com/47631015/125050465-977f2680-e0bf-11eb-9566-152876964fcb.JPEG)

EscPosPrinter initialization block -
<img width="1237" alt="Screenshot 2021-07-09 at 2 13 18 PM" src="https://user-images.githubusercontent.com/47631015/125050689-d319f080-e0bf-11eb-9824-7de695f7974a.png">

printer I am using - 
https://www.flipkart.com/shreyans-srs80b-80mm-portable-bluetooth-mobile-printer-3-inch-thermal-receipt/p/itmc6efba4e1f740

**Comment by DantSu** [comment]
You don't count how many chars per line this printer print.
 It's not 32

**Comment by DantSu** [comment]
48 characters per line. Read the documentation before open an issue

**Comment by DantSu** [comment]
`new EscPosPrinter(printerConnection, 203, 76f, 48)`

**Comment by uplamartya** [comment]
Thanks man, this works. 😊
