### ISSUE TITLE
Printing @ anonymously  at the start of second page print

### ISSUE THREAD

**Issue by umarwaqaas** [DantSu/ESCPOS-ThermalPrinter-Android#158]
I am printing two pages simultaneously , but for the second page @ sign appear before the text.
But when I print the second page only it (@ the rate ) didn't appear.

The alignment for the qr code is not working as it takes few more spaces to left side .

**Comment by DantSu** [comment]
2 pages simultaneously ? On the same printer ?

Reduce the printerWidthMM value. It's millimeter width of printing area, not the width of the paper so you have to substract 4mm (2mm margin on each side).

**Comment by umarwaqaas** [comment]
Absolutely 2 pages printing  simultaneously on the same printer . 

Reducing printerWidthMM value doesn't affect it.

**Comment by DantSu** [comment]
if you don't share code, screen, picture, I can't help you.
