### ISSUE TITLE
Character encoding issue with some printer

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [DantSu/ESCPOS-ThermalPrinter-Android#166]
I used character encoding type GB18030 actually don't know it's charsetId so I passed default 16 but some printer got issue in Chinese character have any solution for that? @DantSu

**Comment by DantSu** [comment]
Each printer model have their own charsets id table. You can't do a universal application.

**Comment by iAmAndroidDeveloper** [comment]
Ok but same thing working in many printer and not working in some of 

Any solution for that?

**Comment by DantSu** [comment]
Only solution is human. Or you can reference all printer models and create a correlation table... but it's impossible due to the lot of existing models.

**Comment by iAmAndroidDeveloper** [comment]
@DantSu This "GB18030" encoding type working with most of language like Chinese, English, Japanese as i check some different company's printer you need to just pass this encoding type and change following and its work you can check it your own
```
/**
     * Create new instance of EscPosCharsetEncoding.
     *
     * @param charsetName Name of charset encoding (Ex: windows-1252)
     * @param escPosCharsetId Id of charset encoding for your printer (Ex: 16)
     */
    public EscPosCharsetEncoding(String charsetName, int escPosCharsetId) {
        this.charsetName = charsetName;
        this.charsetCommand = new byte[]{0x1B, 0x52, 0x15};
       //this.charsetCommand = new byte[]{0x1B, 0x52, (byte) 54936};
    }
```
You just replace this `this.charsetCommand = new byte[]{0x1B, 0x52, 0x15};` and its work

**Comment by DantSu** [comment]
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=29 
You replace by this command. 21 isn't referenced in the official documentation.
All printer doesn't have same index.
