### ISSUE TITLE
LAN and Bluetooth printer printing not smooth

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [DantSu/ESCPOS-ThermalPrinter-Android#168]
https://user-images.githubusercontent.com/26490351/129145655-a994d82c-e5a6-4681-a16a-18c37b8e53c0.mp4

Please check @DantSu i attached video of LAN printer with printing Bitmap and QR code but its not printing smooth

**Comment by DantSu** [comment]
Normal behavior, due to the time that take to transfert data.

**Comment by iAmAndroidDeveloper** [comment]
@DantSu When i used any specific SDK for particular product printer like epson library and try to print same receipt with epson library logic code its working fine print without ziczac

**Comment by DantSu** [comment]
You have a Epson Android SDK ?

**Comment by DantSu** [comment]
You can't compare this library with a sdk for specific product...

**Comment by iAmAndroidDeveloper** [comment]
ok NP but any solution that working without any ziczac when i send all details before print without printing time logic
Actually i used imin library for here device only [https://docs.imin.sg/docs/en/DevicesInfo.html#d4](url)

**Comment by iAmAndroidDeveloper** [comment]
https://user-images.githubusercontent.com/26490351/129184000-4124e6cf-79f9-4738-8235-29501ad8f579.mp4

Please check video that's print speedy only QR print have stuck some millisecond but its ok
