### ISSUE TITLE
Connected To Printer

### ISSUE THREAD

**Issue by GitKyRep** [DantSu/ESCPOS-ThermalPrinter-Android#17]
how to check device is connected to printer ?

**Comment by htooaunghlaing** [comment]
I still hope for that with callback for device and printer status : CONNECTED, DISCONNECTED, CONNECTING

**Comment by DantSu** [comment]
All can be do with Exception : 

If you read the code of `BluetoothPrintersConnections.selectFirstPaired()` : 

```java
        BluetoothPrintersConnections printers = new BluetoothPrintersConnections();
        BluetoothConnection[] bluetoothPrinters = printers.getList();
        
        if (bluetoothPrinters != null && bluetoothPrinters.length > 0) {
            for (BluetoothConnection printer : bluetoothPrinters) {
                try {
                    return printer.connect();
                } catch (EscPosConnectionException e) {
                   // Printer is disconnected
                    e.printStackTrace();
                }
            }
        }
        return null;
```

You can see that `BluetoothPrintersConnections.selectFirstPaired()` return `null` if no printer is connected to the device.

If you print text and the printer is disconnected, it's throwing an exception, like this : 

```java
        try {
            EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 48f, 32);
            printer .printFormattedText("[L]Some text to print\n[L][R]Some text to print\n");
        } catch (EscPosConnectionException e) {
            // The printer is disconnected !
        } catch (EscPosParserException e) {
            // There is a formatted text problem (Bad syntax)
        } catch (EscPosEncodingException e) {
            // There is an encoding character problem
        } catch (EscPosBarcodeException e) {
            // There is a QRCode or Barcode generation problem
        }
```

> I still hope for that with callback for device and printer status : CONNECTED, DISCONNECTED, CONNECTING

The status "CONNECTING" doesn't exists. Devide is connected or disconnected. With Exception you have the answer of this question.

If you want to display a windows with a loader during the printing, you have to use a separated thread like : 

```java
public class AsyncEscPosPrint extends AsyncTask<EscPosPrinter, Integer, Integer>
```

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/app/src/main/java/com/dantsu/thermalprinter/MainActivity.java

You can read the asynchronous implementation. It might interrest you.
Git clone or pull the master branch, and test it.
