### ISSUE TITLE
Should i send Byte code to printer for print accept string?

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [DantSu/ESCPOS-ThermalPrinter-Android#172]
@DantSu should i send Byte code to printer for print accept string format that you created with tags?

**Comment by DantSu** [comment]
I don't understand your need

**Comment by iAmAndroidDeveloper** [comment]
I create receipt with convert text in to bytes and add all bytes command in to one list (like open drawer command, center text command, font size command) 

How should I pass this list of bytes command direct to printer

**Comment by DantSu** [comment]
`printerConnection.write()` and `printerConnection.send()`. I think this what you looking for.

**Comment by iAmAndroidDeveloper** [comment]
Ok let me check same and let you know
