### ISSUE TITLE
unknown error 9

### ISSUE THREAD

**Issue by 19AshutoshMishra** [DantSu/ESCPOS-ThermalPrinter-Android#173]
Getting unknown error 9 toast msg at the time of printing via inbuilt printer available in Android POS

**Comment by DantSu** [comment]
See your log

**Comment by 19AshutoshMishra** [comment]
That was battery issue battery percentage was 2% only.

**Comment by 19AshutoshMishra** [comment]
Now i am getting another issue my device printer roll paper is scrolling and getting out but nothing is printed on it (it is blank).
