### ISSUE TITLE
Printer not show in the list of BluetoothPrintersConnections

### ISSUE THREAD

**Issue by MMohamad70** [DantSu/ESCPOS-ThermalPrinter-Android#176]
Hi,

I am using this library for connecting to the printers inside my application. Everything was ok with my previous printer. But now I am using a new printer which is not known when getting the list of connected printers. 
I should mention that the printer is paired with Bluetooth in the setting of the device, but not showing inside my application when using this method: BluetoothPrintersConnections().list

Printer: KP80B

Is the library has any problem with this printer?! what should I do to support it?

![photo_2021-08-25 19 30 19](https://user-images.githubusercontent.com/8926585/130815978-3e17c7dc-f994-49a3-ab25-9c3cdf28e72d.jpeg)

**Comment by joskar201** [comment]
> use `BluetoothConnections.getList()` to find your printer.

I tried this but I only get an empty list.

**Comment by DantSu** [comment]
I wrote `BluetoothConnections` and not `BluetoothPrintersConnections`. `BluetoothConnections.getList()` list all bluetooth device, not only printers.

**Comment by MMohamad70** [comment]
I Think `BluetoothPrintersConnections().list` has some limitations on identifying some kind of printers. By the way, `BluetoothConnections.getList()` lists all the Bluetooth devices and this is just fine by me, thank you.
