### ISSUE TITLE
Font not work

### ISSUE THREAD

**Issue by thiagoreri** [DantSu/ESCPOS-ThermalPrinter-Android#178]
When applying as fonts, such as

`<font size="big">test</font>`

print comes out

!test!

My printer is Bematech 4200 th

**Comment by DantSu** [comment]
This printer accept two types of commands ESC/BEMA & ESC/POS ... are sure to be on esc/pos ? May be you are in esc/bema mode and you have to switch to esc pos mode.

**Comment by thiagoreri** [comment]
where do i change this configuration

**Comment by DantSu** [comment]
I don't know. It's your printer
