### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by Aashir1111** [DantSu/ESCPOS-ThermalPrinter-Android#179]
Some time with Bluetooth connection i face this problem. when i give cmd to print 
                    printer.printFormattedTextAndCut(textToPrint.toString())
then Exception "Broken Pipe"

**Comment by DantSu** [comment]
I know... bluetooth is lame. Use USB or TCP that will be better.

**Comment by thinhlh** [comment]
I still face this problem when trying to use TCP

**Comment by mayerfabian** [comment]
same problem. when phone sleeps 4 a while and reopen app pipe is broken

**Comment by jaco** [comment]
I had the same issue with broken pipe and solution is pretty straight forward.

When I get broken pipe exception, I call disconnectPrinter() and retry print. Works like a charm :)

**Comment by natsirasrafi** [comment]
> I had the same issue with broken pipe and solution is pretty straight forward.
> 
> When I get broken pipe exception, I call disconnectPrinter() and retry print. Works like a charm :)

can you share how the code ? detect broken pipe connection and disconnect dan retri?
