### ISSUE TITLE
Printer get disconnected before all content printed on Android 11

### ISSUE THREAD

**Issue by RHMDHDYT** [DantSu/ESCPOS-ThermalPrinter-Android#184]
I have a case in my app to make the printer idle (ready to make other connection) after printing so it can be used for other devices. Previously I don't have any issue on Android 10 and below, it's working as expected. Just found it on Android 11.

To make it easier to repro, I'm using the demo app. The implementation was like this:

```
            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);

            printer.printFormattedTextAndCut(printerData.getTextToPrint());
            printer.disconnectPrinter();

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTED);
```
            
File: AsyncEscPosPrint.java

It will stop the printer before reaching the end of the content demo on Android 11.

do you found the same issue @DantSu ?

**Comment by DantSu** [comment]
Do you use Bluetooth ?

**Comment by RHMDHDYT** [comment]
@DantSu yes, im using bluetooth connection

**Comment by DantSu** [comment]
It's very because I use flush() to force data transmission. So data should be send before disconnect... Wich version do you use ?

**Comment by RHMDHDYT** [comment]
@DantSu I'm using 3.0.1. Agree, when it uses a `flush()` all data are passed to OS but it doesn't guarantee that it has been written on the printer. Seem's like the data transmission between OS and Printer in OS 11 is slower than the previous OS. But, I did not found yet what's changed in OS 11.

Btw to make sure this is not Custom OS issue, I have tested on Samsung Galaxy A71 & Xiaomi POCO X3 NFC

**Comment by DantSu** [comment]
Only solution is to use `Thread.sleep(waitingTime);` before disconnect.

**Comment by RHMDHDYT** [comment]
I also thought of that solution, but the waiting time should be dynamic because my app doesn't limit the item's transaction.

I'm curious what the `send(int addWaitingTime)` is for?
and how did you find this formula: `int waitingTime = addWaitingTime + this.data.length / 16;`
I have tried this, put 1 to 5 waiting time value but still no lucky.
```
public void send(int addWaitingTime) throws EscPosConnectionException {
        if(!this.isConnected()) {
            throw new EscPosConnectionException("Unable to send data to device.");
        }
        try {
            this.outputStream.write(this.data);
            this.outputStream.flush();
            int waitingTime = addWaitingTime + this.data.length / 16;
            this.data = new byte[0];
            if(waitingTime > 0) {
                Thread.sleep(waitingTime);
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            throw new EscPosConnectionException(e.getMessage());
        }
    }
    ```

**Comment by DantSu** [comment]
"addWaitingTime" is in millisecond so you have to pass minimum 300 or more to be signifiant.

"addWaitingTime + this.data.length / 16" this formula was found with my phone and printer, I tried many values to prevent image printing corruption, and this formula adapt waiting time to the data length. `addWaitingTime` is for little command like cutting paper or paper feed that take physical time but only 3 bytes to be send.

try `Thread.sleep(500);`

**Comment by k1n6m4n** [comment]
Hello, I'm facing the same issues here, if I print a longer text, the result will cut off at some point. 

I'm testing using OS 11 and 9, both have same issue, but with OS 9 I can print way longer than OS 11

is there anyway to workaround this issue? 

@DantSu where should I put the Thread.sleep(500); ? can you be more specific?

thanks

**Comment by DantSu** [comment]
After printFormattedTextAndCut and before disconnectPrinter.

**Comment by k1n6m4n** [comment]
Yes sir, it's working now... but I need to raised it up to 3000.

500 still stop at some point, and 3000 doesn't really matter since the receipt I need to print out averagely took more or less 3 seconds too.

thank you very much!

**Comment by RHMDHDYT** [comment]
Well, in my case it's still not working for receipt format with a lot of items printed like 45 items and up but it works on small items. It needs a longer dynamic value of delay.

In OS 11 I've found that the OutputStream should not be closed until the printer motor stop rolling or it will still get cut off before reaching the end of the content. Seems like the OS emitting the bytes part by part.

Thank you for fast-responding @DantSu I think nothing we can do since the printer / OutputStream doesn't have any callback to notify when the printer has finished printing the data. I'm closing this issue.

**Comment by DantSu** [comment]
I have search commands to get printing status without success... I think is a big miss !

**Comment by RHMDHDYT** [comment]
@DantSu interesting, would you elaborate more on `get printing status without success` ?

**Comment by DantSu** [comment]
Sorry bad wording. I don't find any commands to get printing status.

**Comment by k1n6m4n** [comment]
@RHMDHDYT I make something like this to calculate dynamic delay time, maybe not best solution but it's working on my apps

```
 private long getDelayTime(String mPrintText) {
        int mDelay = 100;

        String[] mListImg = mPrintText.split("</img>");
        mDelay += ((mListImg.length) * 500);

        String[] mListRow = mPrintText.split("</font>");
        mDelay += ((mListRow.length) * 50);

        return mDelay;
    }
```

so basicly i just parsed how many line to print, every line i added 50 ms, and every image i print i added 500 ms

I managed to print out client logo on top, 60 lines of text and an QR code at the bottom
