### ISSUE TITLE
Text is printed with chinese characters (CP866, 17)

### ISSUE THREAD

**Issue by Divasik** [DantSu/ESCPOS-ThermalPrinter-Android#185]
I use charset cp866 (page 17) with cyrillic characters, but printer gives me chinese.

After some tests I see the problem is in Chinese character mode on my Xprinter XP-300, 
I resolved it with sending 0x1C, 0x2E (Cancel chinese mode) so printCharsetEncodingCharacters() gives me write characters.

BUT printFormattedText() still prints chinese, it seems printer.reset() inside this method cancels that 0x1C, 0x2E, so I have to extend EscPosPrinter overriding printFormattedText() with reset() extraction.

Please, extract this reset() to use commands before printing, and implement Chinese mode cancellation.

**Comment by DantSu** [comment]
The good way is to do  : 

```java
public class MyEscPosPrinterCommands extends EscPosPrinterCommands {
    public static final byte[] CANCEL_CHINESE = new byte[]{0x1C, 0x2E};
    /**
     * Reset printers parameters.
     */
    public EscPosPrinterCommands reset() {
        if (!this.printerConnection.isConnected()) {
            return this;
        }
        super.reset();
        this.printerConnection.write(EscPosPrinterCommands.CANCEL_CHINESE);
        return this;
    }
}
```

and do : 

```java
EscPosPrinter printer = new EscPosPrinter(new MyEscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired(), charsetEncoding), 203, 48f, 32);
```

**Comment by Divasik** [comment]
Ok, thanks!
