### ISSUE TITLE
printer width not handle bluetooth

### ISSUE THREAD

**Issue by mohsinmughal1630** [DantSu/ESCPOS-ThermalPrinter-Android#187]
Hi, my receipt print but its not human understandable i think the issue is in width and printer dpi please help me with that?

Printer: High Speed 58 thermal printer with print speeds over 70mm/s. 
Paper roll specification: 58mm / 40mm

My code
 val printer = EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32 )

**Comment by mohsinmughal1630** [comment]
![d798b762-314e-495b-9da6-b8213ce8296b](https://user-images.githubusercontent.com/75029620/134362038-28bc31d9-34b1-49bc-96ee-4c79249c07c7.jpeg)

**Comment by DantSu** [comment]
You have a charset encoding problem. Find the list of charset of your printer

**Comment by mohsinmughal1630** [comment]
how i can find this?

**Comment by mohsinmughal1630** [comment]
lifecycleScope.launch(Dispatchers.IO) {

                            try {

                                
                                val printer = EscPosPrinter(
                                    BluetoothPrintersConnections.selectFirstPaired(),
                                    203,
                                    48f,
                                    32
                                )


                                printer.printFormattedText(
                                    """
        [C]<img>${
                                        PrinterTextParserImg.bitmapToHexadecimalString(
                                            printer,
                                            src
                                        )
                                    }</img>
                                    
        """.trimIndent(), 0
                                )

                                try {
                                    Thread.sleep(500)
                                } catch (e: InterruptedException) {
                                    e.printStackTrace()
                                }

                                printer.printFormattedTextAndCut("")


                            } catch (exception: Exception) {
                                showAlertDialog(exception.message.toString())
                            }


                        }

**Comment by mohsinmughal1630** [comment]
please help me i waste so much time on it please

**Comment by DantSu** [comment]
On your manual or print selftest of your printer

**Comment by DantSu** [comment]
Ohh you print only image ??

**Comment by DantSu** [comment]
If you save the image in a jpg file. What did you see ?

**Comment by mohsinmughal1630** [comment]
Yes i only print image

**Comment by mohsinmughal1630** [comment]
No that is the xml layout which i convert into bitmap and pass there

**Comment by DantSu** [comment]
Save your bitmap in a file

**Comment by mohsinmughal1630** [comment]
![CB8B5A7D-40D5-46F6-ACAB-8227BF1F0AD0](https://user-images.githubusercontent.com/75029620/134372981-32543a01-1899-4f49-9dfe-c9a0008827c4.jpeg)

**Comment by DantSu** [comment]
What's the resolution ?

**Comment by mohsinmughal1630** [comment]
![FC39D1AF-14AA-45FB-B4A8-20E99BC27B44](https://user-images.githubusercontent.com/75029620/134374451-e5e823e5-41e4-48a4-bc03-bc9079e6d68a.jpeg)
Please see that is storing perfect

**Comment by mohsinmughal1630** [comment]
private fun generateBitmapFromView(view: View): Bitmap {
        val specWidth = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
        val specHeight = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
        view.measure(specWidth, specHeight)
        val width = view.measuredWidth
        val height = view.measuredHeight
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        view.layout(view.left, view.top, view.right, view.bottom)
        view.draw(canvas)
        return bitmap
    }

**Comment by mohsinmughal1630** [comment]
Sir that is the code from which i generate bitmap

**Comment by mohsinmughal1630** [comment]
Sir😒

**Comment by DantSu** [comment]
Try tobgenerate a 406px width version

**Comment by mohsinmughal1630** [comment]
Sorry i didn’t understand?

**Comment by DantSu** [comment]
48mm / 25.4 * 203 = the width of your image to be printed

**Comment by mohsinmughal1630** [comment]
Okay so what’s the code i write and where?

**Comment by DantSu** [comment]
>  private fun generateBitmapFromView(view: View): Bitmap {
>         val specWidth = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
>         val specHeight = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
>         view.measure(specWidth, specHeight)
>         val width = view.measuredWidth
>         val height = view.measuredHeight
>         val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
>         val canvas = Canvas(bitmap)
>         view.layout(view.left, view.top, view.right, view.bottom)
>         view.draw(canvas)
>         return bitmap
>     }

The bitmap that you generate here. Try to generate a bitmap of 383px width.

Then you have to split this image.

**Comment by mohsinmughal1630** [comment]
Sir i have only one image for print so i don’t need to make the list of bitmaps?

**Comment by DantSu** [comment]
Read this issue https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70#issuecomment-714390014

**Comment by DantSu** [comment]
You can also do that but the image must have a correct width.

- 1 inch = 25.4mm
- Thermal printer commonly have 203px by inch.
- So the width of the printed bitmap must be `millimetersWidthPrintingZone / 25.4 * 203` pixels.

```java
        EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(printerConnection);
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(myBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }

```

**Comment by mohsinmughal1630** [comment]
![image](https://user-images.githubusercontent.com/75029620/134494035-eb20048d-a87a-4819-be24-88d745aff902.jpeg)

Sir please see that is the now i use and this is the output

      Thread {
                            try {
                                val printer = EscPosPrinter(
                                    BluetoothPrintersConnections.selectFirstPaired(),
                                    203,
                                    48f,
                                    32
                                )

                                val byteArrayOutputStream = ByteArrayOutputStream()
                                src.compress(Bitmap.CompressFormat.PNG, 70, byteArrayOutputStream)
                                val byteArray: ByteArray = byteArrayOutputStream.toByteArray()
                                val encoded: String =
                                    Base64.encodeToString(byteArray, Base64.DEFAULT)
                                val decodedByte =
                                    BitmapFactory.decodeByteArray(byteArray, 0, byteArray.size)
                                val width = decodedByte.width
                                val height = decodedByte.height
                                val textToPrint = StringBuilder()

                                var y = 0
                                while (y < height) {
                                    val bitmap = Bitmap.createBitmap(
                                        decodedByte,
                                        0,
                                        y,
                                        width,
                                        if (y + 256 >= height) height - y else 256
                                    )
                                    textToPrint.append(
                                        """
                [C]<img>${PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap)}</img>
                
                """.trimIndent()
                                    )
                                    y += 256
                                }
                                textToPrint.append("[C]Printed!!!\n");
                                printer.printFormattedTextAndCut(textToPrint.toString());
                            } catch (e: java.lang.Exception) {
                                e.printStackTrace()
                            }
                        }.start()

**Comment by mohsinmughal1630** [comment]
Please i need help

**Comment by DantSu** [comment]
Try this : 
```java
       Bitmap myBitmap = this.generateBitmapFromView(view):
       EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(printerConnection);
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(myBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

**Comment by DantSu** [comment]
> The image must have a correct width :
>
>1 inch = 25.4mm
>Thermal printer commonly have 203dpi (dots per inch / pixels per inch).
>So the width of the printed bitmap must be Math.floor(millimetersWidthPrintingZone / 25.4 * 203) pixels or >Math.floor(inchWidthPrintingZone * 203) pixels.

Read my previous answer

**Comment by DantSu** [comment]
keep in mind that you have 2~4 mm margin each side so the printing zone is 57mm - 4~8mm => 49~53mm

**Comment by mohsinmughal1630** [comment]
from where i get this millimetersWidthPrintingZone
and where i get these dots per inch / pixels per inch

**Comment by DantSu** [comment]
> from where i get this millimetersWidthPrintingZone

take a ruler and measure it

> and where i get these dots per inch / pixels per inch

On you printer manual. Commonly is 203.

**Comment by DantSu** [comment]
Test with this : 
48 mm for millimetersWidthPrintingZone
203 dpi

48mm / 25.4 * 203 = 383 pixels

Like I said in previous post : Generate an image of 383 pixels width

**Comment by mohsinmughal1630** [comment]
5 inches of my printer paper width so what's the code i write and where?

**Comment by DantSu** [comment]
no is not an 5 inchs

**Comment by DantSu** [comment]
> private fun generateBitmapFromView(view: View): Bitmap {
> val specWidth = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
> val specHeight = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
> view.measure(specWidth, specHeight)
> val width = view.measuredWidth
> val height = view.measuredHeight
> val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
> val canvas = Canvas(bitmap)
> view.layout(view.left, view.top, view.right, view.bottom)
> view.draw(canvas)
> return bitmap
> }

Generate here an image with  383px width !!

**Comment by mohsinmughal1630** [comment]
did you please tell how i set this pixel i search alot

**Comment by mohsinmughal1630** [comment]
its a request

**Comment by DantSu** [comment]
bitmap = Bitmap.createScaledBitmap(bitmap, bitmapWidth, bitmapHeight, false);

Try this : 
```java
       Bitmap viewBitmap = this.generateBitmapFromView(view):
       Bitmap myBitmap = Bitmap.createScaledBitmap(
           viewBitmap, 
           383, 
           Math.round(((float) viewBitmap.getHeight()) * 383f / ((float) viewBitmap.getWidth())), 
           true
       );

       EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(myBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

**Comment by DantSu** [comment]
Does it works ?

**Comment by mohsinmughal1630** [comment]
Sir thank you its work but not perfect

fonts not perfect if you i attach two images in first image it showing half but font looking perfect in second image its full receipt showing but fonts no
![second last](https://user-images.githubusercontent.com/75029620/134666731-ead0b8bf-e394-48b4-8116-833f4eb8eacc.jpeg)
t clear as mu
![last image](https://user-images.githubusercontent.com/75029620/134666746-ebe43551-5d1a-4cc9-a036-9c5b95c130aa.jpeg)
ch

**Comment by DantSu** [comment]
Try this to remove marging from view that will increase font size : 

```java
       Bitmap viewBitmap = this.generateBitmapFromView(view):
       Bitmap myBitmap = Bitmap.createBitmap(viewBitmap, 30, 30 ,viewBitmap.getWidth() - 30, viewBitmap.getHeight() - 30);
       myBitmap = Bitmap.createScaledBitmap(
           viewBitmap, 
           383, 
           Math.round(((float) viewBitmap.getHeight()) * 383f / ((float) viewBitmap.getWidth())), 
           true
       );

       EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(myBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

**Comment by DantSu** [comment]
Send me a picture of final render

**Comment by DantSu** [comment]
Try this, I have fix a problem : 

```java
       int originalMarginSize = 30;
       Bitmap viewBitmap = this.generateBitmapFromView(view):
       Bitmap myBitmap = Bitmap.createBitmap(viewBitmap, originalMarginSize, originalMarginSize,viewBitmap.getWidth() - originalMarginSize, viewBitmap.getHeight() - originalMarginSize);
       myBitmap = Bitmap.createScaledBitmap(
           myBitmap, 
           383, 
           Math.round(((float) viewBitmap.getHeight()) * 383f / ((float) viewBitmap.getWidth())), 
           true
       );

       EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(myBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

**Comment by laithbzour** [comment]
@DantSu 

image after convert to PrinterTextParserImg.bitmapToHexadecimalString is corrupted what is wrong ??
