### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by fitalinformatica** [DantSu/ESCPOS-ThermalPrinter-Android#188]
Good afternoon, I've implemented zebra printer support in my App, for printing labels it's an excellent printer, posi offers support for printing using ZPL, EPL language that allows you to position elements very easily. However, as it is an extremely expensive printer here in BRAZIL, since it is quoted in dollars, to acquire a PT-210 ESC/POS printer from CHINA, and I loved this library, but I have difficulty rotating the elements that are printed on paper, that is, 90 degrees. I looked in the ESC/POS specification... for a way to do this, I even found the byte[] hex that allows you to rotate the element, but when I send a text, it prints everything in a single column, it doesn't distribute it horizontally.

Att
Sebastiao Fidencio

**Comment by DantSu** [comment]
Hi, share us photos, pieces of code of your problem.

**Comment by fitalinformatica** [comment]
Good Morning,

![WhatsApp Image 2021-09-24 at 08 18 05](https://user-images.githubusercontent.com/77156789/134667796-2ab10591-9ada-455b-bb6c-470e5341a2a4.jpeg)

Follow the way the print is coming out with the 58mm printer model Goojprt PT-210.

Note the arrow rotating clockwise, I need to rotate the content 90º, as this paper is very narrow, so I get more out of the label printing in the other direction.



![image](https://user-images.githubusercontent.com/77156789/134668139-302d4df3-d9a7-4386-9221-80ca7c5611f7.png)
I tried various methods to observe the above situation, I even created the code in computer hexadecimal in the documentation for the low platform ESC / POS command, which allowed this process to run, but it still didn't work.

Maybe I don't know where to put this logic, or I'm hitting my head with something ESC/POS can't do, but I believe you have the answer to that question.


Regards ,
Sebastiao Fidencio

**Comment by DantSu** [comment]
Seems to works only on text. Not on image, barcode or anything else.

https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=30

### [Notes]
- The 90° clockwise rotation mode is effective for alphanumeric, Kana, multilingual, and user-defined characters.
- When underline mode is turned on, the printer does not underline 90° clockwise-rotated characters.
- When character orientation changes in 90° clockwise rotation mode, the relationship between vertical and horizontal directions is reversed.
- The 90° clockwise rotation mode has no effect in Page mode.
- Some printer models support 90° clockwise rotation mode when n = 2 or 50.
- Some printer models have a font for which 90° clockwise rotation mode is not effective.
- Settings of this command are effective until ESC @ is executed, the printer is reset, or the power is turned off.

**Comment by DantSu** [comment]
Maybe this will works : 
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=55

**Comment by DantSu** [comment]
But this library use standard mode not page mode.

**Comment by fitalinformatica** [comment]
Grateful for the information, I will analyze... the possibility.

See how the zebra print looks here..that was how necessary.

![índice](https://user-images.githubusercontent.com/77156789/134672149-f75ceedf-e142-4868-a4d3-46f8a3a37640.jpg)

![índice2](https://user-images.githubusercontent.com/77156789/134672229-0f7af309-df8b-44fb-a56a-612414e4d1d6.jpg)

**Comment by DantSu** [comment]
Maybe you can try : 

Extend `EscPosPrinterCommands` like this : 
```java
public class MyEscPosPrinterCommands extends EscPosPrinterCommands {
    public static final byte[] ENABLE_PAGE_MODE = new byte[]{0x1B, 0x4C};
    public static final byte[] PAGE_MODE_DIRECTION = new byte[]{0x1B, 0x54, 0x02};
    /**
     * Reset printers parameters.
     */
    public EscPosPrinterCommands reset() {
        if (!this.printerConnection.isConnected()) {
            return this;
        }
        super.reset();
        // ACTIVE HERE PAGE MODE AND DIRECTION
        this.printerConnection.write(EscPosPrinterCommands.ENABLE_PAGE_MODE);
        this.printerConnection.write(EscPosPrinterCommands.PAGE_MODE_DIRECTION);
        return this;
    }
}
```

and do : 

```java
EscPosPrinter printer = new EscPosPrinter(new MyEscPosPrinterCommands(deviceConnection, charsetEncoding), 203, 48f, 32);
```

**Comment by DantSu** [comment]
say me if it works

**Comment by fitalinformatica** [comment]
Franck,

I ran the tests now at my lunchtime, and it didn't work, below are the videos...

Thank you for your attention and understanding of the matter.


Yours sincerely,
Sebastiao Fidencio



1º
https://drive.google.com/file/d/1-yK_Uy_9vYOWLdD9kNYcb18knUIGV4Kl/view?usp=sharing

2º
https://drive.google.com/file/d/1-ygNcDBGs59EZHeeQUYKccTt6BS2tWXs/view?usp=sharing

3º
https://drive.google.com/file/d/1-zsUXPavzg0BboEaP8Ch6Q7D-tPsvHyx/view?usp=sharing

**Comment by DantSu** [comment]
Sorry it was my only option to solve your need. :( I don't know how do that.

**Comment by fitalinformatica** [comment]
![image](https://user-images.githubusercontent.com/77156789/134716889-0a705e87-f217-43ed-91f3-e68e28501d8c.png)

Thank you for the committed data, however, no problem.

I will wait for another printer that we acquired ESC / POS to arrive from CHINA, who knows it works, then I will report it here. Thank you anyway.

Note that in the image, it shows printing in another direction, certainly this one has the page mode option.


Regards

**Comment by DantSu** [comment]
You can do that if you generate a Bitmap programmatically and print bitmap, but is more complicated.

**Comment by fitalinformatica** [comment]
In fact, I saw another developer proposing a similar solution, however, I'll wait for the printer to arrive to test the solution you proposed directly in the library, however, if it doesn't work, I'll check the possibility of the bitmap. I don't know at what point I could get the byte array converted through ASCII, and convert it to bitmap, then rotate it using "Canvas"... I got a bit lost, where could I fit this solution into your LIB .


Look at the proposal on another project.

https://github.com/anastaciocintra/escpos-coffee/issues/58

**Comment by fitalinformatica** [comment]
Good evening, passing to say that I solved my problem with printer above, it has ESC / POS support, but I used her SDK, called LPAPI, which allows to print the label using the drawings, X and Y, etc.. and so on. Via ESC/POS it is possible to print only Receipts, because this language uses the maximum size or width of the coil, whether 58mm or 80mm, so that it works with alignments to the left, center and right, that is, does not work with DPI. It would be even possible, but converting the label to Bitmap.
 
Thanks!


![image](https://user-images.githubusercontent.com/77156789/140452729-58882eb6-0418-47ad-b42e-37d93071941e.png)

**Comment by Eftychiou** [comment]
Can you please help me to solve this ? How can i print text and barcode 90% rotated ?

**Comment by fitalinformatica** [comment]
It's not 90% but 90º, the printer has to be supported as CPLC, or ZPL, or TSPL languages. In the case of this NETUM printer, it has its own SDK or API that allows you to rotate images and texts, or shapes, in short, it's called LPAPI.

**Comment by Eftychiou** [comment]
> Good evening, passing to say that I solved my problem with printer above, it has ESC / POS support, but I used her SDK, called LPAPI, which allows to print the label using the drawings, X and Y, etc.. and so on. Via ESC/POS it is possible to print only Receipts, because this language uses the maximum size or width of the coil, whether 58mm or 80mm, so that it works with alignments to the left, center and right, that is, does not work with DPI. It would be even possible, but converting the label to Bitmap.
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/77156789/140452729-58882eb6-0418-47ad-b42e-37d93071941e.png)

can i have the link to this lpapi sdk please ?

**Comment by Eftychiou** [comment]
> It's not 90% but 90º, the printer has to be supported as CPLC, or ZPL, or TSPL languages. In the case of this NETUM printer, it has its own SDK or API that allows you to rotate images and texts, or shapes, in short, it's called LPAPI.

can you provide link to this LPAPI sdk please ?

**Comment by Eftychiou** [comment]
![Untitled](https://user-images.githubusercontent.com/72862933/164216367-626c46c5-d4c8-4dec-9d68-16aaa20b6090.png)
![20220420_135713](https://user-images.githubusercontent.com/72862933/164216388-88c023e5-c0e6-4859-bc9b-5eeaf42a2664.jpg)

I am changing the width value(shown in the picture) but the width on the paper remains the same . What could it be ?

**Comment by DantSu** [comment]
583mm = 58.3cm....0.6 meter.

**Comment by DantSu** [comment]
This value is for images alignment only.

**Comment by Eftychiou** [comment]
but isn't this hexadecimal value  ? What is the last parameter printerNbrCharactersPerLine used for ? I've tried to half it from 32 to 16 to see if i can restrict the characters per line but failed :/

**Comment by DantSu** [comment]
for text alignment, if you do [C]test or [R]test with 16 and 32, you will see a difference.
Is not for restriction. just used for alignment.

**Comment by Eftychiou** [comment]
Thanks, now i can see the changes.
I am trying to apply the chocolate solution of creating an image and rotating it by 90°, i have tried to figure out where should i apply in your code but it seems that i can't rotate the whole thing but it could be possible to rotate each line after transforming it to an image right ?
________________________________

**Comment by kelalaka153** [comment]
> Maybe you can try :
> 
> Extend `EscPosPrinterCommands` like this :
> 
> ```java
> public class MyEscPosPrinterCommands extends EscPosPrinterCommands {
>     public static final byte[] ENABLE_PAGE_MODE = new byte[]{0x1B, 0x4C};
>     public static final byte[] PAGE_MODE_DIRECTION = new byte[]{0x1B, 0x54, 0x02};
>     /**
>      * Reset printers parameters.
>      */
>     public EscPosPrinterCommands reset() {
>         if (!this.printerConnection.isConnected()) {
>             return this;
>         }
>         super.reset();
>         // ACTIVE HERE PAGE MODE AND DIRECTION
>         this.printerConnection.write(EscPosPrinterCommands.ENABLE_PAGE_MODE);
>         this.printerConnection.write(EscPosPrinterCommands.PAGE_MODE_DIRECTION);
>         return this;
>     }
> }
> ```
> 
> and do :
> 
> ```java
> EscPosPrinter printer = new EscPosPrinter(new MyEscPosPrinterCommands(deviceConnection, charsetEncoding), 203, 48f, 32);
> ```

This cannot be work since `printerConnection` is private.
