### ISSUE TITLE
Print line height is too much

### ISSUE THREAD

**Issue by developerGM** [DantSu/ESCPOS-ThermalPrinter-Android#189]
I have a problem about text format only if I use this:
JP-Q2i POS Terminal PDA (Embedded printer is configured as Bluetooth device)

There is a but line height and text on the right [R] is printed on the start left.

This is the result
![image](https://user-images.githubusercontent.com/9252653/134691692-0bb57061-d9f2-47e4-aacc-0e8eaef0a7af.png)

**Comment by DantSu** [comment]
This printer do not understand basic esc/pos commands. Printer not compatible with this library.
