### ISSUE TITLE
Does Vietnamese support

### ISSUE THREAD

**Issue by taphuong** [DantSu/ESCPOS-ThermalPrinter-Android#19]
I need to use Vietnamese. Can you help me ?

**Comment by DantSu** [comment]
If you read the documentation :

You have to go https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32 and see : 
> 52 | Page 52 [WPC1258: Vietnamese]

If your printer has the same encoding table as the ESPON models, this code should works :

`EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32, new EscPosCharsetEncoding("windows-1258", 52));`

**Comment by DantSu** [comment]
On my printer it's 94 : 
`EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32, new EscPosCharsetEncoding("windows-1258", 94));` for vietnamese characters.

**Comment by taphuong** [comment]
I tried with 52 and 94. But replace vietnamese words with spaces

**Comment by DantSu** [comment]
You have to find WPC1258 id for your printer.
