### ISSUE TITLE
Greek Chars Printing Issue

### ISSUE THREAD

**Issue by giannis4284** [DantSu/ESCPOS-ThermalPrinter-Android#190]
Hello,

Im trying to print in Bixolon SPP-R410 but cant manage o print Greek chars. In bixolon Greek charset setting is WPC1253.

When I use this charset is not printing at all...

Do you have any clue on this?

Thanks

**Comment by DantSu** [comment]
Do you have the list of charsets encoding of your printer?

**Comment by giannis4284** [comment]
Hi they have a codepage PDF
Please check here: https://bixolon.com/_upload/manual/Manual_SPP-R410_Code_Pages_english_Rev_1_00.pdf

**Comment by DantSu** [comment]
No find by yourself

**Comment by DantSu** [comment]
like is write in the documentation : 

## Charset encoding

To change charset encoding of the printer, use EscPosCharsetEncoding class :

EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32, new EscPosCharsetEncoding("windows-1252", 16));

escPosCharsetId may change with printer model. [Follow this link to find escPosCharsetId that works with many printers](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32)
