### ISSUE TITLE
sunmi v2 inderprint problem

### ISSUE THREAD

**Issue by teykmen** [DantSu/ESCPOS-ThermalPrinter-Android#194]
Hello There
I would like to use a device called sunmi v2. It has a built-in printer with virtual Bluetooth connection. My problem is that I can not get print from built-in printer through my android web-view app. 
By the way other external printers works fine with my app.
Any suggestions?

**Comment by TekMem** [comment]
Yes It Is an ESC/POS commands compatible

**Comment by DantSu** [comment]
List devices with `BluetoothConnections.getList()` instead of `BluetoothPrintersConnections.getList()`.

**Comment by DantSu** [comment]
you don't read my answer...

> List devices with `BluetoothConnections.getList()` instead of `BluetoothPrintersConnections.getList()`.

So, don't use `BluetoothPrintersConnections.selectFirstPaired()` and check if your printer is in `BluetoothConnections.getList()`.

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/80#issuecomment-729728791

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/80#issuecomment-729759832

**Comment by TekMem** [comment]
Thanks. I will return with the result.

**Comment by TekMem** [comment]
I could not make it work. Thank you very much anyway.

**Comment by TekMem** [comment]
Hello again. Could it be that the system can see the printer but the printer cannot read the data being sent?

**Comment by Github2786** [comment]
> It's not the perfectly clean solution but I had to do this in order to meet my deadlines.
> 
> the SUNMI devices lists it's printer as INNERPRINTER.
> 
> In bluetoothprinterconnections.java there is a getlist() method, that lists the BLE printers visible to the SDK. the INNERPRINTER doesnt show up on that list because of this code block below.
> 
> ![image](https://user-images.githubusercontent.com/87540815/137979265-778a31a6-e3f3-426f-9c74-ba17b699baae.png)
> 
> if(BluetoothClass.Device.Major.IMAGING && (deviceCl == 1664 || deviceCl == BluetoothClass.Device.Major.IMAGING) For an unknown reason, the above returns false for the INNERPRINTER, hence it doesn't show up on the list
> 
> So i converted this to an if/else block which worked successfully ![image](https://user-images.githubusercontent.com/87540815/137979331-95ccacc3-0640-4a90-9bda-ba707adfe5f4.png)
> 
> Now the above is just a test code block that i quickly wrote, I will recommend storing the printer name configurable instead of hardcoding it

really working ? i also stuck on this

**Comment by Github2786** [comment]
really working ? im also stuck on this

**Comment by ElVats** [comment]
Try download and install the Printer plugin, it will pickup.

**Comment by nadeemabualarayes** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'com.sunmi.printerx.api.LineApi com.sunmi.printerx.PrinterSdk$Printer.lineApi()' on a null object reference

**Comment by KeitelDOG** [comment]
Some tips in case some developers who are working with POS Thermal Printer.

Normally you use Bluetooth Scanning, get the names (Sunmi: "InnerPrinter", Senraise: "InnerPrinter", ALPS: "vBtPrinter").

⚠️ Because it often fails to detect it in the scan, in Android system I check the Mac Address for the devices:

- Sunmi V2: `00:11:22:33:44:55`
- Senraise H10S: `00:11:22:33:44:55`
- ALPS Q2I: `00:AA:11:BB:22:CC`

You can try to connect directly with a Mac Address, then if it fails, try the other one, or detect the device model to know which Mac Address to connect with. But Bluetooth gotta be activated, and it never fails. Other option is to go Android AIDL.
