### ISSUE TITLE
Hello there! Can I get an 'aar' file for this library please?

### ISSUE THREAD

**Issue by samir-dahal** [DantSu/ESCPOS-ThermalPrinter-Android#195]
I am trying to integrate this on Xamarin Forms. I cannot directly use this library. I can access the code written here with an 'aar' file.

**Comment by DantSu** [comment]
I don't create a aar file.

**Comment by samir-dahal** [comment]
> I don't create a aar file.

There should be an aar file in your build output directory?

**Comment by DantSu** [comment]
No but it's an open source project with MIT licence. So, fork the repository and do what you want, create your aar file.
