### ISSUE TITLE
I am getting this issue, help?

### ISSUE THREAD

**Issue by samir-dahal** [DantSu/ESCPOS-ThermalPrinter-Android#196]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\MyProjects\ESCPOS-ThermalPrinter-Android\pos-thermal\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':pos-thermal'.
> Could not find method compileSdk() for arguments [30] on object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':pos-thermal'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by DantSu** [comment]
Your build.gradle seems to be incomplete. Is not a library issue.

**Comment by samir-dahal** [comment]
But I followed your exact instruction. I cloned the project and opened in android studio , after doing that it should build the project normally but it's not syncing the gradle stuff. I new to this native world so please help. If I didn't get ?

**Comment by DantSu** [comment]
Do you have download android SDK, build tools and cie ?

**Comment by DantSu** [comment]
Look at your SQK manager in Android Studio and download a SDK,  Android SDK Build Tools,  Android SDK Platform-Tools.
Is not an issue of this library but an issue of your Android Studio configuration.

**Comment by samir-dahal** [comment]
![IMG_20211005_223919.jpg](https://user-images.githubusercontent.com/39849021/136068069-0c571549-1eb0-41f3-89f0-92ba9da5d006.jpg)
I was able to run the app but it didn't print the Order No in big and bold font why is that? It's my printer fault? It can print the image and QR code nicely but other text are not well formatted?
