### ISSUE TITLE
I can't print Arabic character,  self test not show any charsetname or id

### ISSUE THREAD

**Issue by abdogamerpro** [DantSu/ESCPOS-ThermalPrinter-Android#198]
I found in self test
Default code page: cp1265 :Arabic ( only this!!)
What should i do?
Note: printer print English word without any problem.

**Comment by abdogamerpro** [comment]
Thanks very much for reply, 
Where i can add this code?

**Comment by DantSu** [comment]
Instead of printFormattedTextAndCut

**Comment by abdogamerpro** [comment]
Please explain more, I use the sample project from github, I use AsyncEscPosPrinter to print the text 
How to add the code below to it?
Thanks in advance.

**Comment by abdogamerpro** [comment]
Thanks very much,  I was stupid,  finally I understand you
Thanks

**Comment by Sardorbek97** [comment]
> I can't find any printFormattedTextAndCut in the project(I found printFormattedTextAndCut in the library), and the library already have printAllCharsetsEncodingCharacters. How I can use (printAllCharsetsEncodingCharacters) in my main activity . I mean , how to use (printAllCharsetsEncodingCharacters) with method AsyncEscPosPrinter. Please give me any example.

Please give me an example!

**Comment by Sardorbek97** [comment]
> Thanks very much, I was stupid, finally I understand you Thanks

Can you share it with us ?

**Comment by Sardorbek97** [comment]
> search printFormattedTextAndCut and replace by printAllCharsetsEncodingCharacters

Please show us an example i don't understand!
