### ISSUE TITLE
Character not print well ,after set default code page and charset id.

### ISSUE THREAD

**Issue by abdogamerpro** [DantSu/ESCPOS-ThermalPrinter-Android#199]
My printer default code page is windows-1256(CP1256).
And charset that support Arabic and English is 10 like photo here:
![received_679975226740147](https://user-images.githubusercontent.com/63253832/136363845-5ce1cc09-1956-4fa9-b826-5fda945961ad.jpeg)
This only charset that support Arabic and English. 
But this is output 
![20211007_121028](https://user-images.githubusercontent.com/63253832/136364811-1ae1368d-a13f-4e3f-ab66-18996576a773.jpg)

English words print properly but Arabic not.

And I use this to change CharsetEncoding:
`EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 48f, 32, new EscPosCharsetEncoding("windows-1256",10));`
How to fix that?
Thanks in advance

**Comment by DantSu** [comment]
`new EscPosCharsetEncoding("windows-1256",0)` or `new EscPosCharsetEncoding("windows-1256",1)`

**Comment by abdogamerpro** [comment]
Ok, I try like you said
And this what happens 
![received_1256117434904294](https://user-images.githubusercontent.com/63253832/136439458-6279f1b5-1ee0-4405-a720-7fd30023726b.jpeg)
![received_168928348749064](https://user-images.githubusercontent.com/63253832/136439478-3f0ca323-510f-44b9-b485-5e1b6de4a6bd.jpeg)

And at Arabic words , words will be Reverses, like here:
![received_208654334667412](https://user-images.githubusercontent.com/63253832/136439730-a5d3b73f-5773-413c-9b3e-c2b2e55a3526.jpeg)

The words must be like this (يا رب يشتغل)
But will be Reverses like photo.
I try to add Reverses word to print it correctly but not showing any letters. 
How to solve this?

**Comment by abdogamerpro** [comment]
I write the same code that you have provided it below
Same issue.
Maybe issue in windows-1256 like you said.
Forget it.
In the end, I want to thank you for your hard work with me in solving problems, I know that my level is average, thank you 💜
