### ISSUE TITLE
Cannot use the USB print command.

### ISSUE THREAD

**Issue by Chaianun** [DantSu/ESCPOS-ThermalPrinter-Android#2]
Printer fujitsu ftp-639 cannot print usb command.

I want you help me please.

**Comment by DantSu** [comment]
Please explain me what you have do.
Have you try to clone this project and test the Print USB button ?

**Comment by Chaianun** [comment]
I clone this project
Then I test, press the USB Print button

It freezes

D/UsbRequestJNI: init

**Comment by Chaianun** [comment]
In my log

Load Settings
				Cannot load settings from file 'C:\Users\User\Downloads\AndroidPrinter-master\AndroidPrinter-master\AndroidPrinter.iml': File C:\Users\User\Downloads\AndroidPrinter-master\AndroidPrinter-master\AndroidPrinter.iml does not exist
				Please correct the file content

**Comment by DantSu** [comment]
You have clone this project into another project or you try to rename ThermalPrinter project to AndroidPrinter.

Create empty directory, and do `git clone https://github.com/DantSu/ESCPOS-ThermalPrinter-Android.git .` open this directory with android studio and test it ! Don't rename anything !

**Comment by Chaianun** [comment]
I did as you said But still not present

![image](https://user-images.githubusercontent.com/47379064/80477882-e509ea80-8976-11ea-9644-ff311bfb1f4f.png)

**Comment by DantSu** [comment]
I don't see any error on your screenshot. You still have the problem ?

**Comment by Chaianun** [comment]
I don't understand either Why doesn't the error show, but my screen freezes? And didn't print out the receipt

**Comment by DantSu** [comment]
Try to use `UsbConnections `class may be is not `UsbConstants.USB_CLASS_PRINTER` and the printer is not selected. Try to see what `UsbConnections.getList()` return.

I can't help you more.

**Comment by Chaianun** [comment]
I thank you very much for your help. But I tried what you said. Remaining and unusable like walking And the return value clearly shows my printer And my paper is 80mm in size

**Comment by DantSu** [comment]
Can you see your printer when you do a `UsbPrintersConnections.getList()` instead of `UsbConnections.getList()` ?

**Comment by Chaianun** [comment]
Is this correct?

![image](https://user-images.githubusercontent.com/47379064/80575389-b13dcc00-8a2d-11ea-84eb-defd5fa2af1d.png)

**Comment by DantSu** [comment]
Ok so `UsbPrintersConnections.getList()` reconize your printer....
I don't understand where the problem is. The printer is reconized, no error is shown, but screen freeze and nothing is printed.... I don't know how I can help you, sorry.

Last question : `UsbPrintersConnections.selectFirstConnected()` return the FTP-629 device ?

**Comment by Chaianun** [comment]
Yes , return the FTP-629 device 

![image](https://user-images.githubusercontent.com/47379064/80577334-e861ac80-8a30-11ea-854d-24f7877c4f2c.png)

**Comment by Chaianun** [comment]
I've tried Debug until the end. But it stopped here and didn't go on. Is it possible that this code will not work?  "printFormattedText"

![image](https://user-images.githubusercontent.com/47379064/80577681-7b024b80-8a31-11ea-937e-829d590bcc17.png)

**Comment by DantSu** [comment]
I think the problem is on `line 48` here : https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/connection/usb/UsbOutputStream.java

`this.usbConnection.requestWait();` may not have response from your printer. Test to comment this line.

**Comment by DantSu** [comment]
But the first line should be printed... so it's still a weird behavior.

**Comment by Chaianun** [comment]
It really stops here Is there a way to fix it?

![image](https://user-images.githubusercontent.com/47379064/80580270-793a8700-8a35-11ea-9d1b-56a959bc45b0.png)

**Comment by DantSu** [comment]
Try to comment this line, and see what's happen.

**Comment by Chaianun** [comment]
Loop usbRequest.close();

![image](https://user-images.githubusercontent.com/47379064/80581530-76d92c80-8a37-11ea-9c0e-3bd144da8494.png)

**Comment by DantSu** [comment]
it's normal. Each line, I send data to the printer. `usbRequest.close()` is called as many times as the number of line.

**Comment by DantSu** [comment]
Nothing is printed ?

**Comment by Chaianun** [comment]
Yes , Nothing is printed.

**Comment by DantSu** [comment]
Ok so the problem coming when the data is sent to the printer... The printer does'nt respond. I don't know what's happen. sorry

**Comment by Chaianun** [comment]
Or should I set up my paper first? My paper size is 80MM

**Comment by DantSu** [comment]
not really. Try but you can do that later normally.

**Comment by Chaianun** [comment]
In the end, I couldn't type. I thank you for answering me.

**Comment by Chaianun** [comment]
It my log

![image](https://user-images.githubusercontent.com/47379064/80583651-b2c1c100-8a3a-11ea-85c4-a00eac0a5d05.png)

**Comment by DantSu** [comment]
Where is red in the top of logcat, select the tested application.
