### ISSUE TITLE
printFormattedText does nothing without any exception

### ISSUE THREAD

**Issue by justjew** [DantSu/ESCPOS-ThermalPrinter-Android#200]
I am trying to print something on XPrinter XP-365B.

Am calling the following Kotlin code from Flutter Method Channel
```
ActivityCompat.requestPermissions(context, arrayOf(Manifest.permission.BLUETOOTH), 1)

val printer: EscPosPrinter = EscPosPrinter(BluetoothPrintersConnections().list!![0], 203, 48f, 32)
printer.printFormattedText("[L]test")
printer.disconnectPrinter()
```

I added the permission to `AndroidManifest.xml`.
Sure `BluetoothPrintersConnections().list!![0]` returns the correct device (I checked it in debug).
After calling `printFormattedText("[L]test")` nothing happens. Not even an exception raises.

What do I do wrong?

**Comment by justjew** [comment]
> Remove disconnectPrinter and try

I does not work with and without `disconnectPrinter`.
I tried both

**Comment by DantSu** [comment]
So, I don't know.

**Comment by justjew** [comment]
I am sure the printer works fine. I tested it with XLabel application.
Also it beeps on connect. But not printing.

**Comment by DantSu** [comment]
Can't help you. I never encounter a similar problem.

**Comment by DantSu** [comment]
You trst the default application ? Git clone the project open it with android studio, run it on your phone and test to print. To see if the library doesn't works with your printer

**Comment by justjew** [comment]
I am disappointed.
I really need to make this stupid printer work via bluetooth. It took more than a week but still absolutely nothing. I tried to use all Flutter libs for printing, after that I decided to do it via java/kotlin BUT STILL NOTHING HAPPENS.

crying...

**Comment by DantSu** [comment]
Is there a button on the printer to switch to esc pos mode ?

**Comment by DantSu** [comment]
Youpi !! Solved !!
