### ISSUE TITLE
Hello please how can I solved this problem please I need help .

### ISSUE THREAD

**Issue by daniel3133** [DantSu/ESCPOS-ThermalPrinter-Android#201]
![IMG_20211011_151050_594](https://user-images.githubusercontent.com/63508187/136787828-ad5e9878-ecc0-4ba1-8787-703fee3d88f5.jpg)

**Comment by DantSu** [comment]
Look log in logcat window in android studio. Copy paste all red and orange log

**Comment by DantSu** [comment]
I can't help you

**Comment by daniel3133** [comment]
![Uploading IMG_20211011_202858_551.jpg…]()
