### ISSUE TITLE
probleme with mmFeedPaper (or dotFeedPaper) 

### ISSUE THREAD

**Issue by treeindark** [DantSu/ESCPOS-ThermalPrinter-Android#203]
I use  paystory-de/thermal-printer-cordova-plugin (lib is update to v3)

setting are ok, for printing  except the feedPaper:

I find mmFeedPaper : 30.0 ok but cut is just below the last list.

all other 20, 80 and cut before the last line.
but i would have some blank under last line ....
I would try with dot but same problem.

in paystory-de/thermal-printer-cordova-plugin  : ThermalPrinterCordovaPlugin.java printing is exec with:

```
EscPosPrinter printer = this.getPrinter(callbackContext, data);
        try {
            int dotsFeedPaper = data.has("mmFeedPaper")
                ? printer.mmToPx((float) data.getDouble("mmFeedPaper"))
                : data.optInt("dotsFeedPaper", 20);
            if (action.endsWith("Cut")) {
                printer.printFormattedTextAndCut(data.getString("text"), dotsFeedPaper);
            } else {
                printer.printFormattedText(data.getString("text"), dotsFeedPaper);
            }...
```

**Comment by DantSu** [comment]
try to put some empty lines "[L]\n" at the end.
