### ISSUE TITLE
I found the Chinese words, but...

### ISSUE THREAD

**Issue by OwenChen0911** [DantSu/ESCPOS-ThermalPrinter-Android#21]
`EscPosPrinter printer = new EscPosPrinter(new TcpConnection(iIPaddress, iPort),
                            203, 48f,32,
                            new EscPosCharsetEncoding("CP-950", 16)`

While I am using "CP-950" that I can print out Chinese words, but...

1. what does the second param  means???   EscPosCharsetEncoding("",16) 

2. when I using `[C]<u><font size='big'>LINE@線上點餐</font></u>\n`, the font size does not work.

**Comment by DantSu** [comment]
The second parameter is the printer charset encoding ID. 
You have to find the good charset ID for your charset CP-950.
For example my printer have this IDs : 
![20200623_151000](https://user-images.githubusercontent.com/4188774/85408231-8b7fff80-b564-11ea-8e13-3dde5f3d7680.jpg)

I don't know if chinese font can have other size.

**Comment by Bhoomi-Zalavadiya** [comment]
How you have printed £ pound sign 
can you send me code?

**Comment by DantSu** [comment]
In your test editor wich text encoding you can use for write £ symbol ? (For many ESC printers, UTF-8 is not an option)

**Comment by Bhoomi-Zalavadiya** [comment]
I am not familier with charset encoding can you send me your code for above image?

**Comment by DantSu** [comment]
No I haven't code to share. Read the doc find your charset encoding. Each printer is different.
