### ISSUE TITLE
Is there any way to increase QR Code "density"

### ISSUE THREAD

**Issue by fugogugo** [DantSu/ESCPOS-ThermalPrinter-Android#210]
I'm making the qr code a bit bigger, size 50 
but the qr code generated is a bit .. "not dense" (like in screenshot)
sorry I do not know what it is called
is there any setting to make it more "dense" ?
the one in readme looks more "dense" than this even though it is smaller

![IMG_20211028_163351](https://user-images.githubusercontent.com/1118608/139229768-7bf352ed-bffc-4300-ac60-37d5cda88cf9.jpg)

**Comment by fugogugo** [comment]
Hello I am sorry for late reply 

what I mean is I want the QR code to have more "bits" 
here is the example, the right one is the QR Code generated by this library 
I want to make the QR code to be like the left one 
is there any setting to make it more "dense" like that 

![image](https://user-images.githubusercontent.com/1118608/144585371-b0a0f82d-4bb1-4f0e-a2ff-b85dc3286ff9.png)

**Comment by DantSu** [comment]
The size of the bit is directly linked to the size of data you put into your QR Code.
If you do a QR Code with a long string, you will have very small squares, and if you do a QR code with a very short string you will have big squares.  What string do you put in your QR code ?

**Comment by fugogugo** [comment]
a has string like this 

`oKRXmG1neqGG2zp`

is there any way to artificially force it? :S

**Comment by DantSu** [comment]
add fake chars to have a constant string length.

like `oKRXmG1neqGG2zp_____________________________________________________________________`

**Comment by DantSu** [comment]
and if you have a longer string do : 

`oKRXmG1neqGG2zp_____________________________________________________________________`
`uUjebnJBdnLLIJEBnPPIOnnfclsinfcbnlLIKHsdb___________________________________________`

In this case, you are sure to have a constant QR code

**Comment by fugogugo** [comment]
actually how about making the correction level adjustable?
I see in the EscPosPrinterCommands.QRCodeDataToBytes you use hardcoded L value 

https://zxing.github.io/zxing/apidocs/com/google/zxing/qrcode/decoder/ErrorCorrectionLevel.html

hmm I'll try to clone the project and change the correction level

**Comment by DantSu** [comment]
It's not implemented yet

**Comment by fugogugo** [comment]
Hehe it worked :)

I changed the correction level to H , a bit easier to scan as well

![image](https://user-images.githubusercontent.com/1118608/144595469-d7c0e7ab-e104-4a7a-b850-4cc40ee329d3.png)

it is okay then I will use my local change for now.
Thank you 🙏
