### ISSUE TITLE
TOSHIBA B-FP3D-GH30_QM_R Printer can't print QR code and Image 

### ISSUE THREAD

**Issue by tampro9x92** [DantSu/ESCPOS-ThermalPrinter-Android#211]
I have issue with TOSHIBA B-FP3D can't print image and qr code
![IMG_20211102_103430](https://user-images.githubusercontent.com/55266330/139782894-4e6eacd5-f57c-4338-b846-6fdb90fbe732.jpg)

**Comment by DantSu** [comment]
It's seems to not be compatible with image command.

**Comment by tampro9x92** [comment]
so this TOSHIBA printer is using it own command i really confuse about this printer can't you have me solve this issue thank you very much

**Comment by DantSu** [comment]
you can fork the project and edit code to make it works with your printer ;)

**Comment by tampro9x92** [comment]
if i know how to do it i will :+1:
