### ISSUE TITLE
Asynchronous printing with EscPosCharsetEncoding

### ISSUE THREAD

**Issue by rogerthedeveloper** [DantSu/ESCPOS-ThermalPrinter-Android#212]
I'm trying to get the async printing with instance of **EscPosCharsetEncoding("CP850", 2);** to work, but it seems the class **AsyncEscPosPrinter** does not have constructor for this field, so I can't use the **EscPosCharsetEncoding** parameter for config printer needed for get áéíóú chars and ÁÉÍÓÚ also Ñ.

Working (Sync):
```java
EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32, new EscPosCharsetEncoding("CP850", 2));
```
Not Working (Async):
```java
AsyncEscPosPrinter printer = new AsyncEscPosPrinter(printerConnection, 203, 48f, 32, new EscPosCharsetEncoding("CP850", 2));
```

**Comment by DantSu** [comment]
Normal, it's a demo app, you have to develop your own classes.
Async classes are not part of the library, this is for the demonstration.
