### ISSUE TITLE
Error When Removing the <img> tag at the top

### ISSUE THREAD

**Issue by busdago** [DantSu/ESCPOS-ThermalPrinter-Android#213]
Hi guys, I was wondering why every time I remove the <img> tag that is right at the top like this: 

```java
            printer.printFormattedText(
                            "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                            "[L]\n" +
                            "[C]================================\n" +
                            "[L]\n" +
                            "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                            "[L]  + Size : S\n" +
                            "[L]\n" +
                            "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                            "[L]  + Size : 57/58\n" +
                            "[L]\n" +
                            "[C]--------------------------------\n" +
                            "[R]TOTAL PRICE :[R]34.98e\n" +
                            "[R]TAX :[R]4.23e\n" +
                            "[L]\n" +
                            "[C]================================\n" +
                            "[L]\n" +
                            "[L]<font size='tall'>Customer :</font>\n" +
                            "[L]Raymond DUPONT\n" +
                            "[L]5 rue des girafes\n" +
                            "[L]31547 PERPETES\n" +
                            "[L]Tel : +33801201456\n" +
                            "[L]\n" +
                            "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                            "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                    );
```

I get an error in .printFormattedText() could anybody tell me how to remove the image tag without getting an error. 
Thanks

**Comment by DantSu** [comment]
what's the error ?

**Comment by busdago** [comment]
The Error is: 
Unhandled exceptions: com.dantsu.escposprinter.exceptions.EscPosConnectionException, com.dantsu.escposprinter.exceptions.EscPosParserException, com.dantsu.escposprinter.exceptions.EscPosEncodingException, com.dantsu.escposprinter.exceptions.EscPosBarcodeException

Here is an immage of the error attached! 
![pic](https://user-images.githubusercontent.com/66003646/141074735-ce8e67a0-e708-439d-abda-e90f2507c2cf.png)

Thanks!

**Comment by busdago** [comment]
This is the error: 

Unhandled exceptions: com.dantsu.escposprinter.exceptions.EscPosConnectionException, com.dantsu.escposprinter.exceptions.EscPosParserException, com.dantsu.escposprinter.exceptions.EscPosEncodingException, com.dantsu.escposprinter.exceptions.EscPosBarcodeException

Here is a picture of the error!
![pic2](https://user-images.githubusercontent.com/66003646/141075179-8234e03d-060a-4e31-a8eb-a3290394ed0c.png)

Thanks!

**Comment by DantSu** [comment]
You show me the documentation of the printFormattedText method. Is not an error...

**Comment by busdago** [comment]
Sorry I sent the wrong pic, my bad
When I hover over .printFormattedText() method I get this: 

Unhandled exceptions: com.dantsu.escposprinter.exceptions.EscPosConnectionException, com.dantsu.escposprinter.exceptions.EscPosParserException, com.dantsu.escposprinter.exceptions.EscPosEncodingException, com.dantsu.escposprinter.exceptions.EscPosBarcodeException

**Comment by DantSu** [comment]
You just forgot to use a try catch. Is not an error. Clone the project and look how i use it
