### ISSUE TITLE
Text not printing

### ISSUE THREAD

**Issue by LouayAD** [DantSu/ESCPOS-ThermalPrinter-Android#216]
Hi there,
I cloned the repo and everything seem fine until I print. I realized whenever I print with my thermal printer using bluetooth only images and Qr codes get printed and texts seem to be totally ignored.

![1636620385976](https://user-images.githubusercontent.com/77132854/141266893-32dc118f-0ab4-4d37-a4af-55dfc93a5b9b.jpg)

This is the result I get when using the default layout from the repo.

**Comment by DantSu** [comment]
Seems to be a Charset Encoding problem. Find the correct charset encoding ID for your printer.
