### ISSUE TITLE
Need Dynamic Barcode irrespective of string length?

### ISSUE THREAD

**Issue by YogeshLegendkiller** [DantSu/ESCPOS-ThermalPrinter-Android#217]
How to implement the dynamic barcode (int type) irrespective of length?

For example:

5011007008482 - code uses <barcode>5011007008482</barcode>
84155634 - code uses <barcode type='ean8'>5011007008482</barcode>
10026102126155- this code doesn't support anytype

how to solve this

**Comment by YogeshLegendkiller** [comment]
yes is it possible??

**Comment by YogeshLegendkiller** [comment]
[C]<barcode type='128' width='40' text='above'>$barcode</barcode>

prints only text not barcode

**Comment by DantSu** [comment]
So, Your printer is not comptible barcode 128. My printer do it well.

**Comment by DantSu** [comment]
Use QR code instead ?
