### ISSUE TITLE
Arabic Text Not Printing

### ISSUE THREAD

**Issue by KamalBalah** [DantSu/ESCPOS-ThermalPrinter-Android#218]
public void aa2(View view) throws EscPosConnectionException, EscPosParserException, EscPosEncodingException, EscPosBarcodeException {
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.BLUETOOTH) != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.BLUETOOTH}, 5);
        } else {
            EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(),
                    203,
                    48f,
                    32);
            printer.printFormattedText("[C]مرحبا");

        }
    }
This is my printing function but arabic text don't printed

**Comment by DantSu** [comment]
Charset encoding problem. Many issues talking about that.

**Comment by iAmAndroidDeveloper** [comment]
@KamalBalah try this  #224
