### ISSUE TITLE
For first time it is printing fine but for second time app is closing

### ISSUE THREAD

**Issue by Rahulvamshi** [DantSu/ESCPOS-ThermalPrinter-Android#219]
**Error**
`
Attempt to invoke virtual method 'com.dantsu.escposprinter.connection.DeviceConnection com.dantsu.escposprinter.connection.DeviceConnection.connect()' on a null object reference
`

**My code** 

```java
 Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                bitma1p,
                383,
                Math.round(((float) bitma1p.getHeight()) * ((float) 383) / ((float) bitma1p.getWidth())),
                true
        );

        EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

**Comment by Rahulvamshi** [comment]
yes

**Comment by DantSu** [comment]
So you lost the bluetooth connection.

**Comment by Rahulvamshi** [comment]
But for the first time, it is also returning null, but the printer is printing the bill

**Comment by DantSu** [comment]
no it doesn't return null the first time. 
Try this : 

```java
class MyActivity {
    private DeviceConnection printerConnection;

    // ... 

    public void myPrintMethod() {
        if(this.printerConnection == null) {
            this.printerConnection = BluetoothPrintersConnections.selectFirstPaired();
        }
         Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                bitma1p,
                383,
                Math.round(((float) bitma1p.getHeight()) * ((float) 383) / ((float) bitma1p.getWidth())),
                true
        );

        EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(this.printerConnection);
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
    }

    // ... 

}
```

**Comment by Rahulvamshi** [comment]
**Still same error** 

Attempt to invoke virtual method 'com.dantsu.escposprinter.connection.DeviceConnection com.dantsu.escposprinter.connection.DeviceConnection.connect()' on a null object reference

**Now it's not working for the first time also.**

**Comment by DantSu** [comment]
show me your entire class code

**Comment by Rahulvamshi** [comment]
**This is m code 👍** 


public class Home extends AppCompatActivity
 {
	CardView bill;
 	private DeviceConnection printerConnection;

    	protected void onCreate(Bundle savedInstanceState)
	{
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);

    	ImageView imageView3 = findViewById(R.id.imageView3);
    	bill = findViewById(R.id.bill);
   	imageView3.setOnClickListener(v-> {
           	printBill();
        	});
	}

	void printBill()
	{
        	int targetWidth = 383;
        	Bitmap bitma1p = getBitmapFromView(bill);

         	if(this.printerConnection == null)
         	{
            	this.printerConnection = BluetoothPrintersConnections.selectFirstPaired();
       		}


             Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                     bitma1p,
                     383,
                     Math.round(((float) bitma1p.getHeight()) * ((float) 383) / ((float) bitma1p.getWidth())),
                     true
             );

             EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(this.printerConnection);

             try {
                 printerCommands.connect();
                 printerCommands.reset();
                 printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
                 printerCommands.feedPaper(50);
                 printerCommands.cutPaper();
             } catch (EscPosConnectionException e) {
                 e.printStackTrace();
             }
    }

  	public static Bitmap getBitmapFromView(View view)
	 {
        Bitmap returnedBitmap = Bitmap.createBitmap(view.getWidth(), view.getHeight(),Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(returnedBitmap);
        Drawable bgDrawable = view.getBackground();
        if (bgDrawable!=null)
            bgDrawable.draw(canvas);
        else
            canvas.drawColor(Color.WHITE);
        view.draw(canvas);
        return returnedBitmap;
  	  }
}

**Comment by DantSu** [comment]
This is weird. This code should normally works.

If you clone this project and test it, did it work ?

**Comment by Rahulvamshi** [comment]
yeah i did, but For the second time it says it "**can't find any printer connected in the app**"

**Comment by DantSu** [comment]
Is not the normal behavior. There is a problem with your printer or Android device. Can't help you.
