### ISSUE TITLE
USB can be disabled ?

### ISSUE THREAD

**Issue by mcapello** [DantSu/ESCPOS-ThermalPrinter-Android#22]
Hi, one question again.
Is it possible that you have this inside the library ?

`<uses-feature android:name="android.hardware.usb.host" />`

Because this significantly reduce the number of devices supported.
Is there a way to dasactive this feature?

thanks

**Comment by DantSu** [comment]
What's happens when this library is used on devices that don't have usb port ? It's crash ?

**Comment by mcapello** [comment]
Right now, you can not used in devices not USB compatibles because you use:
<uses-feature android:name="android.hardware.usb.host" />
and google chek for this in play store.
That is why this library reduce the number of devices that an APP could be installed. 

Maybe if you update to:
<uses-feature android:name="android.hardware.usb.host" android:required="false"/>
the APPs can be installed on non USB compatible devices.

Then in your library you can use this to control if USB is in te device:
PackageManager.hasSystemFeature()

**Comment by DantSu** [comment]
Thx for the feedback, I will trying some test.

**Comment by mcapello** [comment]
grate, thx you

**Comment by mcapello** [comment]
I re open this to know if you test this.

**Comment by DantSu** [comment]
v2.0.2 solve this problem.

Now USB permission have to be defined in application manifest and it's no more in library manifest.
