### ISSUE TITLE
My Bluethooth Deviceclass  number is 1540 , where as current code allows either 1536/1664

### ISSUE THREAD

**Issue by anuragvohraec** [DantSu/ESCPOS-ThermalPrinter-Android#223]
Hi,

My Bluetooth thermal printer was not working, so started debugging found out that my device class is 1540 and hence not working.
Can a provision be made to pass a list of Device class ID while fetching the first paired device?
![printer_suggestion](https://user-images.githubusercontent.com/53807480/143375748-bc3d8e7f-e6bb-43f9-a818-98c458780e94.png)

**Comment by DantSu** [comment]
Yes ! Rewrite this class, and put your ids ! You have just to copy past this code and change the device class id.
