### ISSUE TITLE
Chinese font problem

### ISSUE THREAD

**Issue by Kaohan** [DantSu/ESCPOS-ThermalPrinter-Android#224]

**Comment by Kaohan** [comment]
> Hello, we want to print out Chinese characters, but this program seems to have no way. May I ask which way should I change it? (The printer supports Chinese), thank you!!!
> 
> Printer model:XP-D58IIIL

**Comment by DantSu** [comment]
Not possible yet

**Comment by Kaohan** [comment]
thanks!!

Franck Alary ***@***.***> 於 2021年11月25日 週四 下午3:21寫道：

**Comment by iAmAndroidDeveloper** [comment]
@Kaohan change following and check
![image](https://user-images.githubusercontent.com/26490351/144398780-3d2df72e-3d0e-4f0d-83ee-ef6973014b5e.png)
![image](https://user-images.githubusercontent.com/26490351/144398838-fca94688-aa50-450e-93fe-96642d9d77f3.png)
