### ISSUE TITLE
Increase or change the font size

### ISSUE THREAD

**Issue by masternkl** [DantSu/ESCPOS-ThermalPrinter-Android#226]
Hi,
Im using this lib and works perfect in android. But I need increase the size of BIG font size and custom other font sizes. How can I do that?.

Thanks in advance.

**Comment by DantSu** [comment]
You can't.

**Comment by yousseffarni** [comment]
Is there any way to increase the font size slightly because <font size='big'>Some text</font> is larger?

**Comment by yousseffarni** [comment]
Is there any way to increase the font size slightly because `<font size='big'>Some text</font>` is larger?
