### ISSUE TITLE
the printer stops doing its job

### ISSUE THREAD

**Issue by Egi10** [DantSu/ESCPOS-ThermalPrinter-Android#228]
while printing, there are cases where the printer stops working. so don't print until it's finished.

**Comment by DantSu** [comment]
do you use .disconnect() ?

**Comment by Egi10** [comment]
yes, 

open fun print() {
        val conn = connection() ?: throw PrinterUnavailableException()

        try {
            val printer = createEscPrinter(conn)
            execute(printer)
        } finally {
            conn.disconnect()
        }
    }

**Comment by yovi-ep** [comment]
halo sir @DantSu 
i am a team with @Egi10 

we have also tried with code

```
open fun print() {
        val conn = connection() ?: throw PrinterUnavailableException()
       try {
        val printer = createEscPrinter(conn)
        execute(printer)
       Thread.sleep(1500)
    } finally {
        conn.disconnect()
    }
}
```

and the result is the same

we using printer :
https://www.tokopedia.com/jual-barcode/printer-bluetooth-usb-struk-thermal-58-mm-port-rj-11-kassen-bt-p58

**Comment by DantSu** [comment]
The problem come from disconnect. Android don't wait to finish to send all data before disconnect and that stop the print.

**Comment by DantSu** [comment]
remove disconnect and say me if that still the same

**Comment by yovi-ep** [comment]
okey. we will try

**Comment by Egi10** [comment]
thanks, solved my issue

**Comment by k1n6m4n** [comment]
Hi Mr DantSu, I'm facing the same issues (again), the problem same as #184 

but somehow with certain hardware it's just stop after printing like 20 lines.

my question is, is it safe to comment out the disconnect? so never disconnect the printer? so far I tried no problem, but I'm afraid there's gonna be something else I haven't aware of.

Thanks

**Comment by DantSu** [comment]
If you use only one printer per Android device I think is not a problem. But I'm not sure, I haven't test all cases.

**Comment by k1n6m4n** [comment]
Hello Mr DantSu, I just tested, it only worked for the first print, but the following print will throw "Unable to connect to bluetooth device."

I Guess I'll sticking back to my previous method, but giving more larger delay time
