### ISSUE TITLE
Printing on Sunmi T1 not working

### ISSUE THREAD

**Issue by mehdei** [DantSu/ESCPOS-ThermalPrinter-Android#229]
Hello, I've the same example that you put it on GitHub ... I'm try to connect to Sunmi T1 built-in printer using Bluetooth ... everything goes well in the code (no exceptions), but I got nothing on the printer
I've tried the Sunmi SDK and it works on the same device
please may you check that

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/223#issue-1063124982
same answer as here

**Comment by mehdei** [comment]
Thanks for your response, but that's not the issue ... the library already reaches the printer (BluetoothConnection object), and the connect method goes well ... also, the code goes will with (printFormattedTextAndCut) method ... but printer show nothing

**Comment by DantSu** [comment]
You are sure that BluetoothPrinterConnection.getList() do not return null ?

**Comment by mehdei** [comment]
Yes, I've checked the debugger again and again ... that what lead me to check with Sunmi library.
In your library everything goes fine in the debugger, but nothing on the printer ... your sample project connects to an old Bluetooth Printer I have it, works fine and print out

**Comment by DantSu** [comment]
On Sumni, do you have a button to active ESC/POS mode ?

**Comment by DantSu** [comment]
Is tis printer compatible with ESC/POS commands ?

**Comment by mehdei** [comment]
Yes, you can set ESC/POS commands "ON" for the Sunmi device ... It's already "ON", and I've used the Sunmi library to send some text using ESC/POS commands ... Sunmi library it's not a fancy library ... you have to convert the command to an array of bytes then write it via the socket

**Comment by mehdei** [comment]
The thing that makes me crazy... your library allows me to print on ESC/POS printers via Bluetooth and WIFI very well... and Sunmi library allows me to print on its printer using ESC/POS commands... and I hardly find any difference in the process of connecting to the printer 
Now I'm trying to build a very simple library to call and send a test text on a Sunmi printer and on an Epson printer

**Comment by iAmAndroidDeveloper** [comment]
@mehdei try with this 

object BluetoothPrintConfig {

    private var outputStream: OutputStream? = null
    private var mbtSocket: BluetoothSocket? = null

    fun connect(device: BluetoothDevice) {
        try {
            val uuids: Array<ParcelUuid>? = device.uuids
            val uuid = if (uuids != null && uuids.isNotEmpty()) uuids[0].uuid else UUID.randomUUID()

            mbtSocket = device.createRfcommSocketToServiceRecord(uuid)
            mbtSocket?.connect()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    fun printTest(
        byteArray: ByteArray,
      
    ) {

        try {
            try {
                Thread.sleep(100)
            } catch (e: Exception) {
                disconnect()
                e.printStackTrace()
            }

            outputStream = mbtSocket?.outputStream

           
            outputStream?.write(byteArray)

            outputStream?.flush()

            try {
                Thread.sleep(1000)
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }

            disconnect()

        } catch (e: Exception) {
            disconnect()
            e.printStackTrace()
        }
    }

    /**
     * Close the socket connection with the bluetooth device.
     */
    fun disconnect() {
        // this.data = ByteArray(0)

        outputStream?.close()
        outputStream = null
        mbtSocket?.close()
        mbtSocket = null

        //return this
    }
}

And Call like 

val printBlReceipt = BluetoothPrintConfig
            printBlReceipt.connect(deviceForPrint)
            printBlReceipt.printTest(bytecode)

**Comment by mehdei** [comment]
@iAmAndroidDeveloper thanks for you ... But I can connect to Sunmi printer or any other printer now by my own lib, but I'm try to use this neat library to handle escpos printers in a simple easy way.

**Comment by iAmAndroidDeveloper** [comment]
@mehdei Ok are you facing any issue now?

**Comment by mehdei** [comment]
@iAmAndroidDeveloper Yes, I'm try to connect to Sunmi T1 built-in printer using this library via Bluetooth ... everything goes well in the code (no exceptions), but I got nothing on the printer

**Comment by iAmAndroidDeveloper** [comment]
@mehdei Sunmi have a library for print with inbuilt printer?

**Comment by mehdei** [comment]
@iAmAndroidDeveloper Yes, it's not a fancy library, but it works and my own library also work with Sunmi built-in printer.

**Comment by iAmAndroidDeveloper** [comment]
@mehdei then what issue now you facing?

**Comment by mehdei** [comment]
@iAmAndroidDeveloper Thanks for you, but please try to read before asking, I've told you my issue in the last 23 hours, also it exists at the issue description and title ... you just came and commented with some code and start to ask the same question again and again (what is the issue?), please learn to read
