### ISSUE TITLE
Print Full Image Not Print

### ISSUE THREAD

**Issue by yovi-ep** [DantSu/ESCPOS-ThermalPrinter-Android#232]
halo si @DantSu 

I print from full image and the result is a symbol.
but with another printer it works.

Code:
1. using encoding 0
2. command :
```
"[L]\n" +
"[L]<img>PrinterTextParserImg.bytesToHexadecimalString(EscPosPrinterCommands.bitmapToBytes(rescale(printer, newBitmap)))</img>\n\n" +
"[L]\n" +
"[L]\n" +
"[L]\n" +
"[L]\n";
```
3. Rescale Image:
```
private fun rescale(printer: EscPosPrinter, bitmap: Bitmap): Bitmap {
        val maxWidth: Int = printer.printerWidthPx
        var newBitmap = bitmap
        bitmap.apply {
            if (width > maxWidth) {
                val ratio = height.toDouble() / width.toDouble()
                val newHeight = ceil(maxWidth * ratio).toInt()
                newBitmap = Bitmap.createScaledBitmap(this, maxWidth, newHeight, false)
            }
        }

        return newBitmap
    }
```

Other Printer:
![image](https://user-images.githubusercontent.com/17000456/145316852-f2d06faa-3d7d-441c-9992-584d0d439753.png)

Printer Issue:
![WhatsApp Image 2021-12-01 at 8 18 03 AM](https://user-images.githubusercontent.com/17000456/145316027-c7421533-78c1-41f0-a071-9c3fafe80a5d.jpeg)

**Comment by DantSu** [comment]
If you only print image, like documentation said go here : https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70#issuecomment-714390014

If you use bluetooth, big image will cause trouble. 
- Do not use `disconnect()` method.
- Increase waiting time before print the next element

**Comment by yovi-ep** [comment]
thanks @DantSu

**Comment by laithbzour** [comment]
@yoviep 
how fix this issue can share code

**Comment by yoviep** [comment]
Do not use disconnect() method after you use printer.printFormattedText().

**Comment by laithbzour** [comment]
@yoviep  here is my code my image dim 383 *301 my printer Aisino A90 40mm 
      int targetWidth = 383;
            Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                    bytes,
                    targetWidth,
                    Math.round(((float) bytes.getHeight()) * ((float) targetWidth) / ((float) bytes.getWidth())),
                    true
            );

            EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(MyBluetoothPrintersConnections.selectFirstPairedOne());
            try {
                printerCommands.connect();
                printerCommands.reset();
                printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(bytes));
                printerCommands.feedPaper(150);
                printerCommands.cutPaper();
            } catch (EscPosConnectionException e) {
               
still same issue

**Comment by yoviep** [comment]
i just use this code

command :
```
"[L]\n" +
"[L]<img>PrinterTextParserImg.bytesToHexadecimalString(EscPosPrinterCommands.bitmapToBytes(rescale(printer, newBitmap)))</img>\n\n" +
"[L]\n" +
"[L]\n" +
"[L]\n" +
"[L]\n";
```

Rescale Image:
```
private fun rescale(printer: EscPosPrinter, bitmap: Bitmap): Bitmap {
        val maxWidth: Int = printer.printerWidthPx
        var newBitmap = bitmap
        bitmap.apply {
            if (width > maxWidth) {
                val ratio = height.toDouble() / width.toDouble()
                val newHeight = ceil(maxWidth * ratio).toInt()
                newBitmap = Bitmap.createScaledBitmap(this, maxWidth, newHeight, false)
            }
        }

        return newBitmap
    }
```

with step
1. printer.connect
2. printer.printFormattedText the command

**Comment by laithbzour** [comment]
@yoviep         
 val escAlign = toESCAlign(align).??

**Comment by laithbzour** [comment]
@yoviep  when split image and rescale on print give me 
java.lang.RuntimeException: Buffer not large enough for pixels
can help me ??

**Comment by laithbzour** [comment]
![49cf8bff-07bf-4bee-8747-e10c6470f7cb](https://user-images.githubusercontent.com/14046215/183258404-d0226f30-1c5a-43a6-832b-d623be183970.jpeg)

**Comment by yoviep** [comment]
> @yoviep         
>  val escAlign = toESCAlign(align).??
> 

only my mapper for alignment
```
    fun toESCAlign(align: PrintShareAlign): String = when (align) { 
         is PrintShareAlign.Right -> "[R]" 
         is PrintShareAlign.Center -> "[C]" 
         else -> "[L]" 
     }
```

**Comment by yoviep** [comment]
> @yoviep  when split image and rescale on print give me 
> java.lang.RuntimeException: Buffer not large enough for pixels
> 
> and when change heigh to split to 193 print as image below
> can help me ??

try to split the image into several parts based on height, for example the image is split by 256px. per page is written per line to the printer.

**Comment by laithbzour** [comment]
@yoviep thanks for help  i will try put how get the correct width and heigh for bitmap for my printer "Aisino A90"

**Comment by yoviep** [comment]
overall like this
```
        val imageFixed = newBitmap.rescale(printer.printerWidthPx) 
  
         val commands = StringBuilder() 
         imageFixed.splitHeight(256).forEach { 
             val imageBytes = EscPosPrinterCommands.bitmapToBytes(it) 
             val imageHex = PrinterTextParserImg.bytesToHexadecimalString(imageBytes) 
               commands.append("$escAlign<img>$imageHex</img>\n") 
         } 
  
         return commands.append("[L]\n".repeat(2)).toString()
```

**Comment by laithbzour** [comment]
@yoviep i use your code above still give me :
Buffer not large enough for pixels

**Comment by laithbzour** [comment]
@DantSu  @yoviep  thanks for your support the image is printing fine full heigh when split it but and when change font color to gray ... on black not printing

**Comment by yoviep** [comment]
i think epson command only supports black color.
maybe @DantSu can give insight
