### ISSUE TITLE
Could not find com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.0.1.

### ISSUE THREAD

**Issue by alcadiosystem** [DantSu/ESCPOS-ThermalPrinter-Android#233]
When trying to compile in a new or existing project, it generates the following error when compiling the app
`FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/7.0.2/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.0.1/ESCPOS-ThermalPrinter-Android-3.0.1.pom
       - https://repo.maven.apache.org/maven2/com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.0.1/ESCPOS-ThermalPrinter-Android-3.0.1.pom
       - https://jcenter.bintray.com/com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.0.1/ESCPOS-ThermalPrinter-Android-3.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/7.0.2/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.0.1/ESCPOS-ThermalPrinter-Android-3.0.1.pom
       - https://repo.maven.apache.org/maven2/com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.0.1/ESCPOS-ThermalPrinter-Android-3.0.1.pom
       - https://jcenter.bintray.com/com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.0.1/ESCPOS-ThermalPrinter-Android-3.0.1.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
`

For a new project, my gradle config file is as follows:

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }

    }

}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

Gradle app
`plugins {
    id 'com.android.application'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.testappprint"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.0.1'
}`

It should be noted that this error only appears when the compilation is carried out by calling this library, when the line of code is eliminated or commented, it compiles normally

Does anyone know how I could fix this error?
![error](https://user-images.githubusercontent.com/26491349/145612459-c9c695d3-69fd-47a0-a4c5-61d7a9aac94f.PNG)

**Comment by alcadiosystem** [comment]
I proceed to close this thread, dissolution and it is as follows:

Select the project view from the file viewer, the file setting.gradle is made two modifications

1) The line
repositoriesMode.set (RepositoriesMode.FAIL_ON_PROJECT_REPOS)
which is the original, you need to replace it with the following
repositoriesMode.set (RepositoriesMode.PREFER_SETTINGS)

2) add the maven {url 'https://jitpack.io'} inside the repositories object

**Comment by DantSu** [comment]
Thx for your feedback, there will be helpfull !

**Comment by ldavidsp** [comment]
Fixed https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/279
