### ISSUE TITLE
Encoding Arabic not working

### ISSUE THREAD

**Issue by KJ92** [DantSu/ESCPOS-ThermalPrinter-Android#235]
Hello team development,
i use encoding "Arabic" for encoding Arabic, but not working properly. character in not valid sequence 
new EscPosCharsetEncoding("Arabic", 22)

**Comment by hjhub** [comment]
Did you solve this ?
I am having the same problem.

**Comment by KJ92** [comment]
I added my custom code for string order change. and it's working for me.
if you want that code then please share your email id so i will share that code with you.

But i have issue with font.

**Comment by hjhub** [comment]
> I added my custom code for string order change. and it's working for me. if you want that code then please share your email id so i will share that code with you.
> 
> But i have issue with font.

Please send me the code to this email:

hj0077@hotmail.com

Thanks.

**Comment by KJ92** [comment]
Pleas check your inbox
Thanks

**Comment by hjhub** [comment]
@KJ92 
I fixed the problem. The way I fixed it is by converting the string to bitmap, then converting the bitmap to hexadecimal.

Code to convert string to bitmap:

        private Bitmap getBitmap(String text) {
                Paint paint = new Paint();
                paint.setTextSize(28);

                Rect bounds = new Rect();
                paint.getTextBounds(text, 0, text.length(), bounds);
                int width = bounds.width();
                int height = bounds.height();

                Bitmap bitmap = Bitmap.createBitmap(width*2, height, Bitmap.Config.ARGB_8888);
                Canvas canvas = new Canvas(bitmap);
                canvas.drawColor(Color.WHITE);
                canvas.drawText(text, 20, 20, paint);
                return bitmap;
        }

Then convert this bitmap to hexadecimal in the print code:

               EscPosPrinter printer = new EscPosPrinter(connection, 203, 78f, 48);
               final String text ="[C]<img>"+  PrinterTextParserImg.bitmapToHexadecimalString(printer,
                                getBitmap("شركة الحياة"))+"</img>";

               printer.printFormattedText(text);

**Comment by KJ92** [comment]
Yes, it's work if we convert it as image but
we require to pass it as text not as image because if we are passing it as image then it's taking time to print.
and we are not sure that how long image will be

**Comment by KJ92** [comment]
Still, it's not working for me so kindly update me if any solution is there.

**Comment by DantSu** [comment]
I don't have solution for you. I close this du to inactivity.

**Comment by taim786** [comment]
> 

Hi, can we use this code with stringbuilder with [this code](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/58#issuecomment-1202591978)?
