### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by selvam920** [DantSu/ESCPOS-ThermalPrinter-Android#236]
can we connect wifi thermal printer?

**Comment by DantSu** [comment]
Yes is TCP connection

**Comment by selvam920** [comment]
Will wifi printer connect automatically? Without knowing the IP

**Comment by selvam920** [comment]
I m using this plugin iin flutter android, can you provide sample code to print image from byte array

**Comment by DantSu** [comment]
No you have to know ip address

**Comment by yovi-ep** [comment]
@selvam920 if you using epson device. you can scanning epson printer using epson sdk (https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=6737&scat=61&pcat=4).
Sdk return profile device like name and ip adress.

if you using another device. you can using scanning IP range in subnetmask and try to open the port.

**Comment by selvam920** [comment]
can you provide sample code to print image from byte array?

**Comment by yovi-ep** [comment]
i have not.
please try that
escposprinter/src/main/java/com/dantsu/escposprinter/textparser/PrinterTextParserImg.java

**Comment by selvam920** [comment]
can we print html using this library?

**Comment by DantSu** [comment]
No it's not html
