### ISSUE TITLE
Small font size suggestion

### ISSUE THREAD

**Issue by SyedNoorullahShah** [DantSu/ESCPOS-ThermalPrinter-Android#237]
Hello sir, thank you for this awesome library ! we are using for printing invoices. Just needed some help. We feel the need of using text with smaller font size. Is there such an option or a way  (e.g <font size='small'>) ?
Thank you again

**Comment by DantSu** [comment]
It was but removed because it's not Epson standard.

**Comment by SyedNoorullahShah** [comment]
we are using Black Copper printer. As experimented, Black copper supports small font size text. Can you kindly guide me a bit about how can i achieve this (maybe using your own library)

**Comment by yoviep** [comment]
hi @SyedNoorullahShah you can using the print sdk from official website 
http://www.blackcopper.net/mobile-printers/62-bc-p58b-bluetooth-thermal-receipt-printer.html
