### ISSUE TITLE
Can not print Vietnamese on Xprinter Q-200

### ISSUE THREAD

**Issue by linhlq58** [DantSu/ESCPOS-ThermalPrinter-Android#238]
![image](https://user-images.githubusercontent.com/10673572/147813801-75867939-24bc-4336-aa53-9cd61c4aacc3.png)

There is code page 27 that supports Vietnamese. But when I implemented
`EscPosCharsetEncoding("windows-1258", 27)` 

with text "Đây là tiếng Việt"

Here is the result:
![image](https://user-images.githubusercontent.com/10673572/147813923-9aa7404e-3632-4896-b536-97104f47dd04.png)

What did I go wrong?

**Comment by yovi-ep** [comment]
you can try encode 30 or 31
refer to https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32

**Comment by linhlq58** [comment]
@yovi-ep It still doesn't work

**Comment by DantSu** [comment]
`EscPosCharsetEncoding("windows-1258", 27)`

It's seems to not be `windows-1258` but another encoding like `TCVN-3` but java don't reconize this encoding. You seems to have to convert your text to image to print your receipt.

**Comment by linhlq58** [comment]
@DantSu I converted string to bitmap and printed Vietnamese receipt successfully. But the printing speed is too slow when comparing with normal text printing. 

How can I improve it?

**Comment by DantSu** [comment]
It's normal. Image is very very more data than simple text. Instead of one byte by char, you have to send ~24 bytes... blank space is 24bytes too.

**Comment by DantSu** [comment]
If you only print image, like documentation said go here : https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70#issuecomment-714390014

If you use bluetooth, big image will cause trouble. 
- Do not use `disconnect()` method.
- Increase waiting time before print the next element
