### ISSUE TITLE
Unable to print in Arabic using Xprinter XP-P810

### ISSUE THREAD

**Issue by hjhub** [DantSu/ESCPOS-ThermalPrinter-Android#239]
Hello,

I am trying to print a string containing Arabic characters, but when I print it, the paper is blank.

Here is the code I wrote:

`                
try {
          
            if (ContextCompat.checkSelfPermission(this, Manifest.permission.BLUETOOTH) != PackageManager.PERMISSION_GRANTED) {

                    ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.BLUETOOTH}, InvoiceActivity_AR.PERMISSION_BLUETOOTH);

                } else {

                    BluetoothConnection connection = BluetoothPrintersConnections.selectFirstPaired();

                    if (connection != null) {

                        EscPosPrinter printer = new EscPosPrinter(connection, 203, 78f, 48);

                        final String text = "[C]شركة الحياة";

                        printer.printFormattedText(text);
                    } else {
                        Toast.makeText(this, "No printer was connected!", Toast.LENGTH_SHORT).show();
                    }
                }
            } catch (Exception e) {
                Log.e("APP", "Can't print", e);
            }`

At first I thought that this printer does not support Arabic. But I tried to print from text app and it worked normally.

Please help me fix it.

Thanks.

**Comment by DantSu** [comment]
Text app convert to picture before print. You have to do the same.
