### ISSUE TITLE
 Image printing not  work well

### ISSUE THREAD

**Issue by lavahasif** [DantSu/ESCPOS-ThermalPrinter-Android#24]
image 1
![exit1](https://user-images.githubusercontent.com/22430922/85937764-3d804880-b924-11ea-8f7a-df7f55175b66.png)
photo size :256*256 and color bit 8bit

image 2
![cup](https://user-images.githubusercontent.com/22430922/85937780-699bc980-b924-11ea-9c99-ad13d72150c2.jpg)
With image  Simultaneous printing feel printer getting slow down
Thank you work well other in side

**Comment by DantSu** [comment]
Explain your problem. Share your image....

**Comment by lavahasif** [comment]
> Explain your problem. Share your image....

![](https://user-images.githubusercontent.com/22430922/85937780-699bc980-b924-11ea-9c99-ad13d72150c2.jpg)

**Comment by DantSu** [comment]
Esc Pos printer print in two color... black/white... it's not a bug... it's a limit of ESC commands.
