### ISSUE TITLE
Print icon and text on one line 

### ISSUE THREAD

**Issue by yovi-ep** [DantSu/ESCPOS-ThermalPrinter-Android#242]
how to print a receipt with a view like below? 
![Screenshot_20220103-191115_Chrome.jpg](https://user-images.githubusercontent.com/17000456/147930538-c39ec8d4-bc1f-4aaf-81cf-4bf3a007ad72.jpg)

**Comment by DantSu** [comment]
Not possible. With ESC/POS commands, you can't write text and image on the same line.

**Comment by yurii-chernii** [comment]
What about page mode?
