### ISSUE TITLE
System.error :: Broken Pipe Issue for TCP Printing

### ISSUE THREAD

**Issue by project-lambda** [DantSu/ESCPOS-ThermalPrinter-Android#243]
I am using a Wifi POS Printer. But using TCP Printer it gives me the broken pipe error.

`                var tcpConnection = TcpConnection("192.168.0.230", 5555, 60000)
                tcpConnection.connect()
                println(tcpConnection.isConnected)
                val printer = EscPosPrinter(tcpConnection, 300, 80f, 48)
                printer.printFormattedText("Text")`

This following error was thrown every time. But USB printing is ok with the same printer.

`W/System.err: java.net.SocketException: Broken pipe
W/System.err:     at java.net.SocketOutputStream.socketWrite0(Native Method)
W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
W/System.err:     at java.net.SocketOutputStream.write(SocketOutputStream.java:149)
W/System.err:     at com.dantsu.escposprinter.connection.DeviceConnection.send(DeviceConnection.java:54)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.feedPaper(EscPosPrinterCommands.java:613)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:128)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:89)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:78)
W/System.err:     at com.example.posprinter.MainActivity.onResume$lambda-0(MainActivity.kt:48)
W/System.err:     at com.example.posprinter.MainActivity.$r8$lambda$AvvoVuh6qjUVNlKiBQfre9S3RUw(Unknown Source:0)
W/System.err:     at com.example.posprinter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:0)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Broken pipe
W/System.err:     at com.dantsu.escposprinter.connection.DeviceConnection.send(DeviceConnection.java:63)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.feedPaper(EscPosPrinterCommands.java:613)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:128)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:89)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:78)
W/System.err:     at com.example.posprinter.MainActivity.onResume$lambda-0(MainActivity.kt:48)
W/System.err:     at com.example.posprinter.MainActivity.$r8$lambda$AvvoVuh6qjUVNlKiBQfre9S3RUw(Unknown Source:0)
W/System.err:     at com.example.posprinter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:0)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
Disconnected from the target VM, address: 'localhost:64083', transport: 'socket'`

Please help me out.

**Comment by DantSu** [comment]
Broken pipe means that's your device can't be connected to your printer on the network.

**Comment by project-lambda** [comment]
But I am tested through the terminal and ping to the ip and port, It succeeded.
Using socket, Also ping to the specific IP and port its connected well. But when sending the printing command it says the Broken pipe issue.  

                 `var socket = Socket()
                    socket.connect(
                        InetSocketAddress(
                            InetAddress.getByName("192.168.0.230"),
                            5555
                        ), 6000
                    )
                    var outputStream = socket.getOutputStream()
                    outputStream.close()`
