### ISSUE TITLE
printing Barcode mode does not print

### ISSUE THREAD

**Issue by waleedmakarem** [DantSu/ESCPOS-ThermalPrinter-Android#244]
When my Xprinter XP-318B in Receipt mode , it does print. But , when in Barcode mode, app give message that print was successful  But actually, nothing print. 
Are there any reason for this. 
Thanks..

**Comment by DantSu** [comment]
I don't know what's barcode mode. But if is not ESC/POS commands mode, it's normal.

**Comment by waleedmakarem** [comment]
noted, Thanks DantSu.
One last thing, do you have normal .Net framwork for this excellent library. 
Thanks..
