### ISSUE TITLE
BluetoothPrintersConnections.selectFirstPaired() freeze UI

### ISSUE THREAD

**Issue by tohedul** [DantSu/ESCPOS-ThermalPrinter-Android#245]
Hi, current <b>BluetoothPrintersConnections.selectFirstPaired()</b> method freeze the UI. Which hampers the user-experince and we can't use UI base task like progress dialog.
Another thing is there are no other methods in this class where I can pass printer mac address and get <b>selectFirstPaired()</b> method like BluetoothConnection. I write a method locally, here it is

<code>
public static BluetoothConnection getPrinterConnection(String printerAddress) {
        BluetoothPrintersConnections printers = new BluetoothPrintersConnections();
        BluetoothConnection[] bluetoothPrinters = printers.getList();

        if (bluetoothPrinters != null && bluetoothPrinters.length > 0) {
            for (BluetoothConnection printer : bluetoothPrinters) {
                try {
                    if (printer.connect().getDevice().getAddress().equals(printerAddress))
                        return printer.connect();
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
            }
        }
        return null;
    }
</code>

You can add this method. But most important these two methods should be <b>ansynchronous functional interface</b>, which return BluetoothConnection on connection succeed and error message on any error occur. So this async functional interface won't block or freeze UI and we can use dialogs or any UI base task during this processing.

**Comment by DantSu** [comment]
Use async method, not in main activity.
