### ISSUE TITLE
Print Image Not Work, EPSON TM-U220B 76mm (LAN/WIFI)

### ISSUE THREAD

**Issue by yoviep** [DantSu/ESCPOS-ThermalPrinter-Android#249]
Halo @DantSu
i have problem in printer epson TM-U220B 76mm set 203dpi, print image not work.
my payload like this:
```
    "[C]<img>PrinterTextParserImg.bytesToHexadecimalString(EscPosPrinterCommands.bitmapToBytes(image.rescale(maxWidth: 256))</img>\n\n" +
    "[L]\n" +
    "[L]<b>                 GS Shop                </b>" +
```

with result:
![WhatsApp Image 2022-01-26 at 5 31 45 PM](https://user-images.githubusercontent.com/17000456/151148556-b05388ec-ac4a-4d89-bae0-85dcc2663811.jpeg)

expectation like this, (to printer bluetooth 58mm, set 203dpi):

![WhatsApp Image 2022-01-26 at 5 42 35 PM](https://user-images.githubusercontent.com/17000456/151149150-2a9bd20f-3377-4faf-9439-74d7871249ed.jpeg)

Please help me

**Comment by yoviep** [comment]
any solution?

**Comment by DantSu** [comment]
no, closed due to inactivity.

**Comment by DantSu** [comment]
TM-U220B seems to not be compatible with old image command. That's it.

**Comment by yoviep** [comment]
do you have any suggestions for a new image command?

**Comment by DantSu** [comment]
Today the library use this command : 
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=94

They say : 

> ### [Recommended Functions]
>This command is supported by only some of the printer models and will not be supported by future models.
>It is recommended to use graphics function (GS ( L   <Function 50> and GS ( L   /   GS 8 L   <Function 112> ). The graphics function is superior in operating to GS v 0   [obsolete command] for the following reasons:
> -    Selecting a color for printing is possible.
> -    Size setting in dot unit is possible.

But many "not Epson" printers don't know those commands, like my printer. I can't use it.
