### ISSUE TITLE
[feature request] new method printencodedbytes

### ISSUE THREAD

**Issue by selvam920** [DantSu/ESCPOS-ThermalPrinter-Android#250]
can you provide new method "printencodedbytes" 
so i can pass encoded bytes into printer without using formatted

**Comment by DantSu** [comment]
That's what you want no ? https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70#issuecomment-925619716

**Comment by selvam920** [comment]
No, i want to pass esc pos command bytes in new method

**Comment by DantSu** [comment]
I don't understand your need

**Comment by selvam920** [comment]
Need to pass pos command direct without formatting text
I'm using another plugin, in that I'm getting output in bytes not image bytes

**Comment by selvam920** [comment]
i just want to print without your PrinterTextParser

**Comment by selvam920** [comment]
i will pass encoded pos commands

**Comment by DantSu** [comment]
I confirm this is your need....
