### ISSUE TITLE
88mm printer width issue

### ISSUE THREAD

**Issue by ajmalpk23** [DantSu/ESCPOS-ThermalPrinter-Android#252]
![aa462971-1cbd-4b24-8a62-bb05aa7e83e1](https://user-images.githubusercontent.com/61465738/152299218-08471f2e-9588-4104-ba89-50955ba53d20.jpg)

used this 
 printer = new EscPosPrinter(bluetoothConnection.connect(), 203, 76f, 48);

**Comment by ajmalpk23** [comment]
issue fixed

**Comment by rizwanbao** [comment]
> issue fixed

how you fixed that i have same issue?
