### ISSUE TITLE
Insert data to db only if receipt is printed (FINISH_SUCCESS)

### ISSUE THREAD

**Issue by fWd82** [DantSu/ESCPOS-ThermalPrinter-Android#253]
Dear Franck! Thank You very much for this awesome work. 

Everything worked great. Except that I want to insert value to database only if receipt is printed. 

You commented here: 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/206#issuecomment-968725970 that there is no callback. I don't want that. But I want to check this line: 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/e0721be4ff5396d0aa2cc764487fe6b2c625918e/app/src/main/java/com/dantsu/thermalprinter/async/AsyncEscPosPrint.java#L134

```
        switch (result) {
            case AsyncEscPosPrint.FINISH_SUCCESS:
                new AlertDialog.Builder(context)
                        .setTitle("Success")
                        .setMessage("Congratulation ! The text is printed !")
                        .show();
                        // something to be executed here <<<
            break;
```
 
I want to know this above block of code to check in my **MainActivity** 

```
// case AsyncEscPosPrint.FINISH_SUCCESS
// if case is FINISH_SUCCESS I want to insert data via a method call in my MainActivity
if(sucess){
   insertDataToDatabase();      <<<
}
```

I have been working on this for two days and cannot even find a way, please if you help.

**Comment by fWd82** [comment]
What I have done for now is, I created a static method ** insertDataToDatabase()** in **MainActivity.java**
```
public static void insertDataToDatabase(){
        Log.d(TAG, "insertDataToDatabase: The bluetooth device accept command, so it's better to save record.");
}
```

and I called it **AsyncEscPosPrint.java** _(line number: 140)_  as:

```
switch (result) {
            case AsyncEscPosPrint.FINISH_SUCCESS:
                new AlertDialog.Builder(context)
                        .setTitle("Success")
                        .setMessage("Congratulation ! The text is printed !")
                        .show();
                MainActivity.insertDataToDatabase(); // <<< here
                break;
```
This worked just fine for now, as it's not a solution but a temporary workaround. As my code will go away if I decided to update the library, so obviously it's a bad practice. 

I will love if some guide and show me proper way.

**Comment by DantSu** [comment]
git clone the project, or git pull if you already clone the project. I have implemented callback on async print.

**Comment by fWd82** [comment]
The new [updated version](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/commit/007dc9f0f47b98157d6f5550a7867e40eda70ce0) is extremely helpful. The callback is really awesome. Thank You!
