### ISSUE TITLE
Detect if you have an active printer or not before printing

### ISSUE THREAD

**Issue by alcadiosystem** [DantSu/ESCPOS-ThermalPrinter-Android#254]
I have the previously implemented library working well so far, but something crazy comes up (in my opinion), it is that when printing, there is an active bluetooth connection and a printer paired with the device, BUT THE PRINTER IS NOT ACTIVE.
the print action continues to be executed normally and that information is lost by not being able to print due to having an INACTIVE printer
Is there any way to know if the printer that is paired with the device is active or not before generating the print action of the library?

Could you help me with this problem? @DantSu

**Comment by DantSu** [comment]
I can't help you, but if you find an answer please give me a feedback here !
