### ISSUE TITLE
Image and QRCode are in the right position

### ISSUE THREAD

**Issue by rionymous** [DantSu/ESCPOS-ThermalPrinter-Android#255]
I follow your tutorial, but why are the logo and QRCode in the right position?

My code:
<pre>
<code>
 EscPosPrinter printer = null;
                try {
                    printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 88f, 45);
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
                try {
                    assert printer != null;
                    printer
                            .printFormattedText(
                                    "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, itemView.getContext().getDrawable(R.drawable.sap_logo_gray)) + "</img>\n" +
                                    "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                                    "[C]==============================================\n" +
                                    "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                                    "[L]  + Size : S\n" +
                                    "[C]----------------------------------------------\n" +
                                    "[R]TOTAL PRICE :[R]34.98e\n" +
                                    "[R]TAX :[R]4.23e\n" +
                                    "[C]==============================================\n" +
                                    "[L]<font size='tall'>Customer :</font>\n" +
                                    "[L]Raymond DUPONT\n" +
                                    "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                                    "[C]<qrcode size='15'>http://www.sap-express.id/</qrcode>"
                            );
                } catch (EscPosConnectionException | EscPosParserException | EscPosEncodingException | EscPosBarcodeException e) {
                    e.printStackTrace();
                }
</code>
</pre>
![WhatsApp Image 2022-02-09 at 6 24 43 PM](https://user-images.githubusercontent.com/17020791/153190873-e5a5260a-8553-48e3-b09e-8af14aae3542.jpeg)

What's the problem?

**Comment by DantSu** [comment]
is a 88mm 203dpi printer ?

**Comment by rionymous** [comment]
if i change the code to the original, image to the left and qrcode still in right.
<pre>
<code>
EscPosPrinter printer = null;
                try {
                    printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32);
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
                try {
                    assert printer != null;
                    printer
                            .printFormattedText(
                                    "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, itemView.getContext().getDrawable(R.drawable.sap_logo_gray)) + "</img>\n" +
                                    "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                                    "[C]==============================================\n" +
                                    "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                                    "[L]  + Size : S\n" +
                                    "[C]----------------------------------------------\n" +
                                    "[R]TOTAL PRICE :[R]34.98e\n" +
                                    "[R]TAX :[R]4.23e\n" +
                                    "[C]==============================================\n" +
                                    "[L]<font size='tall'>Customer :</font>\n" +
                                    "[L]Raymond DUPONT\n" +
                                    "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                                    "[C]<qrcode size='15'>http://www.facebook.com/</qrcode>"
                            );
                } catch (EscPosConnectionException | EscPosParserException | EscPosEncodingException | EscPosBarcodeException e) {
                    e.printStackTrace();
                }

</code>
</pre>
![WhatsApp Image 2022-02-10 at 5 42 51 PM](https://user-images.githubusercontent.com/17020791/153390789-825bcddf-7dba-4f81-86e3-d98c95664b1d.jpeg)

**Comment by DantSu** [comment]
I think, your printer is not 203 dpi.

printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 102, 84f, 45);

**Comment by bondcs** [comment]
Hi @DantSu, I'm having the same problem on an Epson TM88V printer, I've tried different DPI settings.

102 DPI
![WhatsApp Image 2022-03-24 at 14 29 06](https://user-images.githubusercontent.com/2110613/159977207-e6b0b7da-b92e-484e-a805-e5e4e7b5c465.jpeg)
180 DPI (This is DPI from printer documentation)
![WhatsApp Image 2022-03-24 at 14 38 11](https://user-images.githubusercontent.com/2110613/159977268-f2682068-89b1-4166-a6b2-c023b0441b17.jpeg)
203 DPI
![WhatsApp Image 2022-03-24 at 14 14 15](https://user-images.githubusercontent.com/2110613/159977316-54cf05ce-9503-4ac9-94ec-00a889eef15a.jpeg)
