### ISSUE TITLE
Images contrast problems

### ISSUE THREAD

**Issue by davicrystal** [DantSu/ESCPOS-ThermalPrinter-Android#257]
Hi,

I got some issues with image contrast, when the image has a few  fades of colors  the image is printed as a full black square :disappointed: 

**Exemple of the original image:**

![WhatsApp Image 2022-02-11 at 12 13 05](https://user-images.githubusercontent.com/2035530/153617300-8fb4ae13-9750-4482-9718-24f6c65b0e74.jpeg)

**Exemple of the printed image:**

![WhatsApp Image 2022-02-11 at 12 08 32](https://user-images.githubusercontent.com/2035530/153617343-439c260d-698a-4c4d-ba25-1885c89d3693.jpeg)

Is There something thay I can do to fix that?

**Comment by DantSu** [comment]
normal behavior, thermal printer is'nt greyscale, it's black or white.

**Comment by davicrystal** [comment]
Thank you @DantSu for your response,

Anyway, I going to share my approching to solve this issue for someone that has the same problem, because in a production scenario, there are multiple kinds of logos without specification for good printing.

For me, the solution was to convert the image to black and white with a **halftone filter**

So, this

![flag-normal](https://user-images.githubusercontent.com/2035530/153943665-465edd2d-f677-48df-8bbb-978839a48b1e.jpeg)

Became this

![flag-halftone](https://user-images.githubusercontent.com/2035530/153943704-0ba5f561-b4db-4665-bc0d-2bd2dab1e5fa.png)

And the printing result was as the follow

![image](https://user-images.githubusercontent.com/2035530/153945466-239199f7-e352-481c-813e-7410030f16ec.png)

and...

![image](https://user-images.githubusercontent.com/2035530/153945533-a2474779-83b8-48a4-98f3-cd7b4df83c12.png)

The tool for convert the image was the **Marvin Image Prcessor Framework**, there are plugins for:

- **Java** ( [http://marvinproject.sourceforge.net/en/index.html] ) 
- **Javascript** ( [https://www.marvinj.org/en/index.html] )

In my case,  I have implemented with a javascript npm module: [https://www.npmjs.com/package/marvinj-angular]

**Comment by DantSu** [comment]
Not woth this library

**Comment by davicrystal** [comment]
[Cordova Plugin for Thermal Printer's](https://github.com/paystory-de/thermal-printer-cordova-plugin) implements the printing method of this library

**Comment by DantSu** [comment]
Use another library, this one do not do that.

**Comment by DantSu** [comment]
Hi,

Try v3.1.0.

I have create an algorithm to transform colored pictures to black and white. Give me a feedback on it. 😉

**Comment by DantSu** [comment]
Today I have created an update for better gradients : v3.1.1
