### ISSUE TITLE
printing the letter "r" at the beginning

### ISSUE THREAD

**Issue by jizreelguimaraes** [DantSu/ESCPOS-ThermalPrinter-Android#258]
every print prints the letter "r" at the beginning. do you know what it could be?

**Comment by DantSu** [comment]
yes, already ask, and already answered. Look at closed issues.

**Comment by jizreelguimaraes** [comment]
did not work.

this is the text I send calling the method printFormattedTextAndCut(textBelllow, 5f);


`[L]<b><font size='normal'>           PEDIDO PARA PRODUCAO           </font></b>
[L]<b><font size='normal'>    KDS Padrao - Empresa 103330 (KDS2)    </font></b>
[L]<font size='normal'>------------------------------------------</font>
[L]<b><font size='tall'>1,000 X PRODUTO 1 - KDS 2                 </font></b>
[L]<font size='normal'>------------------------------------------</font>
[L]<font size='normal'>Observacao: Comanda: 235 Mesa: 2          </font>
[L]<font size='normal'>Operador: Jizrieel                        </font>
[L]
[C]<barcode type='128' height='10' text='none'>                   1731                   </barcode>
[L]<font size='normal'>------------------------------------------</font>
[L]<b><font size='normal'>Caixa: 443            21/02/2022 15:07:29</font></b>
[L]<b><font size='normal'>CISSFly                            11.0.0</font></b>
[L]<font size='normal'>                                          </font>
[L]<font size='normal'>                                          </font>
[L]<font size='normal'>                                          </font>
[L]<font size='normal'>                                          </font>
`

and the "r" comes out the same at the beginning of printing

**Comment by jizreelguimaraes** [comment]
![b5c3a277-b4dd-4cb9-8f6c-8a3bbdfce8bc (1)](https://user-images.githubusercontent.com/54091725/155008376-3acac6c5-275a-47ea-9506-2b7370cf922a.jpg)

**Comment by jizreelguimaraes** [comment]
if you can help me

**Comment by DantSu** [comment]
Send me more code of your project.

**Comment by jizreelguimaraes** [comment]
![Screen Shot 2022-02-21 at 15 57 14](https://user-images.githubusercontent.com/54091725/155012848-08e031df-36bd-4eb6-9d2c-1c037d3af754.png)

**Comment by jizreelguimaraes** [comment]
the convertToString returns the text formatted in the way I mentioned above

**Comment by jizreelguimaraes** [comment]
![Screen Shot 2022-02-21 at 16 00 51](https://user-images.githubusercontent.com/54091725/155013206-73dbb644-a67f-42ed-90dd-6f3a477ece97.png)

**Comment by jizreelguimaraes** [comment]
and I haven't made any changes to the methods that are called from printFormattedTextAndCut

**Comment by DantSu** [comment]
You don't read my previous answer...

**Comment by DantSu** [comment]
EscPosPrinter printer = new EscPosPrinter(new MyEscPosPrinterCommands(tcpConnection), 203, 80f, 40);

**Comment by jizreelguimaraes** [comment]
yes, I had already done exactly as mentioned in the first answer, but it continues to print the "r" at the beginning of the print

**Comment by jizreelguimaraes** [comment]
![Screen Shot 2022-02-22 at 11 48 06](https://user-images.githubusercontent.com/54091725/155156890-4120ac8e-ddd5-4ca8-b3e3-913d7acbecb0.png)

**Comment by jizreelguimaraes** [comment]
![Screen Shot 2022-02-22 at 11 48 19](https://user-images.githubusercontent.com/54091725/155157027-751518c1-053d-4901-a02c-ad4ce2f7afae.png)

**Comment by jizreelguimaraes** [comment]
it is this command that prints the "r"

**Comment by jizreelguimaraes** [comment]
I commented out the line this.printerConnection.write(textColor) and it didn't really print the "r" anymore
