### ISSUE TITLE
print bill in loop

### ISSUE THREAD

**Issue by sureshios** [DantSu/ESCPOS-ThermalPrinter-Android#259]
how can i print item in loop ?

**Comment by DantSu** [comment]
Git clone or git pull the project, and look code. I have added example with loop print.

**Comment by sureshios** [comment]
also i need 4 item in one line .  how can i set left right and center

Example - 
Item     Qty   Amount   Value

**Comment by DantSu** [comment]
Read the doc...
`"[L]Item[L]Qty[C]Ammount[R]Value"`

**Comment by DantSu** [comment]
Text alignment and column separation
Add an alignment tag on a same line of text implicitly create a new column.

Column alignment tags :

[L] : left side alignment
[C] : center alignment
[R] : right side alignment
Example :

[L]Some text : One column aligned to left
[C]Some text : One column aligned to center
[R]Some text : One column aligned to right
[L]Some text[L]Some other text : Two columns aligned to left. Some other text starts in the center of the paper.
[L]Some text[R]Some other text : Two columns, first aligned to left, second aligned to right. Some other text is printed at the right of paper.
[L]Some[R]text[R]here : Three columns.
[L][R]text[R]here : Three columns. The first is empty but it takes a third of the available space.
