### ISSUE TITLE
Language printing issue with bitmap Arabic/Hindi etc. 

### ISSUE THREAD

**Issue by madhura365** [DantSu/ESCPOS-ThermalPrinter-Android#260]
I have converted every line to bitmap and Build hexadecimal string as follows.

```java
    public String drawTextToBitmaps(String gText, AsyncEscPosPrinter printer, Activity activity) {
        StringBuilder formatText = new StringBuilder();
        for (String line: gText.split("\n")) {
            formatText.append("[L]<img>").append(PrinterTextParserImg.bitmapToHexadecimalString(printer, ConvUtils.textAsBitmap(activity, line, 28, Color.BLACK, 3))).append("</img>\n");
        }

        return formatText.toString();
    }
```
After that passed it into AsyncEscPosPrint class. And I have used loop printing as follows

```java
    @SuppressLint("SimpleDateFormat")
    public AsyncEscPosPrinter getAsyncEscPosPrinter(DeviceConnection printerConnection) {

        AsyncEscPosPrinter printer = new AsyncEscPosPrinter(printerConnection, 203, 48f, 32);
        return printer.addTextToPrint(drawTextToBitmaps(edit_text.getText().toString(),printer,MainActivity.this));

    }

```
```java
            String[] textsToPrint = printerData.getTextsToPrint();

            for(String textToPrint : textsToPrint) {
                printer.printFormattedText(textToPrint);
                Thread.sleep(500);
            }

```

But my attempt is not success. Print is coming halfly and some time print unknown characters 

I have try this method also.

```java
    private void bigImagePrinting(DeviceConnection printerConnection){

        Bitmap icon = getBitmap(gText);
        int targetWidth = 383; // 48mm printing zone with 203dpi => 383px
        Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                icon,
                targetWidth,
                Math.round(((float) icon.getHeight()) * ((float) targetWidth) / ((float) icon.getWidth())),
                true
        );

        

        EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(printerConnection);
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
            printerCommands.feedPaper(100);
            printerCommands.cutPaper();

        } catch (EscPosConnectionException e) {
            Log.d(TAG, "bigImagePrinting: printer "+e.toString());

        }
    }
```

Can anyone help if bitmap printing is successful. I suggest to the author to add a complete  bitmap printing example that can print any language to a example project. I think it is very important. Reading the issues , is is clear that many people have problems with language printing.

**Comment by DantSu** [comment]
I can't do that because each printer have their own way to print languages. There is no standard for that... that's why many issues are opened on this subject, and the answer is always the same : depend on your printer, look the manual.

If you find a way to write text with your language on your printer, please share us your work, that will always be welcome....

For pictures half printed, in many issue, that come from poor bluetooth connection. Have you try using USB connection ?

**Comment by madhura365** [comment]
The POS system that we create is used all over the world. They use may printers. Therefore language encoding cannot be done by looking at the printer. 

But if we print an image we will not have the encode problem. But bitmap printing is not stable. If it can be stabilized, it will be a victory for all of us.

I have tested on SGT-B58V Scangle printer, CK-710 UWB USB,Bluetooth,Network printer, CK-710 U USB printer, another chinese 80mm portable bluetooth printer(Model not mentioned)

This is sample thermal printer app [Loyverse ](https://apkcombo.com/loyverse-toolkit-unreleased/com.loyverse.toolkit/download/apk) 

This app has used graphic printing for other languages. Image printing is the best way to print other languages. 
If you can develop efficient image printing method/ example all language printing will solve. :)
I am also trying to solve the image printing problem using your library.

**Comment by DantSu** [comment]
I haven't the problem, I print a lot of different pictures with my printer and it's always well printed, by bluetooth or USB.
Have you try another Android device ?

**Comment by DantSu** [comment]
Do you use Bluetooth,USB or TCP ?

**Comment by madhura365** [comment]
Yes I have used USB. But I cannot use TCP. Problem arise when the bill is too long. But i am not going to print whole bill at once.
You have mentioned that can only print maximum of 256px at a time. So I split the bill into 5 line section, bitmapped it and printed it using loop printer method.

`String[] textsToPrint = printerData.getTextsToPrint();

            for(String textToPrint : textsToPrint) {
                printer.printFormattedText(textToPrint);
                Thread.sleep(500);
            }`

1.Convert bill in to relevant bitmap 
2.Pass bitmap into printer

If we do these two part correctly I think we can win. Let's try

**Comment by madhura365** [comment]
> I haven't the problem, I print a lot of different pictures with my printer and it's always well printed, by bluetooth or USB. Have you try another Android device ?

Normal logos and images ok. The problem occur when image larger. Have you try to print bitmap bill? I think this problem is largely solved by including an example of bitmap bill printing in example project.

**Comment by DantSu** [comment]
I think to one thing, may be between each image the library not waiting enougth time. Because image is heavy and tranfer take too long time.

Clobne the project and edit this file : 

https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/68a2e05423eb1346dd500840b45390f231d1b615/escposprinter/src/main/java/com/dantsu/escposprinter/connection/DeviceConnection.java#L49

Go to this method : 

```java
    /**
     * Send data to the device.
     */
    public void send(int addWaitingTime) throws EscPosConnectionException {
        if(!this.isConnected()) {
            throw new EscPosConnectionException("Unable to send data to device.");
        }
        try {
            this.outputStream.write(this.data);
            this.outputStream.flush();
            int waitingTime = addWaitingTime + this.data.length / 16;
            this.data = new byte[0];
            if(waitingTime > 0) {
                Thread.sleep(waitingTime);
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            throw new EscPosConnectionException(e.getMessage());
        }
    }
```

and change this line : `Thread.sleep(waitingTime);` to `Thread.sleep(waitingTime + 1000);`

Try this, 1000 will be very long, but that's for testing. After you will reduce the value, if it works correctly.
