### ISSUE TITLE
No jar and aar

### ISSUE THREAD

**Issue by claudiopizzillo** [DantSu/ESCPOS-ThermalPrinter-Android#262]
Files .jar and .aar for version 3.1.1 are not produced (from Jitpack log):

...
BUILD SUCCESSFUL in 46s
111 actionable tasks: 108 executed, 3 up-to-date
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Archive: ThermalPrinter:escposprinter:unspecified
Publication: com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.1.0
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.1.0
Found artifact: ThermalPrinter:escposprinter:unspecified
Found artifact: com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.1.0
2022-02-18T10:24:45.268221345Z
Exit code: 0

✅ Build artifacts:
com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.1.1

Files: 
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.1
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.1/ESCPOS-ThermalPrinter-Android-3.1.1.pom
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.1/ESCPOS-ThermalPrinter-Android-3.1.1.pom.md5
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.1/ESCPOS-ThermalPrinter-Android-3.1.1.pom.sha1
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.1/build.log

**Comment by DantSu** [comment]
The v3.1.1 doesn't works ?

**Comment by DantSu** [comment]
v3.1.2 build successful with an AAR file :)

```
✅ Build artifacts:
com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.1.2

Files: 
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.2
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.2/ESCPOS-ThermalPrinter-Android-3.1.2.aar
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.2/ESCPOS-ThermalPrinter-Android-3.1.2.pom
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.2/ESCPOS-ThermalPrinter-Android-3.1.2.pom.md5
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.2/ESCPOS-ThermalPrinter-Android-3.1.2.pom.sha1
com/github/DantSu/ESCPOS-ThermalPrinter-Android/3.1.2/build.log
```
