### ISSUE TITLE
Extra space print between some printers

### ISSUE THREAD

**Issue by madhura365** [DantSu/ESCPOS-ThermalPrinter-Android#263]
I have used following example for loop printing. 

`private void dummyPrinter(DeviceConnection connection){
        try {
            EscPosPrinter printer = new EscPosPrinter(connection, 203, 48f, 32);
            for(int i=0;i<4;i++){
                printer.printFormattedText("[L]text\n");
            }
            printer.disconnectPrinter();
        }catch (Exception e){
            e.printStackTrace();
        }

    }`

But CK710 USB printer give huge space between text. 
![WhatsApp Image 2022-02-27 at 12 02 42 PM(1)](https://user-images.githubusercontent.com/100182330/155871507-a50e747e-871b-4c11-bb5f-a8337be8c975.jpeg)

Bluetooth scangle printer it print correctly. 
![WhatsApp Image 2022-02-27 at 12 02 42 PM](https://user-images.githubusercontent.com/100182330/155871585-174f775c-cef5-48f7-9a4b-63c5176055ea.jpeg)

Do you have any idea regarding extra space?

**Comment by DantSu** [comment]
CK710 USB have the correct behavior. You have to use a StringBuilder and call printFormattedText with the complete string just one time.

**Comment by DantSu** [comment]
You have to do something like that :

```java
EscPosPrinter printer = new EscPosPrinter(connection, 203, 48f, 32);
StringBuilder str = new StringBuilder();
for(int i=0;i<4;i++){
    str.append("[L]text\n");
}
printer.printFormattedText(str.toString());
printer.disconnectPrinter();
```

**Comment by DantSu** [comment]
Bluetooth scangle printer don't works correctly...

**Comment by madhura365** [comment]
I want to sent multiple `printFormattedText` like your [loop printing example](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/app/src/main/java/com/dantsu/thermalprinter/async/AsyncEscPosPrint.java)

`
String[] textsToPrint = printerData.getTextsToPrint();

            for(String textToPrint : textsToPrint) {
                printer.printFormattedTextAndCut(textToPrint);
                Thread.sleep(500);
            }`

because data load is huge printer memory not enough. Is there a way to send data all the data little by little without sending it all at once. 

when single line give huge space. But if i add 5 line the not any sapce both printers same. 

`private void dummyPrinter(DeviceConnection connection){
      try {
          EscPosPrinter printer = new EscPosPrinter(connection, 203, 48f, 32);
          for(int i=0;i<4;i++){
              printer.printFormattedText("[L]text\n"+"[L]text\n"+"[L]text\n"+"[L]text\n"+"[L]text\n");
          }
          printer.disconnectPrinter();
      }catch (Exception e){
         e.printStackTrace();
     }

}`
Are there any minimum printer height?

**Comment by DantSu** [comment]
Look optionnal params of printFormattedText.

**Comment by madhura365** [comment]
Do you mean `printFormattedText(String text, float mmFeedPaper)` or `printFormattedText(String text, int dotsFeedPaper)` ?

**Comment by madhura365** [comment]
It is worked fine. Thank you vary much.
