### ISSUE TITLE
Cut is slow.

### ISSUE THREAD

**Issue by stajerg** [DantSu/ESCPOS-ThermalPrinter-Android#264]
Hello.
I am using your library, which is awesome.
Everything is good, except, that the cutting is slow at the end of the picture.
My receipt is a picture, generated from a webView, and I am printing that image.

Here is my code:
`printerCommands.connect();

printerCommands.reset();

printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(bitmapToPrint));

printerCommands.feedPaper(50);

printerCommands.cutPaper();

printerCommands.disconnect();`

The image is good, but the cut at the end takes 3-4-5 second. Can you help me what might be the issue?

Thank you!

**Comment by DantSu** [comment]
can't help you, I don't have printer with cut.
