### ISSUE TITLE
Cant print arabic text

### ISSUE THREAD

**Issue by PranavMalayil** [DantSu/ESCPOS-ThermalPrinter-Android#265]

**Comment by PranavMalayil** [comment]
I have an milestone bluetooth printer and for english it's working fine but arabic text is not printing. @DantSu it's good to add this in your wiki. and also add some examples with printer width too

**Comment by DantSu** [comment]
same answer, again and again... I can't. Each printer have their own charset ID, so you have to do it by yourself. This is not standard...

**Comment by PranavMalayil** [comment]
sorry it's my mistake thanks for your time @DantSu
