### ISSUE TITLE
Datecs DPP-350 doesn't support GS v 0, only ESC *

### ISSUE THREAD

**Issue by jaimevives** [DantSu/ESCPOS-ThermalPrinter-Android#273]
Hi DantSu:

I like very much your library, and I'm using it flawlessly on my app with some cheap chinese printers (rebranded ZiJiang ZJ-5802). The problem is now I'm asked to support a DATECS DPP-350, but it doesn't supports the GS v 0 command you use for printing images, only the ESC * command. Do you think I've any option to use it with your library instead having to use their SDK? I hate to use a different SDK for each printer...

  Thanks again for your great work on this library,

--
Jaime

**Comment by DantSu** [comment]
can you help me for this ?

Git clone this project and uncomment this line (`// printer.useEscAsteriskCommand(true);`) in `AsyncEscPosPrint.java` : 

```java
            EscPosPrinter printer = new EscPosPrinter(
                    deviceConnection,
                    printerData.getPrinterDpi(),
                    printerData.getPrinterWidthMM(),
                    printerData.getPrinterNbrCharactersPerLine(),
                    new EscPosCharsetEncoding("windows-1252", 16)
            );

            // printer.useEscAsteriskCommand(true);

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);
```

and try to print an image. I can't test it, my printer isn't comatible with `ESC *` command.

**Comment by jaimevives** [comment]
Thanks Franck, but still getting garbage chars for the image...
![WhatsApp Image 2022-03-26 at 10 11 20](https://user-images.githubusercontent.com/2656310/160232955-dfa46ddc-f852-492d-a6fb-d3cd55f72064.jpeg)

**Comment by DantSu** [comment]
You have uncomment the line ?

**Comment by jaimevives** [comment]
Yes, of course. I even checked that it is in fact using printImageWithEscAsterisk(), and the code there looks fine to me at first glance... The Datecs DPP-350 has a strange set of ESC/POS commands, but the ESC * seems to be implemented the same as the standard.

P.S.: BTW, you can add my other printer to the list of supported printers, as it works perfectly with your library "out-of-the-box". It's a ZiJiang ZJ-5802. It's sold on Amazon with many other "brands": MUNBYN  MU-IMP006,  ‎ENJOY-UNIQUE ZJ-5802,  ‎YZ-LIANG, EXCELVAN, etc...

**Comment by jaimevives** [comment]
Here is the developer manual for the CPP-350:

https://www.datecs.bg/en/downloads/pdf?id=DPP-350_PM_EN_V.1.59.pdf

Looking at page 23, looks to me like it is implemented in the standard way, so it should be working.

**Comment by DantSu** [comment]
Erf... I really want that ESC * works but without testing is very hard to suceed. I don't know what I doing wrong.

**Comment by DantSu** [comment]
I will looking to that

**Comment by jaimevives** [comment]
I've it already working with the Datecs SDK, as I was in ahurry to get it working (fortunately, Datecs support as very kind in resolving quickly all my doubts and problems). But I don't mind helping you out with this testing all your code, as I'm still using your library for the other ESC/POS printers compatible, and would be a way to thank you for this wonderful free library.

**Comment by DantSu** [comment]
Can you git pull and try a new tie ?

**Comment by DantSu** [comment]
Ok I read documentation a new time and it's more complicated that's I was done.... It's require more work to works fine...

**Comment by jaimevives** [comment]
![WhatsApp Image 2022-03-26 at 14 45 39](https://user-images.githubusercontent.com/2656310/160242352-75ce4cca-636c-4f75-9c3d-90dd71d1ac89.jpeg)

**Comment by DantSu** [comment]
Ok now can you pull and give me a feedback ! I think is the good one !

**Comment by jaimevives** [comment]
Yeah! Almost there.... ;)
![WhatsApp Image 2022-03-26 at 15 38 24](https://user-images.githubusercontent.com/2656310/160244429-5dfe3af8-0b4c-4f17-8208-7e7e433d17d9.jpeg)

**Comment by DantSu** [comment]
You have blank line... hmm.... I will look to find a solution.

**Comment by jaimevives** [comment]
Also, what's that "a" char to the right of the image?

**Comment by DantSu** [comment]
and now, try again ^^

**Comment by jaimevives** [comment]
Sorry, Franck, cannot test it right now... I had to give the printer to the final user to test our app. But will try again later today or tomorrow morning.

**Comment by DantSu** [comment]
Ok thanks for your feedback. I will publish a new release today. ;)

**Comment by DantSu** [comment]
v3.2.0 is out !

**Comment by jaimevives** [comment]
Thanks to you for your great work... it was very useful to me. I forgot to tell you that I'm not using your library directly, as our app is an old project done in Netbeans for Android 14, but I managed to modify your demo app to silently accept an intent and I'm using it like if it was a printing service. Works like a charm, very fast and reliable. Thanks again!
