### ISSUE TITLE
center align issue

### ISSUE THREAD

**Issue by vikrammani-t2s** [DantSu/ESCPOS-ThermalPrinter-Android#277]
"[c]<font size='big'>" + getMessage(item) + '</font> \n' 
center align not working properly

**Comment by DantSu** [comment]
No pictures, no code source, no log.... Wait..... I will read in your mind !

**Comment by vikrammani-t2s** [comment]
sorry i already find the solution

**Comment by NandoDev1997** [comment]
> sorry i already find the solution

what is the solution bro?
