### ISSUE TITLE
Font size print error

### ISSUE THREAD

**Issue by nxhung1610** [DantSu/ESCPOS-ThermalPrinter-Android#278]
When I set font size like this, all the text print will print follow first size I set is tall
Can you help me ?

![image](https://user-images.githubusercontent.com/63885463/162167814-3c8a082e-c657-4156-a2a3-bcb26477c667.png)

**Comment by hidenxtt2001** [comment]
when I split for each line and use printFormattedText function it work well, but print all in one function it not work properly

**Comment by DantSu** [comment]
The formatted text have to look like this : 
```java
"[L]<font size='tall'>Onl[R]Delivery</font>\n" +
"[L]\n" +
"[C]House\n" +
"[C]121 Nguyen Co Thach\n"
```

use "\n" maybe you have \r\n line breaking
