### ISSUE TITLE
Printing from database

### ISSUE THREAD

**Issue by babaoye** [DantSu/ESCPOS-ThermalPrinter-Android#280]
How do we set the data availability on from the database or from an api....doesnt look like it supports using some additional loops or something....please i would appreciate some suggestions and help

**Comment by DantSu** [comment]
Use StringBuilder class to create the formatted text.

**Comment by babaoye** [comment]
Thank You sir.....

**Comment by babaoye** [comment]
if you can help with an example....i will really appreciate this sir

**Comment by DantSu** [comment]
No I can't
