### ISSUE TITLE
How to display  records from database tables to print receipt?

### ISSUE THREAD

**Issue by Harisul44** [DantSu/ESCPOS-ThermalPrinter-Android#282]
Or how to add product list from database

**Comment by DantSu** [comment]
Share more information, piece of code, short example, etc ...

**Comment by Harisul44** [comment]
Here I want to add linearlayout.

"[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer,
this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo,
DisplayMetrics.DENSITY_MEDIUM))+"</img>\n" +

1/ Here I want to add product list from database as like.

While(rs.next())

{

"[L]\n" +
        "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
        "[L]  + Size : S\n" +
        "[L]\n" +
        "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
        "[L]  + Size : 57/58\n" +
        "[L]\n" +

}

Please help me.

Thanks

**Comment by DantSu** [comment]
I'm sorry but I don't understand what you are doing and what your problem. Don't reply to the email, come on Github use Markdown for presentation. Share me your database class and the complete method you use to generate formatted text.

**Comment by Harisul44** [comment]
Create table Item 
( 
     Id int  identity(1,1)primary key, 
     ItemName nvarchar(55),
     Saleprice decimal(18,2)
)
Insert into Item values('Book', '100')
Insert into Item values('Pencil', '7')
Insert into item values('Pen', '5')

I want to display this records from tables to print receipt.  And also display logo from Imageview. How to create invoice.  Please help me.

**Comment by Harisul44** [comment]
8[Invoice format](https://drive.google.com/file/d/1fUcz-jbVeWCWoynoUVpYdFHbIHls2BB8/view?usp=drivesdk)

**Comment by DantSu** [comment]
```java
StringBuilder formattedText = new StringBuilder();
While(rs.next())
{
    formattedText.append("[L]").append(rs.getString("ItemName")).append("[R]").append(rs.getDouble("Saleprice")).appen("\n");
}

printer.printFormattedText(formattedText.toString());
```

**Comment by Harisul44** [comment]
Greeting Sir,
Sir, Please do not mind, I have got error .

StringBuilder formattedText = new StringBuilder();
While(rs.next())    //Error in here
{
    formattedText.append("[L]").append(rs.getString("ItemName")).append("[R]").append(rs.getDouble("Saleprice")).appen("\n");
}

printer.printFormattedText(formattedText.toString()); //Error In Semi collon(;)

**Comment by Harisul44** [comment]
Thank you so much sir.

**Comment by Harisul44** [comment]
Invoice Item is not arrange properly not Arabic latter not display.  I have used this  for Item list. please help [me.]

[https://drive.google.com/file/d/1gboIXql-UYiAypsnRGa06UCmHzCFSLVP/view?usp=drivesdk](url)


 
           formattedText.append("[L]<b>").append(rs.getString("Menu")).append("</b>[C]").append(rs.getString("Qty")).append("[R]").append(rs.getDouble("DueAmount")).append("\n");

**Comment by DantSu** [comment]
stop using Google Drive, if you want to share piece of code, select your code and use '<>' button. If you want to share me picture,  drag and drop image inside the rich text editor.
