### ISSUE TITLE
Set Default BluetoothDevice UUID in Bluetooth Connection class

### ISSUE THREAD

**Issue by yoviep** [DantSu/ESCPOS-ThermalPrinter-Android#284]
Thank you, your library has really helped me so far

can this UUID.randomUUID() be set via the parameters in the connect function, because there are some printers that have special uuid for connection.

https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/b79bf91a1268bf9c1c3444fd5aae36caa4408bcc/escposprinter/src/main/java/com/dantsu/escposprinter/connection/bluetooth/BluetoothConnection.java#L64

**Comment by yoviep** [comment]
any suggestion ?

**Comment by Andr3Silva** [comment]
hello @DantSu, 
I had a similar problem, but in my case this fix doesn't solve. In some devices (I tested it on samsung with android 11 - api 30) it returns uuid 00000000-0000-0000-0000-000000000000.

Please check the change i made, maybe it will help anyone who has the same problem:
` return (uuids != null && uuids.length > 0) ? uuids[0].getUuid() : UUID.fromString("00001101-0000-1000-8000-
00805f9b34fb");`

to

` return (uuids != null && uuids.length > 0 && !uuids[0].toString().equals("00000000-0000-0000-0000-000000000000")) ? uuids[0].getUuid() : UUID.fromString("00001101-0000-1000-8000-00805f9b34fb");
`
