### ISSUE TITLE
# Image quality issue

### ISSUE THREAD

**Issue by tejasmusle** [DantSu/ESCPOS-ThermalPrinter-Android#286]
# If you only print image and do not use formatted text, you can do that : 

The image must have a correct width : 
- 1 inch = 25.4mm
- Thermal printer commonly have 203dpi (dots per inch / pixels per inch).
- So the width of the printed bitmap must be `Math.floor(millimetersWidthPrintingZone / 25.4 * 203)` pixels or  `Math.floor(inchWidthPrintingZone * 203)` pixels.

```java
       int targetWidth = 383; // 48mm printing zone with 203dpi => 383px
       Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
           originalBitmap, 
           targetWidth, 
           Math.round(((float) originalBitmap.getHeight()) * ((float) targetWidth) / ((float) originalBitmap.getWidth())), 
           true
       );

       EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

_Originally posted by @DantSu in https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70#issuecomment-925619716_

**Comment by tejasmusle** [comment]
![IMG_20220414_1954112635425742275541096](https://user-images.githubusercontent.com/47097703/163412658-dd93c3a7-3024-417c-960e-3837ba951548.jpg)

My quality is coming like this 


  val targetWidth = (72*(203/25.4)).roundToInt() // 80mm printing zone with 203dpi => 383px currently 80

             val originalBitmap = getBitmapListOfPdf().get(0)
             val targetHeight = Math.round(originalBitmap.height.toFloat() * targetWidth.toFloat() / originalBitmap.width.toFloat())


    
             val rescaledBitmap = Bitmap.createScaledBitmap(
                 originalBitmap,
                 targetWidth,
                 targetHeight,
                 true
             )


            try {
                 printer.connect()
                 printer.reset()
                 printer.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap))
                 printer.feedPaper(50)
                 printer.cutPaper()
             } catch (e: EscPosConnectionException) {
                 e.printStackTrace()


             }

**Comment by DantSu** [comment]
do you use grey for color font ? Use black color.

**Comment by yoviep** [comment]
hi @tejasmusle , should you can try this.

```

        val escAlign = toESCAlign(align)
        val newBitmap = bitmap.toGrayscale()
        val imageFixed = newBitmap.rescale(printer.printerWidthPx)

        val commands = StringBuilder()
        imageFixed.splitHeight().forEach {
            val imageBytes = EscPosPrinterCommands.bitmapToBytes(it)
            val imageHex = PrinterTextParserImg.bytesToHexadecimalString(imageBytes)

            //double \n https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/220
            commands.append("$escAlign<img>$imageHex</img>\n")
        }

        commands.append("[L]\n".repeat(2)).toString()
        commands.toString() -> execute print to lib
```

rescale extensions
```
internal fun Bitmap.rescale(maxWidth: Int): Bitmap {
    var newBitmap = this

    apply {
        if (width > maxWidth) {
            val ratio = height.toDouble() / width.toDouble()
            val newHeight = ceil(maxWidth * ratio).toInt()
            newBitmap = Bitmap.createScaledBitmap(this, maxWidth, newHeight, false)
        }
    }

    return newBitmap
}
```

split height to optimize printing
```
internal fun Bitmap.splitHeight(maxHeight: Int = 256): List<Bitmap> {
    val yCount = height / maxHeight
    // Allocate a array to hold the individual images.
    val bitmaps = arrayListOf<Bitmap>()

    // Loop the array and create bitmaps for each part
    for (y in 0 until yCount) {
        // Create the sliced bitmap
        val part = Bitmap.createBitmap(this, 0, y * maxHeight, width, maxHeight)
        bitmaps.add(part)
    }

    // sisa bagian
    val remainder = height % maxHeight
    if (remainder > 0) {
        val part = Bitmap.createBitmap(this, 0, yCount * maxHeight, width, remainder)
        bitmaps.add(part)
    }

    return bitmaps
}
```

**Comment by Dharmik57** [comment]
Hello @tejasmusle Does your issue have been resolved?

**Comment by DantSu** [comment]
With latest version, use `EscPosPrinterCommands.bitmapToBytes(rescaledBitmap, false)`
