### ISSUE TITLE
how to generate pdf from thermal print layout

### ISSUE THREAD

**Issue by mushtaq99** [DantSu/ESCPOS-ThermalPrinter-Android#287]
hi  i am using this library from long time now i want to save the printer layout which print as a pdf fie

**Comment by DantSu** [comment]
Share your work if you do this. That will be a great feature !

**Comment by yoviep** [comment]
hi @mushtaq99 i am using Android canvas with static layout.
Previously I created a composer class, this class will be able to serve as a resource view to print and share (pdf)
