### ISSUE TITLE
How can we print a pdf file using this library from android

### ISSUE THREAD

**Issue by nikh-06** [DantSu/ESCPOS-ThermalPrinter-Android#289]
I wanted to print a pdf file using this library. How can I do this ?

**Comment by DantSu** [comment]
Not supported yet

**Comment by yoviep** [comment]
hi @nikh-06 alternative you can convert pdf to image, then print full image using this library

**Comment by nikh-06** [comment]
> 

Thanks @yoviep will try this.

**Comment by yoviep** [comment]
any update @nikh-06 ?

**Comment by DantSu** [comment]
@yoviep see here https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/292
