### ISSUE TITLE
Broken Pipe by with TCP connection

### ISSUE THREAD

**Issue by thinhlh** [DantSu/ESCPOS-ThermalPrinter-Android#290]
I usually face Broken Pipe exception when using TCP connection. How to resolve this case?

**Comment by rizwanbao** [comment]
@thinhlh have you got the solution for it ? i am facing same problem when application going to background and when back to application broken pipe error showing..

**Comment by rizwanbao** [comment]
@thinhlh can you please share your example code ?

**Comment by thinhlh** [comment]
I solved this as mentioned above by disconnecting before executing printing method then disconnect it. Here is the code and how I use it in kotlin. 

**Notice that this exception occurs when we are trying to connect more than once to the same printer without disconnect it.**

```    
override fun performPrinterAction(printerAction: () -> Unit) {
  try {
      disconnect()
      connect()
      printerAction.invoke()
  } catch (e: Exception) {
      Log.d(PrintConstants.TAG, e.toString())
  } finally {
      disconnect()
  }
```

example usage for open cash drawer:
```
fun openCashDrawer(): BillPrinterManager {
    printer?.performPrinterAction {
        printer?.openCashDrawer()
    }
    return this
}
```
