### ISSUE TITLE
Getting an unwanted black border while printing image

### ISSUE THREAD

**Issue by nikh-06** [DantSu/ESCPOS-ThermalPrinter-Android#292]
I am **converting a pdf to bitmap** then converting the **bitmap to ESC/POS command** using the library function of **bitmapToBytes** but I am getting an unwanted black border can you please tell what can be the issue here ?

https://drive.google.com/file/d/1Cu7ydYSyTt3V5QAHuXv3HHbhML88lUjU/view?usp=sharing

**Comment by DantSu** [comment]
if you save the bitmap file, do you have the black border ?

**Comment by nikh-06** [comment]
No I don't have the black border in the preview as well as while saving the file

**Comment by FilipeMarch** [comment]
@nikh-06 have you been able to print the pdf file without black border?

**Comment by RagulSAP** [comment]
@nikh-06, I've tried the same to convert the pdf to bitmap. but I'm getting very low quality image while printing via printer. It would be really helpful, if you have shared the code to do the same.

@DantSu @FilipeMarch @areeb111 @mcarland - Adding all just to check with you all for the same. Kindly share the code if you have. Thanks much.
