### ISSUE TITLE
Barcode positioning with additional information

### ISSUE THREAD

**Issue by Sva95** [DantSu/ESCPOS-ThermalPrinter-Android#295]
if any possibility to create something like that?

![165483671-3fbbb998-0297-45d4-90b1-4010bae1809d jpg (3024×4032) - Google Chrome 5_6_2022 4_01_37 PM (2)](https://user-images.githubusercontent.com/52375528/167148674-5799b847-f29f-4e02-abfb-667e2ef1a72c.png)

**Comment by DantSu** [comment]
No
