### ISSUE TITLE
Images not printing on USB connected NCR 7199

### ISSUE THREAD

**Issue by zob** [DantSu/ESCPOS-ThermalPrinter-Android#298]
Hi. Great work here ;)

Do you have any experience wih NCR printers?
I'm trying to make a NCR 7199 connected via USB to an Android tablet print with the help of your library.
While I can make text and, with a few modifications to the EscPos commands, QR codes print, I seem to have no luck with images.
On the screenshot you can see how your "demo-receipt" prints (for the purpose here I have commented out the qr, and the barcode). On top is what should be the image. To the left is without the useEscAsteriskCommand and to the right is useEscAsteriskCommand(true) - here is actually a little bit of the image.

![20220512_100542](https://user-images.githubusercontent.com/1483680/168027173-b21c8e20-d432-4439-b509-de45b4778c36.jpg)

**Comment by DantSu** [comment]
Can't help you, on my printer everything is ok, by USB and Bluetooth.
