### ISSUE TITLE
POS InnerPrint doesn't work

### ISSUE THREAD

**Issue by rportilla** [DantSu/ESCPOS-ThermalPrinter-Android#306]
Hi DantSu, first of all thank you for this wonderful free library. We currently have the library implemented in our Android APP, it works without problems, we have tested it on numerous printers and it works perfectly. However, it doesn't work on any innerprint.
![WhatsApp Image 2022-06-07 at 5 11 54 PM](https://user-images.githubusercontent.com/5324313/172486796-8aebf276-8704-4d93-a5d7-dc3a93c3215a.jpeg)

My code is:

<img width="1129" alt="Captura de Pantalla 2022-06-07 a la(s) 17 18 29" src="https://user-images.githubusercontent.com/5324313/172486966-2ce531e2-5289-4ca1-8683-915357c9bc1d.png">

Thanks for your help

**Comment by DantSu** [comment]
Your inner printer seems to not be compatible with standard ESC POS commands.
On some printer ESC POS commands have to be enabled with an external button or a parameter in the printer settings.

**Comment by rportilla** [comment]
> Your inner printer seems to not be compatible with standard ESC POS commands. On some printer ESC POS commands have to be enabled with an external button or a parameter in the printer settings.

Thank you for your prompt response, but I think the printer is compatible with ESC/POS because it works with other printing APPs without problems:

![WhatsApp Image 2022-06-08 at 10 29 12 AM (1)](https://user-images.githubusercontent.com/5324313/172642572-a7b63b50-3407-4c8f-8549-6cfd0c9541b8.jpeg)
![WhatsApp Image 2022-06-08 at 10 29 03 AM](https://user-images.githubusercontent.com/5324313/172642580-c2929e67-a376-4bbe-9f13-7c3420283954.jpeg)

I continue to appreciate your guidance and help.

**Comment by DantSu** [comment]
It's not compatible with all ESC POS commands.

https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/258#issuecomment-1047887538
This command cause trouble : EscPosPrinterCommands.TEXT_COLOR_BLACK...

**Comment by rportilla** [comment]
thank you very much, effectively commented the line **this.printerConnection.write(textColor);** the "r" is deleted.
Also the version of the library was not updated to 3.2.0
![WhatsApp Image 2022-06-10 at 4 28 45 PM](https://user-images.githubusercontent.com/5324313/173151572-fb1d02f9-05e5-4fed-b133-8e040599ea2a.jpeg)
