### ISSUE TITLE
Black line in the end of print

### ISSUE THREAD

**Issue by yousefkadah** [DantSu/ESCPOS-ThermalPrinter-Android#307]
I try to print a invoice with two lang arabic and Hebrew.
What I do is convert it to image and split that image by 200px in height.
Every thing work fine,
But I get a black line in the end

![20220608_101417.jpg](https://user-images.githubusercontent.com/5706681/172555775-7f47fa35-8b14-494c-8a0f-1a7f63c9fbfe.jpg)

**Comment by vikrammani-t2s** [comment]
dont cut the image you can print the full image
printer.useEscAsteriskCommand(true) if you enable this
