### ISSUE TITLE
Can't print text

### ISSUE THREAD

**Issue by MadDamar** [DantSu/ESCPOS-ThermalPrinter-Android#309]
Thank you for build this library.
I've tried this lib, but can't print text.
qrcode and barcode work well.

Could you suggest me, what's the problem?

**Comment by MadDamar** [comment]
After googling, maybe the problem is charset & I've tried some scripts
val printer = EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 78f, 60,EscPosCharsetEncoding("CP437",0))

or

for (i in 0..256) {
                val printer = EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 78f, 60)
                    .printCharsetEncodingCharacters(i)
                    .printFormattedText("[C]TESTTESTEST $i")
                    .disconnectPrinter()
                    Log.d("chars",i.toString())
            }

but still no text printed.

FYI: my printer has code page CP437

**Comment by DantSu** [comment]
escPosCharsetId change with printer model. [Follow this link to find escPosCharsetId that works with many printers](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32)
