### ISSUE TITLE
Print image erro on Citizen CMP-30BT

### ISSUE THREAD

**Issue by sonicfafe** [DantSu/ESCPOS-ThermalPrinter-Android#312]
hello, sometimes when printing image gives error in this printer (see image).
I'm using bitmapToHexadecimalString(EscPosPrinterSize printerSize, Bitmap bitmap)

```
val printer = EscPosPrinter(connection, 203, printerWidth, maxLineSize)
val headerImgBitmap = Global.base64ToBitmap(imageBase64)
val headerImgHex = PrinterTextParserImg.bitmapToHexadecimalString(printer, headerImgBitmap)
val printText = "[C]<img>$headerImgHex</img>\n"
printer.printFormattedText(printText, mmFeedPaper)
```

Any idea?
![WhatsApp Image 2022-06-28 at 13 38 54](https://user-images.githubusercontent.com/1252055/176692935-db2c214f-92a6-4a6c-8620-d929e12082c5.jpeg)

**Comment by DantSu** [comment]
if you use `.useEscAsteriskCommand(true)`, the problem still occur ?

**Comment by sonicfafe** [comment]
with `.useEscAsteriskCommand(true)`, it got much better, now it's rarer to happen, and when it happens it gives an error line, but then it continues printing normally. Only loses the initial part of the image.
![20220701_111328](https://user-images.githubusercontent.com/1252055/176875975-4e7e03ba-5474-478d-a45c-b3079958b87f.jpg)

**Comment by DantSu** [comment]
very strange !

**Comment by sonicfafe** [comment]
i think it just happens when i go to print some time after i have printed another. 
but at the end of the print I do `printer.disconnectPrinter()`
