### ISSUE TITLE
Can't print text

### ISSUE THREAD

**Issue by Mustafa744** [DantSu/ESCPOS-ThermalPrinter-Android#317]
I have sunmi v2s device with built in printer and i've tried to run the demo code from the repo and it printed the logo and the qr and the barcode successfuly but there's no text! 
![WhatsApp Image 2022-07-15 at 12 04 22 AM](https://user-images.githubusercontent.com/24313619/179086370-38555824-5340-4a38-8d01-6f534a0db513.jpeg)

I've tried changing the charset but still facing the same problem.
below are the charset supported by the printer (from the official docs)
![Capture](https://user-images.githubusercontent.com/24313619/179086746-a64db60b-5940-4874-a1ed-d9b83ad0a8f7.PNG)

**Comment by aydbtiko24** [comment]
I manage to handle sunmi device with set the Charset to **EscPosCharsetEncoding("GB18030", 1)**
