### ISSUE TITLE
how to add new bluetooth device?

### ISSUE THREAD

**Issue by etman55** [DantSu/ESCPOS-ThermalPrinter-Android#32]
I want to connect to new bluetooth device or make the pairing process inside my app how to do this manually even if i will do the bluetooth connection myself

**Comment by DantSu** [comment]
Look at file `BluetoothPrintersConnections.java` : 

`ESCPOS-ThermalPrinter-Android/escposprinter/src/main/java/com/dantsu/escposprinter/connection/bluetooth/BluetoothPrintersConnections.java`

```java
    /**
     * Easy way to get the first bluetooth printer paired / connected.
     *
     * @return a EscPosPrinterCommands instance
     */
    public static BluetoothConnection selectFirstPaired() {
        BluetoothPrintersConnections printers = new BluetoothPrintersConnections();
        BluetoothConnection[] bluetoothPrinters = printers.getList();

        if (bluetoothPrinters != null && bluetoothPrinters.length > 0) {
            for (BluetoothConnection printer : bluetoothPrinters) {
                try {
                    return printer.connect();
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
            }
        }
        return null;
    }
```

This will help you to get list of bluetooth printers saved on your phone : 

```java
BluetoothPrintersConnections printers = new BluetoothPrintersConnections();
BluetoothConnection[] bluetoothPrinters = printers.getList();
```

This allow you to know if printer is already connected.

```java
try {
    printer.connect();
} catch (EscPosConnectionException e) {
    e.printStackTrace();
}
```

**Comment by etman55** [comment]
Actually i can't find the method connect() in printer object

**Comment by DantSu** [comment]
```java
           for (BluetoothConnection printer : bluetoothPrinters) {
                try {
                    return printer.connect();
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
            }
```
It's in `BluetoothConnection`.

**Comment by ashutoshgithub** [comment]
BluetoothPrintersConnections.selectFirstPaired() is show null where as en-build bluetooth printer is used . how can resolve?

**Comment by ashutoshgithub** [comment]
> BluetoothPrintersConnections.selectFirstPaired() is show null where as en-build bluetooth printer is used . how can resolve?

Sir have you any solution ?

**Comment by leonelmatsinhe** [comment]
Any solution for this?

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/80

Read this issue...

**Comment by TekMem** [comment]
Thanks. I will return with the result.

**Comment by TruptiHKB** [comment]
That android device is already connected to printer but the list of printers using BluetoothPrintersConnections does not show any printer
