### ISSUE TITLE
Get Printer Status

### ISSUE THREAD

**Issue by hugofialho** [DantSu/ESCPOS-ThermalPrinter-Android#326]
@DantSu thank you for this greate project. I tested some printers and all work well.

In my application, i print severals receipts in sequence, and i noticed that, if i turn off the printer after the first receipt i didn't get any error.

I did some tests following this documentation (https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=118) and it's possible to get the current printer status.

Do you think this feature is in the scope of this project?

**Comment by DantSu** [comment]
No is not in the scope but you can do a PR ;)
