### ISSUE TITLE
Text align

### ISSUE THREAD

**Issue by zrachman** [DantSu/ESCPOS-ThermalPrinter-Android#33]
I've cloning this project, run and test without change any code. The output from my printer is different with your output. Here my output

![IMG_20200721_121058](https://user-images.githubusercontent.com/16265749/88057431-46171800-cb8c-11ea-8d4c-bc8248cd5340.jpg)

Hope you can give me me this solution

**Comment by DantSu** [comment]
You seems to have a different configuration of printer. 

https://github.com/DantSu/ESCPOS-ThermalPrinter-Android#user-content-class--comdantsuescposprinterescposprinter

    param DeviceConnection printer : Instance of a connected printer
    param int printerDpi : DPI of the connected printer
    param float printerWidthMM : Printing width in millimeters
    param int printerNbrCharactersPerLine : The maximum number of medium sized characters that can be printed on a line.
    param EscPosCharsetEncoding charsetEncoding (optional) : Set the charset encoding.

But it's centered and that's not normal. But I don't know why.
