### ISSUE TITLE
Image in PNG printing black

### ISSUE THREAD

**Issue by naveen22356** [DantSu/ESCPOS-ThermalPrinter-Android#332]
Hi, Firstly, great library! Thanks a ton.

I'm facing an issue when printing my logo. I've used your sample code and tried to change the text beneath it, but I am seeing a black box being printed instead of the logo.

I initially assumed it might be a printer issue, and so I tried to replace your logo from the sample code and that works fine. So it is not the printer.

**Comment by ydharia** [comment]
the same issue I faced before 
the solution is, don't  use a transparent image because transparent print is black so we need to replace transparent with a background of white

**Comment by naveen22356** [comment]
Thank you, that worked!

**Comment by hokimtam** [comment]
that's worked. Thank you.

**Comment by risalfajar** [comment]
Thanks, glad I found this issue. I think this need to be stated in the docs, it's very important.
