### ISSUE TITLE
want to change/remove AlertDialog box after print successful

### ISSUE THREAD

**Issue by ydharia** [DantSu/ESCPOS-ThermalPrinter-Android#333]
Hello
I am not android developer but in my project, my android developer used this library.
As per my android developer, he can't remove/change text and not even remove AlertDialog because he can't change code of the library

can someone help me to solve this issue?

client requirement is to show a custom message after print success and AlertDialog must go away after 2sec.

thanks in advance

**Comment by Rimondlu** [comment]
Should change a dev

**Comment by ydharia** [comment]
> Should change a dev

he done this task after sending this issue link :)

**Comment by DantSu** [comment]
So why you don't close this issue ?
