### ISSUE TITLE
Unable to change International Character Sets

### ISSUE THREAD

**Issue by Rimondlu** [DantSu/ESCPOS-ThermalPrinter-Android#335]
Hi people,

I m having an issue with some Epson printers (i assume asian models). I send "$" and it is printed as "¥", upon further research i found out that the printer have default International Character Sets set to China. 

I tried to set the International Character Sets to U.S.A by calling `connection.write(new byte[]{0x1B, 0x52, 0x00};` but it doesnt work because `printFormattedText()` calls `this.printer.reset()` which reset all settings I sent to the printer.

The table of International Character Sets
https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=3

Command to select an international character set (0x1B, 0x52)
https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=29

Thanks

**Comment by DantSu** [comment]
Create this class  : 

```java
public class MyEscPosPrinterCommands extends EscPosPrinterCommands {
    /**
     * Reset printers parameters.
     */
    public EscPosPrinterCommands reset() {
        return this;
    }
}
```

and do : 

```java
EscPosPrinter printer = new EscPosPrinter(new MyEscPosPrinterCommands(deviceConnection, charsetEncoding), 203, 48f, 32);
```

**Comment by DantSu** [comment]
And do what you want insede reset method.
