### ISSUE TITLE
Not works with HS 585 Thermal printer 

### ISSUE THREAD

**Issue by arsal072** [DantSu/ESCPOS-ThermalPrinter-Android#336]
I have a printer model HS- 585. This code works excellent with speedX printer but doesn't work with HS-585. Please fix this connectivity issue. As it says no printer connected while printer is paired with the device.

**Comment by arsal072** [comment]
Bluetooth

**Comment by DantSu** [comment]
It's open source project, do it yourself, I' m not your slave....

**Comment by arsal072** [comment]
sorry bro. I don't have much knowledge that's why I told you.
