### ISSUE TITLE
print style not working

### ISSUE THREAD

**Issue by frasjaf** [DantSu/ESCPOS-ThermalPrinter-Android#339]
hi 
its  working without problems 

but by some devices (15%) (same model and version) the style not working 
like break line, right and center

**Comment by DantSu** [comment]
Hi, 15% of ypur printers seems to not be in ESC/POS mode. Some printers have two or three standard commands modes and ESC POS mode have to be selected before print.

**Comment by frasjaf** [comment]
> Hi, 15% of ypur printers seems to not be in ESC/POS mode. Some printers have two or three standard commands modes and ESC POS mode have to be selected before print.

Thank you for your comment DantSu

May I know how to select this mode?

**Comment by DantSu** [comment]
yes in the manual of your printers

**Comment by frasjaf** [comment]
> yes in the manual of your printers

I'm sorry but I not anderstand what exactly to do. 
Or if there is a solution to do it on the sdk 

I'm using this printer 

https://a.aliexpress.com/_mOJqDmk

**Comment by DantSu** [comment]
Nothing say in the description of your printer if it is ESC/POS compatible.
It's your printer, not mine, so check in the manual if you have to enable ESC/POS command compatibility.

**Comment by DantSu** [comment]
It's seems to be a printer problem. Look at the manual.

**Comment by frasjaf** [comment]
not found anything :(

**Comment by frasjaf** [comment]
there is just print coding format now is (CP1257) and some font styles
