### ISSUE TITLE
Text position change

### ISSUE THREAD

**Issue by followthemoney1** [DantSu/ESCPOS-ThermalPrinter-Android#34]
Hey, as you can see from image, It always changes text position. What problem may it be? And also change dpi isn't change anything...
![image](https://user-images.githubusercontent.com/8526612/88083523-d6a12880-cb8b-11ea-917a-ddffc13f5aed.png)
 
Just simple code
```
val printer = EscPosPrinter(
        BluetoothPrintersConnections.selectFirstPaired(), 103, 70f, 46,
        EscPosCharsetEncoding("cp866", 17)
    )

    fun printS() {
        printer
            .printFormattedText(
                "[C]    <b>1</b>[R]24.99e\n" +
                        "[C]  <b>2</b>2\n" +
                        "[C]     <b>3</b>\n" +
                        "[C]         <b>4</b>[R]24.99e\n" +
                        "[C]        <b>5</b>\n" +
                        "[C]        <b>6</b>"
            )
    }
```

**Comment by DantSu** [comment]
I think it's 42 characters by line not 46.

Your printer seems to not have a good line heigth for this stickers. Are they compatible ?

**Comment by followthemoney1** [comment]
> I think it's 42 characters by line not 46.
Also tried, didn't work
> 
> Your printer seems to not have a good line heigth for this stickers. Are they compatible ?
Yep, he understands about sticker height and also may skip them 1 by 1, but seems the library doesn't understand how to skip them correctly when printed. So I sow code `printer.cutPaper()` inside **EscPosPrinter** but it's don't work also because methods `printFormattedText` and `printFormattedTextAndCut` works equals for me. Very strange(

**Comment by DantSu** [comment]
Ok I have may be a solution. I will send you tomorrow.

**Comment by followthemoney1** [comment]
@DantSu That would be very cool, I would be very grateful. I can shoot a video of how it works now if you run it, if it helps

**Comment by DantSu** [comment]
please use the last version v2.0.5.

`printFormattedText(String text, int dotsFeedPaper)`
`dotsFeedPaper` will allow you to feed paper with dot precision (depending of your printer dpi). Accepted value 0 to 255.

**Comment by followthemoney1** [comment]
@DantSu Thank you very much, I did not expect it to work at all !! How can I thank you?) You are using the "buy me coffee" service?

**Comment by DantSu** [comment]
Do you have a picture of the final printing ?

You already star the repo, it's enought ;)

**Comment by followthemoney1** [comment]
@DantSu I would like to support the project in some other way. Yes here is the picture
![image](https://user-images.githubusercontent.com/8526612/88166721-6395c180-cc20-11ea-9d36-ec782692777c.png)

**Comment by DantSu** [comment]
Ho yeah ! Great ! That solve the problem.
To support the project : Test the library, report bugs, create PR.
I just wan't to do the most universal Android library for ESC/POS printer. For now, it's not perfect but each issue and PR help me to be closest. ;)

**Comment by followthemoney1** [comment]
@DantSu Ok, then I'll send you end version with screenshot and code, maybe it's helping someone )))

**Comment by DantSu** [comment]
Yes, that will be perfect :)

**Comment by followthemoney1** [comment]
Here is my case
code:
```
  val printer = EscPosPrinter(
//        BluetoothPrintersConnections.selectFirstPaired(), 36, 24f, 44
        //EscPosCharsetEncoding("cp866", 17)
        BluetoothPrintersConnections.selectFirstPaired(), 603, 70f, 46,
        EscPosCharsetEncoding("cp866", 17)
    )

    fun printS(sticker: Sticker) {
        val day = sticker.day
        val saleData = sticker.saleDate
        val docNumber = sticker.documentNumber
        val conNameFirst = sticker.contractorName.chunked(sticker.contractorName.length/2)[0]
        val conNameSecond = sticker.contractorName.chunked(sticker.contractorName.length/2)[1]
        val direction = sticker.direction
        val warehouseNum = sticker.warehouseNum
        printer
            .printFormattedText(
                "[C]<font size='medium'>   | $day |$saleData |</font>" +
                        "<font size='wide'>$docNumber</font>\n" +
                        "[L]|\n" +
                        "[C]<font size='medium'>| $conNameFirst |</font>\n" +
                        "[C]<font size='medium'><u>| $conNameSecond |</u></font>\n" +
                        "[L]|\n" +
                        "[C]<font size='medium'><u>| $direction |</u></font>\n" +
                        "[C]<font size='medium'><u>| $warehouseNum |</u></font>",
                122
            )
    }
```
And here is how it printing
https://streamable.com/zo3sdj

**Comment by DantSu** [comment]
Nice ! thx for sharing
