### ISSUE TITLE
Sunmi T2 mini is cutting after every image

### ISSUE THREAD

**Issue by ericsilvapaucar** [DantSu/ESCPOS-ThermalPrinter-Android#340]
I use ```<img>``` tag, but every time image is printed, the paper is cut and continue printing the next text.
![WhatsApp Image 2022-09-19 at 17 44 13](https://user-images.githubusercontent.com/15257762/191132314-7449ccd5-6b87-422d-9249-e5c5b6204658.jpg)

**Comment by aydbtiko24** [comment]
It happened with Sunmi T2 pro device to
![WhatsApp Image 2022-09-14 at 10 31 51](https://user-images.githubusercontent.com/15952195/191635236-39536a46-a58b-4e8f-b36b-b4b0e10e334a.jpeg)
on the left side is just cut di paper after image if i use printFormattedText(cmd), 
but it will cut twice if i use printFormattedTextAndCut(cmd) command.

**Comment by ozitrance** [comment]
Anybody ever figured a solution to this problem? It is still happening even without using any cut functions
