### ISSUE TITLE
Please help me to more understand checking printing done

### ISSUE THREAD

**Issue by huutuan06** [DantSu/ESCPOS-ThermalPrinter-Android#343]
I download and read this project and was so surprised with checking the printing done in code. There is no information to check printing is done. But I don't know why this code line below works correctly. Why does that line run on time when the print was finished?

`return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_SUCCESS);`

Anybody can explain to me? Thank you.

**Comment by DantSu** [comment]
Because the only way is to do a Thread.sleep that estimate time that the printer take to print data sended. So `return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_SUCCESS);` is called when Thread.sleep is finished.
