### ISSUE TITLE
QRCODE not align center..

### ISSUE THREAD

**Issue by samrtian** [DantSu/ESCPOS-ThermalPrinter-Android#350]
PRINTER   FEC-TP-100:
   203DPI 
   PagerWidth（82.5mm）   
new AsyncEscPosPrinter(203, 82.5f, 42);
QRCODE not align center...
[L]<qrcode></qrcode>    // ok
[C]<qrcode></qrcode>  //not ok
![2](https://user-images.githubusercontent.com/5282751/197181090-deb09d67-8dd6-4ba3-aaa8-adcdeac97a13.jpg)

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/94#issuecomment-1296813434
