### ISSUE TITLE
Other language

### ISSUE THREAD

**Issue by Nilkesh310307** [DantSu/ESCPOS-ThermalPrinter-Android#351]
Do not print other language in this code.

**Comment by Rimondlu** [comment]
Which language u trying to print

**Comment by Nilkesh310307** [comment]
Gujarati

**Comment by Rimondlu** [comment]
Should work as long as Ur printer supports it

**Comment by Nilkesh310307** [comment]
it doesn't work in gujarati language

**Comment by DantSu** [comment]
it's seems to be printer problem not library.
