### ISSUE TITLE
When printing [L]text1[R]text2. Can text2 be printed starting from the right even if text2 is too long?

### ISSUE THREAD

**Issue by huutuan06** [DantSu/ESCPOS-ThermalPrinter-Android#352]
Hi, I got an issue when I print with small paper. 

This is my printed content:
"[L]Address:[R]this is my address12345\n" +
"[L]this is my address12345"

The text _this is my address12345_ is too long and it misses some characters.
![1667363838632](https://user-images.githubusercontent.com/47626041/199399337-016c55cd-48fb-4647-9da6-03a71de2bc5a.JPEG)
 
Do I have any way to make the first text _this is my address12345_ move to the left on the paper above?

**Comment by DantSu** [comment]
hi, how many letters can be printed in one line ?

**Comment by huutuan06** [comment]
Sorry, I should give more data for my issue.

I set it as 34 characters in one line. Here is the clear code:

AsyncEscPosPrinter printer = new AsyncEscPosPrinter(printerConnection, 203, 50f, 34);
        return printer.addTextToPrint(
           "[L]0123456789012345678901234567890123456789\n" +
           "[L]Address:[R]this is my address12345\n" +
           "[L]Address:[R]My address\n" +
           "[L]Address1:[R]My address1\n" +
           "[L]Address2:[R]My address2\n" +
           "[L]this is my address12345"
        );
![1667378857491](https://user-images.githubusercontent.com/47626041/199442366-0bec3ee7-7e24-4def-809c-c70cba981648.JPEG)

**Comment by DantSu** [comment]
`[L][C][R]` tags create column. 
In this example, two tags in a line will create two 17 chars column _(34 / 2)_. If the text is longer, that will print after the column.
Your problem can only be solved by you with .length() and .substring and create new lines if the text exceeded the second column. Like : 

```
"[L]Address:[R]this is my\n" +
"[L][R]address12345\n" +
```
