### ISSUE TITLE
Problem Printing BitMap

### ISSUE THREAD

**Issue by dlalas** [DantSu/ESCPOS-ThermalPrinter-Android#354]
Hello! I am using the latest version of the library 3.2.1 and I am trying to print a receipt with bitmap format. I am using 3 thermal printers as my testing and one of them sometimes it prints the bitmap with strange characters unencoded. I tried using your latest function 
useEscAsteriskCommand(true) and i limited my problem but sometimes it prints only the first element of the bitmap with strange characters. Is there something else i can use to solve 100% my problem?
This is my code:
 fun printBluetoothReceipt(companyData: String, selectedBranch: String, invoiceData: String, printOp: String, secondPrint: Boolean, promise: Promise){
        var secondPrintTimes = 1;
        var sleepTime = 4500L;
        if(secondPrint == true){
            secondPrintTimes = 2;
        }

        val receiptBitmap = createPrimerReceipt(companyData, selectedBranch, invoiceData);
        val targetWidth = 383 // 48mm printing zone with 203dpi => 383px
        var printer: BluetoothConnection?;
        if(printOp != "0" && printOp != null){
            val bluetoothDevicesList: Array<out BluetoothConnection>? = BluetoothConnections().getList();
            if (bluetoothDevicesList != null) {
                val selectedDevice = bluetoothDevicesList[printOp.toInt() -1];
                printer = selectedDevice;
            } else{
                 printer = BluetoothPrintersConnections.selectFirstPaired();
            }
        } else{
             printer = BluetoothPrintersConnections.selectFirstPaired();
        }
        val printerCommands: EscPosPrinterCommands = EscPosPrinterCommands(printer);
        repeat(secondPrintTimes) {
            try {
                val rescaledBitmap: Bitmap = Bitmap.createScaledBitmap(
                    receiptBitmap,
                    targetWidth,
                    Math.round(( receiptBitmap.getHeight()).toFloat() * (targetWidth).toFloat() / (receiptBitmap.getWidth().toFloat())),
                    true
                )
                printerCommands.connect();
                printerCommands.reset();
                printerCommands.useEscAsteriskCommand(true);
                printerCommands.feedPaper(20);
                printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
                printerCommands.feedPaper(50);
                printerCommands.cutPaper();
                if(secondPrint == true) {
                    Thread.sleep(sleepTime);
                    sleepTime = 0;
                }
                printerCommands.disconnect();
            } catch (e: Exception) {
                promise.resolve(e.message);
            }
        }
        promise.resolve("Επιτυχής Εκτύπωση!");
    }

**Comment by DantSu** [comment]
don't use bluetooth for this one. That lose data and print weird characters.

**Comment by dlalas** [comment]
So you are saying it is on the printer side the problem? My code is correct?
The printer is a NETUM NT-1809

**Comment by DantSu** [comment]
If it works correctly with two printers and the third does error. Yes I think that come from printer. Maybe increase the waiting time will solve your problem. Test it.

**Comment by dlalas** [comment]
Ok i found the solution. It is only priting weird characters for the first element of the bitmap so i added an empty line at the beginning and it prints everything as it should.
