### ISSUE TITLE
TSP-100IIIU Printer not Printing not sure why

### ISSUE THREAD

**Issue by jo-wijaya** [DantSu/ESCPOS-ThermalPrinter-Android#359]
Has anyone tried printing using Star TSP100III (USB) with this library.

I managed to get the printer information but the printer does not do anything.
<img width="668" alt="Screenshot 2022-11-26 at 14 14 49" src="https://user-images.githubusercontent.com/107824717/204077040-81a04fcd-dca2-4baa-a199-9ea9d8473d45.png">

The codes run until the line System.out.println("masuk try")
And yet it does not print anything except returning me this line.
<img width="1164" alt="Screenshot 2022-11-26 at 14 18 03" src="https://user-images.githubusercontent.com/107824717/204077136-3197eee1-3bbe-45f7-a8d8-494db0a9374b.png">

 ```
private final BroadcastReceiver usbReceiver = new BroadcastReceiver() {
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
            if (MainActivity.ACTION_USB_PERMISSION.equals(action)) {
                synchronized (this) {
                    UsbManager usbManager = (UsbManager) getSystemService(Context.USB_SERVICE);
                    System.out.println(usbManager);
                    UsbDevice usbDevice = intent.getParcelableExtra(UsbManager.EXTRA_DEVICE);
                    System.out.println(usbDevice);
                    if (intent.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED, false)) {
                        System.out.println("if pertama");
                        if (usbManager != null && usbDevice != null) {
                            System.out.println("if kedua");
                            EscPosPrinter printer = null;
                            try {
                                System.out.println("masuk try");
                                printer = new EscPosPrinter(new UsbConnection(usbManager, usbDevice), 203, 48f, 32, new EscPosCharsetEncoding("windows-1252", 0));
                                System.out.println("char set");
                                printer
                                        .printFormattedText(
                                                // "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, getResources().getDrawableForDensity(R.drawable.icona, DisplayMetrics.DENSITY_MEDIUM))+"</img>\n" +
                                                        "[L]\n" +
                                                        "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                                                        "[L]\n" +
                                                        "[C]================================\n" +
                                                        "[L]\n" +
                                                        "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                                                        "[L]  + Size : S\n" +
                                                        "[L]\n" +
                                                        "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                                                        "[L]  + Size : 57/58\n" +
                                                        "[L]\n" +
                                                        "[C]--------------------------------\n" +
                                                        "[R]TOTAL PRICE :[R]34.98e\n" +
                                                        "[R]TAX :[R]4.23e\n" +
                                                        "[L]\n" +
                                                        "[C]================================\n" +
                                                        "[L]\n" +
                                                        "[L]<font size='tall'>Customer :</font>\n" +
                                                        "[L]Raymond DUPONT\n" +
                                                        "[L]5 rue des girafes\n" +
                                                        "[L]31547 PERPETES\n" +
                                                        "[L]Tel : +33801201456\n" +
                                                        "[L]\n" +
                                                        "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                                                        "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                                        );
                                        System.out.println("kelar print");
                            } catch (EscPosConnectionException | EscPosParserException | EscPosEncodingException | EscPosBarcodeException e) {
                                System.out.println("masukCtach");
                                e.printStackTrace();
                            }
                        }
                    }
                }
            }
        }
    };

```
I/System.out(20266): UsbEndpoint[mAddress=129,mAttributes=2,mMaxPacketSize=64,mInterval=0]
I/System.out(20266): UsbEndpoint[mAddress=2,mAttributes=2,mMaxPacketSize=64,mInterval=0]]]]
I/System.out(20266): if pertama
I/System.out(20266): if kedua
I/System.out(20266): masuk try
I/System.out(20266): char set
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
D/UsbRequestJNI(20266): init
D/UsbRequestJNI(20266): close
I/System.out(20266): kelar print

Any help will be appreciated.

**Comment by didbarbosa** [comment]
Hi @jo-wijaya, did you find a solution ? I have the same issue with TSP-100III Bluetooth.
Thanks 👍

**Comment by jakubkarlicek** [comment]
Hey guys, tsp100 is not esc/pos printer, that's why it doesn't work for you.

It's also raster only printer, so it prints only images and commands it uses are not subset of esc/pos.
