### ISSUE TITLE
Not able to open cash drawer without printing data

### ISSUE THREAD

**Issue by hpcreator** [DantSu/ESCPOS-ThermalPrinter-Android#361]
First of all Thank you for the wonderful library for printing files using POS. This really helps a lot for developers like me.

I am wondering about one workaround for opening a cash box. Is there any way in your library to open a cash box directly without printing data? I had gone through files and came to know that using EscPosPrinterCommand class we can access the openCashbox() method but it is not working as expected.

Please suggest me how can I achieve this.

**Comment by DantSu** [comment]
If you don't your code, I don't know what you are doing wrong.

**Comment by hpcreator** [comment]
I had tried for Bluetooth devices as below: 
`btnOpenCashBox.setSafeClickListener {
                val print = EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired())
                print.openCashBox()
            }`

I had also try other option which is opening cashbox but for that I have to print some data which I don't want to: 
`binding.btnSend.setSafeClickListener {
            var printer: EscPosPrinter? = null
            printer = EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, getPaperWidthInFloat(), 64)
            printer?.printFormattedTextAndOpenCashBox("", 2)
        }`

**Comment by DantSu** [comment]
You forgot `printer.connect()` first.

**Comment by DantSu** [comment]
```kotlin
btnOpenCashBox.setSafeClickListener {
    val print = EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired()) 
    print.connect().openCashBox()
}
```

**Comment by hpcreator** [comment]
Thank you for your response.

**Comment by itsieber** [comment]
I getting always one empty paperline out on cashopen.

Printing over: [thermal-printer-cordova-plugin](https://github.com/paystory-de/thermal-printer-cordova-plugin)
`
                var data=String.fromCharCode(0x1B, 0x70, 0x00, 0x3C, 0xFF)

              ThermalPrinter.printFormattedText({
                      type: 'usb',
                      id: printer.deviceId,
                      text: data
                  }, function() {
                      console.log('Successfully printed!');
                  }, function(error) {
                      console.error('Printing error', error);
                  });
`
