### ISSUE TITLE
I getting always one empty paperline out on cashopen.

### ISSUE THREAD

**Issue by itsieber** [DantSu/ESCPOS-ThermalPrinter-Android#362]
I getting always one empty paperline out on cashopen.

Printing over: [thermal-printer-cordova-plugin](https://github.com/paystory-de/thermal-printer-cordova-plugin)
`
                var data=String.fromCharCode(0x1B, 0x70, 0x00, 0x3C, 0xFF)

              ThermalPrinter.printFormattedText({
                      type: 'usb',
                      id: printer.deviceId,
                      text: data
                  }, function() {
                      console.log('Successfully printed!');
                  }, function(error) {
                      console.error('Printing error', error);
                  });
`

_Originally posted by @itsieber in https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/361#issuecomment-1337190040_

**Comment by DantSu** [comment]
You are in the wrong place we don't do Javascript here....
