### ISSUE TITLE
QR Code output error

### ISSUE THREAD

**Issue by endlesssong86** [DantSu/ESCPOS-ThermalPrinter-Android#363]
If printWidthMM is set to 80f when creating AsyncEscPosPrinter, the qr code is not output.

**Comment by DantSu** [comment]
Printing width mm is not paper width mm

**Comment by endlesssong86** [comment]
I know but text or image output is fine
only qr output did

**Comment by DantSu** [comment]
QR Code are image printed.

**Comment by DantSu** [comment]
try to use `useEscAsteriskCommand(true)`. Look at documentation.
