### ISSUE TITLE
how to possible print Unicode , UTF-8 for Bangla text ? 

### ISSUE THREAD

**Issue by rahman-cmd** [DantSu/ESCPOS-ThermalPrinter-Android#364]
Hello Dear,
I am trying to print Bangla text, (i  use code page code ) , But not print Bangla text. Help me for print Bangla/Hindi text print.

**Comment by DantSu** [comment]
I don't think printer thermal with UTF-8 charset exists. If you have one find your charsetId that correspond to your charset encoding. Charset id depending to your printer.
