### ISSUE TITLE
Remove strikethrough from the receipt. 

### ISSUE THREAD

**Issue by Azeem00786** [DantSu/ESCPOS-ThermalPrinter-Android#365]
Hi @DantSu
is there any way to remove the strikethrough (a white line on the text) ?
I am trying to solve it from more than 15 days but there no results.I have more than 50 white label apps and all the clients are suffering with this issue.
please suggest if there are any possible way to solve it.
The HTML code is under file printer.txt for print receipt.

![receipt](https://user-images.githubusercontent.com/91094418/207580847-892f8799-b830-49a4-93b6-19c45d4213b2.jpeg)
![printer_details](https://user-images.githubusercontent.com/91094418/207581355-baacb85f-bfc9-4e89-846c-34add9a79349.jpeg)
[printer.txt](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/files/10227357/printer.txt)

**Comment by DantSu** [comment]
Have you try useEscAsteriskCommand  ?

**Comment by Okuro3499** [comment]
![20230404_115708.jpg](https://user-images.githubusercontent.com/64019708/229742164-8c7db0c9-a6fc-4f41-b9d6-974a8628d995.jpg)

I am also experiencing this when I print what is the possible fix for this?

This is my device
![20230404_120153.jpg](https://user-images.githubusercontent.com/64019708/229742682-684ae3f0-ffe5-4460-ae0f-917c93f3ade5.jpg)

**Comment by Okuro3499** [comment]
Kindly at what point do I use this I have added to my "public AsyncEscPosPrinter getAsyncEscPosPrinter" method but I get error Cannot resolve method 'useEscAsteriskCommand' in 'EscPosPrinter'

**Comment by DantSu** [comment]
Which version of the library do you use ?

**Comment by DantSu** [comment]
now we are at version 3.2.1

**Comment by Okuro3499** [comment]
I have upgraded to the latest as advised and enabled printer.useEscAsteriskCommand(true) and it printed this with the data I intend to print at the middle                  
![20230405_120010-min.jpg](https://user-images.githubusercontent.com/64019708/230170239-0218d574-d479-46d6-ad15-9988f1cfefcc.jpg)

**Comment by DantSu** [comment]
Ok, your printer is not compatible with ESC * command 😞
