### ISSUE TITLE
Barcode width size

### ISSUE THREAD

**Issue by erwinkaaa** [DantSu/ESCPOS-ThermalPrinter-Android#366]
Hi, I'm trying to print pretty long text (example 001.230101.01.01.0001) with barcode 128. 

The barcode is printed well but the size pretty small, how to make it bigger? can we? (maybe as long as receipt's width).

Thank you!

**Comment by DantSu** [comment]
I don't understand your issue. Have you read the doc ?

**Comment by erwinkaaa** [comment]
Yes I have, it said ~40mm for barcode 128, I need the width of barcode bigger so the barcode line can be read easily by scanner.

**Comment by DantSu** [comment]
Look at the documentation .... ATTRIBUTES WIDTH AND HEIGHT

Barcode

<barcode></barcode> tag allows you to print a barcode. Inside the tag you need to write the code number to print.

    <barcode>451278452159</barcode> : (12 numbers)
    Prints a EAN13 barcode (height: 10mm, width: ~70% printer width, text: displayed below).
    <barcode type='ean8'>4512784</barcode> : (7 numbers)
    Prints a EAN8 barcode (height: 10mm, width: ~70% printer width, text: displayed below).
    <barcode type='upca' height='20'>4512784521</barcode> : (11 numbers)
    Prints a UPC-A barcode (height: 20mm, width: ~70% printer width, text: displayed below).
    <barcode type='upce' height='25' width='50' text='none'>512789</barcode> : (6 numbers)
    Prints a UPC-E barcode (height: 25mm, width: ~50mm, text: hidden).
    <barcode type='128' width='40' text='above'>DantSu</barcode> : (string)
    Prints a barcode 128 (height: 10mm, width: ~40mm, text: displayed above).

**Comment by erwinkaaa** [comment]
Yes i have read these, when i change the width above 40 it doesn't make any change. Can it be set to 70% or 80% printer width for barcode 128?

**Comment by DantSu** [comment]
Ok, so that was your issue. Change width does'nt change the size of your barcode.
If you do a barcode width less data like `<barcode type='128' width='50' height='30'>HELLO</barcode>`. does the barcode printed bigger ?

**Comment by DantSu** [comment]
It's seems to be the barcose contain to many data for the paper width and if the printer increase to 2 dots per column the barcode will be bigger than the paper, so the printer keep 1 dot per column and your barcode look very small. I think it's a limitation due to the printer dpi and paper size.

**Comment by erwinkaaa** [comment]
![16710974766573871225603994860917](https://user-images.githubusercontent.com/45002009/207826680-d7631118-f241-4b0a-94d4-0b7e987f1be9.jpg)

This is the example from the documentation, i'm using 58mm paper, the most wide is barcode using upce and barcode using no type, you can see 2 barcodes at the bottom its barcode type 128 using width 40 and 50, the most small barcode.

By reading your explanation, i can't use pretty long data on barcode 128 to my 58mm printer?

**Comment by DantSu** [comment]
The only way the printer have to increase the width of barcode is to increase the number of dots by column. But if the barcode contain to many data, 1 dot by column is more than the half of the paper width, so 2 dots by column, barcode is upper than the paper width.

**Comment by DantSu** [comment]
Use QR code instead.

**Comment by erwinkaaa** [comment]
I see, I'm understand now. Thank you for your time and explanation DantSu!
