### ISSUE TITLE
Installation release 3.2.1

### ISSUE THREAD

**Issue by j99ht** [DantSu/ESCPOS-ThermalPrinter-Android#368]
I'm trying to install the latest release in my code, 

This is what I have included
```
targetSdkVersion 31

dependencies {
    implementation 'com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.2.1'
  }
```

I do not see any error but the application gets stuck.

However if I use the same configuration but 
`    implementation 'com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.2.1'
`
the application works correctly.

I want to use the latest release because I'm having issues printing images with bixolon spp-r210 and I want to test new method `useEscAsteriskCommand()` to see if the issues are fixed.

Is there any additional configuration I have to add?

**Comment by DantSu** [comment]
You dont forget step one ? maven { url 'https://jitpack.io' }

**Comment by j99ht** [comment]
I also did it, but no change.
