### ISSUE TITLE
font size 

### ISSUE THREAD

**Issue by Sihui128** [DantSu/ESCPOS-ThermalPrinter-Android#369]
is it possible to have a font size between normal and big? like 1.5 times bigger than normal?
this normal font seems really small and the big looks too big.

**Comment by Sihui128** [comment]
seems switch to font B can be a solution. but it doesn't mention how to switch in the manual

**Comment by DantSu** [comment]
Not implemented yet

**Comment by Sihui128** [comment]
thanks for the reply!  it will be great if this feature can be implemented. Also there is another important feature, to set percentage of the vertical columns space

**Comment by Sihui128** [comment]
or some way to use raw ESC/POS command

**Comment by YanYangTan** [comment]
so implemented already?
