### ISSUE TITLE
Inbuilt printer FB3550

### ISSUE THREAD

**Issue by flash94** [DantSu/ESCPOS-ThermalPrinter-Android#37]
I have a mobile smart POS device, which has an inbuilt printer, how do i use this library with it, because its not connecting using bluetooth

**Comment by DantSu** [comment]
You have choice to Bluetooth, USB, and TCP.

**Comment by linndeveloper** [comment]
I can't find and connect external RONGTA printer how to solve it?

**Comment by DantSu** [comment]
@linndeveloper create your own issue.

**Comment by DantSu** [comment]
@linndeveloper And give us more details / informations of your problem.
