### ISSUE TITLE
JP-Q2 text alignment

### ISSUE THREAD

**Issue by RoinujNosde** [DantSu/ESCPOS-ThermalPrinter-Android#376]
Text align commands don't seem to work with my Q2.

Any idea why? As the printer is in the tested list, I thought some basic functions would work.

Barcode ✅
QRCode ✅

**Comment by RoinujNosde** [comment]
Only [PrinterTextParserBarcode](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/b6b9330cc76814f3054f3556caaf32ea0bc5ea63/escposprinter/src/main/java/com/dantsu/escposprinter/textparser/PrinterTextParserBarcode.java#L34) is sending alignment constants...

@DantSu shouldn't other elements also set the alignment?

**Comment by DantSu** [comment]
printerNbrCharactersPerLine seems to be wrong.


Constructor : EscPosPrinter(DeviceConnection printer, int printerDpi, float printingWidthMM, int nbrCharactersPerLine [, EscPosCharsetEncoding charsetEncoding])

param DeviceConnection printer : Instance of a connected printer

param int printerDpi : DPI of the connected printer

param float printerWidthMM : Printing width in millimeters

param int printerNbrCharactersPerLine : The maximum number of medium sized characters that can be printed on a line.

param EscPosCharsetEncoding charsetEncoding (optional) : Set the charset encoding.

**Comment by RoinujNosde** [comment]
> printerNbrCharactersPerLine seems to be wrong.

It's not. Double checked it, I'm using 32 chars.

**Comment by RoinujNosde** [comment]
Manually sending the ESC/POS alignment commands work.

**Comment by DantSu** [comment]
share picture of a print

**Comment by RoinujNosde** [comment]
![20230125_095218483](https://user-images.githubusercontent.com/6441328/214568324-c7dd2014-acff-4a5b-b2c2-2751719872cd.jpg)
```kotlin
val printer = EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32);
printer.printFormattedText("\n--------------------------------\n[R]Right\n[C]Center\n[L]Left")
```

**Comment by DantSu** [comment]
from left to right .....

**Comment by DantSu** [comment]
Sorry, I misread the code

May be your printer is not compatible with an ESC POS command and return to a new line instead. In this librairy, alignment are do with space.

**Comment by RoinujNosde** [comment]
What commands are usually sent in a text like "[C]Test"?

**Comment by iuryol** [comment]
same problem with SUNMI V1 T2 NT-1880

**Comment by DantSu** [comment]
Yes, read the documentation of your printer, if the printer is not compatible with ESC/POS commands.... Your printer will not work with this library... This is called `ESCPOS-ThermalPrinter-Android` because this library use the ESC/POS commands, Epson Standard Commands !
