### ISSUE TITLE
Is there a way to use the library without having to tell it the printer dimensions?

### ISSUE THREAD

**Issue by robmr88** [DantSu/ESCPOS-ThermalPrinter-Android#38]
Hi, I'm writing an app that should be able to connect to different types of printer, for example 58mm bluetooth printers or 80mm tcp printers. Is there a way to send the print command without having to specify printer dpi, width or characters per line? simply because the user could connect to a printer and not know all this details.
Thank you

**Comment by DantSu** [comment]
No. I using it for text and picture alignment. Can't works without.
