### ISSUE TITLE
Print over Bluetooth using Android 13

### ISSUE THREAD

**Issue by rravasi** [DantSu/ESCPOS-ThermalPrinter-Android#383]
I tried to print a simple ESC-POS text via Bluetooth, the library creates the connection correctly, but on Android 13 when the library executes the `this.outputStream.write(this.data);`  nothing happens or printed, while the same code on Android 11 works perfectly.

Here the piece of code of `DeviceConnection.java`
```
public void send(int addWaitingTime) throws EscPosConnectionException {
        if(!this.isConnected()) {
            throw new EscPosConnectionException("Unable to send data to device.");
        }
        try {
            Log.i("ESC-POS", "Invio i seguenti dati " + Arrays.toString(data));
            this.outputStream.write(this.data);
            this.outputStream.flush();
            int waitingTime = addWaitingTime + this.data.length / 16;
            this.data = new byte[0];
            if(waitingTime > 0) {
                Thread.sleep(waitingTime);
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            throw new EscPosConnectionException(e.getMessage());
        }
    }

```
To reproduce the error I tried using the sample app and it too has the same problem with Android 13.

I'm using a Pixel 6A.

NOTE: With the USB-OTG cable the app prints correctly both on Android 13 and Android 11.

**Comment by KiranShny** [comment]
Facing same issue in Android 13 Devices

**Comment by KiranShny** [comment]
@rravasi is this fixed?

**Comment by rravasi** [comment]
> @rravasi is this fixed?
Unfortunatelly it's not fixed, now I'm trying to find a solution.
I have tried with an app develop with Flutter and it works great on Android 13. I don't know what are the differences between Android 11 and 13, I checked out permissions but I have already declared the necessary ones.

**Comment by z-sanjay** [comment]
@rravasi @KiranShny did you tried unpairing the bluetooth printer and then again pair and try to print. This worked in my case, let me know if it works for you as well.

**Comment by rravasi** [comment]
> @rravasi @KiranShny did you try unpairing the bluetooth printer and then again pairing and try to print. This worked in my case, let me know if it works for you as well.

Hi @z-sanjay , thanks for your suggestion. Unfortunatelly I tried to unpair and pair the bluetooth printer but the issue was not resolved. Did you try on a smartphone with Android 13? If yes, on which model?

Thanks in advance.

**Comment by KiranShny** [comment]
@z-sanjay 

Tried that as well, didn't work.
Will try to fix this and raise a PR for it.

**Comment by rravasi** [comment]
Hi all,

I have fixed this issue with the Bluetooth and created a Pull Request. 
This was reported also on Google IssueTracker [Bug UUIDS Android 13](https://issuetracker.google.com/issues/247449026).
