### ISSUE TITLE
Font size is different on different printers

### ISSUE THREAD

**Issue by huutuan06** [DantSu/ESCPOS-ThermalPrinter-Android#384]
Hello, I got an issue with using some different printers. The text size is different on different printers. It's so not good if my clients use different printers. How to fix it? Please help. Below are my code and printer images, both papers on printers is 56 mm:
![image](https://user-images.githubusercontent.com/47626041/215934729-8072c052-ac7f-494e-82fe-dfc65febd14e.png)
![1675220032003](https://user-images.githubusercontent.com/47626041/215934751-a2f8df08-63a0-47c7-a869-7d310dfb26d2.JPEG)

**Comment by DantSu** [comment]
There is no solution, sorry.

**Comment by huutuan06** [comment]
Hi, I set font text as font A, and it works well on the 3 types of printers that I have. Look like it's standard font.
Below is my code for someone who needs:

class CustomEscPosPrinterCommands(
    private val printerConnection: DeviceConnection,
    encoding: EscPosCharsetEncoding
) : EscPosPrinterCommands(printerConnection, encoding) {

    override fun reset(): EscPosPrinterCommands {
        super.reset()
        printerConnection.write(TEXT_FONT_A)
        return this
    }
}

.....

printer = EscPosPrinter(
                    CustomEscPosPrinterCommands(bluetoothConnection, EscPosCharsetEncoding("windows-1252", 0)),
                    printDpi,
                    pagerWidth,
                    characterPerLine
)
