### ISSUE TITLE
Image printed is not centered/cutting is not at right position

### ISSUE THREAD

**Issue by amkrys** [DantSu/ESCPOS-ThermalPrinter-Android#385]
Please help me to fix alignment of printed ticket.

The ticket is not cutting properly

**Comment by amkrys** [comment]
[](url)
![WhatsApp Image 2023-02-07 at 3 45 10 AM](https://user-images.githubusercontent.com/70586998/217313648-ea898471-ce87-40c5-967b-e22d3d61e00a.jpeg)
![WhatsApp Image 2023-02-07 at 4 33 31 AM](https://user-images.githubusercontent.com/70586998/217313658-c4ddf159-3ad6-4c08-b166-70e80d5cc5c2.jpeg)
Check the images for reference
1.Part of previous ticket is printed in the top of present ticket
2.Eliminate white space

**Comment by amkrys** [comment]
here is the code am using

`int targetWidth = 600;
            Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                    bitmapToPrint,
                    targetWidth,
                    Math.round(((float) bitmapToPrint.getHeight()) * ((float) targetWidth) / ((float) bitmapToPrint.getWidth())),
                    true
            );

            EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
            try {
                printerCommands.connect();
                printerCommands.reset();
                printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
                printerCommands.feedPaper(255);
                printerCommands.cutPaper();
                printerCommands.disconnect();
            } catch (EscPosConnectionException e) {
                new AlertDialog.Builder(this)
                        .setTitle("Something went wrong")
                        .setMessage(e.getMessage())
                        .show();
            }`

**Comment by FilipeMarch** [comment]
I am having the same issue as @amkrys

**Comment by FilipeMarch** [comment]
@amkrys I have been able to solve the issue!

To fix your code, after you do:
```java
printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
```

You need to create a new line:
```java
printerCommands.newLine()
```

After this, what I do is to print an empty string with  `EscPosPrinter.printFormattedText("")`

Then it works! 

![image](https://user-images.githubusercontent.com/23220309/217393122-9664c335-5485-4a2c-89b0-8e9fd4491791.png)

**Comment by FilipeMarch** [comment]
Every time  I print an image, it is aligned to the left. I don't know how to align it to center, do you know how to do it?

**Comment by amkrys** [comment]
Thanks @FilipeMarch
I'll try this today
also what about that spacing see 1st image

how did you eliminated that?

**Comment by shehanGuruge** [comment]
@FilipeMarch the image doesn't get exactly centered. It takes some extra space (padding sort of) from the left. Any workarounds to eliminate that issue?
