### ISSUE TITLE
Font size is always the same for big-2, big-3, big-4, etc

### ISSUE THREAD

**Issue by FilipeMarch** [DantSu/ESCPOS-ThermalPrinter-Android#386]
I realized on [this code](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/c77ee6c70aa3ce1dd81b537d004951e65d264323/escposprinter/src/main/java/com/dantsu/escposprinter/textparser/PrinterTextParser.java#L45#L50) that we could use other font sizes besides `big`, `tall`, `wide` and `normal`.

But this code:
```python
printer.printFormattedText(
    "\n".join(
        [
            "[c]<font size='big'>7</font>",
            "[c]<font size='big-2'>7</font>",
            "[c]<font size='big-3'>7</font>",
            "[c]<font size='big-4'>7</font>",
            "[c]<font size='big-5'>7</font>",
            "[c]<font size='big-6'>7</font>",
            "[c]7",
        ]
    )
)
```

Produces this result:
![image](https://user-images.githubusercontent.com/23220309/217404541-ee9333b4-a658-4931-9862-7f578e9c28bf.png)

I wonder why big-2, big-3, big-4, etc, does not work... Thanks!

**Comment by DantSu** [comment]
Not compatible printer

**Comment by FilipeMarch** [comment]
> Not compatible printer

Ok, thanks!
