### ISSUE TITLE
Can I use this with serial printers?

### ISSUE THREAD

**Issue by robmr88** [DantSu/ESCPOS-ThermalPrinter-Android#39]
Hi, can I use this library to print on a thermal printer connected via serial port? 
I am developing an app that runs on a android device that has a thermal printer integrated and internally
the android device is connected to the printer with serial port. 
Is there some way I can send print commands to that printer using this library?
Thank you.

**Comment by DantSu** [comment]
Serial port is not an USB port ? I always thinking that 's the same thing.

**Comment by robmr88** [comment]
I think they are not the same, also because I ran some tests and tried to print using your library by targeting the printer with UsbPrintersConnections.selectFirstConnected but nothing happens. 
Currently I am able to print on this device by using these two classes : https://github.com/cepr/android-serialport-api/tree/master/android-serialport-api/project/src/android_serialport_api
but I was really hoping I could use your library because it has all those handy tags that make the printing so much nicer .

**Comment by robmr88** [comment]
Hi, I've solved it.
So I keep using the two classes just to reach the printer, then I created a SerialConnection class that extends DeviceConnection and I give it the stream to print on given to me by the device that the SerialPortApi classes give me.
I then pass the SerialConnection object to your EscPoPrinter class and it works perfectly.
Thank you

**Comment by riyasvmc** [comment]
I found it, Thankyou

**Comment by Heller66** [comment]
robmr88 is it possible to have the complete code of your solution? ... I am in the same problem as you but I do not get out ... Thanks

**Comment by robmr88** [comment]
Sure, just a sec

**Comment by robmr88** [comment]
> robmr88 is it possible to have the complete code of your solution? ... I am in the same problem as you but I do not get out ... Thanks

Ok, so you will be needing a couple of extra classes to make this work.
Also I solved it some time ago and I might not remember everything but here's the guidelines.

You will be needing the Google Android serial port api , I don't remember how I found them at that time but doing a search now I found them here:
https://github.com/cepr/android-serialport-api/tree/master/android-serialport-api/project/src/android_serialport_api

You would have to place them directly under the java folder, the same level as the root of your package.
After that you should create a class SerialConnection class, i made this class following the TcpConnection class and BluetoothPrinter class that comes with this library and making the adjustments to work with serial printer.
Here's the class:

public class SerialConnection extends DeviceConnection {

    private SerialPort mSerialPort;

    @Override
    public DeviceConnection connect() throws EscPosConnectionException {
        if (this.isConnected()) {
            return this;
        }
        try {
            mSerialPort = DeliveryApp.getPrintSerialPort();
            this.stream = mSerialPort.getOutputStream();
            this.data = new byte[0];
        } catch (IOException e) {
            e.printStackTrace();
            this.stream = null;
            throw new EscPosConnectionException("Unable to connect to Serial device.");
        }
        return this;
    }

    @Override
    public DeviceConnection disconnect() {
        this.data = new byte[0];
        if (this.isConnected()) {
            try {
                this.stream.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            this.stream = null;
        }
        return this;    }
}

The getPrintSerialPort method is like this:

    public static SerialPort getPrintSerialPort() throws SecurityException, IOException, InvalidParameterException {
        if (mSerialPort == null) {
            /* Open the serial port */
            mSerialPort = new SerialPort(new File("/dev/ttyS1"), 115200, 0, true);
        }
        return mSerialPort;
    }

**Comment by robmr88** [comment]
and then use it as you were using TcpConnection or BluetoothConnection:

              SerialConnection serialConnection = new SerialConnection();

                EscPosPrinter printer = new EscPosPrinter(serialConnection, 203, printerWidthMM, charPerLine);

                printer.printFormattedTextAndCut(txtvalue);

**Comment by Heller66** [comment]
robmr88 Thanks for the help ... but do I need to create a DeviceConnection class as well?

**Comment by robmr88** [comment]
No, that class is a part of this library

**Comment by Heller66** [comment]
robmr88 is this the library?
libserial_port.so

**Comment by robmr88** [comment]
you don't need the .so, just the two java classes.
The serialport.java and serialportfinder.java

**Comment by Heller66** [comment]
I had already done that but extends DeviceConnection remains red with error

**Comment by robmr88** [comment]
<img width="706" alt="Screenshot at Aug 19 16-54-27" src="https://user-images.githubusercontent.com/60899275/130091185-580c7d55-d9f8-4237-aafd-e25591cb7397.png">

**Comment by Heller66** [comment]
ahhh ok ...Thanks

**Comment by DantSu** [comment]
Nice ! I will implement it in the library in september.

**Comment by Heller66** [comment]
robmr88 ... I added the import and actually the errors are resolved, but now if I run the app I find myself with this 
<img width="960" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/89199636/130227649-a07415db-c741-4761-a2cc-ff3955f568b9.png">

**Comment by robmr88** [comment]
<img width="316" alt="Screenshot at Aug 20 13-42-44" src="https://user-images.githubusercontent.com/60899275/130228151-e5468324-a9bb-47a2-ab60-59b344bb9516.png">

plave the SerialPort and SerialPortFinder class in a package name like this under the java folder

**Comment by Heller66** [comment]
robmr88 ho inserito le classi nella loro directory ed in effetti gli errori sono risolti , pero la stampante non da segni di vita ed il log di Android e' questo
![Screenshot (3)](https://user-images.githubusercontent.com/89199636/130482192-9944064e-a34a-4b5f-837c-cc117d8dbeb8.png)

**Comment by robmr88** [comment]
check the serial ports name, those "ttyS1" "tmpfs" could be different for your printer. you could also try to run a scan of all the ports and see the names your printer has, there should be some apps that to that

**Comment by robmr88** [comment]
also don't forget 
    <uses-permission android:name="android.hardware.usb.host" />

**Comment by thinhlh** [comment]
> you don't need the .so, just the two java classes. The serialport.java and serialportfinder.java

Indeed, when I execute with the suggestion of yours, It says that we need a libserial_port.so to run the file. How could we resolve this? 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dantsu.thermalprinter, PID: 20019
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dantsu.thermalprinter-2/base.apk"],nativeLibraryDirectories=[/data/app/com.dantsu.thermalprinter-2/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libserial_port.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.dantsu.thermalprinter.async.SerialPort.<clinit>(SerialPort.java:86)
        at com.dantsu.thermalprinter.async.SerialConnection.connect(SerialConnection.java:23)
        at com.dantsu.escposprinter.EscPosPrinterCommands.connect(EscPosPrinterCommands.java:241)
        at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:54)
        at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:27)
        at com.dantsu.thermalprinter.MainActivity.printSerial(MainActivity.java:222)
        at com.dantsu.thermalprinter.MainActivity$3.onClick(MainActivity.java:78)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22445)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by maelcomx** [comment]
Hi, I am developing an application that manages ticket printing on an Android device with a built-in printer (Thermal Printer). But I coded with flutter and it turns out that I can't connect with the printer to start printing. The package you offer (`https://pub.dev/packages/android_bluetooth_printer`) is not documented enough so I'm having trouble getting it to work. I want help please

**Comment by maelcomx** [comment]
Hi, I am developing an application that manages ticket printing on an Android device with a built-in printer (Thermal Printer). But I coded with flutter and it turns out that I can't connect with the printer to start printing. The package you offer (`https://pub.dev/packages/android_bluetooth_printer`) is not documented enough so I'm having trouble getting it to work. I want help please

**Comment by DantSu** [comment]
Is not my package. Someone do a fork of this library.

**Comment by maelcomx** [comment]
> Is not my package. Someone do a fork of this library.

All right, thank you. I contacted the manufacturer who provided me with the SDK and it works fine.

**Comment by Ahmed-Elswerky** [comment]
> "libserial_port.so"

hi, have you found a solution yet?

**Comment by thinhlh** [comment]
> > "libserial_port.so"
> 
> hi, have you found a solution yet?

I switched to LAN printer instead
