### ISSUE TITLE
How print in Horizontal position?

### ISSUE THREAD

**Issue by lucaspellozo** [DantSu/ESCPOS-ThermalPrinter-Android#395]
I am trying set page mode and page mode direction (to horizontal), but after this setting, the printer dont work anymore!!!

        public final byte[] ENABLE_PAGE_MODE = new byte[]{0x1B, 0x4C};
        public final byte[] PAGE_MODE_DIRECTION = new byte[]{0x1B, 0x54, 0x03};

printerConnection.write(ENABLE_PAGE_MODE);
printerConnection.write(PAGE_MODE_DIRECTION);

**Comment by abdur-rohman** [comment]
i got this one also

**Comment by abdur-rohman** [comment]
Hello @lucaspellozo, i've solution for this one (if u are using bitmap). Instead of change the page mode direction, better rotate the bitmap rotation.

```
private fun Bitmap.rotate(degrees: Float): Bitmap {
    val matrix = Matrix().apply { postRotate(degrees) }
    return Bitmap.createBitmap(this, 0, 0, width, height, matrix, true)
}
```
