### ISSUE TITLE
For Android 13  devices  getting connection exception 

### ISSUE THREAD

**Issue by nikunjflobiz** [DantSu/ESCPOS-ThermalPrinter-Android#396]
Hi @DantSu getting the error message ` Unable to connect to bluetooth device.`  in some of the android 13 devices. mo stly in Oppo devices

**Comment by evervasquez** [comment]
Hello,
the same thing is happening to me, after printing 4 times it disconnects.

**Comment by tanishq14developer** [comment]
Same Issue facing

**Comment by muesmat** [comment]
Same issue here  did anyone find a solution?

**Comment by jaco** [comment]
I have 5 devices with android 13 and no problems whatsoever so… maybe the problem is somewhere else?

**Comment by muesmat** [comment]
> I have 5 devices with android 13 and no problems whatsoever so… maybe the problem is somewhere else?

Yes, it works fine on most of them, but it not working on some specially Oppo devices

**Comment by DantSu** [comment]
create your own BluetoothConnection class with this code and say me if it's solve your issue : 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/19176f3b74df6b36e39079b01e4c7960c1973709/escposprinter/src/main/java/com/dantsu/escposprinter/connection/bluetooth/BluetoothConnection.java

**Comment by muesmat** [comment]
@DantSu Thank you for your reply. I will try and come back to you.

**Comment by muesmat** [comment]
@DantSu It works perfectly fine, Thanks to you :)

**Comment by DantSu** [comment]
v3.3.0 is out. Try with this version !
