### ISSUE TITLE
How To Trigger Open Cash Drawer ?

### ISSUE THREAD

**Issue by ryandan29** [DantSu/ESCPOS-ThermalPrinter-Android#397]
How To Trigger Kick Out Cash Drawer using Thermal printer connect with RJ11 cable to cashdrawer when After Printed??
using Bluetooth Connection..

`ThermalPrinter.printFormattedText({
        type: 'bluetooth',
        id: 'first',
        mmFeedPaper:25,
        text: struk
}, function () {
});`

Thank you, i love this plugin..

**Comment by DantSu** [comment]
You mean this ?

Method : printFormattedTextAndOpenCashBox(String text, float mmFeedPaper)
Print a formatted text, feed paper (mmFeedPaper millimeters), cut the paper and open the cash box. Read the ["Formatted Text : Syntax guide" section](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android#formatted-text--syntax-guide) for more information about text formatting options.

param String text : Formatted text to be printed.
param float mmFeedPaper : Millimeter distance feed paper at the end.
return Printer : Fluent interface

**Comment by mmugnisalamm** [comment]
Sorry, how to open the cash drawer first before print formatted text?

**Comment by DantSu** [comment]
Like that : 

```java
EscPosPrinterCommands EscPosPrinterCommands = new EscPosPrinterCommands(deviceConnection, new EscPosCharsetEncoding("windows-1252", 16));
            EscPosPrinterCommands.openCashBox();
            EscPosPrinter printer = new EscPosPrinter(
                EscPosPrinterCommands,
                printerData.getPrinterDpi(),
                printerData.getPrinterWidthMM(),
                printerData.getPrinterNbrCharactersPerLine()
            );
```
