### ISSUE TITLE
Encoding UTF-8 Khmer text align not working

### ISSUE THREAD

**Issue by Chanthuon168** [DantSu/ESCPOS-ThermalPrinter-Android#398]
Please help i am using sunmi printer. Try to print endcoding UTF-8 exmple:
"[L]សួស្តីអ្នកទាំងអស់គ្នា[L]16[R]2023\n"

![IMG_20230316_102859~2](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/15335882/df73d5bd-2130-41ef-b980-94cdd8deabc8)

**Comment by taehun007** [comment]
How to use endcoding UTF-8 for khmer unicode brother? I can't set EscPosCharsetEncoding it's not working.

**Comment by Chanthuon168** [comment]
@taehun007 It's depend on your printer model dose it support UTF-8 or not. I am using model sunmi cloud printer that model support UTF-8.

**Comment by taehun007** [comment]
Ohh maybe my little printer not support UTF-8. It hard to find solution to print khmer letter for none support UTF-8 printer.

**Comment by taehun007** [comment]
@DantSu can you give me some solution brother? Thank!

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/286

ask him, how he does it ;)

**Comment by taehun007** [comment]
@DantSu ok thank brother. let me check.
