### ISSUE TITLE
Printer pauses briefly while printing

### ISSUE THREAD

**Issue by bo-rik** [DantSu/ESCPOS-ThermalPrinter-Android#399]
Hi,

We've integrated this library in our software and bumped into something very strange going on. While printing, the printer briefly pauses in the middle of printing the receipt (for about 1 - 2 seconds). The weird thing is, it does not depend on  the text being too long or formatting used. It seems to have something to do with the length of the text.

For example, the text below prints in one go (two `\n` after the QR code):

`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`[C]<qrcode size='37'>https://google.be</qrcode>`
` `
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet Curabitur tempus accu`
`Lorem ipsum dolor sit amet Curabitur tempus accu`
`Lorem ipsum dolor sit amet Curabitur tempus accu`
`Lorem ipsum dolor sit amet Curabitur tempus accu`
`Lorem ipsum dolor sit amet Curabitur tempus acc`
`VA��`

But the following briefly stops (1 - 2 secs) after the QR code (two `\n` after the QR code):

`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet`
`[C]<qrcode size='37'>https://google.be</qrcode>`
` `
`Lorem ipsum dolor sit amet`
`Lorem ipsum dolor sit amet Curabitur tempus acc`
`Lorem ipsum dolor sit amet Curabitur tempus acc`
`Lorem ipsum dolor sit amet Curabitur tempus acc`
`Lorem ipsum dolor sit amet Curabitur tempus acc`
`Lorem ipsum dolor sit amet Curabitur tempus acc`
`VA��`

(VA�� is the command for cutting the paper: `\x1DVA\x00`)

As you can see, the only difference is that in the first example, the first four sentences after the QR code are one character longer.
- If only one or two sentences are extended with one character, printing still pauses. 
- When three sentences are extended with one character, the printer only briefly pauses (approx. 0.5 sec). 
- When four sentences are extended with one character (as in the first example), everything prints in one go.

We also have implemented this on iOS, and there we don't encounter any pauses while printing the same text. Also, (much) longer texts do not pose any pauses while printing. So it does not seem to have to do something with the total length. Rather with the specific length of shorter text. This leads us to believe it might have something to do with the parsing of the text and subsequent processing. 

We came across a `Thread.sleep(waitingTime);` in the `send()` method of `DeviceConnection`.
What is odd, is the fact that in `EscPosPrinterCommands`, the `feedPaper()` method calls said send method with the number of dots as parameter of the `send()` function, which triggers a sleep of that amount. But it's weird that the number of dots have anything to do with the waitingTime. 

Maybe it could be a combination of that along with the fact that feedPaper() is called when it should not (e.g. because a line has a specific (short) length?

Any tips that can help us understand this problem and help us fixing it?

Thanks!

**Comment by bo-rik** [comment]
Hi @DantSu 

We fixed the issue and opened a pull request for it: #402 

If you have some time to elaborate, please let us know!

**Comment by nikunjflobiz** [comment]
Hi @DantSu Could you please tell, what is the purpose of adding the sleep time in below code :
`public void send(int addWaitingTime) throws EscPosConnectionException {
        if (!this.isConnected()) {
            throw new EscPosConnectionException("Unable to send data to device.");
        } else {
            try {
                this.outputStream.write(this.data);
                this.outputStream.flush();
                int waitingTime = addWaitingTime + this.data.length / 16;
                this.data = new byte[0];
                if (waitingTime > 0) {
                    Thread.sleep((long)waitingTime);
                }

            } catch (InterruptedException | IOException var3) {
                var3.printStackTrace();
                throw new EscPosConnectionException(var3.getMessage());
            }
        }
    }`
what if i remove/decrease it

**Comment by DantSu** [comment]
If sleep is not here, the smartphone dont wait and send all data to the printer at the same time. This may produce corrupted output with bluetooth, data not delivered in correct order. This issues come from smartphones or printers that having low BT speed. Printers with low cache may cause the problem too. Try with your own config, that can works without sleep.
