### ISSUE TITLE
Random symbol appearing

### ISSUE THREAD

**Issue by mvaz4** [DantSu/ESCPOS-ThermalPrinter-Android#404]
My issue is rather simple (at least to describe). I'm printing a pdf converted to bitmap, as an image, using the following code

            int targetWidth = 464; // 48mm printing zone with 203dpi => 383px -     58mm -> 464px     68mm -> 563
            Bitmap originalBitmap = mPrintUtils.pdfToBitmap(file, false);
            Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                    originalBitmap,
                    targetWidth,
                    Math.round(((float) originalBitmap.getHeight()) * ((float) targetWidth) / ((float) originalBitmap.getWidth())),
                    true
            );

            EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap, false));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();

And I'm getting some random symbols getting printed on the top of the page, event though there is nothing there on my original image. I was testing setting different targetWidth because I realized that my bitmap is not stretching to the width limit (my paper is 58mm), so I have the following examples:

![edited (Medium)](https://user-images.githubusercontent.com/29099581/229825316-2c6a71ef-0f67-474a-abfb-dd02125189de.png)

As you can see, changing the width only stretches my image, but mainly, there are these characters (signaled in red) being printed.

Any help would be appreciated.

**Comment by aneebali** [comment]
i have same issue please provide any solution

**Comment by DantSu** [comment]
it's just that your printer is not compatible with all ESC/POS command, fork the repo and find which command is not understanding by your printer.
