### ISSUE TITLE
Receipt cutting issue

### ISSUE THREAD

**Issue by krishnachaudhary25** [DantSu/ESCPOS-ThermalPrinter-Android#41]
sometimes printing is not completed and did not cut the paper. Printer stucks the paper. can you help me with this?

**Comment by DantSu** [comment]
Try v2.0.4 and say me if it's wprks better

**Comment by krishnachaudhary25** [comment]
Thank you. also can I open cash drawer with the printing?

**Comment by DantSu** [comment]
No, the library doesn't containt function for that but you can send your own comand to the printer with : 
```java
            printerConnection.write(new byte[] {});
            printerConnection.send();
```

**Comment by DantSu** [comment]
You can try the new version 2.0.6, say me if your problem is solved in this version.

**Comment by krishnachaudhary25** [comment]
Thank you for your reply. I will try and let you know.
