### ISSUE TITLE
Android 13 troubles, can't print

### ISSUE THREAD

**Issue by kg-only** [DantSu/ESCPOS-ThermalPrinter-Android#410]
Hi i am having problem,  can't even connect to bluetooth printer, on 13 android, on 12 everything is ok

**Comment by KannarFr** [comment]
Due to https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/411 I guess.

**Comment by KannarFr** [comment]
As @DantSu muted discussions #411, I'll continue here...

> ... so it's not to this library to do permissions, you have to do by yourself....

Agree, so this library must expose the permissions it needs then users will use a library to request them `getRequiredPermissions()`, not README lines. Also, what are the required permissions required for Android 13? 

The main problem here is the library outputs nothing on permissions errors. The activity is just stuck. Can we improve this?

> Any contributions, large or small, major features, bug fixes, are welcomed and appreciated but will be thoroughly reviewed.

Lel.

**Comment by DantSu** [comment]
see here : https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/396#issuecomment-1530906048

I will release a new version in future, for now, create your own BluetoothConnexion class.

**Comment by DantSu** [comment]
v3.3.0 is realease. Try with this version.
