### ISSUE TITLE
How to print a document at Kassen DT-642 Thermal Printer from Android Apps?

### ISSUE THREAD

**Issue by michaelsof47** [DantSu/ESCPOS-ThermalPrinter-Android#413]
i have an issue about bluetooth configuration based on thermal printer hardware is Kassen DT-642  

Here this link barcode printer product : https://kassen.com.tw/products/barcode-printer/dt-642/  

I have try this a few times ago with this sample project. but, it doesn't work when i'm trying to print a document after pair and connect at Kassen DT-642.  

Do you know how to solve this issue? i have grateful if you have tell me about this solution. thank you in advance

**Comment by DantSu** [comment]
Hi, This printer seems to not be compatible with ESC commands.

**Comment by michaelsof47** [comment]
Oh, i see. So, do you have any solution about it and about reason why kassen DT-642 not support ESC command?

**Comment by DantSu** [comment]
This library is for ESC POS Printer. ESC is Epson Standard Commands. If the manufacturer of your printer use another stardard, this library is not compatible with this printer. Read the documentation of your printer, how to use it and which commands standard you have to use. You can fork this repo and change bytes commands in code. You have tp find how by yourself.

**Comment by michaelsof47** [comment]
oh i see. noted, sir. thank you for explain it.
