### ISSUE TITLE
W/System.err: java.io.IOException: Broken pipe 

### ISSUE THREAD

**Issue by natsirasrafi** [DantSu/ESCPOS-ThermalPrinter-Android#414]
![Screen Shot 2023-05-05 at 10 13 27 AM](https://user-images.githubusercontent.com/15030656/236370476-50350114-fe38-4a50-b4ea-2274ce8a4f58.png)
I made a script that runs 2 printers alternately with the detection id bluetoothDevicesList[index] that has been stored, at the start it prints normally, but after changing the selected printer several times, I get an error like this

**Comment by DantSu** [comment]
If your app donc print for a minute, call `disconnectPrinter()`.

**Comment by DantSu** [comment]
Bluetooth simultany don't works. Print on the first printer then when the first print is ended, disconnect and start print the second.

**Comment by natsirasrafi** [comment]
How to detect if broken pipe is happen?, i want to detect that exception so i can make disconnect script, i want to see the script to detect exception

**Comment by tucomel** [comment]
> How to detect if broken pipe is happen?, i want to detect that exception so i can make disconnect script, i want to see the script to detect exception

broken pipe exception was catch from internal lib code, there is no way to throw this exception for your code, same situation happened here, I got broken pipes
