### ISSUE TITLE
Printing breaks after paper out

### ISSUE THREAD

**Issue by goranlazareviccope** [DantSu/ESCPOS-ThermalPrinter-Android#415]
I'm using version 3.3.0 and printing receipts as images. Everything works fine (dozens of receipts printed properly) until I get paper out in the middle of print job. After that everything is broken until I shut down and power up printer again. This happens on different models of BT printers.

![image](https://user-images.githubusercontent.com/6009797/236445801-85637c30-25ae-4712-9b49-3ae553f1575b.png)
![image](https://user-images.githubusercontent.com/6009797/236445835-f470a30f-907e-4605-b28a-59f3c5ed5553.png)
![image](https://user-images.githubusercontent.com/6009797/236445867-812d71f2-c6a1-4669-90f5-dc4f6b3237ab.png)

**Comment by DantSu** [comment]
Normal behavior printer is stopped in middle of image command. You have to clear cache by turning off and on.
