### ISSUE TITLE
Clear Print Buffer/Queue/Cache

### ISSUE THREAD

**Issue by HassanBilal** [DantSu/ESCPOS-ThermalPrinter-Android#42]
Hi,
I am using this library to Print Customer Invoice from my Kotlin App. It prints properly but on second try (actually all subsequent tries), it prints the Invoice twice. I do close the connection after every print but Looks like somehow buffer does not clear after print and every time I send another print, it prints older invoices as well along with new. How can I clear Buffer/Queue/Cache for the Printer?

**Comment by DantSu** [comment]
Have you the same problem with v2.0.4 ?

**Comment by HassanBilal** [comment]
Hi DantSu,
Yes, I am using v2.0.4 and facing this problem.

**Comment by DantSu** [comment]
Someone say me that he use  : `context.unregisterReceiver(usbReceiver);` for resolving a similar problem.
May be that can help you.

**Comment by DantSu** [comment]
After read this : https://stackoverflow.com/questions/52704083/esc-pos-bluetooth-printer-clear-buffer

Can you try to : 

```java
TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 56f, 48, new EscPosCharsetEncoding("windows-1252", 16));

printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST\n");
printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST\n");
printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST\n");
```
Did it solve the problem ?
