### ISSUE TITLE
Star TSP650II not print well

### ISSUE THREAD

**Issue by Chanthuon168** [DantSu/ESCPOS-ThermalPrinter-Android#422]
I am using an other model with star printer but it dose not print well. Something like alignment and printtextandcut also not work. Anyone can help pls.

![photo_2023-05-24_09-50-46](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/15335882/c704cf2b-cdf8-49a8-b647-254dda972fc4)

**Comment by DantSu** [comment]
seems to not be compatible with Epson Standard Command. ESC
