### ISSUE TITLE
Bluetoothconnection not establishing 

### ISSUE THREAD

**Issue by sindhu-nir** [DantSu/ESCPOS-ThermalPrinter-Android#425]
BluetoothConnection connection = BluetoothPrintersConnections.selectFirstPaired();

The connection is always null, while my device is already paired with the printer

what is the issue?

**Comment by vikrammani-t2s** [comment]
shall I know your printer manufacturer 
 public BluetoothConnection[] getList() {
        BluetoothConnection[] bluetoothDevicesList = super.getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();
            if(TextUtils.equals(device.getName().toUpperCase(Locale.ROOT),"INNERPRINTER")){
                printersTmp[i++] = new BluetoothConnection(device);
            }else {
                int majDeviceCl = device.getBluetoothClass().getMajorDeviceClass(),
                        deviceCl = device.getBluetoothClass().getDeviceClass();

                if (majDeviceCl == BluetoothClass.Device.Major.IMAGING && (deviceCl == 1664 || deviceCl == BluetoothClass.Device.Major.IMAGING)) {
                    printersTmp[i++] = new BluetoothConnection(device);
                }
            }

        }
        BluetoothConnection[] bluetoothPrinters = new BluetoothConnection[i];
        System.arraycopy(printersTmp, 0, bluetoothPrinters, 0, i);
        return bluetoothPrinters;
    }
this function should be modified

**Comment by sindhu-nir** [comment]
Here is my code


                BluetoothConnection connection = BluetoothPrintersConnections.selectFirstPaired();
                if (connection != null) {
                    EscPosPrinter printer = new EscPosPrinter(connection, 203, 48f, 32);


                            String text= "<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo, DisplayMetrics.DENSITY_LOW))+"</img>\n";
                    printer.printFormattedText(text);

**Comment by vikrammani-t2s** [comment]
then made this change will check printing or not
EscPosPrinter printer = new EscPosPrinter(connection, 203, 48f, 32);
printer. useEscAsteriskCommand =true
