### ISSUE TITLE
Printer is not printing full content

### ISSUE THREAD

**Issue by Mehdi-android** [DantSu/ESCPOS-ThermalPrinter-Android#428]
Following is my code to print, but instead of printing full content it cuts from between

`fun getAsyncEscPosPrinter(printerConnection: DeviceConnection?): AsyncEscPosPrinter? {
        val format = SimpleDateFormat("yyyy-MM-dd 'at' HH:mm:ss")
        val printer = AsyncEscPosPrinter(printerConnection, 203, 48f, 32)

        return printer.addTextToPrint(
            "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(
                printer,
                this.getApplicationContext().getResources()
                    .getDrawableForDensity(R.mipmap.token, DisplayMetrics.DENSITY_MEDIUM)
            ) + "</img>\n" +
                    "[L]\n" +
                    "[C]<u type='double'>" + format.format(Date()) + "</u>\n" +
                    "[C]================================\n" +
                    "[L]<b>Section: </b>[R]${intent.getStringExtra("section")}\n" +
                    "[L]Thank You\n" +
                    "\n" +
                    "\n"
        )
    }`
    
    How to solve this issue

**Comment by SKarolcik** [comment]
I have a similar issue. Even when printing with the default string provided, it seems to issue the cut command before it finished printing. The second half of the QR code (from default print) stays after the cut.

My only fix so far was to add a few additional "[L]\n" at the end of the print. But it leads to wasted space at the beginning of the next print.

**Comment by raulti** [comment]
i solved this problem using this command  `this.printerConnection.write(new byte[]{0x1D, 0x56, 66, 0x00});`
the original cut command is  `this.printerConnection.write(new byte[]{0x1D, 0x56, 0x01});`
