### ISSUE TITLE
horizontal print

### ISSUE THREAD

**Issue by joao-moniz** [DantSu/ESCPOS-ThermalPrinter-Android#43]
Hello, I've been trying to make my printer, print a bank slip for a long time, but I can't use page mode, do you know any api or can you tell me how to do this ??

**Comment by DantSu** [comment]
different page mode are not supported yet by this library.
You can send custom command to your printer with this : 
```java
            printerConnection.write(new byte[] {});
            printerConnection.send();
```
May be you can use this library mixed with your own command. I can't help you more.
