### ISSUE TITLE
How you are getting in the demo App that user put special character

### ISSUE THREAD

**Issue by Jahnzeb** [DantSu/ESCPOS-ThermalPrinter-Android#430]
Hy @DantSu i am Android developer using your library. i see in the demo app on playstore that when i put special characters.. it shows the popup and enables these characters and it prints very perfect... 
i want to ask that how i can do this in my app so that it can enabled for almost all languages. Thank you

**Comment by Jahnzeb** [comment]
@DantSu i am waiting for your reply.. please guide me in this.. Thank you

**Comment by DantSu** [comment]
I don't know what you asking to me. Which app ? maybe that transform Text to image and print as image.

**Comment by Jahnzeb** [comment]
https://play.google.com/store/apps/details?id=mate.bluetoothprint&referrer=utm_source%3Dshare%26utm_medium%3Dsharebtn
i am talking about this app.. this one using this library.. This app getting special characters and showing the alerts according to the characters.. Means it is getting the special characters and identifying that which type of characters these are.. what is the trick? can you please tell me?

**Comment by DantSu** [comment]
They print custom font so it's image. The only way to have spécial chars working on most of ESC POS printers is to convert text to image and print it. Look in closed issue.

**Comment by Jahnzeb** [comment]
ok let me check
