### ISSUE TITLE
Tag [C] and [R] only work when the string printed 1 line. More than 1, they don't work.

### ISSUE THREAD

**Issue by timotiusfit** [DantSu/ESCPOS-ThermalPrinter-Android#432]
Hi,
Thanks for the library, my printer [Panda PRJ-R58D](https://www.tokopedia.com/pandaretail/printer-kasir-ppob-thermal-58mm-panda-prj-r58d-android-usb-bluetooth) works well with this.

But I have 1 small matter. I noticed if the strings turn out to be printed more than 1 line, the tag [C] and [R] didn't work. They will reverted to default [L]. Is this normal?

I thought maybe this is the behavior from my printer, but then I tried a receipt-printer app from Playstore, and my printer printed the alignment correctly even when the strings is more than 1 line.

This is my code:
```
const text =
 '[C]eeeeeeeeee\n\n' +
 '[C]eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\n\n' +
 '[R]eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\n\n';
 ```
 This is the output image:
 Notice that the first string printed correctly because it only need 1 line. But the second and third string are longer string and turn out need more than 1 line so it reverted to [L] even they are in tag [C] and [R].
 
 
![20230623_112811](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/49468142/530299e9-413a-459b-9c6b-5565202a9e05)

I'll appreciate any help. Thank you.

**Comment by DantSu** [comment]
Yes it's normal behavior
