### ISSUE TITLE
print barcode,The print length is greater than 14 digits and cannot be printed

### ISSUE THREAD

**Issue by xue12311** [DantSu/ESCPOS-ThermalPrinter-Android#437]
[C]<barcode type='128' height='10' width='40' text='below'>202307197957600255</barcode>

The print length is greater than 14 digits and cannot be printed,If the length is less than or equal to 14, the barcode can be printed normally。

![image](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/19585108/f93e926a-ab14-4be8-9f83-a323175032ff)

**Comment by andersoncmota** [comment]
I have the same problem

**Comment by beisir** [comment]
Is there a solution to this problem?

**Comment by beisir** [comment]
Please upgrade ESCPOS Thermal Printer Android: 3.4.0, type set to 128, which can solve this problem
