### ISSUE TITLE
How can we set Bluetooth Printer by MAC Address

### ISSUE THREAD

**Issue by shushantsaxenaaa** [DantSu/ESCPOS-ThermalPrinter-Android#438]
I am trying to print on two different Bluetooth Printers I have their MAC addresses stored. Is this possible?

**Comment by JovandySaputro** [comment]
me too :/

**Comment by shushantsaxenaaa** [comment]
Did you discover anything? or are you still trying?

**Comment by yorigum** [comment]
> Did you discover anything? or are you still trying?

 I haven't found another way yet. It's still stuck here.

**Comment by TomasBozek** [comment]
It's possible. I am printing on many different printers. Just print it one by one with different bt address.

**Comment by Rimondlu** [comment]
> > It's possible. I am printing on many different printers. Just print it one by one with different bt address.
> 
> I mean, if I have a bluetooth mac address, can it be connected using that mac address? how do you use the mac address, because in my case, I saved this mac address in shared preferences.

```
BluetoothConnection[] bluetoothConnections = (new BluetoothPrintersConnections()).getList();
for (BluetoothConnection device : bluetoothConnections) {
  if (device.getDevice().getAddress().equals(address)) {  // address is your device mac address
    EscPosPrinter printer = new EscPosPrinter(device, 203, 48f, 42);
    printer.printFormattedText("hi");
    break;
  }
}
```
