### ISSUE TITLE
Can not print text on CXN80B HS6632MVER2.2.1.1

### ISSUE THREAD

**Issue by quannv2506** [DantSu/ESCPOS-ThermalPrinter-Android#439]
This is my printer information:

![photo_2023-08-11_21-34-16](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/55235117/33b86c14-1be9-42d8-85ea-825aa8f3f691)
i'm trying to follow the example to print via bluetooth, but i can't print the text. When I print out only photos and QR

Here is the result:
![photo_2023-08-11_21-51-02](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/55235117/cbbffdf1-bfe1-4169-abe7-a31ba5c63eed)

Here is my code:

`val printer =
                EscPosPrinter(
                    BluetoothPrintersConnections.selectFirstPaired(),
                    203,
                    48f,
                    32,
                )
            printer
                .printFormattedText(
                    "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(
                        printer,
                        this.applicationContext.resources.getDrawableForDensity(
                            R.drawable.logo,
                            DisplayMetrics.DENSITY_MEDIUM
                        )
                    ) + "</img>\n" +
                            "[L]\n" +
                            "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                            "[L]\n" +
                            "[C]================================\n" +
                            "[L]\n" +
                            "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                            "[L]  + Size : S\n" +
                            "[L]\n" +
                            "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                            "[L]  + Size : 57/58\n" +
                            "[L]\n" +
                            "[C]--------------------------------\n" +
                            "[R]TOTAL PRICE :[R]34.98e\n" +
                            "[R]TAX :[R]4.23e\n" +
                            "[L]\n" +
                            "[C]================================\n" +
                            "[L]\n" +
                            "[L]<font size='tall'>Customer :</font>\n" +
                            "[L]Raymond DUPONT\n" +
                            "[L]5 rue des girafes\n" +
                            "[L]31547 PERPETES\n" +
                            "[L]Tel : +33801201456\n" +
                            "[L]\n" +
                            "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                            "[C]<qrcode size='20'>https://dantsu.com/</qrcode>"
                )
`
Can you tell me where I went wrong? Thanks everyone

**Comment by vikrammani-t2s** [comment]
what type of printer do you used i mean brand name?

**Comment by quannv2506** [comment]
> what type of printer do you used i mean brand name?

i think this is my printer brand
![photo_2023-08-14_20-14-30](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/55235117/611baecf-5ffe-4602-8b31-9cba6ad08b0e)
