### ISSUE TITLE
QR Code issues

### ISSUE THREAD

**Issue by felipef0x** [DantSu/ESCPOS-ThermalPrinter-Android#44]
I am very grateful for making the library available, it has been very useful.

But I'm facing some issues while printing QR Code.
I'm using version 2.0.5 of the library.
Here are the details:

### Successful prints using sizes 20 and 27:

```
[L]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>
[L]<qrcode size='27'>http://www.developpeur-web.dantsu.com/</qrcode>
```

### Unsuccessful prints using sizes greater than 27:

**Error 1:** 
`[L]<qrcode size='28'>http://www.developpeur-web.dantsu.com/</qrcode>`

Library throws exception:

> java.lang.ArrayIndexOutOfBoundsException: length=29; index=29
>     at com.dantsu.escposprinter.EscPosPrinterCommands.QRCodeDataToBytes(EscPosPrinterCommands.java:167)
>     at com.dantsu.escposprinter.textparser.PrinterTextParserQRCode.initConstructor(PrinterTextParserQRCode.java:32)
>     at com.dantsu.escposprinter.textparser.PrinterTextParserQRCode.<init>(PrinterTextParserQRCode.java:40)
>     at com.dantsu.escposprinter.textparser.PrinterTextParserColumn.appendQRCode(PrinterTextParserColumn.java:266)
>     at com.dantsu.escposprinter.textparser.PrinterTextParserColumn.<init>(PrinterTextParserColumn.java:77)
>     at com.dantsu.escposprinter.textparser.PrinterTextParserLine.<init>(PrinterTextParserLine.java:46)
>     at com.dantsu.escposprinter.textparser.PrinterTextParser.parse(PrinterTextParser.java:173)
>     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:95)
>     at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:77)
> 

Using the same size but with another content, the QR Code prints normally:
`[L]<qrcode size='28'>http://www.google.com/</qrcode>`

I think the problem is not only related to the size, but also to the content of QR Code.

**Error 2:** 
`[L]<qrcode size='35'>http://www.developpeur-web.dantsu.com/</qrcode>`

QR Code starts to be printed, but before completing, some characters are printed instead of the content and the printer continues to feed these characters repeatedly until I switch off manually. See the result:

![IMG_20200807_120127673](https://user-images.githubusercontent.com/33990666/89671341-2f293300-d8b9-11ea-9cb0-249b640fd545.jpg)

I made an even bigger QR Code print through another app that doesn’t use the library and it managed to print normally, see the image:

![IMG_20200807_120156827](https://user-images.githubusercontent.com/33990666/89671444-613a9500-d8b9-11ea-9910-8427becdbb9d.jpg)

So we can tell that the problem while printing large QR Codes is not related to the printer device.

**Comment by felipef0x** [comment]
I made a pull request to fix error 1, it worked as expected when I tested it. 
But error 2 is still occurring.

**Comment by felipef0x** [comment]
The pull request should fix error 1, I tested it with sizes from 10 to 30.
But error 2 still occurs with sizes greater than 30.

**Comment by DantSu** [comment]
Hi,
Your pull request remove essential condition.
For a largest compatibility with ESC printer, I create and print a picture of QR code, and don't use ESC/POS QR Code command because many printer doesn't reconize it.
It's important to be sure to have set the good params for your printer : DPI and printer mm width.

**Comment by DantSu** [comment]
I found and fix the error 1.
The error 2 is more complicated. The QR code generate an image bigger than 255 bytes (255 * 8 pixels). I will have to work on it.

**Comment by DantSu** [comment]
Please use v2.0.6 and give me a feedback.

**Comment by felipef0x** [comment]
Thank you, I appreciate your attention.
I will do some tests with the latest version and report the results.

**Comment by felipef0x** [comment]
Now with v2.0.6 the QR Code prints perfectly, regardless of the data size or print size :) 
Thanks!!

**Comment by DantSu** [comment]
Thx for your feedback :)

**Comment by VannakYet** [comment]
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 48f, 32);
            printer
                    .printFormattedText(
                                   "[L]\n" +      
                                    "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                    );

not aline center.
