### ISSUE TITLE
Image not printing

### ISSUE THREAD

**Issue by chaitusy09** [DantSu/ESCPOS-ThermalPrinter-Android#449]
"[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, imageToPrint,false) + "</img>\n"

         

This tag is not printing image. Printing some unwanted text. Can anyone suggest how to print image by using abve library.

 
![WhatsApp Image 2023-09-11 at 5 40 43 PM](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/5885833/33d0595f-a4f5-4cf6-b334-bd612e0dc9e7)

**Comment by laux98** [comment]
Hello, 

you have to put the tag <img> like this :

```
[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap, false) + "</img>\n
```
