### ISSUE TITLE
White stripes between bitmap when printing image

### ISSUE THREAD

**Issue by laux98** [DantSu/ESCPOS-ThermalPrinter-Android#451]
Hello,
I have to convert à pdf to bitmap to print it then. 

As the image exceeds 256px in height, I cut it as indicated in another issue into several bitmaps of 256px in height.

Here the code : 

```java
int deltaHeight = 256 ;
for (int y = 0 ; y < height ; y += deltaHeight) {
   Bitmap bitmap = Bitmap.createBitmap(decodeByte , 0 , y , width, (y+deltaHeight >= height) ? height - y : deltaHeight);
   textToPrint.append("<img>" + 
   PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap, false) + "</img>\n");
}
textToPrint.append("\n");
```

Finally, I need to be able to print these images by two types of printers.

Here the declaration of the printer I will use : 

```java
if (splittedConfig[0].equals("bluetooth"))
   printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 205, 72f, 32);
else if (splittedConfig[0].equals("ip"))
   //splittedConfig[1] is the Ip and splittedConfig[2] is the port
   printer = new EscPosPrinter(new TcpConnection(splittedConfig[1], Integer.parseInt(splittedConfig[2]) , 15), 203, 72f, 48);
```

For the bluetooth printer, it works perfectly, but for the ip printer, I get white bands when printing

![proof](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/134645261/b565e70a-5949-4798-bd19-54f55b005825)

I specify that the configurations on the printers are the correct ones.

Has anyone ever had this problem?

**Comment by laux98** [comment]
Close this because I find solution to print an image in one time and not have white stripe.

**Comment by DantSu** [comment]
thx for your feedback
