### ISSUE TITLE
Can't center qrcode

### ISSUE THREAD

**Issue by 0xberkay** [DantSu/ESCPOS-ThermalPrinter-Android#459]
Hello I'm trying to center qrcode but the result is not in the center.

**Code : **
`"[C]<qrcode size='40'>asd</qrcode>\n"`

![image](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/70816926/cf94e2b8-b4d5-4f00-a584-95bb1490ef0a)

**Comment by HuyLeUS** [comment]
how to print qrcode 😭😭

**Comment by RazaRehman-Dev** [comment]
@0xberkay Were you able to find any solution to this?

**Comment by 0xberkay** [comment]
No I couldn't find any solution
