### ISSUE TITLE
What font does this library use to print?

### ISSUE THREAD

**Issue by longWay11** [DantSu/ESCPOS-ThermalPrinter-Android#468]
I have web app to print receipt, i want my web app and mobile app have receipt with similar font. Can anyone help me, what kind of font this library use to print?
Thanks

**Comment by DantSu** [comment]
Hi, The library use font A by default.

**Comment by longWay11** [comment]
Hi Dantsu, do you mean default by device printer?

**Comment by DantSu** [comment]
Esc Pos printer have font inside the printer. You can select font A or font B (in most case there are same font but B is little less than A).

**Comment by DantSu** [comment]
if you want custom font, you have to print image.

**Comment by longWay11** [comment]
Ok, thanks for the information.
