### ISSUE TITLE
How to print large image

### ISSUE THREAD

**Issue by tusharmate** [DantSu/ESCPOS-ThermalPrinter-Android#47]
I am using USB thermal printing method. If I keep image below 256 for width and height, it prints successfully but it does not print anything if I keep any of these above 256. Can someone help?

**Comment by DantSu** [comment]
yes, you have to split image every 256 px. I will working on this and try to split it inside the library. but I can't working on it yet.

**Comment by DantSu** [comment]
Thermal printer has only black print.

**Comment by nikunjflobiz** [comment]
Just wanted to know why we have fixed it to 256px? can we increase this number?
Reason are :
- If I print the image height of  2048px, it prints with little lag.
Please suggest any solution for optimizing printing speed?
