### ISSUE TITLE
SUNMI Printer prints "  r" at the beginning of text

### ISSUE THREAD

**Issue by YESMAD123** [DantSu/ESCPOS-ThermalPrinter-Android#471]
Hi DantSu,

"  r" (r with two " " before it) will be printed at the beginning of text each time I printed something. It only happened at the SUNMI inner printer connected with Bluetooth.

I have tried all the ways in the thread #258 (Create MyEscPosPrinterCommands extends EscPosPrinterCommands, and comment the line 'this.printerConnection.write(textColor);' in EscPosPrinterCommands.java) but none of them worked. Could you help to fix the problem?

![WhatsApp Image 2023-11-22 at 16 35 40](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/151722589/12ae9ba9-8a68-437b-a973-52e1d0dc9de5)

**Comment by DantSu** [comment]
I think your printer is not compatible with many ESC POS command. Try to change size, make bold, black background, and many other option that a standard ESP POS printer do, and show me the result.

**Comment by YESMAD123** [comment]
The black background white text does not work (it does not matter), below are the examples:

![WhatsApp Image 2023-11-22 at 19 05 12](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/151722589/73d79274-2014-4d65-b2c5-f7abb564453e)

![WhatsApp Image 2023-11-22 at 19 05 28](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/151722589/172ce12f-9473-49cd-8cf5-3119240eeca1)

**Comment by DantSu** [comment]
ok so this is the black background initialization that write the r. You have to remove command from EscPosPrinterCommands class.

```
    public static final byte[] TEXT_COLOR_BLACK = new byte[]{0x1B, 0x72, 0x00};
    public static final byte[] TEXT_COLOR_RED = new byte[]{0x1B, 0x72, 0x01};

    public static final byte[] TEXT_COLOR_REVERSE_OFF = new byte[]{0x1D, 0x42, 0x00};
    public static final byte[] TEXT_COLOR_REVERSE_ON = new byte[]{0x1D, 0x42, 0x01};
```

## Two solutions : 

- Delete all line that contains this four constants

### OR

- Assign `new byte[0];` for this four constants.

```java
    public static final byte[] TEXT_COLOR_BLACK = new byte[0];
    public static final byte[] TEXT_COLOR_RED = new byte[0];

    public static final byte[] TEXT_COLOR_REVERSE_OFF = new byte[0];
    public static final byte[] TEXT_COLOR_REVERSE_ON = new byte[0];
```

**Comment by YESMAD123** [comment]
I tried the two solutions above but not working, so I deleted the lines of the four constants and after that I also deleted the

```
public static final byte[] TEXT_UNDERLINE_LARGE = new byte[]{0x1B, 0x2D, 0x02};

public static final byte[] TEXT_DOUBLE_STRIKE_OFF = new byte[]{0x1B, 0x47, 0x00};
public static final byte[] TEXT_DOUBLE_STRIKE_ON = new byte[]{0x1B, 0x47, 0x01};
```

but the "  r" is still printed.
Extra information: The SUNMI printer can support sticker printing.

**Comment by YESMAD123** [comment]
Hi DantSu, any other solution to the "  r" printing problem?

**Comment by DantSu** [comment]
Change your printer OR fork, remove some code and run the application. If you can't do that, don't use this library.

**Comment by YESMAD123** [comment]
Alright, thank you
