### ISSUE TITLE
How Do I print on 80MM printer. 

### ISSUE THREAD

**Issue by adesun2k** [DantSu/ESCPOS-ThermalPrinter-Android#473]
I use this: AsyncEscPosPrinter printer = new AsyncEscPosPrinter(printerConnection, 203, 48f, 32);
Please do I print on 80mm printer is there a way to use any default printer width and dpi instead of a specifics?

**Comment by DantSu** [comment]
read the doc

**Comment by adesun2k** [comment]
> read the doc

Please can you point to the part of the document, I have red through couldn't find it. Thanks

**Comment by fikrihkll** [comment]
@adesun2k You can use this config for 80mm printer

`new AsyncEscPosPrinter(printerConnection, 203, 70f, 46);`
