### ISSUE TITLE
Will this app print without dialog?

### ISSUE THREAD

**Issue by SIKU-KR** [DantSu/ESCPOS-ThermalPrinter-Android#476]
Hello.
I am trying to build new POS app for my church.
I wonder will this library show Android's print dialog?
I am so sorry to ask without testing myself.
yet I don't have any printer...
Thankyou

**Comment by albgen** [comment]
The library has nothing to do with the UI(User Interface). You have to build the interface. The job of the library is to convert the simple text syntax(Read the docs on the main page) in to ESC/POS commands and send to the printer. So keep in mind that the printer has to support ESC/POS commands.

You can also test by yourself by following the steps [Test It!](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android#test-it-)
There is a simple UI built around this library for testing purposes so you can check that code.

**Comment by SIKU-KR** [comment]
Thank you so much sir!
