### ISSUE TITLE
Watermark 

### ISSUE THREAD

**Issue by Surjeet-Singh-Rathore** [DantSu/ESCPOS-ThermalPrinter-Android#479]
Is it possible to give a watermark to the Bluetooth printer?

**Comment by DantSu** [comment]
I don't understand

**Comment by Surjeet-Singh-Rathore** [comment]
![watermark](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/113584117/4c1f970b-dd2a-4e1e-8d05-565fbe4e89a5)
As you can see some text in the background of the print, So can we print the same?

**Comment by DantSu** [comment]
if you print only images, yes. 

If you want to print watermark in front of formatted text, no.
