### ISSUE TITLE
Text Alignement issue on some POS with inner bleutooth printer

### ISSUE THREAD

**Issue by FimboIsso** [DantSu/ESCPOS-ThermalPrinter-Android#485]
escopos-thermalPrinter is printing but alignement command doesnt work.
I am using a Q8 POS model
![printer](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/28241223/6986f28a-6383-40a8-b79f-51d1f05f007b)

**Comment by DantSu** [comment]
This printer seems to not have full ESC support, can't help you.
