### ISSUE TITLE
Question about the Syntax format

### ISSUE THREAD

**Issue by jyling** [DantSu/ESCPOS-ThermalPrinter-Android#488]
Hi DantSu, thanks for the amazing library, I have been using your library indirectly by using the project that's using this library.

Regarding the commands syntax of `[L]`, `[C]`, `<qrcode>` etc.

Are these commands limited to this project ? or it's a standard command that this project uses that the printer understands.

Like browser understanding HTML format regardless of the vendor (Chrome, Firefox, Internet Explorer).

**Comment by DantSu** [comment]
I created this "language." The ESC/POS commands are in binary. For example, `new byte[]{0x1B, 0x2D, 0x01}` underlines the text. The majority of developers are not comfortable with binary, so I wrote this library to make thermal printer printing more familiar.

I assumed that HTML was the most popular way to format text. Therefore, I drew inspiration from HTML and invented this language to adapt well to receipt printing.
I developed the interpreter for this language, and you can read it in the source code. So, unless another project has taken up my code or idea, you won't find an identical language elsewhere.

**Comment by jyling** [comment]
Ah, I see, Thanks for your speedy response, I finally understands how it works now

**Comment by DantSu** [comment]
Can you share me the project from which you used this library ?

**Comment by jyling** [comment]
> Can you share me the project from which you used this library ?

Hi, I'm sorry that I missed your message, I'm using https://github.com/AllInOneYT/react-native-thermal-printer,
