### ISSUE TITLE
printerWidthMM not work, 

### ISSUE THREAD

**Issue by TrungPQ-konbini** [DantSu/ESCPOS-ThermalPrinter-Android#489]
![image](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/82367720/fa5c962b-cf10-405a-ba36-c35fdf738dff)
i'm using Xprinter K200, page width is 80 mm. But I can't print the entire width. I tried changing printerWidthMM = 80f but it still doesn't work.

**Comment by TrungPQ-konbini** [comment]
This is my print format
    [C]<font size='tall'><b>RECEIPT #240118000021</b></font>
    [L]
    [L]<b>Products</b>[R]<b>Qty</b>[R]<b>Price</b>
    [L]--------------------------------
    [L] a bun[R]1[R]$0.01
    [L] b bun[R]1[R]$0.01
    [L]--------------------------------
    [L]TOTAL DISCOUNT:[R][R]$0.00
    [L]TOTAL TAX:[R][R]$0.00
    [L]<b>TOTAL PRICE:[R][R]$0.02</b>
    [L]PAYMENT MODE: [R]CASH
    [L]--------------------------------

**Comment by DantSu** [comment]
Go read the doc. What's the others params of `EscPosPrinter` constructor ?

**Comment by TrungPQ-konbini** [comment]
i think it correct
MainApplication.escPosPrinterCommands = EscPosPrinterCommands(
                            UsbConnection(MainApplication.mManager, usbConnection.device),
                            EscPosCharsetEncoding("windows-1252", 16)
                        )

                        MainApplication.escPosPrinter = EscPosPrinter(
                            MainApplication.escPosPrinterCommands,
                            203,
                            80f,
                            32,
                        )

**Comment by DantSu** [comment]
Nop, I think is not correct. Go read the doc. What's the others params of EscPosPrinter constructor ?

**Comment by TrungPQ-konbini** [comment]
Can you tell me where I'm going wrong?
param DeviceConnection printer : Instance of a connected printer
param int printerDpi : 203
param float printerWidthMM : 80
param int printerNbrCharactersPerLine : 32.

**Comment by TrungPQ-konbini** [comment]
@DantSu  Thank you for your suggestion, I need to adjust the printerNbrCharactersPerLine value

**Comment by DantSu** [comment]
Yes you have right !
