### ISSUE TITLE
Small Font Black Background

### ISSUE THREAD

**Issue by onuryurtturk** [DantSu/ESCPOS-ThermalPrinter-Android#49]
When I use the small font option and try to print, the text background is black and the font color is white but there is no such problem in the medium font option.

What is the reason of this? I'm printing in the format you mentioned on the wiki.

**Comment by DantSu** [comment]
I use this command : https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=23
The small size seems to not be conventionnal. May be it's not works on all printer.

**Comment by onuryurtturk** [comment]
Could be a situation regarding the length of the text sent? When I use the Medium option, text overflows from the line. Is there anything to avoid this? I'm trying to find a solution other than using small fonts.

**Comment by DantSu** [comment]
I don't understand your problem when you use medium size.

**Comment by onuryurtturk** [comment]
half of the text on the line slips to the next line and continues from there

**Comment by DantSu** [comment]
So where is the problem ? It's a normal behavior. Use subtring if is a too long string for you.

**Comment by DantSu** [comment]
like `myLongString.length() > 42 ? myLongString.substring(0, 39) + "..." : myLongString`

**Comment by onuryurtturk** [comment]
The issue was solved when the command for the relevant text size was changed. Thank you
