### ISSUE TITLE
Device Class ID changed

### ISSUE THREAD

**Issue by DimiDR** [DantSu/ESCPOS-ThermalPrinter-Android#506]
Hello, I both a new cheap phone "Ulefone Note 16 Pro" on Android 13. After execution of the app, the new phone could not find the Bluetooth device. On my other phone, it went pretty well.

The issue is in BluetoothPrintersConnections class in the getList() method. The IDs on which the check was done on 1664, now I have 7936 (UNCATEGORIZED). I assume this represent somehow that this is a printer, and on other devices I never had this issue.

For now my solution is to allow 7936.
```
if ((majDeviceCl == BluetoothClass.Device.Major.IMAGING || majDeviceCl == 7936 ) && (deviceCl == 1664 || deviceCl == 7936 || deviceCl == BluetoothClass.Device.Major.IMAGING )) {
                printersTmp[i++] = new BluetoothConnection(device);
            }
```
After this it works. Any idea on the root cause?
![image](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/10392928/27c9a5c2-b3f7-459c-8a63-c972c3fe9d76)

**Comment by DantSu** [comment]
Yes, create your own BluetoothPrintersConnections class and add all id you want.

**Comment by DimiDR** [comment]
Thank you for the fast answer. But there could be maybe an issue, normally it should 1664. Your coding is correct. I think the detection of the printer changed somewhere. Unfortinately I cannot emulate it, as the Emulators dont have the Bluetooth connection.

**Comment by DantSu** [comment]
Not it's not, many chinese printer have custom id, if I want to take all printers models I have to add a lot of ids....
Create your custom class that works with your printers.
