### ISSUE TITLE
Letter "r" is coming at the start of print

### ISSUE THREAD

**Issue by syedbaber** [DantSu/ESCPOS-ThermalPrinter-Android#509]
![IMG_20240321_130738](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/assets/77399208/47606481-b666-446e-a5dc-1772bd7c4e09)

Letter "r" is printing in Sunmi printers.
I have tried on Sunmi v2 pro and Sunmi v2 s. Both have same issue.
And I am using the latest version 3.4.0.

**Comment by DantSu** [comment]
look closed issue

**Comment by syedbaber** [comment]
I closed it by mistake... This problem is not resolved

**Comment by DantSu** [comment]
I not have to resolve it, it's a problem of your printer, look at closed issue.
