### ISSUE TITLE
Connect to integrated printer

### ISSUE THREAD

**Issue by AlvaroBrizPixel** [DantSu/ESCPOS-ThermalPrinter-Android#51]
Hi there.
How can i connect to an integrated printer? I have this printer model https://www.pcmira.com/es/pda-y-terminales-android/272-pda-android-sunmi-v2.html and i dont need TCP, USB or Bluetooth connection, just local.
Thanks!

**Comment by DantSu** [comment]
Hi,
Many integrated printer are in bluetooth or usb connection.
What s type of connexion ? What's local ? If is Serial port, please take a look to this issue https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/39
