### ISSUE TITLE
Indian language tamil font is not printing

### ISSUE THREAD

**Issue by sjnaveenkumar** [DantSu/ESCPOS-ThermalPrinter-Android#517]
I'm trying to print "தமிழ்" Font in HOP-E801 thermal printer but it is printing random characters instead of tamil. 

I get to know that Tamil is supported at page 68 from [epson-biz](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32). Also i tried with charsets like "UTF-8", "ISO-8859-1", "CP864". 

No luck so far. It would be great if someone can help me with this issue. Thanks in advance.

**Comment by nicolasmdq** [comment]
Hi, printing non-english characters depends mainly of your printer support.

Advice: Try to convert your text as image, then print the image. It makes your print more device independant.

**Comment by sjnaveenkumar** [comment]
@nrs1022  I can able to print the font in this [App](https://play.google.com/store/apps/details?id=mate.bluetoothprint).

**Comment by nicolasmdq** [comment]
> @nrs1022 I can able to print the font in this [App](https://play.google.com/store/apps/details?id=mate.bluetoothprint).

It's because app probably does text-to-image convert before printing. Most chinese printers has fonts supporting english and (of course) chinese characters. To print any another character you'll have to pass text in canvas to a Bitmap, then print the Bitmap.

**Comment by nicolasmdq** [comment]
You can try with this code. It puts text on a StaticLayout and put it on a canvas to return a Bitmap. 

```
 Bitmap getMultiLangTextAsImage(String text, float textSize, Typeface typeface)  {
        TextPaint mPaint = new TextPaint();
        mPaint.setColor(Color.BLACK);
        if (typeface != null) mPaint.setTypeface(typeface);
        mPaint.setTextSize(textSize);
        Layout.Alignment alignment = Layout.Alignment.ALIGN_NORMAL;
        StaticLayout mStaticLayout = new StaticLayout(text, mPaint, 385, alignment, 1.0f, 0, false);

        int width = mStaticLayout.getWidth();
        int height = mStaticLayout.getHeight();

        Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);

        Canvas canvas = new Canvas(bitmap);

        canvas.drawColor(Color.WHITE);

        mStaticLayout.draw(canvas);

        return bitmap;
    }
```

StaticLayout was my choice because we could print with HTML tags too, in that case replace 
`StaticLayout(text...` 
with
 `StaticLayout(Html.fromHtml(text, Html.FROM_HTML_MODE_LEGACY)...`

The Bitmap has max width of 385px but you can put more text, in this case text will be multilined.

In my app:

```
EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32);
Bitmap xb = getMultiLangTextAsImage("á é í ó ú ñ Ñ தமிழ்", 24, Typeface.DEFAULT_BOLD);
printer.printFormattedText("[C]<img>"+PrinterTextParserImg.bitmapToHexadecimalString(printer,xb) + "</img>\n");
```

It will print your text with size 24 and bold typeface. Feel free to test it and improve it to your needs.

EDIT: Code was extracted from a working app of mine, removed unnecesary code.

**Comment by sjnaveenkumar** [comment]
@nrs1022 Thank you very much for the help. It worked as i expected.

**Comment by anhthoai** [comment]
@nrs1022 I am testing with XP-P300 with html tags, but text size is very small and width of image is not fixed to 58mm printer, do you have any suggestion:
`    fun getMultiLangTextAsImage(text: String, bold: Boolean): Bitmap {
        // Define printer resolution and paper width
        val dpi = 300
        val widthMm = 58f
        val widthPixels = mmToPixels(widthMm, dpi)

        // Set font size dynamically based on input type
        val fontSize = if (isHtml(text)) 50f else 42f

        // Parse text as HTML or plain text
        val spannedText: Spanned = if (isHtml(text)) {
            Html.fromHtml(text, Html.FROM_HTML_MODE_LEGACY)
        } else {
            SpannableString(text)
        }

        // Set up TextPaint
        val mPaint = TextPaint().apply {
            color = Color.BLACK
            textSize = fontSize
            //isAntiAlias = true
            typeface = if (bold) {
                Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            } else {
                Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            }
        }

        // Determine alignment (NORMAL is better for mixed content)
        val alignment: Layout.Alignment = Layout.Alignment.ALIGN_CENTER

        // Create StaticLayout for text rendering
        val mStaticLayout = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            StaticLayout.Builder.obtain(spannedText, 0, spannedText.length, mPaint, widthPixels)
                .setAlignment(alignment)
                .setLineSpacing(0f, 1.0f)
                .setIncludePad(false)
                .build()
        } else {
            StaticLayout(spannedText, mPaint, widthPixels, alignment, 1.0f, 0f, false)
        }

        // Calculate the height required for the text
        val width = mStaticLayout.width
        val height = mStaticLayout.height

        // Create bitmap with calculated dimensions
        val bitmap = Bitmap.createBitmap(widthPixels, height, Bitmap.Config.ARGB_8888)

        // Draw text on the canvas
        val canvas = Canvas(bitmap)
        canvas.drawColor(Color.WHITE)
        //canvas.translate(4f, 0f) // Add horizontal padding
        mStaticLayout.draw(canvas)

        return bitmap
    }`

**Comment by SpyrosMourelatos** [comment]
Even though this is a good approach to print centered text, it is not good enough for rows:
Imagine the very common use case:
```
coffeee             7E
choco               3E
```

**Comment by nicolasmdq** [comment]
> Even though this is a good approach to print centered text, it is not good enough for rows: Imagine the very common use case:
> 
> ```
> coffeee             7E
> choco               3E
> ```

Hi, you could use a monospaced font or build a layout on code and print as desired.
