### ISSUE TITLE
Problema letras acentuadas al usar <font size='small'>

### ISSUE THREAD

**Issue by desarrollo-grupo-adec** [DantSu/ESCPOS-ThermalPrinter-Android#52]
Good day,

I have read the problem when not using the correct encoding, but I am having a problem when using font size small, instead of placing the accented letter, it adds a symbol like a diamond, this does not happen to me with the other font sizes, only with small.

Thanks!

**Comment by IAmJulianAcosta** [comment]
Hi @desarrollo-grupo-adec what encoding are you using?

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/62

Your printer seems to not works correctly with small font.
