### ISSUE TITLE
update SDK Version to 34 and using android 14 USB crash

### ISSUE THREAD

**Issue by natsirasrafi** [DantSu/ESCPOS-ThermalPrinter-Android#530]
When printing via USB App crash after updating compileSdkVersion and targetSdkVersion to 34 and using android 14 

java.lang.IllegalArgumentException: : Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.

when i change to FLAG_IMMUTABLE not crash but print not working

**Comment by harsh8088** [comment]
I am getting the same issue. Any fixes so far?? @DantSu

**Comment by DantSu** [comment]
![image](https://github.com/user-attachments/assets/a4c61e52-c372-4ab1-99fe-f1001e34c6cc)


May be .... Read the migrate documentation..... I havent time to work on this.

**Comment by natsirasrafi** [comment]
I change to this code, no error again in console but print not working
```
public void printUsb(String struktext, String status, Bitmap imgcode, int widthprinter) {
		UsbConnection usbConnection = UsbPrintersConnections.selectFirstConnected(this);
		UsbManager usbManager = (UsbManager) this.getSystemService(Context.USB_SERVICE);

		if (usbConnection == null || usbManager == null) {
			new AlertDialog.Builder(this)
					.setMessage("Printer tidak ditemukan\nSilahkan hubungkan dengan printer")
					.setPositiveButton(Html.fromHtml("<font color='#ffffff'>OK</font>"),null)
					.show();
			return;
		}

		xusbprinter = "struk";
		xstruktext = struktext;
		xstatus = status;
		ximgcode = imgcode;
		xwidthprinter = widthprinter;

		PendingIntent permissionIntent = PendingIntent.getBroadcast(
				this,
				0,
				new Intent(MainActivity.ACTION_USB_PERMISSION),
				PendingIntent.FLAG_IMMUTABLE
		);

		IntentFilter filter = new IntentFilter(MainActivity.ACTION_USB_PERMISSION);

		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
			registerReceiver(usbReceiver, filter, RECEIVER_NOT_EXPORTED);
		}else {
			registerReceiver(usbReceiver, filter);
		}
		usbManager.requestPermission(usbConnection.getDevice(), permissionIntent);
	}
	
	
	
```

FLAG_IMMUTABLE make print not working, but in android 14 i must change FLAG_MUTTABLE to FLAT_IMUTTABLE

@DantSu can you give me more information?

**Comment by taylorlacort** [comment]
"I am facing the same problem through this [documentation:](https://developer.android.com/reference/android/app/PendingIntent) , it shows a promising Flag: FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT. I haven't tested it yet, but I think it might help if it works for you. Could you give me your feedback?" @natsirasrafi @harsh8088

**Comment by natsirasrafi** [comment]
> "I am facing the same problem through this [documentation:](https://developer.android.com/reference/android/app/PendingIntent) , it shows a promising Flag: FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT. I haven't tested it yet, but I think it might help if it works for you. Could you give me your feedback?" @natsirasrafi @harsh8088

i was try it , but not solve the problem

**Comment by taylorlacort** [comment]
@natsirasrafi @harsh8088 

I managed to solve it in the following way.


Make the Intent Explicit: Use setPackage() to specify the app's package in the Intent.

Use PendingIntent.FLAG_MUTABLE: Allow modifications if needed, but ensure the Intent is explicit.

Register BroadcastReceiver Securely: Use Context.RECEIVER_NOT_EXPORTED for Android 13 and above to prevent external access.

These steps ensure the function is secure and compatible with newer Android versions.

### Before Changes:
```


PendingIntent permissionIntent = PendingIntent.getBroadcast(
    cordova.getActivity().getBaseContext(),
    0,
    new Intent(intentName),  // Implicit Intent
    FLAG_MUTABLE
);**

cordova.getActivity().registerReceiver(broadcastReceiver, filter);
```

### **After Changes:**

```
Intent explicitIntent = new Intent(intentName);
explicitIntent.setPackage(cordova.getActivity().getPackageName()); // Make Intent explicit
PendingIntent permissionIntent = PendingIntent.getBroadcast(
    cordova.getActivity().getBaseContext(),
    0,
    explicitIntent,
    PendingIntent.FLAG_MUTABLE
);

if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {  // TIRAMISU is Android 13 / API 33
    cordova.getActivity().registerReceiver(broadcastReceiver, filter, Context.RECEIVER_NOT_EXPORTED);
} else {
    cordova.getActivity().registerReceiver(broadcastReceiver, filter);
}


```

**Comment by natsirasrafi** [comment]
> @natsirasrafi @harsh8088
> 
> I managed to solve it in the following way.
> 
> Make the Intent Explicit: Use setPackage() to specify the app's package in the Intent.
> 
> Use PendingIntent.FLAG_MUTABLE: Allow modifications if needed, but ensure the Intent is explicit.
> 
> Register BroadcastReceiver Securely: Use Context.RECEIVER_NOT_EXPORTED for Android 13 and above to prevent external access.
> 
> These steps ensure the function is secure and compatible with newer Android versions.
> 
> ### Before Changes:
> ```
> 
> 
> PendingIntent permissionIntent = PendingIntent.getBroadcast(
>     cordova.getActivity().getBaseContext(),
>     0,
>     new Intent(intentName),  // Implicit Intent
>     FLAG_MUTABLE
> );**
> 
> cordova.getActivity().registerReceiver(broadcastReceiver, filter);
> ```
> 
> ### **After Changes:**
> ```
> Intent explicitIntent = new Intent(intentName);
> explicitIntent.setPackage(cordova.getActivity().getPackageName()); // Make Intent explicit
> PendingIntent permissionIntent = PendingIntent.getBroadcast(
>     cordova.getActivity().getBaseContext(),
>     0,
>     explicitIntent,
>     PendingIntent.FLAG_MUTABLE
> );
> 
> if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {  // TIRAMISU is Android 13 / API 33
>     cordova.getActivity().registerReceiver(broadcastReceiver, filter, Context.RECEIVER_NOT_EXPORTED);
> } else {
>     cordova.getActivity().registerReceiver(broadcastReceiver, filter);
> }
> ```

Thank You your codes is work on me too, you save me

**Comment by natsirasrafi** [comment]
After i get solution from @taylorlacort 
this is my before after codes :

**Before**  =

```
PendingIntent permissionIntent = PendingIntent.getBroadcast(
		this,
		0,
		new Intent(MainActivity.ACTION_USB_PERMISSION),
		android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S ? PendingIntent.FLAG_MUTABLE : 0 
);
IntentFilter filter = new IntentFilter(MainActivity.ACTION_USB_PERMISSION);
registerReceiver(this.usbReceiver, filter);
usbManager.requestPermission(usbConnection.getDevice(), permissionIntent);
```

**After**  =

```
Intent explicitIntent = new Intent(MainActivity.ACTION_USB_PERMISSION);
explicitIntent.setPackage(this.getPackageName()); // Make Intent explicit
PendingIntent permissionIntent = PendingIntent.getBroadcast(
		this,
		0,
		explicitIntent,
		android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S ? PendingIntent.FLAG_MUTABLE : 0
);
IntentFilter filter = new IntentFilter(MainActivity.ACTION_USB_PERMISSION);

if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {  // TIRAMISU is Android 13 / API 33
	this.registerReceiver(this.usbReceiver, filter, Context.RECEIVER_NOT_EXPORTED);
} else {
	this.registerReceiver(this.usbReceiver,filter);
}
usbManager.requestPermission(usbConnection.getDevice(), permissionIntent);
```
