### ISSUE TITLE
Printer has to pe reset after a few copies

### ISSUE THREAD

**Issue by robmr88** [DantSu/ESCPOS-ThermalPrinter-Android#54]
Hi, I'm having an issue when I'm printing on lan printers.
At some point the print command stops working, it fives me "printer not found error" and it only starts printing again if I restart the printer. It happens on different printer models that did not have this issue before I started to use the library.
Do you know if this is a known bug or maybe I'm doing something wrong.
I am using the print command like in yout examples.
Thank you

**Comment by DantSu** [comment]
Weird issue. I can't test lan issue. I can't help you.

**Comment by DantSu** [comment]
After read this : https://stackoverflow.com/questions/52704083/esc-pos-bluetooth-printer-clear-buffer

Can you try to : 

```java
TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 56f, 48, new EscPosCharsetEncoding("windows-1252", 16));

printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST\n");
printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST\n");
printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST\n");
```
Did it solve the problem ?
