### ISSUE TITLE
Text align wrong when too long 

### ISSUE THREAD

**Issue by thanhnd** [DantSu/ESCPOS-ThermalPrinter-Android#55]
I tried to test with this, but the number 9.99 was aligned left
`"[L]<b>BEAUTIFUL SHIRT BEAUTIFUL SHIRT BEAUTIFUL SHIRT BEAUTIFUL SHIRT</b>[R]9.99e\n"`

**Comment by DantSu** [comment]
Normal behavior. is not a bug.
