### ISSUE TITLE
Print from Bluetooth Printer using MAC address

### ISSUE THREAD

**Issue by saputraiqbal** [DantSu/ESCPOS-ThermalPrinter-Android#56]
Hi, in README.md, it tells that we can connect to TCP printer using IP address, but it also only tells to connect to bluetooth using BluetoothPrintersConnections.selectFirstPaired(). I wonder if we can print from bluetooth printer using MAC address (either got from server or typed by user), like the way we connect to TCP printer. Thanks

**Comment by DantSu** [comment]
It's not implemented yet.
