### ISSUE TITLE
Not able to print euro sign €

### ISSUE THREAD

**Issue by steamerstudio** [DantSu/ESCPOS-ThermalPrinter-Android#6]
Hey, I'm using this great lib since a couple of months ago and I just figured out that I was not able to print the euro sign : '€'. This symbol is replaced by a question mark.
My printer is a Munbyn.
Do you face the same issue ?

Thanks.
Regards

**Comment by SlaveMast3r** [comment]
It could be because of two reasons. First: Char table doesn't contains euro symbol. Or you are not using proper character encoding.

Default char table: "WESTERN_EUROPE_ENCODING"
Default encoding: "ISO-8859-1"

There is [pull request](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/pull/4/commits/bb7a434bb6749eb73d98bc399e783f97af9a767d#diff-7a8cf3c98ff425e7f774d9514941b52f) to solve this issue.

**Comment by DantSu** [comment]
Many printer don't have € char.
May be you can't print this with your printer. I just added charset encoding in v1.0.1. 
Try to select another encoding, refers to the ESC manual of your printer to know ID number of charset encoding. Exemple, for my printer :
6 => "ISO-8859-1" (Western Europe)
16 => "windows-1252" (Latin-I)
94 => "windows-1258" (Vietnam)

https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html => Find here JAVA string charset

**Comment by steamerstudio** [comment]
Hi DantSu, many thanks for your quick answer.
Actually, I double checked with this page in order to get confirmation : [https://www.fileformat.info/info/unicode/char/20ac/charset_support.htm](https://www.fileformat.info/info/unicode/char/20ac/charset_support.htm)
And, as you suggested, windows-1252 handles the euro sign.
It works like a charm.
Issue solved, thanks !

**Comment by AdilTechDart** [comment]
Where i can get **escPosCharsetId**?

**Comment by DantSu** [comment]
> Many printer don't have € char.
> May be you can't print this with your printer. I just added charset encoding in v1.0.1.
> Try to select another encoding, refers to the ESC manual of your printer to know ID number of charset encoding. Exemple, for my printer :
> 6 => "ISO-8859-1" (Western Europe)
> 16 => "windows-1252" (Latin-I)
> 94 => "windows-1258" (Vietnam)
> 
> https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html => Find here JAVA string charset

Try to select another encoding, refers to the ESC manual of your printer to know ID number of charset encoding.

**Comment by AdilTechDart** [comment]
Latin letter 'Ñ' still not working
![image](https://user-images.githubusercontent.com/37257868/82731055-a0773200-9d1d-11ea-8510-ea5f1659ee9e.png)

**Comment by DantSu** [comment]
Only your printer manual can say you the answer. Find the charset encoding availables on your printer and test it.

**Comment by AdilTechDart** [comment]
> Only your printer manual can say you the answer. Find the charset encoding availables on your printer and test it.

Here is the printer:
https://www.amazon.es/dp/B07QYV8MN9/ref=cm_sw_r_wa_apap_96TRebIKPKj8v

**Comment by DantSu** [comment]
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32
Here you have a list for the EPSON models. May be it's the same for you !
