### ISSUE TITLE
how to get charsetName for EscPosCharsetEncoding

### ISSUE THREAD

**Issue by earthprakan** [DantSu/ESCPOS-ThermalPrinter-Android#60]
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32

from document i use Page 20 [Thai Character Code 42] for charsetName and 20 for escPosCharsetId but throw EscPosEncodingException

how to print thailand language ?

Thank you for answer

**Comment by jehadmashhour** [comment]
Same here , how to print arabic language ?

**Comment by DantSu** [comment]
#6 

> Try to select another encoding, refers to the ESC manual of your printer to know ID number of charset encoding. Exemple, for my printer :
> 6 => "ISO-8859-1" (Western Europe)
> 16 => "windows-1252" (Latin-I)
> 94 => "windows-1258" (Vietnam)
> 
> https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html => Find here JAVA string charset

**Comment by DantSu** [comment]
#31

**Comment by jehadmashhour** [comment]
@DantSu Please can you explain more for me , i have tried to change the charset name to be UTF-8 but i don't know what is the 
escPosCharsetId(code page ) , check my below POSs : 

https://www.sunmi.com/en/V1s/
https://www.szzcs.com/m/prod_view.aspx?TypeId=10&Id=171&Fid=t3:10:3

I have checked many of charset names and ids , but no avail , every time i see a Chinese language instead Arabic .

What is the problem and how i can get the required code page for my printers above .

**Comment by jehadmashhour** [comment]
@DantSu Any help?

**Comment by DantSu** [comment]
Nop, I have'nt more to say about it.
