### ISSUE TITLE
How to set line height?

### ISSUE THREAD

**Issue by CeLTechn0** [DantSu/ESCPOS-ThermalPrinter-Android#61]
Here's my Code.

    private void printText() throws EscPosConnectionException, EscPosParserException, EscPosEncodingException, EscPosBarcodeException {
        EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 58f, 32);
        printer.printFormattedText(
                "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                        "[L]\n" +
                        "[C]================================\n" +
                        "[L]\n" +
                        "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                        "[L]  + Size : S\n" +
                        "[L]\n" +
                        "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                        "[L]  + Size : 57/58\n" +
                        "[L]\n" +
                        "[C]--------------------------------\n" +
                        "[R]TOTAL PRICE :[R]34.98e\n" +
                        "[R]TAX :[R]4.23e\n" +
                        "[L]\n" +
                        "[C]================================\n" +
                        "[L]\n" +
                        "[L]<font size='tall'>Customer :</font>\n" +
                        "[L]Raymond DUPONT\n" +
                        "[L]5 rue des girafes\n" +
                        "[L]31547 PERPETES\n" +
                        "[L]Tel : +33801201456\n" +
                        "[L]\n" +
                        "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                        "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                );
    }

-----------------------------------------------------------------------------------

I copy and pasted the format and I get an output like this...

![IMG_20200904_101400](https://user-images.githubusercontent.com/69677688/92191949-878f2880-ee97-11ea-8fe2-45cc38d1dd22.jpg)
![IMG_20200904_101433](https://user-images.githubusercontent.com/69677688/92191959-8c53dc80-ee97-11ea-8caf-e3bc53da1dce.jpg)

Thanks in advance.

**Comment by DantSu** [comment]
It"s a very weird behavior.
Test with : `EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 58f, 31);`

**Comment by CeLTechn0** [comment]
> It"s a very weird behavior.
> Test with : `EscPosPrinter printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 58f, 31);`

Thanks. problem fixed..

**Comment by DantSu** [comment]
In fact, problem is not fixed. I think, it's a charset encoding printer problem. It's adding at the end of line. `N°045` become `N5`. I think you have to find the correct charset encoding with the correct ID.
