### ISSUE TITLE
i can't print Arabic letters , i use new EscPosCharsetEncoding("WPC1256", 50)) but there is error happens "android Thread java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-3,5,main] that has not called Looper.prepare()"

### ISSUE THREAD

**Issue by M-Elnemr** [DantSu/ESCPOS-ThermalPrinter-Android#63]

**Comment by ahmedmnk** [comment]
@DantSu 
Would you please support for what is the the charset encoding to be used in the below  method for arabic data
EscPosCharsetEncoding("WPC1256",50)
I tried many but it did not work

**Comment by DantSu** [comment]
Can you paste me the full error code ? and the function that make the error ?

**Comment by M-Elnemr** [comment]
i solved this error with adding the method into AsyncTask class but i have another  problem 
 i can't print Arabic letters the output is only Chinese letters 

here is the method which i use 

  private void testPrint() {
        try {
            EscPosPrinter printer = new EscPosPrinter(new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT)
                    , 203, 56f, 48,
                    new EscPosCharsetEncoding("windows-1256", 50));

            printer.printFormattedTextAndCut(
                    "[R] English writing \n" +
                            "[R] نص باللغة العربيه\n" +
                            "[L] نص باللغة العربيه\n" +
                            "[C] نص باللغة العربيه\n" +
                            "[R] English writing "

            );

        } catch (Exception e) {
            e.printStackTrace();
        }
    } 

i took a photo to the output 
here is the link 
https://ibb.co/RyDXKh3

[https://ibb.co/RyDXKh3](url)

**Comment by ahmedmnk** [comment]
@DantSu 
![WhatsApp Image 2020-09-15 at 11 11 38 PM](https://user-images.githubusercontent.com/68162733/93259677-df3b6700-f7a8-11ea-8f34-f3881c46212a.jpeg)
 The below is my implementation , and when am using the encoding windows-1256  with charset 50 the arabic data is coming empty and when the charset is 16 unreadable data appears
btw the below implementation is inside async task
`try {

            val printer =
                EscPosPrinter(
                    TcpConnection(host, port),
                                        203,
                                        48f,
                                        32,
//                    EscPosCharsetEncoding("ISO-8859-6",22)
                    EscPosCharsetEncoding("windows-1256",50)
                )
            printer.printFormattedTextAndCut(data)
            printer.disconnectPrinter()

        }
        catch(e : ConnectException)
        {
            //Toast.makeText(context, "Socket Exception : $e", Toast.LENGTH_LONG).show()

        }`
PFA attached images
![WhatsApp Image 2020-09-15 at 11 11 38 PM](https://user-images.githubusercontent.com/68162733/93259730-f67a5480-f7a8-11ea-8cfa-0627b72b66ce.jpeg)

**Comment by DantSu** [comment]
Do you have the list of charset with id supported by your printer ?

**Comment by M-Elnemr** [comment]
a simple way to print Arabic is to create a bitmap from a text then print it as an image

**Comment by M-Elnemr** [comment]
@DantSu yes i have the character set and i use it correctly and still Chinese letters , but currently i print Arabic as an bitmap image

**Comment by DantSu** [comment]
@M-Elnemr may be the selected font is not the good one, read here https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=27

**Comment by ahmedmnk** [comment]
@M-Elnemr thank , i did it but the image is becoming very small using this library com.izettle:html2bitmap:1.9

**Comment by M-Elnemr** [comment]
@ahmedmnk why you even use a library , it's a simple method allows you to determine the text size,  you can search

**Comment by M-Elnemr** [comment]
@DantSu how i can change the font , is there any method i can use ?

**Comment by DantSu** [comment]
Try this before `.printFormattedText()` : 

```java
printerConnection.write(new byte[] {0x1B, 0x4D, 0x01});
printerConnection.send();
```

if it's don't works, try with 0x02 then 0x03 then 0x04 instead of 0x01 (the last byte).

**Comment by M-Elnemr** [comment]
EscPosPrinter printer = ......;

printer.write(new byte[] {0x1B, 0x4D, 0x01});
printer.send();

but..
connot resolve method write
connot resolve method send

why the compiler cand find those two methods ?

**Comment by DantSu** [comment]
It's with PrinterConnection not with EscPosPrinter.

Use write and send with the DeviceConnection you give to your EscPosPrinter instance.

**Comment by DantSu** [comment]
```java
TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);

printer.write(new byte[] {0x1B, 0x4D, 0x01});
printer.send();

EscPosPrinter printer = new EscPosPrinter(printerConnection
, 203, 56f, 48, new EscPosCharsetEncoding("windows-1256", 50));
```

**Comment by M-Elnemr** [comment]
![WhatsApp Image 2020-09-18 at 7 22 51 PM](https://user-images.githubusercontent.com/50822992/93627163-cdde9e80-f9e4-11ea-9d33-b54fdec4a3cd.jpeg)

-- the code i use
----------------------------------------------------------------------------------------------------------------
   TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);

            EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 56f, 48, new EscPosCharsetEncoding("PC864", 37));

            printerConnection.write(new byte[] {0x1B, 0x4D, 0x04});
            printerConnection.send();

            printer.printFormattedTextAndCut(
                    "[R] English writing \n" +
                            "[R] نص باللغة العربيه\n" +
                            "[L] نص باللغة العربيه\n" +
                            "[C] نص باللغة العربيه\n" +
                            "[R] English writing "

            );
---------------------------------------------------------------------------------------------------------
i have error while using some charset 
i sent you the charset setting paper from the printer and there is 4 charset for arabic language 

i get an error for the first three charset 
and Chinese characters for the fourth and last charset 

-- here is the error 
-------------------------------------------------------------------------------------------------------
W/System.err: java.io.UnsupportedEncodingException: PC864
        at java.nio.charset.Charset.forNameUEE(Charset.java:580)
W/System.err:     at java.lang.String.getBytes(String.java:914)
        at com.dantsu.escposprinter.EscPosPrinterCommands.printText(EscPosPrinterCommands.java:285)
        at com.dantsu.escposprinter.textparser.PrinterTextParserString.print(PrinterTextParserString.java:40)
        at com.dantsu.escposprinter.textparser.PrinterTextParserString.print(PrinterTextParserString.java:8)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:114)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:157)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:142)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:131)
        at com.example.hp.baleno.Cart.test(Cart.java:394)
W/System.err:     at com.example.hp.baleno.Cart.access$300(Cart.java:42)
        at com.example.hp.baleno.Cart$MyTask.doInBackground(Cart.java:243)
        at com.example.hp.baleno.Cart$MyTask.doInBackground(Cart.java:232)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    Caused by: java.nio.charset.UnsupportedCharsetException: PC864
W/System.err:     at java.nio.charset.Charset.forName(Charset.java:566)
        at java.nio.charset.Charset.forNameUEE(Charset.java:578)
    	... 18 more
    com.dantsu.escposprinter.exceptions.EscPosEncodingException: PC864
W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.printText(EscPosPrinterCommands.java:304)
        at com.dantsu.escposprinter.textparser.PrinterTextParserString.print(PrinterTextParserString.java:40)
        at com.dantsu.escposprinter.textparser.PrinterTextParserString.print(PrinterTextParserString.java:8)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:114)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:157)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:142)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:131)
        at com.example.hp.baleno.Cart.test(Cart.java:394)
        at com.example.hp.baleno.Cart.access$300(Cart.java:42)
        at com.example.hp.baleno.Cart$MyTask.doInBackground(Cart.java:243)
        at com.example.hp.baleno.Cart$MyTask.doInBackground(Cart.java:232)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by M-Elnemr** [comment]
nothing special happens when i change the  0x04

0x04, 0x03, 0x02, 0x01     all are the same output for the last charset (just Chinese letters)
printerConnection.write(new byte[] {0x1B, 0x4D, 0x04});

**Comment by DantSu** [comment]
ok, so it's not a solution.

For `System.err: java.io.UnsupportedEncodingException: PC864`, you don't use a valid charset name.
You have to use the first column of this table : https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html

For example `PC864`, you have to write `new EscPosCharsetEncoding("IBM864", 37)`

**Comment by DantSu** [comment]
```java
        TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);
        EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 56f, 48, new EscPosCharsetEncoding("windows-1256", 50));

        printer.printFormattedTextAndCut(
                "[R] English writing \n" +
                        "[R] نص باللغة العربيه\n" +
                        "[L] نص باللغة العربيه\n" +
                        "[C] نص باللغة العربيه\n" +
                        "[R] English writing "

        );
```


**AND convert your java file in the good charset encoding too :** 

![CharsetEncoding](https://user-images.githubusercontent.com/4188774/93663956-ae3e8900-fa6b-11ea-82f5-89b327488fe6.png)

**Comment by M-Elnemr** [comment]
![WhatsApp Image 2020-09-20 at 2 29 47 AM](https://user-images.githubusercontent.com/50822992/93691732-ee445100-fae9-11ea-85db-9fe46f0ffde9.jpeg)

okay i changed the charset into "IBM864", 37
and i have converted the  java file charset

and it printed but just ignored all Arabic letters as they are not even exist

"[R] English writing \n" +
                            "[R] نص باللغة العربيه\n" +
                            "[L] نص باللغة العربيه\n" +
                            "[C] نص باللغة العربيه\n" +
                            "[R] English writing "

the output is only English writing and shown at the image

**Comment by DantSu** [comment]
Try with windows-1256 instead of this.

**Comment by DantSu** [comment]
> ```java
>         TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);
>         EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 56f, 48, new EscPosCharsetEncoding("windows-1256", 50));
> 
>         printer.printFormattedTextAndCut(
>                 "[R] English writing \n" +
>                         "[R] نص باللغة العربيه\n" +
>                         "[L] نص باللغة العربيه\n" +
>                         "[C] نص باللغة العربيه\n" +
>                         "[R] English writing "
> 
>         );
> ```
> 
> 
> **AND convert your java file in the good charset encoding too :** 
> 
> ![CharsetEncoding](https://user-images.githubusercontent.com/4188774/93663956-ae3e8900-fa6b-11ea-82f5-89b327488fe6.png)
> 

Try with windows 1256. Like my comment.
