### ISSUE TITLE
Reverse

### ISSUE THREAD

**Issue by mozkan0687** [DantSu/ESCPOS-ThermalPrinter-Android#67]
How can write reverse ? 
![image](https://user-images.githubusercontent.com/69143247/95782631-dc189580-0cd8-11eb-9ccc-37de40855c32.png)

**Comment by DantSu** [comment]
I don't understand the question.

**Comment by mozkan0687** [comment]
I want to invert  White \ Black like on photo

**Comment by DantSu** [comment]
I don't think you can do that with a thermal printer.

**Comment by mozkan0687** [comment]
![image](https://user-images.githubusercontent.com/69143247/95902600-b3a69f00-0d9d-11eb-97e1-bc1a0f4b5b77.png)

![image](https://user-images.githubusercontent.com/69143247/95902717-d3d65e00-0d9d-11eb-9369-28930fcc5ee4.png)

You can do it thermal printer.

**Comment by DantSu** [comment]
It's not implemented yet in the library.

**Comment by wiscomsolutions** [comment]
Are there plans of implementing this in the near future?

**Comment by DantSu** [comment]
No
