### ISSUE TITLE
Cannot align center text with small font 

### ISSUE THREAD

**Issue by thanhnd** [DantSu/ESCPOS-ThermalPrinter-Android#69]
I've tried with this below, but not successfully.

`[C]<font size='small'>This one may be a very long small text</font>\n`

**Comment by DantSu** [comment]
It's seems that small font don't works properly on all printer. I have to do a refactor for the font size tag but haven't enouht time right now.

**Comment by DantSu** [comment]
Small font is not a standard. Epson don't have small font in their documentation. I will remove this option.
