### ISSUE TITLE
Does not detect broken pipe

### ISSUE THREAD

**Issue by steamerstudio** [DantSu/ESCPOS-ThermalPrinter-Android#7]
Hi guys. There's an enhancement to be made regarding exception propagations.
Indeed, in DeviceConnection.send(), we print stack trace whereas we should throws the raw exception or, better, a custom one.
The result is that the application is not notified of a broken pipe situation and can't request a new connection. This appends when you turn off and on your thermal printer.
I will try to make a PR.
Your comments are welcome.
Cheers

**Comment by DantSu** [comment]
Yes, it's a good point.

It will better to delete `try {} catch {}` inside the library. But that will be a big braking change. That's mean a new major version.
