### ISSUE TITLE
Size of the image

### ISSUE THREAD

**Issue by asaadbaw** [DantSu/ESCPOS-ThermalPrinter-Android#70]
Hello

Is there any way to make the image large? 
I have base64 image that I convert to bitmap and then pass it to bitmapToHexadecimalString.

Ex. 
![image](https://user-images.githubusercontent.com/8416276/96729071-6e95f480-13bd-11eb-87cb-b3aa12ae0f0f.png)

![20201021_165012](https://user-images.githubusercontent.com/8416276/96729246-9e44fc80-13bd-11eb-9542-99264430c47c.jpg)

**Comment by DantSu** [comment]
You have to generate a bitmap in the good dpi and size.
Assume you have a printer with a definition of 201 dpi and printing width of 70mm, you have to generate a picture of :
`201 * 7 / 2.54` = 554 px width.

**Comment by asaadbaw** [comment]
I am still facing the same issue. can you share a sample code for generating that picture passing base64 string?

**Comment by MustafaAlsihati** [comment]
We managed to get the image print at full width, but i think there is a height restriction, we want to print the image at its full height.

here is the code we did:
`
String receipt = "...base64 image";

byte[] decodedString = Base64.decode(receipt, Base64.DEFAULT);
Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

Bitmap resizedBitmap = Bitmap.createScaledBitmap(decodedByte, (int) (201 * 77 / 2.54), (int) ((201 * 77 / 2.54) * 2.5), false);
decodedByte.recycle();

printer.printFormattedTextAndCut( "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, resizedBitmap) + "</img>\n");
`

**Comment by DantSu** [comment]
Yes, you have to split every 256px.

**Comment by MustafaAlsihati** [comment]
Thanks, i managed to do it with the following code:

```
        new Thread(new Runnable() {
            public void run() {
                try {
                    byte[] decodedString = Base64.decode(receipt, Base64.DEFAULT);
                    List<Bitmap> segments = new ArrayList<Bitmap>();
                    Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

                    int width = decodedByte.getWidth();
                    int height = decodedByte.getHeight();

                    for(int y = 0; y < height; y += 256) {
                        y = y >= height? height : y;
                        int limit = y + 256 >= height? height - y : 256;
                        Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, limit);
                        segments.add(bitmap);
                    }

                    TcpConnection tcpConnection = new TcpConnection(ipAddress.getText().toString(), Integer.parseInt(portAddress.getText().toString()));
                    EscPosPrinter printer = new EscPosPrinter(tcpConnection, 201, 77f, 1);

                    for (Bitmap segment : segments) {
                        printer.printFormattedText("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, segment) + "</img>", 0);
                    }

                    printer.printFormattedTextAndCut("[C]Printed!!!\n");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
```

The only problem is that each split have a space after, it seems that the img tag is causing this, any solution?

**Comment by DantSu** [comment]
Great !
Don't forget \n at the end of line : 
```java
                    for (Bitmap segment : segments) {
                        printer.printFormattedText("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, segment) + "</img>", 0);
                    }
```
Did it solved your blank space problem ?

**Comment by MustafaAlsihati** [comment]
Tried it, still the same problem

**Comment by DantSu** [comment]
Great but you do it wrong.

```java
        new Thread(new Runnable() {
            public void run() {
                try {
                    byte[] decodedString = Base64.decode(receipt, Base64.DEFAULT);
                    List<Bitmap> segments = new ArrayList<Bitmap>();
                    Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

                    int width = decodedByte.getWidth();
                    int height = decodedByte.getHeight();

                    for(int y = 0; y < height; y += 256) {
                        y = y >= height? height : y;
                        int limit = y + 256 >= height? height - y : 256;
                        Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, limit);
                        segments.add(bitmap);
                    }

                    TcpConnection tcpConnection = new TcpConnection(ipAddress.getText().toString(), Integer.parseInt(portAddress.getText().toString()));
                    EscPosPrinter printer = new EscPosPrinter(tcpConnection, 201, 77f, 1);
                    StringBuilder printText = new StringBuilder();
                    for (Bitmap segment : segments) {
                        printText.append("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, segment) + "</img>\n");
                    }
                    printText.append("[C]Printed!!!\n");
                    printer.printFormattedTextAndCut(printText.toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
```

**Comment by MustafaAlsihati** [comment]
> Great but you do it wrong.
> 
> ```java
>         new Thread(new Runnable() {
>             public void run() {
>                 try {
>                     byte[] decodedString = Base64.decode(receipt, Base64.DEFAULT);
>                     List<Bitmap> segments = new ArrayList<Bitmap>();
>                     Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);
> 
>                     int width = decodedByte.getWidth();
>                     int height = decodedByte.getHeight();
> 
>                     for(int y = 0; y < height; y += 256) {
>                         y = y >= height? height : y;
>                         int limit = y + 256 >= height? height - y : 256;
>                         Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, limit);
>                         segments.add(bitmap);
>                     }
> 
>                     TcpConnection tcpConnection = new TcpConnection(ipAddress.getText().toString(), Integer.parseInt(portAddress.getText().toString()));
>                     EscPosPrinter printer = new EscPosPrinter(tcpConnection, 201, 77f, 1);
>                     StringBuilder printText = new StringBuilder();
>                     for (Bitmap segment : segments) {
>                         printText.append("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, segment) + "</img>\n");
>                     }
>                     printText.append("[C]Printed!!!\n");
>                     printer.printFormattedTextAndCut(printText.toString());
>                 } catch (Exception e) {
>                     e.printStackTrace();
>                 }
>             }
>         }).start();
> ```

Tried this solution, still the same problem unfortunately.

**Comment by DantSu** [comment]
Very weird, this should works. :/

Try this : 
```java
        new Thread(new Runnable() {
            public void run() {
                try {
                    TcpConnection tcpConnection = new TcpConnection(ipAddress.getText().toString(), Integer.parseInt(portAddress.getText().toString()));
                    EscPosPrinter printer = new EscPosPrinter(tcpConnection, 203, 70f, 48);

                    byte[] decodedString = Base64.decode(receipt, Base64.DEFAULT);
                    Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

                    int width = decodedByte.getWidth(), height = decodedByte.getHeight();

                    StringBuilder textToPrint = new StringBuilder();
                    for(int y = 0; y < height; y += 256) {
                        Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, (y + 256 >= height) ? height - y : 256);
                        textToPrint.append("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap) + "</img>\n");
                    }
                    
                    textToPrint.append("[C]Printed!!!\n");
                    printer.printFormattedTextAndCut(textToPrint.toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
```

**Comment by DantSu** [comment]
Do you find the solution ?

**Comment by MustafaAlsihati** [comment]
> Do you find the solution ?

Sorry for not replying earlier i was off on the weekend. Unfortunately it did not solve the issue,
it managed to reduce the empty space size but it still visible.

**Comment by DantSu** [comment]
I don't understand where does this spaces come from.

**Comment by MustafaAlsihati** [comment]
I think it's something related to the '\n' making margin between each img tag, not sure though. I tried many solutions but no luck so far

**Comment by greentill** [comment]
hi, can anyone give me the code of how to print image in full width and height , i tried your code but didnt worked. help

**Comment by DantSu** [comment]
\n is just use for spliting line. There are not printed.

**Comment by nhuttrung** [comment]
I got the same problem.
The issue is on the file https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/EscPosPrinterSize.java

It scales the image to maxHeight of 255.

**Comment by DantSu** [comment]
yes i know and is not an issue.

**Comment by romaia** [comment]
Same problem for me here. 

One thing I noticed is that if i split every 256px (or 128 and probably true for other powers of 2) I get a much bigger space than if i split every 255px (or 127).

I could also guess that the printer is adding the extra space after each image, but printing images using some other applications from the play store work fine, and I also guess that they also have to handle this max height of 256 pixels - but I could be totally wrong here.

**Comment by AlexandreLumertz** [comment]
The problem is here: http://prntscr.com/vdcdqd

`this.printer.newLine();`
If printing images only, ignore this command.

**Comment by DantSu** [comment]
Instead of your extra param newLine, try this ;)

```java
        for (PrinterTextParserLine line : linesParsed) {
            PrinterTextParserColumn[] columns = line.getColumns();

            IPrinterTextParserElement lastElement = null;
            for (PrinterTextParserColumn column : columns) {
                IPrinterTextParserElement[] elements = column.getElements();
                for (IPrinterTextParserElement element : elements) {
                    element.print(this.printer);
                    lastElement = element;
                }
            }
            
            if(!(lastElement instanceof PrinterTextParserImg) && !(lastElement instanceof PrinterTextParserBarcode)) {
                this.printer.newLine();
            }
        }
```

**Comment by DantSu** [comment]
say me if it works, I will publish a new release !

**Comment by Elblassy** [comment]
@DantSu Do you solve the problem ?

**Comment by Elblassy** [comment]
@DantSu  this solution work for me , you can update library with this solution

**Comment by DantSu** [comment]
Ok thx i will publish a new releass.

**Comment by DantSu** [comment]
Ok v2.0.7 is out.

**Comment by romaia** [comment]
I can confirm this release fixed the issue.

**Comment by DantSu** [comment]
# If you only print image and do not use formatted text, you can do that : 

The image must have a correct width : 
- 1 inch = 25.4mm
- Thermal printer commonly have 203px by inch.
- So the width of the printed bitmap must be `millimetersWidthPrintingZone / 25.4 * 203` pixels.

```java
        EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(printerConnection);
        try {
            printerCommands.connect();
            printerCommands.reset();
            printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(myBitmap));
            printerCommands.feedPaper(50);
            printerCommands.cutPaper();
        } catch (EscPosConnectionException e) {
            e.printStackTrace();
        }
```

**Comment by Elblassy** [comment]
this work for width of image but some of height not printed

**Comment by Elblassy** [comment]
it work fine when increase feed , nice solution thanks

**Comment by laithbzour** [comment]
still have errorr : Buffer not large enough for pixels

when try print bitmap image

**Comment by DantSu** [comment]
I think the error message is explicit.... your printer haven't enougth memory for the image you try to print...

**Comment by laithbzour** [comment]
@DantSu thanks for reply
i try split image to chunk but still have same issue 

just print image 60*60. 

POS device type Aisino A90

**Comment by DantSu** [comment]
Try to use `useEscAsteriskCommand(true)`

Method : useEscAsteriskCommand(boolean enable)

Active "ESC *" command for image printing.

 param boolean enable : true to use "ESC *", false to use "GS v 0"
 return Printer : Fluent interface

**Comment by laithbzour** [comment]
@DantSu 
i try this method print Chinese char

this is my code 

     int targetWidth = 383; // 48mm printing zone with 203dpi => 383px
                    Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                            bmp,
                            targetWidth,
                            Math.round(((float) bmp.getHeight()) * ((float) targetWidth) / ((float) bmp.getWidth())),
                            true
                    );

                    EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(MyBluetoothPrintersConnections.selectFirstPairedOne());
                    try {
                        printerCommands.connect();
                        printerCommands.useEscAsteriskCommand(true);
                        printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
                        printerCommands.feedPaper(50);
                    } catch (EscPosConnectionException e) {
                        e.printStackTrace();
                    }

**Comment by laithbzour** [comment]
@DantSu 
my Thermal Printer specification 
Paper Width: 58mm
Diameter: 40mm
Android 7.1
RAM: 1GB

**Comment by laithbzour** [comment]
![PrintImage](https://user-images.githubusercontent.com/14046215/179470135-8fc841d6-acf5-4af6-a056-d8a35067d00d.jpeg)

**Comment by DantSu** [comment]
Cant help you more

**Comment by laithbzour** [comment]
@DantSu thanks i fix isssue

**Comment by DantSu** [comment]
How ?

**Comment by laithbzour** [comment]
@DantSu 
i split Text contain (Arabic & english) word to chunk then convert it to bitmap image 
then send it to printer and print it

**Comment by laithbzour** [comment]
![7e2326ef-4d85-4e67-8db7-73e231ab2bc7](https://user-images.githubusercontent.com/14046215/179696466-222d6bf2-813a-4c3a-a95b-0d60d3ecd8b2.jpeg)

**Comment by Ashubhutani** [comment]
Hi my image is accurate. but the quality of the image is too low 

i am using this below code 
  new Thread(new Runnable() {
            public void run() {
                try {
                    TcpConnection tcpConnection = new TcpConnection(ipAddress.getText().toString(), Integer.parseInt(portAddress.getText().toString()));
                    EscPosPrinter printer = new EscPosPrinter(tcpConnection, 203, 70f, 48);

                    byte[] decodedString = Base64.decode(receipt, Base64.DEFAULT);
                    Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

                    int width = decodedByte.getWidth(), height = decodedByte.getHeight();

                    StringBuilder textToPrint = new StringBuilder();
                    for(int y = 0; y < height; y += 256) {
                        Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, (y + 256 >= height) ? height - y : 256);
                        textToPrint.append("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap) + "</img>\n");
                    }
                    
                    textToPrint.append("[C]Printed!!!\n");
                    printer.printFormattedTextAndCut(textToPrint.toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();

**Comment by 8unique** [comment]
to get full sized bitmap, use this code in EscPosPrinterSize class.

        public byte[] bitmapToBytes(Bitmap bitmap, boolean gradient) {
        boolean isSizeEdit = false;
        int bitmapWidth = bitmap.getWidth(),
                bitmapHeight = bitmap.getHeight(),
                maxWidth = bitmapWidth,  // Increase the maximum width
                maxHeight = bitmapHeight; // Increase the maximum height

        if (bitmapWidth > maxWidth) {
            bitmapHeight = Math.round(((float) bitmapHeight) * ((float) maxWidth) / ((float) bitmapWidth));
            bitmapWidth = maxWidth;
            isSizeEdit = true;
        }
        if (bitmapHeight > maxHeight) {
            bitmapWidth = Math.round(((float) bitmapWidth) * ((float) maxHeight) / ((float) bitmapHeight));
            bitmapHeight = maxHeight;
            isSizeEdit = true;
        }

        if (isSizeEdit) {
            bitmap = Bitmap.createScaledBitmap(bitmap, bitmapWidth, bitmapHeight, true);
        }

        return EscPosPrinterCommands.bitmapToBytes(bitmap, gradient);
    }

**Comment by mlhtnc** [comment]
> it work fine when increase feed , nice solution thanks

Inreasing feed did not work for me. Actually it looks like any parameter passed to feedPaper is ignored for the printer i use.

**Comment by thatsgamer** [comment]
If someone still facing this issue, i am using a simpler solution...

Just create new class that extends EscPosPrinterSize

package com.yourpackage.name

import android.graphics.Bitmap
import com.dantsu.escposprinter.EscPosPrinterCommands
import com.dantsu.escposprinter.EscPosPrinterSize

class CustomEscPosPrinterSize(i: Int, fl: Float, i1: Int) : EscPosPrinterSize(i, fl, i1) {

    override fun bitmapToBytes(bitmap: Bitmap): ByteArray {
        var bitmap = bitmap
        var isSizeEdit = false
        var bitmapWidth = bitmap.width
        var bitmapHeight = bitmap.height
        val maxWidth = this.printerWidthPx
        val maxHeight = 256
        if (bitmapWidth > maxWidth) {
            bitmapHeight =
                Math.round(bitmapHeight.toFloat() * maxWidth.toFloat() / bitmapWidth.toFloat())
            bitmapWidth = maxWidth
            isSizeEdit = true
        }

        if (isSizeEdit) {
            bitmap = Bitmap.createScaledBitmap(bitmap, bitmapWidth, bitmapHeight, true)
        }

        return EscPosPrinterCommands.bitmapToBytes(bitmap)
    }

}


Following Code is Removed / Commented which was causing Height Issues in original lib
if (bitmapHeight > maxHeight) {
    bitmapWidth =
        Math.round(bitmapWidth.toFloat() * maxHeight.toFloat() / bitmapHeight.toFloat())
    bitmapHeight = maxHeight
    isSizeEdit = true
}

**Comment by vaibhav7700** [comment]
> Ok thx i will publish a new release.

Hi @DantSu ,
I’m facing an issue while printing a bitmap image on the receipt in our POS Android application.
The bitmap is not rendering correctly on the full 88mm receipt width, and part of the content gets clipped or scaled improperly during print.

![Image](https://github.com/user-attachments/assets/4e5a7b60-1415-45da-8d5a-2cc754b4d372)

**Comment by vaibhav7700** [comment]
Here is my Code @DantSu 
 val originalBitmap = base64ToBitmap(order.ticketPng)
        if (originalBitmap == null) {
            onError("IMAGE: Bitmap generation failed from Base64")
            return
        }
        val scaledWidth = 876
        val scaledHeight = ((originalBitmap.height.toFloat() / originalBitmap.width.toFloat()) * scaledWidth).roundToInt()
        val scaledBitmap = Bitmap.createScaledBitmap(originalBitmap, scaledWidth, scaledHeight, true)

        val cleanBitmap = Bitmap.createBitmap(scaledBitmap.width, scaledBitmap.height, Bitmap.Config.ARGB_8888)
        Canvas(cleanBitmap).apply {
            drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR)
            drawBitmap(scaledBitmap, 0f, 0f, null)
        }
        
        isPrinting = true
        try {
            val connection = getOrCreateConnection()
            val printer = EscPosPrinter(connection, 201, 48f, 48)

            val width = cleanBitmap.width
            val height = cleanBitmap.height
            val sliceHeight = 456
            val sb = StringBuilder()
            var y = 0
            while (y < height) {
                val remaining = height - y
                val h = if (remaining > sliceHeight) sliceHeight else remaining
                val slice = Bitmap.createBitmap(cleanBitmap, 0, y, width, h)

                val hex = PrinterTextParserImg.bitmapToHexadecimalString(printer, slice)
                sb.append("[C]<img>$hex</img>\n")

                y += sliceHeight
            }

            sb.append("[C]Printed!!!\n")
            
            printer.printFormattedTextAndCut(sb.toString())
            

        } catch (e: Exception) {
            e.printStackTrace()
        
        }
