### ISSUE TITLE
Weird characters on label printer

### ISSUE THREAD

**Issue by mossaabrafih** [DantSu/ESCPOS-ThermalPrinter-Android#71]
Hi, the sdk works perfectly with receipt printers, but with label printer it does this:

![IMG-20201022-WA0006](https://user-images.githubusercontent.com/29213454/96910754-db7dbd00-1497-11eb-9f55-2d38cd3b02ad.jpg)

Note that i used the same text with both of them

**Comment by DantSu** [comment]
Hi, It's only compatible with ESC printer. (EPSON Standart Command)

**Comment by DantSu** [comment]
Some label printer are ESC compatible.

**Comment by mossaabrafih** [comment]
Thanks for the reply, any idea about where to find an sdk for label printers?

**Comment by livotov** [comment]
@mossaabrafih I think you first need to check with your printer docs to find out the ESC/P compatibility level of the device. Some printers only support part of ESC/P, some are using custom codes - this all may lead to such artifacts like in your picture. Having this info you may send proper codes or tweak the library, etc.
