### ISSUE TITLE
Couldn't print arabic or persian. prints reversed

### ISSUE THREAD

**Issue by MegaPower987** [DantSu/ESCPOS-ThermalPrinter-Android#74]
Hi
I couldn't print Arabic or Persian. I use the correct charset. windows-1256 but the result is not good.
everything looks reversed and letters are not connected correctly.
This is the result: 

![WhatsApp Image 2020-11-02 at 9 05 53 PM](https://user-images.githubusercontent.com/24763246/97980790-938b5e00-1de6-11eb-88a2-ebee82932ad5.jpeg)

The original form is " تست ا ب پ چ پ ژ ش ق ل"
"تست" letters should be connected. but it won't get connected.

Also I tried printing bitmap but it's not readable when printed.

![WhatsApp Image 2020-11-03 at 1 21 03 AM](https://user-images.githubusercontent.com/24763246/97981123-114f6980-1de7-11eb-9ed5-8c5ebef38da7.jpeg)

Thanks

**Comment by DantSu** [comment]
Please, Share your code.

**Comment by MegaPower987** [comment]
` public static boolean bluetoothPrint() throws EscPosConnectionException, EscPosParserException, EscPosEncodingException, EscPosBarcodeException {
        if (Looper.myLooper() == Looper.getMainLooper())
            throw new IllegalAccessError("This method should only be called on a separate thread");
        //Safety Check
        if (context == null)
            throw new IllegalArgumentException("Context shouldn't be null");

        Handler handler = new Handler(Looper.getMainLooper());


        BluetoothConnection bluetoothPrinter = new BluetoothConnection(bluetoothDevice);

        if (bluetoothPrinter.getDevice() == null) {
            handler.post(() -> Toast.makeText(context, "There was an error", Toast.LENGTH_SHORT).show());
            return false;
        }

        String text = "[R] تست ا ب پ چ پ ژ ش ق ل";

        EscPosPrinter printer = new EscPosPrinter(bluetoothPrinter, dpi, mm, charsPerLine, new EscPosCharsetEncoding("windows-1256", 92));

        //Printing customer's receipt
        printer.printFormattedTextAndCut(text, 58);
        printer.disconnectPrinter();
        return true;
    }`

Also here's encoding list of my printer

![WhatsApp Image 2020-11-02 at 1 31 42 PM](https://user-images.githubusercontent.com/24763246/97984723-66da4500-1dec-11eb-9b83-d0c0d0c96fd9.jpeg)



![WhatsApp Image 2020-11-02 at 1 31 52 PM](https://user-images.githubusercontent.com/24763246/97984728-6a6dcc00-1dec-11eb-9bf3-c9d76bbe359d.jpeg)

Thank you for answering :)

**Comment by DantSu** [comment]
Why you don't remove space between letter ?

**Comment by MegaPower987** [comment]
I'm testing different letters to see if my printer can print those chars. but the word "تست" does not have any space but it won't be printer correctly.

**Comment by DantSu** [comment]
AAAh ok, sorry I have misunderstood your problem.

Reverse your text with `"[R]" + new StringBuilder("تست ا ب پ چ پ ژ ش ق ل").reverse().toString()`
It's due to arabic text has chars order reversed.

For this char تست  I don't know how to help you.

**Comment by DantSu** [comment]
Bitmap has top be in 255px height.
Split the image if it's too tall.

**Comment by MegaPower987** [comment]
I reversed the string but that fixed the problem but still letters in words are not connected. 
If there's no fix for not connected letters, then I have to choose the bitmap way.
It's not too tall. it is just not readable. I generate the bitmap from html using [this ](https://github.com/iZettle/android-html2bitmap)library.
Then printing it this way
        printer.printFormattedTextAndCut("[C]<img>"  + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap) + "</img>", 58);

The original bitmap is OK when i save it as png to. but it becomes unreadable when printed. is there any better way to generate bitmap from a text so the printed result is more clear and readable?

**Comment by DantSu** [comment]
Thermal printer generally are in 203 dpi. So you have to increase font size if you want to see correctly the text.
