### ISSUE TITLE
Could not print arabic. What is the characterset code for arabic?

### ISSUE THREAD

**Issue by mfiaz** [DantSu/ESCPOS-ThermalPrinter-Android#76]

**Comment by Elblassy** [comment]
best way to do this is drawing image with your receipt and print it as image 
you can use this library to create your bitmap 
[](https://github.com/danielfelgar/DrawReceipt)
this is my result
![IMG_20201109_000753](https://user-images.githubusercontent.com/30121703/98485534-c470f600-221f-11eb-9b84-699685277c92.jpg)

you will have some issue while printing image in size of image you can check  this issue and solve it till @DantSu update the library 
[](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/70)

**Comment by mfiaz** [comment]
Thanks for the reply!
You have developed a pretty good library for printing solution and it is
easy to implement.
You are right but the problem is that I have a long list of reports so it
is difficult to create a view, convert it to bitmap and then send it to the
printer.

How can I use some custom font-family and how to center the logo on top?

**Comment by DantSu** [comment]
Custom font family is not implemented.

Center the logo : look at the documentation or clone this project to see usage examples.

**Comment by laithbzour** [comment]
@Elblassy 

can you share example i try but still have problem

thanks
