### ISSUE TITLE
How to change Font Family

### ISSUE THREAD

**Issue by azamalvi** [DantSu/ESCPOS-ThermalPrinter-Android#77]
How can we change font family? Also is there any way to use solid lines instead using of dash (------).
One more thing is that possible to  fill background color to black and text to white for a row without using image or pdf.

**Comment by DantSu** [comment]
Changing font family is not implemented yet.
Some charset have long dash. Try to find the good char with the good charset.
Changing color is implemented in the v2.0.8. use `<font color='bg-black'>text</font>`

**Comment by azamalvi** [comment]
I have tried this but it is simply printing not black background.

**Comment by DantSu** [comment]
Which version do you use ?

**Comment by azamalvi** [comment]
2.0.7

**Comment by azamalvi** [comment]
I think I am using 2.0.7 let me update it then try.
