### ISSUE TITLE
Can't find the inner printer

### ISSUE THREAD

**Issue by lightning331** [DantSu/ESCPOS-ThermalPrinter-Android#80]
I am using the Sunmi V2.
(https://www.amazon.com/Thermal-Bluethooth-Compatible-Loyverse-CashStock/dp/B07XKQQKTG/ref=sr_1_3?dchild=1&gclid=Cj0KCQiAqdP9BRDVARIsAGSZ8AkhVNPT1GdhicFNdsuOZAS6yGZOGQCNgTipf0qBaz2_t6GsL6MdYYAaAv_WEALw_wcB&hvadid=386279051701&hvdev=c&hvlocphy=9007754&hvnetw=g&hvqmt=b&hvrand=4302453039542365253&hvtargid=kwd-425465870078&hydadcr=22333_9728250&keywords=sunmi+pos&qid=1605709884&sr=8-3&tag=googhydr-20)

When I install the project and click the button - "PRINT BY BLUETOOTH!" on the device, the app doesn't recognize the inner printer.
It says "No printer". 

If I test the printer with the default app installed on the device, it works well.

Any resolution?

**Comment by DantSu** [comment]
May be it's not bluetooth connection.

**Comment by lightning331** [comment]
But I see it in the connected Bluetooth list exactly.

**Comment by lightning331** [comment]
If I test this library - https://github.com/shangmisunmi/SunmiPrinterDemo, it works fine.
I am not sure what's wrong with me.

**Comment by DantSu** [comment]
use BluetoothConnections : https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/connection/bluetooth/BluetoothConnections.java

```
        BluetoothConnection[] bluetoothDevicesList = (new BluetoothConnections()).getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();

            int majDeviceCl = device.getBluetoothClass().getMajorDeviceClass(),
                    deviceCl = device.getBluetoothClass().getDeviceClass();

            // Find the correct one HERE
        }
```

**Comment by DantSu** [comment]
It seems that this printer haven't a classic DeviceClass or MajorDeviceClass.

**Comment by DantSu** [comment]
One more thing, Are you sure that this printer is compatible with ESC/POS commands (EPSON Standard Commands) ?

**Comment by lightning331** [comment]
When I debug the app, I get 0 value with both majDeviceCl and deviceCl.
How can I check this supports EPSON Standard Commands?

**Comment by DantSu** [comment]
Try this : 
```java
        BluetoothConnection[] bluetoothDevicesList = (new BluetoothConnections()).getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();
            Log.i("BLUETOOTH DEVICE", device.getName());
        }
```
Do you find your printer ?

**Comment by lightning331** [comment]
It shows as "InnnerPrinter".
![image](https://user-images.githubusercontent.com/40198243/99549261-6c42ac80-29f4-11eb-9f91-f2b310b1fced.png)

**Comment by DantSu** [comment]
```java
    /**
     * Get a list of bluetooth printers.
     *
     * @return an array of EscPosPrinterCommands
     */
    @SuppressLint("MissingPermission")
    public BluetoothConnection[] getList() {
        BluetoothConnection[] bluetoothDevicesList = super.getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();
            if (device.getName().equals("InnerPrinter")) {
                printersTmp[i++] = new BluetoothConnection(device);
            }
        }
        BluetoothConnection[] bluetoothPrinters = new BluetoothConnection[i];
        System.arraycopy(printersTmp, 0, bluetoothPrinters, 0, i);
        return bluetoothPrinters;
    }
```

**Comment by lightning331** [comment]
Ha, if I remove the condition for majDeviceCl and deviceCl, the print works well. :)

**Comment by DantSu** [comment]
keep this condition :
```java
           if (device.getName().equals("InnerPrinter")) {
                printersTmp[i++] = new BluetoothConnection(device);
            }
```

**Comment by lightning331** [comment]
OK, so I will change the condition as follows.

from  if (majDeviceCl == BluetoothClass.Device.Major.IMAGING && (deviceCl == 1664 || deviceCl == BluetoothClass.Device.Major.IMAGING)) 
=>
to  if ((majDeviceCl == BluetoothClass.Device.Major.IMAGING && (deviceCl == 1664 || deviceCl == BluetoothClass.Device.Major.IMAGING)) || (device.getName().equals("InnerPrinter")))

Is it correct?

**Comment by DantSu** [comment]
the correct way is to create your own class in your project that `extends BluetoothPrintersConnections` like : 

```java
public class MyBluetoothPrintersConnections extends BluetoothPrintersConnections {

    
    /**
     * Get a list of bluetooth printers.
     *
     * @return an array of EscPosPrinterCommands
     */
    @SuppressLint("MissingPermission")
    public BluetoothConnection[] getList() {
        BluetoothConnection[] bluetoothDevicesList = super.getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();

            int majDeviceCl = device.getBluetoothClass().getMajorDeviceClass(),
                    deviceCl = device.getBluetoothClass().getDeviceClass();

            if (device.getName().equals("InnerPrinter")) {
                printersTmp[i++] = new BluetoothConnection(device);
            }
        }
        BluetoothConnection[] bluetoothPrinters = new BluetoothConnection[i];
        System.arraycopy(printersTmp, 0, bluetoothPrinters, 0, i);
        return bluetoothPrinters;
    }

}
```

**Comment by DantSu** [comment]
```java
public class MyBluetoothPrintersConnections extends BluetoothConnections {

    /**
     * Easy way to get the first bluetooth printer paired / connected.
     *
     * @return a EscPosPrinterCommands instance
     */
    public static BluetoothConnection selectFirstPaired() {
        BluetoothPrintersConnections printers = new MyBluetoothPrintersConnections();
        BluetoothConnection[] bluetoothPrinters = printers.getList();

        if (bluetoothPrinters != null && bluetoothPrinters.length > 0) {
            for (BluetoothConnection printer : bluetoothPrinters) {
                try {
                    return printer.connect();
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
            }
        }
        return null;
    }


    /**
     * Get a list of bluetooth printers.
     *
     * @return an array of EscPosPrinterCommands
     */
    @SuppressLint("MissingPermission")
    public BluetoothConnection[] getList() {
        BluetoothConnection[] bluetoothDevicesList = super.getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();

            int majDeviceCl = device.getBluetoothClass().getMajorDeviceClass(),
                    deviceCl = device.getBluetoothClass().getDeviceClass();

            if (device.getName().equals("InnerPrinter")) {
                printersTmp[i++] = new BluetoothConnection(device);
            }
        }
        BluetoothConnection[] bluetoothPrinters = new BluetoothConnection[i];
        System.arraycopy(printersTmp, 0, bluetoothPrinters, 0, i);
        return bluetoothPrinters;
    }

}
```

**Comment by lightning331** [comment]
ok, but when there exists multiple printers, I think is not a good way. 
I have to select one of the connected printers in my app before starting the printer.

**Comment by DantSu** [comment]
Ah ! Ok so yes ! Keep your class in your project : 

```java
public class MyBluetoothPrintersConnections extends BluetoothConnections {

    /**
     * Easy way to get the first bluetooth printer paired / connected.
     *
     * @return a EscPosPrinterCommands instance
     */
    public static BluetoothConnection selectFirstPaired() {
        BluetoothPrintersConnections printers = new MyBluetoothPrintersConnections();
        BluetoothConnection[] bluetoothPrinters = printers.getList();

        if (bluetoothPrinters != null && bluetoothPrinters.length > 0) {
            for (BluetoothConnection printer : bluetoothPrinters) {
                try {
                    return printer.connect();
                } catch (EscPosConnectionException e) {
                    e.printStackTrace();
                }
            }
        }
        return null;
    }


    /**
     * Get a list of bluetooth printers.
     *
     * @return an array of EscPosPrinterCommands
     */
    @SuppressLint("MissingPermission")
    public BluetoothConnection[] getList() {
        BluetoothConnection[] bluetoothDevicesList = super.getList();

        if (bluetoothDevicesList == null) {
            return null;
        }

        int i = 0;
        BluetoothConnection[] printersTmp = new BluetoothConnection[bluetoothDevicesList.length];
        for (BluetoothConnection bluetoothConnection : bluetoothDevicesList) {
            BluetoothDevice device = bluetoothConnection.getDevice();

            int majDeviceCl = device.getBluetoothClass().getMajorDeviceClass(),
                    deviceCl = device.getBluetoothClass().getDeviceClass();

            if ((majDeviceCl == BluetoothClass.Device.Major.IMAGING && (deviceCl == 1664 || deviceCl == BluetoothClass.Device.Major.IMAGING)) || device.getName().equals("InnerPrinter")) {
                printersTmp[i++] = new BluetoothConnection(device);
            }
        }
        BluetoothConnection[] bluetoothPrinters = new BluetoothConnection[i];
        System.arraycopy(printersTmp, 0, bluetoothPrinters, 0, i);
        return bluetoothPrinters;
    }

}
```

**Comment by DantSu** [comment]
Try to not edit the code in the escposprinter package because if you update the version you will loose your change.

**Comment by muchamadsubchan** [comment]
How to print product with looping array ?

return printer.setTextToPrint(
                "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer,
                        this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo_mykasir,
                                DisplayMetrics.DENSITY_LOW, getTheme())) + "</img>\n" +
                        "[L]\n" +
                        "[C]<font size='wide'>"+ nama_toko +"</font>\n" +
                        "[L]\n" +
                        "[C]"+ alamat_toko +"\n" +
                        "[C]"+ nomor_hp +"\n\n" +
                        "[L]"+ format.format(new Date()) +"\n" +
                        "[L]Kode Transaksi : "+ kode_transaksi +"\n" +
                        "[C]================================\n" +
                        "[L]\n" +
                        "[L]<b>"+ nama_produk +"</b>[R]Rp. "+ harga_jual +"\n" +
                        "[L]     x "+ qty +"\n" +
                        "[L]\n" +
                        "[C]--------------------------------\n" +
                        "[R]Total :[R]Rp. "+ harga_total +"\n" +
                        "[R]Cash :[R]Rp. "+ uang_pembeli +"\n" +
                        "[C]--------------------------------\n" +
                        "[R]<b>Kembalian :[R]Rp. "+ uang_kembalian +"</b>\n" +
                        "[L]\n" +
                        "[C]Terimakasih ^_^\n" +
                        "[L]\n" +
                        "[C]Created By App MY KASIR\n" +
                        "[C]Download Sekarang\n" +
                        "[C]di PlayStore");

**Comment by muchamadsubchan** [comment]
> 

package com.uas.mykasir;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.util.DisplayMetrics;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.dantsu.escposprinter.connection.DeviceConnection;
import com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection;
import com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections;
import com.dantsu.escposprinter.textparser.PrinterTextParserImg;
import com.uas.mykasir.async.AsyncBluetoothEscPosPrint;
import com.uas.mykasir.async.AsyncEscPosPrinter;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

public class PembayaranActivity extends AppCompatActivity {
    private DBHelper db;
    private RecyclerView listTrans;
    private TextView tvTotalBayar, tvUangPembeli, tvUangKembalian, tvTotalUntung, tvKodeTrans;
    private Button btnSelesai, btnLihatLaba, btnPrint, btnBluetooth;
    private Bitmap mutableBitmap;
    public ArrayList<ModelTransaksi> transaksiModel, transaksiModelLama;
    AdapterTransaksi adapterTransaksi;
    String nama_toko, alamat_toko, nomor_hp;
    String nama_produk;
    String harga_jual;
    String qty;

    public static final int PERMISSION_BLUETOOTH = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pembayaran);

        db = new DBHelper(this);
        transaksiModel = new ArrayList<>();
        transaksiModel.clear();
        transaksiModelLama = (ArrayList<ModelTransaksi>) getIntent().getSerializableExtra("transaksiModels");
        
        inisialisasi();
        Integer harga_total = getIntent().getIntExtra("harga_total", 0);
        Integer uang_pembeli = getIntent().getIntExtra("uang_pembeli", 0);
        Integer uang_kembalian = getIntent().getIntExtra("uang_kembalian", 0);
        Integer total_keuntungan = getIntent().getIntExtra("total_keuntungan", 0);
        String kode_transaksi = getIntent().getStringExtra("kode_transaksi");

        tvKodeTrans.setText("Kode Transaksi : " + kode_transaksi);
        tvTotalBayar.setText("Total Harga : Rp " + harga_total);
        tvUangPembeli.setText("Uang Yang Dibayar : Rp " + uang_pembeli);
        tvUangKembalian.setText("Uang Kembalian : Rp " + uang_kembalian);
        tvTotalUntung.setText("Keuntungan : Rp " + total_keuntungan);

        fillData();
        bacaProduk();
        listTrans.setLayoutManager(new LinearLayoutManager(this));

        btnSelesai.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent i = new Intent(PembayaranActivity.this, com.uas.mykasir.MainActivity.class);
                clearTabelKeranjang();
                startActivity(i);
            }
        });

        btnLihatLaba.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent i = new Intent(PembayaranActivity.this, LabaActivity.class);
                startActivity(i);
            }
        });

        btnPrint.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                printBluetooth();
                clearTabelKeranjang();
            }
        });

        btnBluetooth.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                browseBluetoothDevice();
            }
        });

    }

    private void fillData() {
        db = new DBHelper(this);

        String query = "SELECT * FROM pengaturan WHERE nomor = 1";
        Cursor cursor = db.customQuery(query);
        cursor.moveToFirst();
        if (cursor != null && cursor.moveToFirst()) {
            do{
                nama_toko = cursor.getString(cursor.getColumnIndex("nama_toko"));
                alamat_toko = cursor.getString(cursor.getColumnIndex("alamat_toko"));
                nomor_hp = cursor.getString(cursor.getColumnIndex("nomor_hp"));
            }while (cursor.moveToNext());
        }else if(nama_toko == null && alamat_toko == null && nomor_hp == null) {
            nama_toko = "Isikan Nama Toko";
            alamat_toko = "Alamat Toko";
            nomor_hp = "Nomor HP di Pengaturan";
        }
    }

    private void bacaProduk() {
        db = new DBHelper(this);

        String query = "SELECT * FROM keranjang WHERE jumlah_produk > 0";
        Cursor cursor = db.customQuery(query);
        cursor.moveToFirst();
        if (cursor != null && cursor.moveToFirst()) {
            do{
//                nama_produk = cursor.getString(cursor.getColumnIndex("nama_produk"));
//                harga_jual = cursor.getString(cursor.getColumnIndex("harga_jual"));
//                qty = cursor.getString(cursor.getColumnIndex("jumlah_produk"));

                ModelTransaksi model = new ModelTransaksi();
                model.setNamaProduk(cursor.getString(cursor.getColumnIndex("nama_produk")));
                model.setHargaJual(cursor.getInt(cursor.getColumnIndex("harga_jual")));
                model.setJumlahItem(cursor.getInt(cursor.getColumnIndex("jumlah_produk")));
                transaksiModel.add(model);

                int harga = cursor.getInt(cursor.getColumnIndex("harga_jual"));
                int qty = cursor.getInt(cursor.getColumnIndex("jumlah_produk"));
            }while (cursor.moveToNext());

            AdapterTransaksi adapterTransaksi = new AdapterTransaksi(this, transaksiModel);
            listTrans.setAdapter(adapterTransaksi);
            listTrans.getAdapter().notifyDataSetChanged();
        }
    }

    private void clearTabelKeranjang(){
        SQLiteDatabase database = db.getWritableDatabase();
        database.delete("keranjang", null, null);
    }

    private void inisialisasi() {
        tvTotalBayar = findViewById(R.id.tvtotalBayarP);
        tvUangPembeli = findViewById(R.id.tvUangPembeli);
        tvUangKembalian = findViewById(R.id.tvUangKembalian);
        tvTotalUntung = findViewById(R.id.tvTotalUntung);
        btnSelesai = findViewById(R.id.btnSelesai);
        btnPrint = findViewById(R.id.btnPrint);
        btnBluetooth = findViewById(R.id.btnBluetooth);
        btnLihatLaba = findViewById(R.id.btnLihatLaba);
        tvKodeTrans = findViewById(R.id.tvKodeTrans);
        listTrans = findViewById(R.id.listTransaksi);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, int[] grantResults) {
        if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            switch (requestCode) {
                case PembayaranActivity.PERMISSION_BLUETOOTH:
                    this.printBluetooth();
                    break;
            }
        }
    }

    private BluetoothConnection selectedDevice;

    public void browseBluetoothDevice() {
        final BluetoothConnection[] bluetoothDevicesList = (new BluetoothPrintersConnections()).getList();

        if (bluetoothDevicesList != null) {
            final String[] items = new String[bluetoothDevicesList.length + 1];
            items[0] = "Default printer";
            int i = 0;
            for (BluetoothConnection device : bluetoothDevicesList) {
                items[++i] = device.getDevice().getName();
            }

            AlertDialog.Builder alertDialog = new AlertDialog.Builder(PembayaranActivity.this);
            alertDialog.setTitle("Bluetooth printer selection");
            alertDialog.setItems(items, new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialogInterface, int i) {
                    int index = i - 1;
                    if(index == -1) {
                        selectedDevice = null;
                    } else {
                        selectedDevice = bluetoothDevicesList[index];
                    }
                    Button button = (Button) findViewById(R.id.btnBluetooth);
                    button.setText(items[i]);
                }
            });

            AlertDialog alert = alertDialog.create();
            alert.setCanceledOnTouchOutside(false);
            alert.show();

        }
    }

    public void printBluetooth() {
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.BLUETOOTH) != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.BLUETOOTH}, PembayaranActivity.PERMISSION_BLUETOOTH);
        } else {
            new AsyncBluetoothEscPosPrint(this).execute(this.getAsyncEscPosPrinter(selectedDevice));
        }
    }

    /**
     * Asynchronous printing
     */
    @SuppressLint("SimpleDateFormat")
    public AsyncEscPosPrinter getAsyncEscPosPrinter(DeviceConnection printerConnection) {
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss dd-MM-yyyy");
        AsyncEscPosPrinter printer = new AsyncEscPosPrinter(printerConnection, 203, 48f, 32);

        Integer harga_total = getIntent().getIntExtra("harga_total", 0);
        Integer uang_pembeli = getIntent().getIntExtra("uang_pembeli", 0);
        Integer uang_kembalian = getIntent().getIntExtra("uang_kembalian", 0);
        String kode_transaksi = getIntent().getStringExtra("kode_transaksi");

        return printer.setTextToPrint(
                "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer,
                        this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo_mykasir,
                                DisplayMetrics.DENSITY_LOW, getTheme())) + "</img>\n" +
                        "[L]\n" +
                        "[C]<font size='wide'>"+ nama_toko +"</font>\n" +
                        "[L]\n" +
                        "[C]"+ alamat_toko +"\n" +
                        "[C]"+ nomor_hp +"\n\n" +
                        "[L]"+ format.format(new Date()) +"\n" +
                        "[L]Kode Transaksi : "+ kode_transaksi +"\n" +
                        "[C]================================\n" +
                        "[L]\n" +
                        "[L]<b>"+ nama_produk +"</b>[R]Rp. "+ harga_jual +"\n" +
                        "[L]     x "+ qty +"\n" +
                        "[L]\n" +
                        "[C]--------------------------------\n" +
                        "[R]Total :[R]Rp. "+ harga_total +"\n" +
                        "[R]Cash :[R]Rp. "+ uang_pembeli +"\n" +
                        "[C]--------------------------------\n" +
                        "[R]<b>Kembalian :[R]Rp. "+ uang_kembalian +"</b>\n" +
                        "[L]\n" +
                        "[C]Terimakasih ^_^\n" +
                        "[L]\n" +
                        "[C]Created By App MY KASIR\n" +
                        "[C]Download Sekarang\n" +
                        "[C]di PlayStore");
    }
}
