### ISSUE TITLE
How to print the Euro symbol -  € ?  And does the italic font style support? 

### ISSUE THREAD

**Issue by lightning331** [DantSu/ESCPOS-ThermalPrinter-Android#81]

**Comment by lightning331** [comment]
When I print the symbol - "€",  it appears as "?" character.

**Comment by DantSu** [comment]
use "windows-1252" (WPC1252) encoding with Western Europe.

**Comment by DantSu** [comment]
Italic is not supported.

**Comment by lightning331** [comment]
> use "windows-1252" (WPC1252) encoding with Western Europe.

How to use it?

**Comment by lightning331** [comment]
I tried to use the following code.

String euro = "€"
String encoded= new String(euro.getBytes(), Charset.forName("Windows-1252"));

But it still shows as "?".

**Comment by DantSu** [comment]
Do you have the list id of the code page for your printer ?

**Comment by lightning331** [comment]
printer information:

device name: "BT-PRINT"
majDeviceCl: 1536
deviceCl:  1664

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/6

**Comment by lightning331** [comment]
And I have 2 printers and it also doesn't work in the InnerPrinter.

**Comment by DantSu** [comment]
read the documentation, and read the closed issues.
