### ISSUE TITLE
Cyrillic text not print

### ISSUE THREAD

**Issue by JavohirYakubov** [DantSu/ESCPOS-ThermalPrinter-Android#82]
Cyrillic text not print my xprinter. Please help me!

**Comment by takhirovich** [comment]
EscPosPrinter printer = new EscPosPrinter(
                    deviceConnection,
                    170,
                    printerData.getPrinterWidthMM(),
                    printerData.getPrinterNbrCharactersPerLine(),
                    new EscPosCharsetEncoding("windows-1251", 73)
            );

Change it in AsyncEscPosPrint class -> ("windows-1251", 73) this is for Cyrillic chars

**Comment by DantSu** [comment]
The 73 charset id may not work with your printer. Each printer have its own charset id.
