### ISSUE TITLE
BluetoothConnections should return empty array instead of null, or document nullable return value

### ISSUE THREAD

**Issue by okarmazin** [DantSu/ESCPOS-ThermalPrinter-Android#83]
Pertains to: `BluetoothConnections.getList`, `BluetoothPrintersConnections.getList`

When Bluetooth is not supported by current device (`adapter == null`) or adapter is not enabled, the method returns undocumented `null` instead of the advertised array of devices.

Either document this fact or return an empty array in those cases. I argue for returning a guaranteed non-null value, so that consumers have a better quality-of-life. Either way the current state is not optimal and leads to NPEs.

**Comment by okarmazin** [comment]
Documenting API nullability is more and more important as Kotlin becomes the dominant language in the Android ecosystem. Using nullability annotations should be considered and is strongly encouraged.

**Comment by DantSu** [comment]
@Nullable has been added v2.0.10
