### ISSUE TITLE
crash with other library

### ISSUE THREAD

**Issue by mghanif** [DantSu/ESCPOS-ThermalPrinter-Android#84]
I use this library and the zxing scanner library. Before I used theESCPOS-ThermalPrinter, the scanner was running smoothly. But when I use the ESCPOS-ThermalPrinter, the barcode scanner is always force closed: 

java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

![gambar](https://user-images.githubusercontent.com/21106287/100567267-aa947180-32fa-11eb-98de-6e19e5889f94.png)

**Comment by DantSu** [comment]
I use `implementation 'com.google.zxing:core:3.4.0'` for generate QR Code.
May it's coming from this.

**Comment by mghanif** [comment]
thankyou, solved
