### ISSUE TITLE
bluetooth print always failed for the 2nd attempt

### ISSUE THREAD

**Issue by k1n6m4n** [DantSu/ESCPOS-ThermalPrinter-Android#89]
hi, I'm trying to implement this awesome library, and I bumped into this situation

whenever I try to print with printer that I choose from the list, the result will always like this :

            BluetoothConnection[] mBtList = new BluetoothPrintersConnections().getList();
            new AsyncBluetoothEscPosPrint(this).execute(getAsyncEscPosPrinter(mBtList[0]));

1. first print success (printing already finished)
2. the led printer indicator keep blinking (indicating bluetooth is still working)
3. when I hit print again, it always failed with AsyncEscPosPrint.FINISH_PRINTER_DISCONNECTED
4. the led indicator immediately off after I got that error message
5. if I click print, it will working again, and step back to number 1

I already tried with 3 different brand of printer which all of them is support ESC/POS, all facing the same problem, but only 1 printer have led indicator, but the pattern always the same

but if I used _BluetoothPrintersConnections.selectFirstPaired()_ the problem somehow non exist, but the waiting time is bit longer for the 2nd print, around 10 seconds before the printer start printing after I click it. (the led keep blinking too after finish printing the first one)

from what i observe, seems like the printer cannot closed the connection properly after finish printing, but when i hit print again then it will close it, so the next print will working again.
but if i use selectFirstPaired, somehow it will keep trying after receiving FINISH_PRINTER_DISCONNECTED, so the 2nd print is working but slower response.

I cannot use selectFirstPaired because my apps will connected to more than 1 bluetooth printer.

Thanks in advance if you can help me.

**Comment by DantSu** [comment]
Have you try to use `disconnectPrinter()` _(EscPosPrinter method)_ after each print ?

**Comment by k1n6m4n** [comment]
thanks for the speedy reply, i never know the disconnectPrinter() function at all since i followed the example from the source and never mention it.

i'll give it a try now.

**Comment by DantSu** [comment]
In the example, I use `selectFirstConnectedPrinter` so I don't have this issue.
`disconnectPrinter` is present in the documentation (). All existing method aren't used in the example. ;)

**Comment by k1n6m4n** [comment]
so i used the printIt function in the example to use the EscPosPrinter method, like this :

```
 EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 48f, 32);
            printer
                    .printFormattedText(
                        "[L]\n" +
                                "[C]--------------------------------\n" +
                                "[R]TOTAL PRICE :[R]34.98e\n" +
                                "[R]TAX :[R]4.23e\n" +
                                "[L]\n" +
                                "[C]================================\n" +
                                "[L]\n"
                    );
            printer.disconnectPrinter();

```

and i called it from 
```
            BluetoothConnection[] mBtList = new BluetoothPrintersConnections().getList();
            printIt(mBtList[2]);
```

and the result i got is : 
1. the button grey out, and froze like 10-15 second
2. start printing with dialog showing progress
3. paper coming out
4. dialog showing "Success"
5. dialog showing "Broken connection" unable to connect to bt device
6. button back to normal color and ready to go again

is there anyway to disconnect using AsyncBluetoothEscPosPrint ?

**Comment by k1n6m4n** [comment]
> In the example, I use `selectFirstConnectedPrinter` so I don't have this issue.
> `disconnectPrinter` is present in the documentation (). All existing method aren't used in the example. ;)

from my experiment, selectFirstConnectedPrinter is kinda slow if the phone is paired with 4 printer and the 4th is the one online, seems like they're looping from the top until get the success print message or the last paired printer is reached.

**Comment by DantSu** [comment]
Add this line in `doInBackground` method of `AsyncEscPosPrint` class : 
```java
           this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);

            printer.printFormattedTextAndCut(printerData.getTextToPrint());
            printer.disconnectPrinter();

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTED);
```

**Comment by k1n6m4n** [comment]
Man, it works like a charm!!

maybe you should add that to the example you publish, so ppl won't bump into same scenario like me in the future

thank you very much!
