### ISSUE TITLE
How i can send paper cutting command?

### ISSUE THREAD

**Issue by AdilTechDart** [DantSu/ESCPOS-ThermalPrinter-Android#9]
I am not able to find  paper cutting command or i think there is no paper cutting command

**Comment by DantSu** [comment]
Not implemented yet.

**Comment by AdilTechDart** [comment]
i solved by using this command 

new byte[]{  0x1D,
                    0x56,
                    66,
                    0x00};

**Comment by DantSu** [comment]
thx, i will implement a `printTextAndCut()` method

**Comment by AdilTechDart** [comment]
Some Spanish character and Euro sign '€' not working

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/6

**Comment by AdilTechDart** [comment]
Can i use "UTF-8"

**Comment by greenboxinnovations** [comment]
// change
EscPosPrinter printer = new EscPosPrinter(new TcpConnection("192.168.0.107", 9100), 203, 48f, 32);

// to
TcpConnection deviceConnection = new TcpConnection("192.168.0.101", 9100);
EscPosPrinter printer = new EscPosPrinter(deviceConnection, 203, 48f, 32);
printer.printFormattedText(
			...
			...
			);


// cut paper
deviceConnection.write(new byte[]{ 0x1D,
                            0x56,
                            66,
                            0x00});
deviceConnection.send();


// worked on epson UB-E03

**Comment by DantSu** [comment]
done
