### ISSUE TITLE
cash drawer support

### ISSUE THREAD

**Issue by k1n6m4n** [DantSu/ESCPOS-ThermalPrinter-Android#90]
Hi, is there a command to open the cash drawer?

**Comment by DantSu** [comment]
Hi, it's not implemented.
But you can send your own command to printer by : 
```java
printer.write(byte[] {...});
printer.send();
```

**Comment by k1n6m4n** [comment]
Hi, thanks for the information, 

The the write and send command is accessed via DeviceConnection, it cannot access directly from EscPosPrinter

and this should be the command for drawer with 2 pin
write(new byte[]{0x1B, 0x70, 0x00, 0x19, 0xFA});
send(100);

I'll give it a try whenever I got a cash drawer and update here if it success

**Comment by k1n6m4n** [comment]
hi, I tested the code and it's working, we can choose to use the 2pin (channel 0) or 5pin (channel 1) 


```
    public EscPosPrinterCommands openCashDrawer(int channel) throws EscPosConnectionException {
        if (!this.printerConnection.isConnected()) {
            return this;
        }

        if (channel == 0) {
            this.printerConnection.write(new byte[]{0x1B, 0x70, 0x00, 0x19, (byte) 0xFA});
        } else {
            this.printerConnection.write(new byte[]{0x1B, 0x70, 0x05, 0x19, (byte) 0xFA});
        }

        this.printerConnection.send(100);
        return this;
    }
```

**Comment by DantSu** [comment]
Great !

**Comment by YovanggaAnandhika** [comment]
is there a version update for the cash drawer in the android library?
