### ISSUE TITLE
Nordic character set printing issue

### ISSUE THREAD

**Issue by guardian12397** [DantSu/ESCPOS-ThermalPrinter-Android#91]
Hey i am new to this printing stuff and i am having some trouble in print the swedish letters like å,ö and ä. can u plz tell me what i need to write in this class new EscPosCharsetEncoding("", )); to print these characters.

**Comment by DantSu** [comment]
Nobody can help you, each printer have their own charset id. Check the manual to find a list of available charset encoding for your printer.
