### ISSUE TITLE
Unable to print text

### ISSUE THREAD

**Issue by gs1109** [DantSu/ESCPOS-ThermalPrinter-Android#92]
Hey, we are unable to print text, but images are getting printed properly.

` EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 48f, 32, new EscPosCharsetEncoding("windows-1252", 16));

String printableContent = "[C]<img>"
                    + PrinterTextParserImg.bitmapToHexadecimalString(
                    printer, this.getApplicationContext().getResources().getDrawableForDensity(
                            R.drawable.logo, DisplayMetrics.DENSITY_LOW))
                    + "</img>\n"
                    + "[L] Testing Printer";`

Its not even able to print any text character. 

https://user-images.githubusercontent.com/11091196/102917851-ee1e6d80-44ab-11eb-964d-681aea8f550a.mp4

**Comment by DantSu** [comment]
In your example I don't see <img></img> tag.

**Comment by gs1109** [comment]
Hey, sorry attached wrong video. 
This video is of the same sample printable string which you have given in the example.

I tried with just text too without the images.  In that case also, it doesn't print anything.

**Comment by DantSu** [comment]
Give me more code. Your example don't contain enougth. surround your code by three `

**Comment by DantSu** [comment]
\`\`\`java
// your code here
\`\`\`

**Comment by gs1109** [comment]
```java
    protected void printContents(View view, DeviceConnection printerConnection, String messageToBePrinted) {

        try {

            EscPosPrinter printer = new EscPosPrinter(printerConnection, 203,
                    48f, 32,
                    new EscPosCharsetEncoding("windows-1252", 16));

            String printableContent = "[C]<img>"
                    + PrinterTextParserImg.bitmapToHexadecimalString(
                    printer, this.getApplicationContext().getResources().getDrawableForDensity(
                            R.drawable.logo, DisplayMetrics.DENSITY_LOW))
                    + "</img>\n"
                    + "[L] Testing Printer";

            printer.printFormattedText(printableContent);

        } catch (EscPosConnectionException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.broken_connection))
                    .setMessage(e.getMessage())
                    .show();
        } catch (EscPosParserException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.invalid_formatted_text))
                    .setMessage(e.getMessage())
                    .show();
        } catch (EscPosEncodingException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.invalid_encoding))
                    .setMessage(e.getMessage())
                    .show();
        } catch (EscPosBarcodeException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.invalid_barcode))
                    .setMessage(e.getMessage())
                    .show();
        }
    }

```

**Comment by DantSu** [comment]
Are you sure to have a 48mm width printer, 203 dpi ?
Have you a list of the charset encoding supported by your printer ?

**Comment by gs1109** [comment]
Its a 58mm width printer, but we tried changing to that as well.
For DPI and Charset Encoding, we don't have enough data, as the device is an assembled one and not from any popular brand.


![WhatsApp Image 2020-12-22 at 9 55 33 PM](https://user-images.githubusercontent.com/11091196/102977634-4778b200-4529-11eb-8ebe-c159577ab30f.jpeg)

![WhatsApp Image 2020-12-22 at 9 55 38 PM](https://user-images.githubusercontent.com/11091196/102977629-45aeee80-4529-11eb-848d-bfcc519fa214.jpeg)

**Comment by gs1109** [comment]
The text part did work with one other library (Printooth), but it was having issues with the images.
There, we were using an inbuilt method to set CHARCODE_PC437.  Do you have any idea, as to what would be the charset string for this encoding.  
Sorry, it might be a silly question, but I dont have much idea in this space. Apologies for that.

**Comment by DantSu** [comment]
https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html

`new EscPosCharsetEncoding("IBM437", YOU_HAVE_TO_FIND_THE_ID_NUMBER)`

**Comment by gs1109** [comment]
Thanks!! Will give it a try and let you know.

**Comment by DantSu** [comment]
Run a selftest of your printer. like this : 

https://user-images.githubusercontent.com/4188774/85408231-8b7fff80-b564-11ea-8e13-3dde5f3d7680.jpg

**Comment by gs1109** [comment]
Unfortunately, still didn't work with the appropriate charset.  We checked for the charset and it was 0.

```java
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203,
                    58f, 40,
                    new EscPosCharsetEncoding("IBM437", 0));
```

Can you suggest any other place, where it might be breaking up?

**Comment by DantSu** [comment]
```java
    protected void printContents(View view, DeviceConnection printerConnection, String messageToBePrinted) {

        try {
            for(int i = 0; i < 255; ++i) {
                EscPosPrinter printer = new EscPosPrinter(
                        printerConnection, 
                        203,
                        48f, 
                        32,
                        new EscPosCharsetEncoding("windows-1252", i)
                );
                printer.printFormattedText("[L]" + i + " : €");
            }
        } catch (EscPosConnectionException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.broken_connection))
                    .setMessage(e.getMessage())
                    .show();
        } catch (EscPosParserException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.invalid_formatted_text))
                    .setMessage(e.getMessage())
                    .show();
        } catch (EscPosEncodingException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.invalid_encoding))
                    .setMessage(e.getMessage())
                    .show();
        } catch (EscPosBarcodeException e) {
            new AlertDialog.Builder(this)
                    .setTitle(getResources().getString(R.string.invalid_barcode))
                    .setMessage(e.getMessage())
                    .show();
        }
    }

```

**Comment by DantSu** [comment]
the line that print € correctly will be the good charset encoding.

**Comment by david-2020** [comment]
I have the same problem, did you manage to solve it? If you help me please
