### ISSUE TITLE
print QR code

### ISSUE THREAD

**Issue by VannakYet** [DantSu/ESCPOS-ThermalPrinter-Android#94]
[C] now work with single QR code i want only qrcode but can not aline center.

**Comment by DantSu** [comment]
I dont understand your problem. You have to be more explicit.

**Comment by VannakYet** [comment]
when i want to print QR code only but QR code not aline center sir.

**Comment by VannakYet** [comment]
how ever i set [C] it still aline Left

**Comment by VannakYet** [comment]
my QR code string is more than 32 characters

**Comment by VannakYet** [comment]
[
<img width="377" alt="Screen Shot 2021-01-03 at 3 48 27 PM" src="https://user-images.githubusercontent.com/39559065/103474933-20e53180-4ddb-11eb-9508-ef225ae503ee.png">
](url)

**Comment by VannakYet** [comment]
<img width="303" alt="Screen Shot 2021-01-03 at 3 49 25 PM" src="https://user-images.githubusercontent.com/39559065/103474951-4d00b280-4ddb-11eb-8a50-bbde59a8f075.png">
result

**Comment by DantSu** [comment]
Show me full code and share me a picture.

**Comment by VannakYet** [comment]
<img width="1272" alt="Screen Shot 2021-01-03 at 3 50 57 PM" src="https://user-images.githubusercontent.com/39559065/103474969-7a4d6080-4ddb-11eb-94a0-523db7ad2de0.png">

**Comment by DantSu** [comment]
Are you sure that your printer is 48mm width, 203 dpi, 32chars by line ?

**Comment by VannakYet** [comment]
![photo_2021-01-03 15 54 47](https://user-images.githubusercontent.com/39559065/103475015-05c6f180-4ddc-11eb-8003-495d2a28981f.jpeg)
my printer sir.

**Comment by VannakYet** [comment]
my printer port :9100

**Comment by VannakYet** [comment]
my printer is width 80mm sir.what is , dpi, 32chars by line to put sir.?

**Comment by DantSu** [comment]
"[L]0123456789012345678901234567890123456789012345678901234567890123456789"

**Comment by DantSu** [comment]
Print this and share me a picture

**Comment by VannakYet** [comment]
many thanks sir. i will share to sir tomorrow sir.

**Comment by VannakYet** [comment]
![IMAGE 2021-01-04 09:53:10](https://user-images.githubusercontent.com/39559065/103496958-a8ca4a80-4e72-11eb-896c-2fdebfa0c5ba.jpg)

**Comment by VannakYet** [comment]
thanks sir now done.

**Comment by DantSu** [comment]
Ok you change for this ? 
`new AsyncEscPosPrinter(printerConnection, 203, 75f, 47);`

**Comment by huutuan06** [comment]
> my printer is width 80mm sir.what is , dpi, 32chars by line to put sir.?

Hi @DantSu , @vannakyet .
Can I ask a question, the paper width of the printer is 80 mm. Why do you enter 75f when init AsyncEscPosPrinter "new AsyncEscPosPrinter(printerConnection, 203, 75f, 47);"?

**Comment by DantSu** [comment]
It's in the doc. 

Printing width millimeters not paper width millimeters. Left and right margin have to be substract.
```
EscPosPrinter(DeviceConnection printer, int printerDpi, float printingWidthMM, int nbrCharactersPerLine [, EscPosCharsetEncoding charsetEncoding])

param DeviceConnection printer : Instance of a connected printer

param int printerDpi : DPI of the connected printer

param float printerWidthMM : Printing width in millimeters

param int printerNbrCharactersPerLine : The maximum number of medium sized characters that can be printed on a line.

param EscPosCharsetEncoding charsetEncoding (optional) : Set the charset encoding.
```

**Comment by huutuan06** [comment]
I got it. Thank you so much, @DantSu !
