### ISSUE TITLE
QR Code not aline center

### ISSUE THREAD

**Issue by VannakYet** [DantSu/ESCPOS-ThermalPrinter-Android#95]
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 48f, 32);
            printer
                    .printFormattedText(
                                   "[L]\n" +      
                                    "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                    );

not aline center.

**Comment by DantSu** [comment]
Normal is more than 32 characters...

**Comment by VannakYet** [comment]
my string is more then 32 characters sir.

**Comment by DantSu** [comment]
Read the doc. Your code print text. Not qr code...

**Comment by VannakYet** [comment]
yes sir i have try to read the doc. but still have the bugs 
my code 
 "[C]<qrcode size='50'>" + myQrCode + "</qrcode>\n"

**Comment by VannakYet** [comment]
"[C]<barcode type='ean8' height='0' width='0'></barcode>\n" it will center when i add barcode above qrcode sir.

**Comment by VannakYet** [comment]
printer.setTextToPrint(
//                "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo, DisplayMetrics.DENSITY_MEDIUM)) + "</img>\n" +
//                        "[L]\n" +
//                        "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
//                        "[L]\n" +
//                        "[C]<u type='double'>" + format.format(new Date()) + "</u>\n" +
//                        "[C]\n" +
//                        "[C]================================\n" +
//                        "[L]\n" +
//                        "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
//                        "[L]  + Size : S\n" +
//                        "[L]\n" +
//                        "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
//                        "[L]  + Size : 57/58\n" +
//                        "[L]\n" +
//                        "[C]--------------------------------\n" +
//                        "[R]TOTAL PRICE :[R]34.98e\n" +
//                        "[R]TAX :[R]4.23e\n" +
//                        "[L]\n" +
//                        "[C]================================\n" +
//                        "[L]\n" +
//                        "[L]<u><font color='bg-black' size='tall'>Customer :</font></u>\n" +
//                        "[L]Raymond DUPONT\n" +
//                        "[C]Virtual Card\n" +
//                        "[L]31547 PERPETES\n" +
//                        "[L]Tel : +33801201456\n" +
//                        "\n" +
//                        "[C]<barcode type='ean8' height='0' width='0'>          </barcode>\n" +
//                 "[C]\n" +
                        "[C]<qrcode size='50'>" + myQrCode + "</qrcode>\n" + "[C]\n" + "[C]\n" + "[C]\n" + "[C]\n" + "[C]\n" + "[C]\n" + "[C]\n" + "[C]\n"
        );

**Comment by VannakYet** [comment]
any something wrong sir.

**Comment by VannakYet** [comment]
<qrcode size='50'>
