### ISSUE TITLE
Why is there !B extra for each line printed

### ISSUE THREAD

**Issue by isllyend** [DantSu/ESCPOS-ThermalPrinter-Android#97]
No matter what I print,What's wrong？help，):
![121611218466_ pic](https://user-images.githubusercontent.com/15176790/105325382-802ea880-5c07-11eb-9e29-9820a18bd306.jpg)

**Comment by DantSu** [comment]
your printer seems to not be compatible with : 
- GS ! : https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=34
- GS B : https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=35
