### ISSUE TITLE
How to manage alignment of item name and rest of in column

### ISSUE THREAD

**Issue by kashyap2468** [DantSu/ESCPOS-ThermalPrinter-Android#99]
![image_2021_01_29T05_53_43_165Z](https://user-images.githubusercontent.com/11816589/106237345-a7e3c900-6224-11eb-8a49-6cedc10c92da.png)

**Below is my code that i do for Lan printer**

"[L]<font size='normal'>\n" +
                "[L]------------------------------------------------\n" +
                "[L]<b>ITEM[L][R]QTY[R]PRICE[R]AMT</b>\n" +
                "[L]------------------------------------------------\n" +
                "[L]Apple Juice苹果汁 Only for test space Between[R]1[R]250[R]500\n" +
                "[L]Carrot Juice萝卜汁dfgdfg[R]1KG[R]20[R]1000\n" +
                "[L]Sarsi沙士(罐装terte tefsdf[R]2g[R]5[R]1.22\n" +
                "[L]------------------------------------------------\n" +
                "[L][R]SUBTOTAL[R]10.99\n" +
                "[L][R]SERVICE CHARGE($)(10)[R]10.99\n" +
                "[L]------------------------------------------------\n" +
                "[L][R]GRNDTOTAL[R]10.99\n" +
                "[L][R]ROUNDING[R]0.01</font>\n"
                

I need product name in given space if larger then its break the line and print below not override QTY and rest of things,
Thanks in advance

**Comment by DantSu** [comment]
Count chars of the product name and do it in two line instead of one.

**Comment by kashyap2468** [comment]
Yes you are tight but this logic not work in some languages like chines, i hope you understand what i want say

**Comment by kashyap2468** [comment]
> Count chars of the product name and do it in two line instead of one.

Yes you are right but this logic not work on some other languages like chines

**Comment by DantSu** [comment]
What's the difference ? Explain your problem.

**Comment by kashyap2468** [comment]
For Example = "Amount"

English 6 Character count = Amount
Chines 2 Character count  = 数额
Japanese 2 Character count = 総計
Korean 2 Character count = 금액

Look above all example you can see all character have different size for print so how we can manage it according to character count?

**Comment by DantSu** [comment]
You have to count bytes with getBytes method.

**Comment by kashyap2468** [comment]
Ok, Thanks for your suggestion, let me try same and i'll inform you soon @DantSu

**Comment by beniidh** [comment]
> Count chars of the product name and do it in two line instead of one.

how about unpredictable lenght of chars ?
